### ISSUE TITLE
GitLab-integration failing with 405

### ISSUE THREAD

**Issue by paulkernstock** [taigaio/taiga-back#1002]
Some things seem to be wrong with my Taiga-installation when I'm trying to webhook into GitLab:

**Info**: I'm running Taiga on my own server (everything working fine).

**First**: The ADMIN->Integrations-tab gives me a strange payload URL:

`http://localhost:8000/api/v1/gitlab-hook?project=8&key[...]`

**Second**: Knowing that this URL surely won't work, I changed it to the servers actual IP-address and gave

` http://[IP-address]/api/v1/gitlab-hook?project=8&key=[...]`

to GitLab. I had to disable SSL-verification as my server has no valid certificate. Still when I try to test the webhook, GitLab gives:

> Hook executed successfully but returned HTTP 405 {"_error_message"=>"Method 'GET' not allowed.", "_error_type"=>"taiga.base.exceptions.MethodNotAllowed"}

Also the webhook apparently doesn't work (new GitLab-issues are not transmitted to Taiga).

I tried the solution to issue #930 but no effect.

Thank you for any proposals!

**Comment by mohsens22** [comment]
Hey bro!
You need to do these modifications : 
 in `~/taiga-back/settings/local.py`
add
```
SITES["api"]["scheme"] = "http"
SITES["front"]["domain"] = "yourdomain.com"
```
Notice:  if you are using HTTPS, change API scheme to https

 then restart services in terminal
```
sudo service circusd restart
sudo service nginx restart
```

**Comment by paulkernstock** [comment]
This is working thanks, @Mohsens22.

**Comment by iwkse** [comment]
Hi, I have  SITES["front"]["domain"] sets properly but in the integrations I see localhost yet. Any hint?
