### ISSUE TITLE
Outdated cryptography requirement broken on newer versions of openssl

### ISSUE THREAD

**Issue by jgresty** [taigaio/taiga-back#1003]
Currently there is a requirement for cryptography 1.7.1 which will not install with openssl versions >1.0.2.

Updating cryptography to 1.9 makes the package install without any errors however I have not extensively tested this new version.

**Comment by muellert** [comment]
Although I was able to install Taiga with the current requirements.txt a few days ago, I now tried again on a new machine, and surely it failed. Your change makes at least the compile step work. Thank you!

**Comment by losinggeneration** [comment]
@jgresty I think this has been updated [here](https://github.com/taigaio/taiga-back/blob/master/requirements.txt#L13) #1127 appears to be similar issue.

**Comment by migonzalvar** [comment]
Thank you @losinggeneration. Let me close this issue as fixed.
