### ISSUE TITLE
psycopg2.ProgrammingError: permission denied for relation projects_project

### ISSUE THREAD

**Issue by kaisbe** [taigaio/taiga-back#1007]
After following all the installation steps from https://taigaio.github.io/taiga-doc/dist/setup-production.html and opening localhost on the web browser, I get problems with the frontend content display, along with the following errors within /home/kais/.taiga/logs/gunicorn.stderr.log:

> Internal Server Error: /api/v1/stats/discover
> Traceback (most recent call last):
>   File "/home/kais/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
>     return self.cursor.execute(sql, params)
> psycopg2.ProgrammingError: permission denied for relation projects_project

**Comment by superalex** [comment]
Hello @kaisbe,

Are you using a standard ubuntu 16.04 server with a local postgres database?

**Comment by kaisbe** [comment]
Hello @superalex,

No, I'm using Debian 8 unstable, but with a local postgres database.

**Comment by superalex** [comment]
It seems related to your postgresql configuration but I don't know exactly what can be failing.

**Comment by kaisbe** [comment]
Okay. So, is there any info I can provide?

**Comment by superalex** [comment]
No, but you could try updating the privileges for the user: https://stackoverflow.com/questions/15520361/permission-denied-for-relation

**Comment by kaisbe** [comment]
I tried that method before posting, yet no solution.
