### ISSUE TITLE
View Error Logs and troubleshoot Development environment

### ISSUE THREAD

**Issue by vinoopraj** [taigaio/taiga-back#1009]
Hi folks, 

I need to setup the taiga development environment and customize accordingly.  I followed the document http://taigaio.github.io/taiga-doc/dist/setup-development.html and ends with an issue "Something happened and our Oompa Loompas are working on it."   Able to hit the public url and page shows with this error message. But i could not find any logs or other thing where i am missing. Hope there is an issue in db which returns empty when i hit the API url. Also i need the application to be public, so the ip address in conf.json is updated. 

Is it possible to connect database from outside ?
How to view the logs and troubleshoot ?
Nothing displayed in console,

Also i am using ubuntu without gui

Thanks in advance
Vinoop

**Comment by superalex** [comment]
You could check your browser console to see what's the response from the API call. If you are running taiga in development mode you should see all the errors in the console where you are running the "python manage.py runserver".

> Is it possible to connect database from outside ?

Yes, but you will have to configure postgres properly

> How to view the logs and troubleshoot ?

On development mode you should see the errors on the runserver shell
