### ISSUE TITLE
[Q] Is there documentation on how to upgrade an installation from source to a new version?

### ISSUE THREAD

**Issue by AridDay** [taigaio/taiga-back#101]
&gt; **READ THIS FIRST!**: We recently announced Taiga plans for the future and they greatly affect how we manage this repository and the current Taiga 6 release. Check it [here](https://blog.taiga.io/announcing_taiganext.html).chore: readme announce taiga-next

 
Where can I find documentation on how to update Taiga to new versions on a self-hosted installation from source?

**Comment by bameda** [comment]
You can find documentation about that at https://docs.taiga.io/#upgrading-guide
