### ISSUE TITLE
role and role_id clarification in api documentation

### ISSUE THREAD

**Issue by mkpelletier** [taigaio/taiga-back#1014]
Greetings,

So far, I love Taiga.  It has a great overall UI- clean and simple.  Well done!

With regard to my issue, I am attempting to utilise the api, but I am running into issues with the documentation.  There are a few places where where the criteria for a given call is insufficiently documented.  A case in point is when making a call to memberships.  The required parameters specify include "role": 3,  however there is no clear indication as to what this detail is or where it can be found in Taiga.  As a result, my attempt to call the method returns "Invalid pk '1' - object does not exist."

All that to say, is there a place where I can find this detail?  Could this information be added to the api documentation?

Thanks in advance for your help!

**Comment by mkpelletier** [comment]
Okay, I see one needs to query the project detail to find the role numbers.  This was tough to find.  Perhaps this can be cross-referenced in the api documentation? I think this would help for newcomers to the api.

Thanks again for the amazing work!

**Comment by superalex** [comment]
Thank you very much @mkpelletier!
I think you are right, we should improve this part of the documentation to make it clearer.
