### ISSUE TITLE
Typo in API Docs

### ISSUE THREAD

**Issue by nomorebugs** [taigaio/taiga-back#1017]
There is a little typo in the excellent API documentation.
In the membership section (https://taigaio.github.io/taiga-doc/dist/api.html#memberships-create) it says:
 ```
curl -X POST \
-H "Content-Type: application/json" \
-H "Authorization: Bearer ${AUTH_TOKEN}" \
-d '{
        "project": 1,
        "role": 3,
        "username": "test-user@test.com"
    }' \
-s http://localhost:8000/api/v1/memberships
```
But 
 ```
curl -X POST \
-H "Content-Type: application/json" \
-H "Authorization: Bearer ${AUTH_TOKEN}" \
-d '{
        "project": 1,
        "role": 3,
        "email": "test-user@test.com"
    }' \
-s http://localhost:8000/api/v1/memberships
```
would be correct.

**Comment by superalex** [comment]
Hello @nomorebugs 

It should be username and it allows and email or an username. If you send the post with an email attribute it shouldn't work.

**Comment by nomorebugs** [comment]
@superalex 
I am using stable branch commit ce530e8e7127b0db9a0415c1d138ee6a6417d9fb . I don't know if the api definitions changed since then (I couldn't find documentation for older releases). 
But for this version I use 'email' attribute, which works and 'username' doesn't work.
Was this changed in newer versions?

**Comment by nomorebugs** [comment]
For "3.1.0 Perovskia Atriplicifolia (2017-03-10)" I found in changelog:

- Memberships API endpoints now allows using usernames and emails instead of using only emails.

Maybe API was changed at that point. Is there any resource to keep track of API changes? Thx and sorry for filing a wrong issue report.

**Comment by superalex** [comment]
You are welcom @nomorebugs , thank you very much for reporting ;)

API changed with that release. Right now the only resource to track the API changes is the github repo: https://github.com/taigaio/taiga-doc/commits/master/api/memberships/bulk-create.adoc

The doc update was done in this commit: https://github.com/taigaio/taiga-doc/commit/24071015a3f5029a7d7dda90096b90e8901b9dc0#diff-87427209a0e564568358ac6fae7715a0
