### ISSUE TITLE
[Q] How do i get authentication token for non-password user?

### ISSUE THREAD

**Issue by Muyv** [taigaio/taiga-back#102]
The users are created and login by gitlab(self-hosted),  in the django-admin page, i can see these users has no password been set.
When i want integrate taiga using my code, i need to use taiga rest api, but to call each api must provide token.
To get token, must call auth api, the [doc](https://docs.taiga.io/api.html#_authentication) shows two auth type.

- the `Standard token authentication` should have to provide password, but the users has no password. in fact they SHOULD NOT set password, avoid user login is the original requirement, one purpose of integration is to make auth implicitly.
- the `Application token authentication` also requires auth token, and seems more complicated to use, and i am not sure if it could satisfy my requirements.

Soooo.. how to make rest api calls as a standard user?

**Comment by yamila-moreno** [comment]
Hi there!

Do you know that we have [Taiga Community](https://community.taiga.io/) for questions? Please, check there; maybe another user has already ask something similar. If not, create your own. There are people there willing to help, members of the Taiga team members and other users.

To simplify  the process, we will systematically close all issues that are general support questions and redirect people to Taiga Community.

Taiga Team
