### ISSUE TITLE
Git Integration

### ISSUE THREAD

**Issue by zkanda** [taigaio/taiga-back#102]
Do you plan on supporting git/github?

**Comment by ahmedkorany** [comment]
+1 bitbucket

**Comment by superalex** [comment]
We included github + gitlab + bitbukect integration in taiga core some time ago! ;)

And via external plugins with gogs

**Comment by marceloboeira** [comment]
Why is the issue still open then ?

**Comment by superalex** [comment]
Good question :)

**Comment by marceloboeira** [comment]
@superalex  kkk :+1:

**Comment by ahmedkorany** [comment]
What is gogs ?

**Comment by superalex** [comment]
@ahmedkorany it's a self hosted git service -> https://github.com/gogits/gogs

**Comment by ayr-ton** [comment]
+1 gitlab

**Comment by mkaito** [comment]
What about standalone git or gitolite?

**Comment by bameda** [comment]
@frederico https://taiga.io/support/github-integration/

**Comment by n3rV3** [comment]
+1 gitolite and standalone git

**Comment by mkaito** [comment]
Also, gogs.

**Comment by bameda** [comment]
@mkaito https://tree.taiga.io/support/integrations/gogs-integration/
