### ISSUE TITLE
PATCH on /api/v1/userstories/154 returns 504 Gateway Time-out

### ISSUE THREAD

**Issue by saleemepoch** [taigaio/taiga-back#1048]
**Do you want to request a *feature* or report a *bug*?**
Bug (I think)

**What is the current behavior?**
I try to assign a story to a user, but it doesn't save the assignment.

**If the current behavior is a bug, please provide the steps to reproduce.**
E.g. go to KANBAN, for an unassigned story, click on assign then select a user.

**What is the expected behavior?**
I expect it to assign the story to a user 

**Is it happening in taiga.io or in your own instance?**
In our own instance. I followed this guide to setup taiga:
https://taigaio.github.io/taiga-doc/dist/setup-production.htm

**What browser/version are you using?**
Both Chrome and Firefox (and I suspect any other browser I may use)

**Are there any console errors *(Ctrl + F12)* in red?**
Chrome console shows after a while the call fails and returns 503 Gateway Time-out.

nginx.error.log shows this:

2017/12/05 22:10:29 [error] 3014#3014: *278 upstream timed out (110: Connection timed out) while reading response header from upstream, client: _my-ip-address_, server: _example.com_, request: "PATCH /api/v1/userstories/154 HTTP/1.1", upstream: "http://127.0.0.1:8001/api/v1/userstories/154", host: "_example.com_", referrer: "https://_example.com_/project/admin-website-2018/us/37?kanban-status=45"

**Comment by superalex** [comment]
If taiga is working in synchronous mode (by default) the problem could be related to an email configuration problem (Taiga can't send the notification and it fails).
