### ISSUE TITLE
Signed up on tree.taiga.io as directed from taiga.io site

### ISSUE THREAD

**Issue by Hueristic** [taigaio/taiga-back#1053]
I'm signed into /tree.taiga.io but taiga.io states that user account does not exist.

**Comment by superalex** [comment]
Hello!.

It seems like a problem related to tree.taiga.io instance and not directly to the software. Could you please write to support@taiga.io explaining your problem?

Regards,

**Comment by Hueristic** [comment]
Thank you. :)
