### ISSUE TITLE
Circus not on apt

### ISSUE THREAD

**Issue by ThaJay** [taigaio/taiga-back#1063]
sudo apt-get install -y circus

The only circus instance I have is through pip and I can't get it to rus as a deamon.

Sorry if this seems obvious to you, I am a dev and not great at ops.

**Comment by theriverman** [comment]
```
admin@taiga:~$ apt-cache search circus
chaussette - WSGI Server for Circus
circus - process & socket manager. It can be used to monitor and control
circuslinux - Clowns are trying to pop balloons to score points!
circuslinux-data - data files for circuslinux
admin@taiga
```

It is indeed in the default repository.
What's your OS and what's are your repositories? Did you change your used repositories recently?

**Comment by ThaJay** [comment]
I'm sorry, I was too quick to post. The server our Taiga instance runs on still uses Ubuntu 14.04. At the moment I have it installed globally through pip but the deamon does not seem to be available as a service. I should probably leverage our Supervisor install to keep it running through reboots.
