### ISSUE TITLE
502 Bad Gateway - When accessing Taiga (via IP)

### ISSUE THREAD

**Issue by andi1479** [taigaio/taiga-back#1066]
After setting up Taiga Production (http://taigaio.github.io/taiga-doc/dist/setup-production.html) on Ubuntu 16.04.3 LTS and set up everything I can access to Taiga via "10.0.0.14" in which I will be redirected to "/discover", everything is working perfectly fine, but I cant access Taiga-Back via my IP (but via localhost on the server). I also can not create a user because of a 502 Bad Gateway (last screenshot).

![image](https://user-images.githubusercontent.com/12195933/35185199-9fd569a2-fe00-11e7-8844-d30a2bec2bf2.png)
![image](https://user-images.githubusercontent.com/12195933/35185205-b410065c-fe00-11e7-8f13-23dd5d8e86d0.png)
Nginx has default values like in (7.2) --> Documentation

Please help guys...

**What is the expected behavior?**
Work without any error, Access Taiga-back, Create user...

**Is it happening in taiga.io or in your own instance?**
It happens when I connect to my Virtual Machine that hosts Taiga. (IP of Machine - 10.0.0.14)

**What browser/version are you using?**
Google Chrome / 63.0.3239.132

**Are there any console errors *(Ctrl + F12)* in red?**
These Errors appear right after connecting to the startpage.
![image](https://user-images.githubusercontent.com/12195933/35185161-12958e00-fe00-11e7-9cb4-259003c86721.png)

Thanks Andi

**Comment by theriverman** [comment]
Let's see..
Are you trying to access Taiga from your host computer or from the VM itself?
What's the public IP of your virtualized linux towards your host computer?

Issue: `curl http://127.0.0.1:8001/api/v1/` inside your Linux VM.
What do you get? An error message saying connection refused or a huge JSON reply?

if you hit `circusctl status` what do you get?

according to the 502 error message It looks like your API is not accessible to your browser
that could either mean that your backend is down or or your nginx fails to reverse-proxy it or something else..

**Comment by andi1479** [comment]
@theriverman Thank you very much for replying! I booted up a brand new 16.4 version and restarted the whole process of installing again. I think the problem was circusctl. 
Now everything is working fine, but 1 thing.
It seems like pictures are missing?

![image](https://user-images.githubusercontent.com/12195933/35187243-06f98ec2-fe21-11e7-824c-5ca45d069782.png)

The pictures are missing and when I hover over the admin I cant click items in the dropdown, because it will disappear before I reach them. (prob the picture prob?)

Greetings, Andi

**Comment by andi1479** [comment]
FIXED
- UserPictures fixed by setting gravatar to false in conf.json

- previous fail by reinstalling everything

**Comment by jianghong3** [comment]
@andi1479 I have the same problem with you.  You write: "I booted up a brand new 16.4 version and restarted the whole process of installing again. I think the problem was circusctl." What do you do specifically?
