### ISSUE TITLE
E-Mail queue not cleared

### ISSUE THREAD

**Issue by thejockel** [taigaio/taiga-back#1067]
Hey,
we are running taiga on Ubuntu 16.04.3 LTS.
Version Back: 3.1.0-34-g61c0653
Version Front: 3.1.0-stable-14-g93bbd82

The system is used by about 150 users.
Now we want to setup E-Mail notifications for the users.

We decided to use the async process.
Unfortunately our E-Mail provider (Exchange 2016) only allows to send 10 mails per minute.
Also we are note allowed to change by our parent company.

So send_notifications fails with: smtplib.SMTPSenderRefused: (421, b'4.4.2 Message submission rate for this client has exceeded the configured limit', 'taiga@xxxxxxxxxxxxx')

When running send_notifications 10 mails are sent, but not removed from the mail queue.
So when we start send_notifications again, exact the same mails are send again.

Thanks in advance
Jockel
<br><br>

## E-Mail Settings
CHANGE_NOTIFICATIONS_MIN_INTERVAL = 300
DEFAULT_FROM_EMAIL = "taiga@xxxxxxxxxxxxxxxxxxxx"
SERVER_EMAIL = DEFAULT_FROM_EMAIL
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_USE_TLS = True
EMAIL_HOST = "mail.xxxxxxxxxxxxxxxxxxxx"
EMAIL_HOST_USER = "taiga@xxxxxxxxxxxxxxxxxxxx"
EMAIL_HOST_PASSWORD = "xxxxxxxxxxxxxxxxxxxx"
EMAIL_PORT = 587

<br><br>
## Log
$ taiga-back && workon taiga && python manage.py send_notifications
Trying import local.py settings...
WARNING	Property: Unknown Property name. [6:51: -webkit-text-size-adjust]
WARNING	Property: Unknown Property name. [6:82: -ms-text-size-adjust]
WARNING	Property: Unknown Property name. [7:23: mso-table-lspace]
WARNING	Property: Unknown Property name. [7:45: mso-table-rspace]
WARNING	Property: Unknown Property name. [8:17: -ms-interpolation-mode]
ERROR	Property: Invalid value for "CSS Level 2.1" property: 0.8rem 3rem [178:17: padding]
WARNING	Property: Unknown Property name. [277:55: -webkit-text-size-adjust]
WARNING	Property: Unknown Property name.
WARNING	Property: Unknown Property name. [1:1: -webkit-text-size-adjust]
WARNING	Property: Unknown Property name. [1:31: -ms-text-size-adjust]
WARNING	Property: Unknown Property name. [1:1: -webkit-text-size-adjust]
WARNING	Property: Unknown Property name. [1:31: -ms-text-size-adjust]
WARNING	Property: Unknown Property name. [1:1: -webkit-text-size-adjust]
WARNING	Property: Unknown Property name. [1:31: -ms-text-size-adjust]
WARNING	Property: Unknown Property name. [1:1: -webkit-text-size-adjust]
WARNING	Property: Unknown Property name. [1:31: -ms-text-size-adjust]
WARNING	Property: Unknown Property name. [1:1: -webkit-text-size-adjust]
WARNING	Property: Unknown Property name. [1:31: -ms-text-size-adjust]
WARNING	Property: Unknown Property name. [1:1: mso-table-lspace]
WARNING	Property: Unknown Property name. [1:20: mso-table-rspace]
WARNING	Property: Unknown Property name. [1:1: mso-table-lspace]
WARNING	Property: Unknown Property name. [1:20: mso-table-rspace]
WARNING	Property: Unknown Property name. [1:1: -ms-interpolation-mode]
ERROR	Property: Invalid value for "CSS Level 2.1" property: 0.8rem 3rem [1:138: padding]
......
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/home/taiga/taiga-back/taiga/projects/notifications/management/commands/send_notifications.py", line 32, in handle
    send_sync_notifications(change_notification.pk)
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/home/taiga/taiga-back/taiga/projects/notifications/services.py", line 294, in send_sync_notifications
    email.send(user.email, context, headers=headers)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/djmail/template_mail.py", line 122, in send
    return email.send()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/mail/message.py", line 342, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/mail/backends/smtp.py", line 107, in send_messages
    sent = self._send(message)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/mail/backends/smtp.py", line 123, in _send
    self.connection.sendmail(from_email, recipients, message.as_bytes(linesep='\r\n'))
  File "/usr/lib/python3.5/smtplib.py", line 862, in sendmail
    raise SMTPSenderRefused(code, resp, from_addr)
smtplib.SMTPSenderRefused: (421, b'4.4.2 Message submission rate for this client has exceeded the configured limit', 'taiga@xxxxxxxxxxxxx')

**Comment by migonzalvar** [comment]
The database object `notification` is where taiga gathers the information to be notified by email. Each notification can generate emails messages to more than one user.

If one of these sending email attempts fail, the notification is not deleted so we need to start over.

This is the relevant source code fragment:

```python
# taiga-back/taiga/projects/notifications/services.py
@transaction.atomic
def send_sync_notifications(notification_id):
    ...

    for user in notification.notify_users.distinct():
        ...
        email.send(user.email, context, headers=headers)

    notification.delete()
```

I'm not sure which is the best approach to avoid your issue. A naive solution could be to add a `time.sleep()` just after every `email.send()` as a poor's man throttling mechanism.

```python
# taiga-back/taiga/projects/notifications/services.py
@transaction.atomic
def send_sync_notifications(notification_id):
    ...

    for user in notification.notify_users.distinct():
        ...
        email.send(user.email, context, headers=headers)
        import time; time.sleep(6)  # 10 mails per second

    notification.delete()
```

What do you think?

**Comment by thejockel** [comment]
@migonzalvar Thanks for the support.
This solved my problem.
