### ISSUE TITLE
Getting 500 internal server error for API (projects/by_slug?slug=)

### ISSUE THREAD

**Issue by Pavithrajas** [taigaio/taiga-back#1070]
*Bug:* 
Taiga page is not getting loaded. It's returning 500 internal server error for API (https://api.taiga.io/api/v1/projects/by_slug?slug=aarthivideep-keysmith-and-contentgrid)

Browser: Chrome latest version

**Comment by migonzalvar** [comment]
This doesn't seem an issue related with taiga-back source code.

I really hope everything is working now. If not, please take a look to https://tree.taiga.io/support/ and don't hesitate in contact with support.

Thank you!
