### ISSUE TITLE
Attachments exposed publicly

### ISSUE THREAD

**Issue by kellerjustin** [taigaio/taiga-back#1090]
New to this platform as of about a week ago, but I'm loving it so far. However...

**I've encountered an issue which could be a huge privacy concern:**
Private project (user story) attachments are exposed publicly if you have the link. Granted, an attachment link is very long, but I've replicated this issue on my local instance by shrinking an attachment URL from a private project and accessing it from an unauthenticated browser. I suspect most users would expect that their attachments from a Private Project would not be accessible by an unauthenticated 3rd party.

**Comment by kellerjustin** [comment]
**Before adding an issue**
Please ensure that your issue is not already reported in our [issues list](https://tree.taiga.io/project/taiga/issues?order_by=-created_date).
If this issue was already reported, remember that you can upvote it to raise its importance.
I didn't see this specific issue

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
able to browse an attachment URL directly without authentication

**If the current behavior is a bug, please provide the steps to reproduce.**
copy/paste an attachment URL into an unauthenticated browser session

**What is the expected behavior?**
I would expect a login form to appear

**Is it happening in taiga.io or in your own instance?**
local instance

**What browser/version are you using?**
chrome / firefox

**Are there any console errors *(Ctrl + F12)* in red?**
no

Thanks for reporting!

**Comment by migonzalvar** [comment]
First of all, thank you for interest in Taiga @kellerjustin and @lifenautjoe

The current attachment implementation, as of version 3.3.x,  relies on a secret URL. Disclosing the URL is the same as disclosing the attachment itself.

We talked about it in https://github.com/taigaio/taiga-front/issues/607/#issuecomment-129772169.

We know that our design decision, in spite of being a common practice, could surprise some users and lead to undesired information leaks if misused. That is the reason why we are planning to use a different approach in an upcoming release.

**Comment by kellerjustin** [comment]
@migonzalvar  - thank you for explaining. I will close this issue since it is the same as the one you referenced.

**Comment by phgmhendrix** [comment]
Is this issue is still somewhere on the roadmap?

**Comment by migonzalvar** [comment]
We developed a service and a plugin to protect downloads with a cryptographic token. It is activated in https://taiga.io instance.

The relevant projects in Github with the source code:

- https://github.com/taigaio/taiga-protected
- https://github.com/taigaio/taiga-contrib-protected
