### ISSUE TITLE
Taiga should not endorse docker installation methods

### ISSUE THREAD

**Issue by lifenautjoe** [taigaio/taiga-back#1093]
I've tried the three docker installation options mentioned [here](https://taigaio.github.io/taiga-doc/dist/setup-alternatives.html#setup-taiga-scripts).

They are all broken or halfway broken. Most importantly, it's maintainers appear to have jumped ship and left each user on its own. Pull requests with essential fixes are never revised, issues are ignored, taiga versions are outdated years time. It's complete chaos and I've gone through it for the past few days.

Please remove this installation option from your docs and focus efforts on the installation scripts!

**Comment by bameda** [comment]
Hi @lifenautjoe docker is not officially supported by the Taiga development team. we recomend the script or vagrant setup us an automatic method or production or development setup for a full controll over the process. 

However, there are many taiga images for docker made by the community https://tree.taiga.io/support/misc/community-contributions/#docker

**Comment by lonix1** [comment]
OP is right for the wrong reason :smile: 

Docs should not endorse those docker images as they're old and don't work properly.

Rather, taiga team should support an **official docker image**. Who doesn't use docker nowadays? It's the standard.
