### ISSUE TITLE
[Q] Is this project dead?

### ISSUE THREAD

**Issue by nacho-domatix** [taigaio/taiga-back#111]
As most of issues are not even replied, and code seems to be still since 2020...

**Comment by mkurtipek** [comment]
I wonder the same :)
Jira importer is not working with the cloud version. I might work on it but not sure if it will be worth it.

**Comment by NatachaMenjibar** [comment]
Hi there! The project is alive, but our team is fully focused on Taiga Next (see this post for [further information](https://community.taiga.io/t/announcing-taiganext-and-much-more/107)). Regarding Taiga 6, we are only attending to critical bugs and major performance issues.

Cheers!

**Comment by Chaostheorie** [comment]
@NatachaMenjibar it is awesome to hear that the project is still alive. The contents of the blogpost sounds promising. Is there any approximate date for a first public beta/ release-candidate for Taiga Next?

**Comment by yamila-moreno** [comment]
Hi there!

Do you know that we have [Taiga Community](https://community.taiga.io/) for questions? Please, check there; maybe another user has already ask something similar. If not, create your own. There are people there willing to help, members of the Taiga team members and other users.

To simplify  the process, we will systematically close all issues that are general support questions and redirect people to Taiga Community.

Taiga Team
