### ISSUE TITLE
[Bug] Taiga is completely broken after updating from 3.1

### ISSUE THREAD

**Issue by pierre-le** [taigaio/taiga-back#1111]
**Issue**

After upgrading to 3.3, all modification requests (create a project, add a comment to a US, etc.) are failing, leaving Taiga completely unusable.

I've enabled the debug mode in the backend, and I've included the response on the `joyride` endpoint and when attempting to add a comment.

[taiga_errors.zip](https://github.com/taigaio/taiga-back/files/2034451/taiga_errors.zip)

We currently have a Taiga deployment on version 3.1. Please note that a few months ago, we already tried to upgrade to 3.2, but we've encountered the same issue. After the announcement for version 3.3, we tried again, but it yielded the same results.

**Steps to reproduce**

Follow the official migration procedure from Taiga's website:
https://taigaio.github.io/taiga-doc/dist/upgrades.html#_backend_application

**Is it happening in taiga.io or in your own instance?**

It only happens on our instance.

**What browser/version are you using?**

Not sure if this is relevant, but I'm using Chrome 66.

**Are there any console errors *(Ctrl + F12)* in red?**

If the debug mode is not enabled, we get a "Internal server error".

**Comment by alexhermida** [comment]
@pierre-le make sure you don't get any error doing `python manage.py migrate --noinput` and the base code in `taiga-back` is the same. The error you sent to us is related to a "wrong" `history` object. 

But if the whole system returns to you an error probably is some database inconsistence or a code base change.

**Comment by pierre-le** [comment]
@alexhermida Thanks for the answer, there was no error when performing migrations.
I eventually ended up redeploying the whole Taiga platform from scratch, on another server, and then I reimported the production database and migrated it. And it seems to work fine now.
