### ISSUE TITLE
Duplicated US on the dashboard

### ISSUE THREAD

**Issue by theshauny** [taigaio/taiga-back#1114]
**Do you want to request a *feature* or report a *bug*?**
A bug

**What is the current behavior?**
I see duplicated US on my daskboard (which is real duplicate link to the US).

**If the current behavior is a bug, please provide the steps to reproduce.**
The only USs which are duplicate are thoses with me and another person assigned to it.

**What is the expected behavior?**
It's not because there is another person assigned to the US that it need to be duplicated.

**Is it happening in taiga.io or in your own instance?**
On my own instance. I didn't try in taiga.io.

**What browser/version are you using?**
Google Chrome 66.

**Are there any console errors *(Ctrl + F12)* in red?**
No, nothing in red, even on reload.

Thanks for reporting!

**Comment by alexhermida** [comment]
Thanks for reporting @theshauny 

Fixed in [3.3.8](https://github.com/taigaio/taiga-back/releases/tag/3.3.8)
