### ISSUE TITLE
"column users_user.accepted_terms" does not exist in a fresh installation of 3.3.7

### ISSUE THREAD

**Issue by g0blin79** [taigaio/taiga-back#1116]
**Do you want to request a *feature* or report a *bug*?**
bug 
**What is the current behavior?**
I tried to install the 3.3.7 version in a docker environment. Software starts with success, but when I try to log in I receive in gunicorn logs:

`django.db.utils.ProgrammingError: column users_user.accepted_terms does not exist`

Obviously i ran correctly your migrate scripts (reported by your Setup production environment guidelines):

```
python manage.py migrate --noinput
python manage.py loaddata initial_user
python manage.py loaddata initial_project_templates
python manage.py compilemessages
python manage.py collectstatic --noinput

```

I don't know if it can be a issue related to the fact that I'm running Taiga from a docker env, but honestly I don't think so...it seems that the application is changed but not the migration schemas

**If the current behavior is a bug, please provide the steps to reproduce.**

- Start a fresh installation of Taiga enabling "info" log level for gunicorn
- Try to Login
- Check your logs

**What is the expected behavior?**
A correct login

**Is it happening in taiga.io or in your own instance?**
On my own instance

**What browser/version are you using?**
Google Chrome, Firefox, Safari

**Are there any console errors *(Ctrl + F12)* in red?**

```
GET http://MYDOMAIN/api/v1/projects?discover_mode=true&order_by=-total_fans_last_week 500 (Internal Server Error)
GET http://MYDOMAIN/api/v1/projects?discover_mode=true&order_by=-total_activity_last_week 500 (Internal Server Error)
GET http://MYDOMAIN/api/v1/projects?discover_mode=true&is_featured=true 500 (Internal Server Error)
POST http://MYDOMAIN/api/v1/auth 500 (Internal Server Error)
````
Thanks for reporting!

**Comment by alexhermida** [comment]
@g0blin79 please execute `python manage.py showmigrations users` and check if you have applied migration `0026_auto_20180514_1513`.

Make sure that you are connecting with an updated database (or postgresql container if you have it).

**Comment by g0blin79** [comment]
@alexhermida the command output is:

```
users
 [X] 0001_initial
 [X] 0002_auto_20140903_0916
 [X] 0003_auto_20140903_0925
 [X] 0004_auto_20140913_1914
 [X] 0005_alter_user_photo
 [X] 0006_auto_20141030_1132
 [X] 0007_auto_20150209_1611
 [X] 0008_auto_20150213_1701
 [X] 0009_auto_20150326_1241
 [X] 0010_auto_20150414_0936
 [X] 0011_user_theme
 [X] 0012_auto_20150812_1142
 [X] 0013_auto_20150901_1600
 [X] 0014_auto_20151005_1357
 [X] 0015_auto_20160120_1409
 [X] 0016_auto_20160204_1050
 [X] 0017_auto_20160208_1751
 [X] 0018_remove_vote_issues_in_roles_permissions_field
 [X] 0019_auto_20160519_1058
 [X] 0020_auto_20160525_1229
 [X] 0021_auto_20160614_1201
 [X] 0022_auto_20160629_1443
 [X] 0023_json_to_jsonb
 [X] 0024_auto_20170406_0727
 [X] 0025_user_uuid
 [ ] 0026_auto_20180514_1513
```
Then probably the migration `0026_auto_20180514_1513`was not applied.

But I think that something is missing because, as I said,  I had a fresh installation of taiga at the end of which this commands was launched (:

```
python manage.py migrate --noinput
python manage.py loaddata initial_user
python manage.py loaddata initial_project_templates
python manage.py compilemessages
python manage.py collectstatic --noinput
```

I could see the execution of these commands in the log streaming during installation.

**Comment by g0blin79** [comment]
Ok guys, my fault, sorry.

I was using a volume for postgresql container datafiles but I completely forgot. Then at `docker-compose up -d`, the system cannot refresh data and I was using old migrations (done with a previous version of Taiga) in which this update did not exist.

Thanks for your help, you are great and your software is great as well! :)

**Comment by alexhermida** [comment]
Thank you for your comments @g0blin79 :-D
