### ISSUE TITLE
As an unauthenticated user, bookmarks to private project pages return a 404 error message instead of showing the login page

### ISSUE THREAD

**Issue by mfriedetzki** [taigaio/taiga-back#1117]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
As an unauthenticated user bookmarks to private projectpages like https://tree.taiga.io/project/privateExampleProject/issues return an error: 

> NOT FOUND 
> Error 404. The page you are looking for no longer exists. Perhaps you can return back to TAIGA homepage and see if you can find what you are looking for.

**If the current behavior is a bug, please provide the steps to reproduce.**

1. As an authenticated user bookmark the issue page of an private project. 
2. Log out of Taiga.
3. Open bookmarked URL as an unauthenticated user.

**What is the expected behavior?**
It should show the login page for authentication.

**Is it happening in taiga.io or in your own instance?**
taiga.io and own instance since upgrade to version 3.3.3 (version 3.1.0 showed the expected behavior)

**What browser/version are you using?**
Mozilla Firefox 60 and Google Chrome 66

**Are there any console errors *(Ctrl + F12)* in red?**
No

**Comment by alexhermida** [comment]
@mfriedetzki in fact this is a `feature` not a bug. Every project URL returns a NOT FOUND for not giving extra information about registered projects. This is the original Taiga issue: https://tree.taiga.io/project/taiga/issue/5240

**Comment by phgmhendrix** [comment]
Aha, but this is quite a hassle for our customers.
Could this be made a configurable option?

**Comment by alexhermida** [comment]
@phgmhendrix yes of course. If we receive more feedback about that feature maybe we can develop them in the future. You can use the public project 
https://tree.taiga.io/project/taiga/ to ask for new features and vote them.

**Comment by phgmhendrix** [comment]
btw. when always redirecting to the login page you do not give away any info... only after login you receive 404 or the correct page. This would be the preferable way in my humble opinion.

**Comment by phgmhendrix** [comment]
As stated in [https://tree.taiga.io/project/taiga/issue/4415](https://tree.taiga.io/project/taiga/issue/4415) this issue will soon be resolved.
