### ISSUE TITLE
A closed User Story assigned to multiple people only computes to the first asignee

### ISSUE THREAD

**Issue by renanliberato** [taigaio/taiga-back#1121]
**Before adding an issue**
Please ensure that your issue is not already reported in our [issues list](https://tree.taiga.io/project/taiga/issues?order_by=-created_date).
If this issue was already reported, remember that you can upvote it to raise its importance.

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
A closed Issue assigned to multiple people only computes to the first asignee.

**If the current behavior is a bug, please provide the steps to reproduce.**
- Create an User Story on 'Ready'.
- Assign yourself to the User Story.
- Assign another member to the User Story.
- Pass the User Story to 'Done'.
- Check the two member's profile:
  - The first member will have the closed US counted on "Closed US".
  - The second member will not have the closed US counted on "Closed US".

**What is the expected behavior?**
- Check the two member's profile:
  - The first member will have the closed US counted on "Closed US".
  - The second member will have the closed US counted on "Closed US".

**Is it happening in taiga.io or in your own instance?**
It is happening in taiga.io

**What browser/version are you using?**
Google Chrome Version 67.0.3396.87 - Mac OS

**Are there any console errors *(Ctrl + F12)* in red?**
No.

Thanks for reporting!

**Comment by renanliberato** [comment]
I looked that when getting the stats for the user profile on [taiga.user.services.get_stats_for_user](https://github.com/taigaio/taiga-back/blob/1dc19695b57df90f338ad06866b0712cb794c7bf/taiga/users/services.py#L158) the query looks for _assigned_to_ column instead of _assigned_users_, (as I've seen in [taiga.projects.userstories.models.UserStory](https://github.com/taigaio/taiga-back/blob/master/taiga/projects/userstories/models.py#L97)) where I think the multiple assigned users are.

I don't have much experience with Python, but later I'll try to setup the [dev environment](https://github.com/taigaio/taiga-back#setup-development-environment) and check if my assumptions are correct.

**Comment by alexhermida** [comment]
@renanliberato this must be fixed in the current _master_ and _stable_ branch. Thanks for reporting 😄

**Comment by renanliberato** [comment]
Thank you too!
