### ISSUE TITLE
A User Story assigned to multiple people is not filtered corrected in kanban

### ISSUE THREAD

**Issue by renanliberato** [taigaio/taiga-back#1124]
**Before adding an issue**
Please ensure that your issue is not already reported in our [issues list](https://tree.taiga.io/project/taiga/issues?order_by=-created_date).
If this issue was already reported, remember that you can upvote it to raise its importance.

**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
A closed Issue assigned to multiple people only computes to the first asignee.

**If the current behavior is a bug, please provide the steps to reproduce.**
- Create an User Story on 'Ready'.
- Assign yourself to the User Story.
- Assign another member to the User Story.
- Filter the kanban board by 'Asigned to' selecting the second member:
  - The User Story will not be listed (only when selecting yourself).

**What is the expected behavior?**
- Filter the kanban board by 'Asigned to' selecting the second member:
  - The User Story will be listed (as will be when selecting yourself).

**Is it happening in taiga.io or in your own instance?**
It is happening in taiga.io

**What browser/version are you using?**
Google Chrome Version 67.0.3396.87 - Mac OS

**Are there any console errors *(Ctrl + F12)* in red?**
No.

Thanks for reporting!

**Comment by renanliberato** [comment]
I looked at this service [taiga.projects.userstories.services. get_userstories_filters_data](https://github.com/taigaio/taiga-back/blob/master/taiga/projects/userstories/services.py#L675). It calls [_get_userstories_assigned_to](https://github.com/taigaio/taiga-back/blob/master/taiga/projects/userstories/services.py#L355) function, which I think is responsible for filtering by assigneds and should be using in any matter the association _assigned_users_, (as I've seen in [taiga.projects.userstories.models.UserStory](https://github.com/taigaio/taiga-back/blob/master/taiga/projects/userstories/models.py#L97)) where I think the multiple assigned users are.

I don't have much experience with Python, but later I'll try to setup the [dev environment](https://github.com/taigaio/taiga-back#setup-development-environment) and check if my assumptions are correct.

**Comment by renanliberato** [comment]
The Assigned User Stories are not being counted correctly in the filters tab, when choosing which user to select. Should I open another issue regarding this bug?

**Comment by alexhermida** [comment]
@renanliberato thank you so much for your feedback. We've already working on this issue. It will be available in next release. It's not necessary to open another issue because it's related to the same functionality.

**Comment by alexhermida** [comment]
@renanliberato this is fixed in current release 3.3.13

Thanks for your feedback!
