### ISSUE TITLE
“ASSIGNED TO” of "FILTERS " ,the number of Member's Stories is not correct

### ISSUE THREAD

**Issue by geekmingl** [taigaio/taiga-back#1138]
hi , recently i was ueing taiga.io. i think it is a great tool for project management.but the number of Member's Stories is not correct when i click “ASSIGNED TO” of BACKLOG FILTERS " .

**1 version**
  [1]taiga-back version: 3.3.10
  [2]taiga-front-dist version: 3.3.10
**2 steps**
  [1] create a story 
  [2]assigned to member Jack and memberTom
  [3]“ASSIGNED TO” of "FILTERS ".  
      **the number of Jack’s Stories is 1;
      the number of Jack’s Stories is 0;**

Thanks for reading.

**Comment by alexhermida** [comment]
@geekmingl this is fixed in current release *3.3.13*

Thanks for your feedback ;-)

**Comment by geekmingl** [comment]
it's cool. I can't wait to try it.
