### ISSUE TITLE
Report: Please include an "id" column in the CSV

### ISSUE THREAD

**Issue by muellert** [taigaio/taiga-back#1142]
**Do you want to request a *feature* or report a *bug*?**

This is a feature request.

**What is the current behavior?**

If I look at the User Stories Report of a project, the CSV does not contain IDs for the sprints and user stories, making it a bit difficult to identify them in the database, because there seems to be no search facility for eg. the sprint or user story name, as opposed to their id.

**If the current behavior is a bug, please provide the steps to reproduce.**

In a project, go to "Settings", then "Reports", and download a User Story Report. Open it and see.

**What is the expected behavior?**

It would be nice to have additional columns like userstory_id and sprint_id to ease matching rows against the database.

**Is it happening in taiga.io or in your own instance?**

This is happening on my own instance. Should be latest-stable everytime.

**Comment by muellert** [comment]
Alternative (better?) idea: Expose all report types via the API.

**Comment by alexhermida** [comment]
@muellert we added those related id's fields in current _stable_ and _master_ branch.
