### ISSUE TITLE
Where to get the jira certificate?

### ISSUE THREAD

**Issue by zhaoyuxuan** [taigaio/taiga-back#1149]
I am trying to enable the built-in jira importer, I wonder where to get the public cert and cert in local.py

**Comment by theriverman** [comment]
https://tree.taiga.io/support/importers/jira-importer/

You got this?

**Comment by zhaoyuxuan** [comment]
I followed the link you sent, but the setting/local.py, in order to enable the jira importer, I need to fill in public_cert, cert and customer key, I wonder where do I get those. 
https://github.com/taigaio/taiga-back/blob/master/settings/local.py.example#LC190

**Comment by theriverman** [comment]
I'm no JIRA guru, but I found these for you:
https://confluence.atlassian.com/display/JIRA042/Configuring+OAuth+Consumer+Information+for+JIRA

https://confluence.atlassian.com/display/JIRA042/Configuring+an+OAuth+Service+Provider+in+JIRA
