### ISSUE TITLE
Development Environment?

### ISSUE THREAD

**Issue by benyanke** [taigaio/taiga-back#1162]
I am starting to work on a full PRs for both front and back.

Is there any core-developer-focused docker-compose tools or similar environments to assist in setting up a development environment?

**Comment by alexhermida** [comment]
@benyanke you have available some non official documentation at https://taigaio.github.io/taiga-doc/dist/setup-alternatives.html#_important_notes_about_using_strong_taiga_docker_strong 

I hope it helps.

**Comment by benyanke** [comment]
Thanks!
