### ISSUE TITLE
how to reset password

### ISSUE THREAD

**Issue by itnikita** [taigaio/taiga-back#1164]
I am admin of a taiga system.someone forget the password.
How can I do to reset or change the password of a normal user?

**Comment by theriverman** [comment]
Open the admin panel (/admin/), go to users, find the user, then you can set a new password on the top.

**Comment by alexhermida** [comment]
@itnikita as @theriverman commented you can do it from the Django admin panel. Moreover you could give to your users the password recovery url https://{host}/forgot-password.

You can use also the Taiga mailing list https://groups.google.com/forum/#!forum/taigaio for this kind of questions.
