### ISSUE TITLE
How do I manage my postgresql?

### ISSUE THREAD

**Issue by l903404160** [taigaio/taiga-back#1178]
I have been deploy the taiga on my server Ubuntu 16.04.And then the question is how can I delete some useless test users? I try to use psql syntaxes, but there were no response while I was typig. Or there are some other ways to solve this problem?

**Comment by l903404160** [comment]
I directly use the ip address.And then the browser shows that URL was not found:). I think there must be something I have made some mistakes. And I found the /admin ,at the beginning , was not available. 😄

**Comment by alexhermida** [comment]
@l903404160 as @theriverman commented you can use the Django admin panel. If you didn't solve it you can ask for advice on the mailing list at https://groups.google.com/d/forum/taigaio.  Taiga community can help you.
