### ISSUE TITLE
Taiga Upgrade 

### ISSUE THREAD

**Issue by ag-ose** [taigaio/taiga-back#119]
Hello,

I need upgrade Taiga in production environment from version 4.2 to latest 6 version.

https://docs.taiga.io/upgrades-5to6.html

I need to know if this upgrade can be done directly from version 4.2 to latest 6 version or should I upgrade from version 4 to version 5 and after then from version 5 to latest 6 version.

Hope anyone had done this in the past and know how is the best way to upgrade Taiga for production environment.

Thanks!
Nice day :)

**Comment by bameda** [comment]
This is the documentation to upgrade from older version https://docs.taiga.io/upgrades-older.html

We haven't tested it but it should be possible. You can try to do the update once, but applying the sum of the different configurations of each update from the initial one.

But, first, **remember to make a system backup** (db, settings and media files).

And for future questions or support request like these, we would like you to use our new [community space](https://community.taiga.io/).  We prefer to reserve this space for bugs.

**Comment by ag-ose** [comment]
Thanks!
