### ISSUE TITLE
INTEGRATING TAIGA IN OTHER APPS 

### ISSUE THREAD

**Issue by ajay01994** [taigaio/taiga-back#1191]
Hi all , Thanks for making taiga , i want to understand how to integrate taiga in other apps , i am trying to add taiga to QGIS , but i do not know how to do that , sorry i am new to it .
Thanks

**Comment by alexhermida** [comment]
@ajay01994 you have full Taiga documentation in http://taigaio.github.io/taiga-doc/dist/ and details about the all API calls in http://taigaio.github.io/taiga-doc/dist/api.html

You must use Taiga mailing list https://groups.google.com/forum/#!forum/taigaio for this kind of questions. Thanks!
