### ISSUE TITLE
Interface error reporting, hoping to help solve.

### ISSUE THREAD

**Issue by dwwendy** [taigaio/taiga-back#1196]
**Before adding an issue**
Please ensure that your issue is not already reported in our [issues list](https://tree.taiga.io/project/taiga/issues?order_by=-created_date).
If this issue was already reported, remember that you can upvote it to raise its importance.

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Is it happening in taiga.io or in your own instance?**

**What browser/version are you using?**

**Are there any console errors *(Ctrl + F12)* in red?**

Thanks for reporting!

**Comment by dwwendy** [comment]
root@Taiga01:/home/taiga/taiga-back# curl -i http://taiga.vargo.com.cn/api/v1/tasks/990
HTTP/1.1 401 Unauthorized
Server: nginx/1.10.3 (Ubuntu)
Date: Mon, 12 Nov 2018 08:44:43 GMT
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Expose-Headers: x-pagination-count,x-paginated,x-paginated-by,x-pagination-current,x-pagination-next,x-pagination-prev,x-site-host,x-site-register,taiga-info-total-opened-milestones,taiga-info-total-closed-milestones,taiga-info-project-memberships,taiga-info-project-is-private,taiga-info-order-updated
Vary: Cookie, Accept-Language
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: POST,GET,OPTIONS,PUT,DELETE,PATCH,HEAD
Access-Control-Allow-Headers: content-type,x-requested-with,authorization,accept-encoding,x-disable-pagination,x-lazy-pagination,x-host,x-session-id,set-orders
Allow: GET, PUT, PATCH, DELETE, HEAD, OPTIONS
Access-Control-Allow-Origin: *
WWW-Authenticate: Bearer realm="api"
Access-Control-Max-Age: 3600
Content-Language: en

{"_error_type": "taiga.base.exceptions.NotAuthenticated", "_error_message": "Authentication credentials were not provided."}root@Taiga01:/home/taiga/taiga-back#

**Comment by alexhermida** [comment]
@dwwendy you can follow the instructions to make API calls at http://taigaio.github.io/taiga-doc/dist/api.html.

Also, you can ask for advice on the mailing list at https://groups.google.com/d/forum/taigaio.  Taiga community can help you, there are more eyes and maybe someone had had the same issue.
