### ISSUE TITLE
[Q] Backend Memory Usage

### ISSUE THREAD

**Issue by Thanzex** [taigaio/taiga-back#12]
Hi there! I'm really interested in using taiga, I installed it to run some tests and couldn't help but notice relatively high memory usage of the backend, my mostly empty instance is using ~1GB of RAM between its components.
Of course, I understand this is not a problem for professional teams, but as a small team with limited resource availability, I was wondering if something can be done to decrease memory consumption. 

I don't know the inner workings of the software, but `taiga-async` for example seems to be another whole instance of the main backend, which combined use ~700MB of RAM. 

Does the backend really need this amount of memory usage? Could it be possible to reduce its footprint?

**Comment by yamila-moreno** [comment]
Hi there!

Do you know that we have [Taiga Community](https://community.taiga.io/) for questions? Please, check there; maybe another user has already ask something similar. If not, create your own. There are people there willing to help, members of the Taiga team members and other users.

To simplify  the process, we will systematically close all issues that are general support questions and redirect people to Taiga Community.

Taiga Team
