### ISSUE TITLE
Taiga doesnt show projects after upgrade

### ISSUE THREAD

**Issue by fabianfritz1994** [taigaio/taiga-back#1217]
**Before adding an issue**
Please ensure that your issue is not already reported in our [issues list](https://tree.taiga.io/project/taiga/issues?order_by=-created_date).
If this issue was already reported, remember that you can upvote it to raise its importance.

**Do you want to request a *feature* or report a *bug*?**
bug
**What is the current behavior?**
After upgrading taiga with the info here
https://taigaio.github.io/taiga-doc/dist/upgrades.html
from
3.4.6 (2018-10-30) 
to 
4.0.3 (2018-12-11)

I am not able to see any of my projects anymore. If I click on my user and then on the latest activities I got the error shown below. I restarted the whole host and do the upgrade steps again but nothing changed.

**If the current behavior is a bug, please provide the steps to reproduce.**

Request Method: | GET
-- | --
Request URL: | https://fritz-cloud.ddns.net:8044/api/v1/projects/by_slug?slug=fabianfritz-prasidialjahr
Django Version: | 1.11.16
Exception Type: | ProgrammingError
Exception Value: | relation   "settings_userprojectsettings" does not exist   LINE 178:                    FROM   settings_userprojectsettings                                     ^
Exception Location: | /home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/backends/utils.py   in execute, line 64
Python Executable: | /home/taiga/.virtualenvs/taiga/bin/python3.5
Python Version: | 3.5.2
Python Path: | ['/home/taiga/taiga-back',    '/home/taiga/taiga-back',    '/home/taiga/.virtualenvs/taiga/bin',    '/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages',    '/home/taiga/.virtualenvs/taiga/lib/python35.zip',    '/home/taiga/.virtualenvs/taiga/lib/python3.5',    '/home/taiga/.virtualenvs/taiga/lib/python3.5/plat-x86_64-linux-gnu',    '/home/taiga/.virtualenvs/taiga/lib/python3.5/lib-dynload',    '/usr/lib/python3.5',    '/usr/lib/python3.5/plat-x86_64-linux-gnu',    '/home/taiga/taiga-back']
Server time: | Sat, 15   Dec 2018 17:05:04 +0000

**What is the expected behavior?**
show projects as before
**Is it happening in taiga.io or in your own instance?**
own instance
**What browser/version are you using?**
chrome / ie both 
**Are there any console errors *(Ctrl + F12)* in red?**
see above 
Thanks for reporting!

**Comment by migonzalvar** [comment]
It seems to me that database migration was not applied. In https://taigaio.github.io/taiga-doc/dist/upgrades.html the step is:

```bash
python manage.py migrate --noinput
```

**Comment by fabianfritz1994** [comment]
Hey,
the step emntioned above was already executed, but with an error:

(taiga) taiga@fritz-ubuntu-production:~/taiga-back$ python manage.py migrate --noinput
Trying import local.py settings...
Operations to perform:
  Apply all migrations: admin, attachments, auth, bitbucket, contact, contenttypes, custom_attributes, djmail, easy_thumbnails, epics, external_apps, feedback, github, gitlab, gogs, history, issues, likes, milestones, notifications, projects, references, sessions, settings, tasks, timeline, users, userstorage, userstories, votes, webhooks, wiki
Running migrations:
  Applying custom_attributes.0013_auto_20181022_1624... OK
  Applying custom_attributes.0014_auto_20181025_0711... OK
  Applying notifications.0008_auto_20181010_1124... OK
  Applying projects.0061_auto_20180918_1355...Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: relation "projects_issuestatus_project_id_slug_ca3e758d_uniq" already exists


Meanwhle I was able to export my projects on a backup of the host (which was von Taiga 3.6) into JSON and import these projects in an empty database under taiga 4.0 except 1 project that is might causing the issue. When I try to upload this project I got this error in  gunicorn.stderr.log:


Trying import local.py settings...
ERROR:2018-12-18 22:25:49,720: Internal Server Error: /api/v1/projects
Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in exe$
    return self.cursor.execute(sql, params)
psycopg2.ProgrammingError: relation "settings_userprojectsettings" does not exist
LINE 178:                    FROM settings_userprojectsettings
                                  ^

**Comment by migonzalvar** [comment]
I see @fabianfritz1994.

I don't how, but the changes on migration `projects.0061_auto_20180918_1355` are already applied on the database.

The solution is to fake apply the problematic migration and then continue the migration process. Something like this:

```
./manage.py migrate --fake projects 0061_auto_20180918_1355
./manage.py migrate
```

**Comment by fabianfritz1994** [comment]
Hey,
meanwhile I was able to resolve this issue be deleting one users on the backup and new export of the project. Then I was able to import the project. But for me it is unclear why dis misconfig in the old database was created.

**Comment by migonzalvar** [comment]
Although is working now, I think is important to apply all the migrations now, because if not, you would find problems in the future.
