### ISSUE TITLE
Cannot change port

### ISSUE THREAD

**Issue by rhclayto** [taigaio/taiga-back#1222]
**Do you want to request a *feature* or report a *bug*?** 
Report a *bug*.

**What is the current behavior?**
The API server is starting up on the default port (8000), rather than respecting the settings in local.py.

**If the current behavior is a bug, please provide the steps to reproduce.**

Change the API server port in local.py. Start the server with `python3 manage.py runserver`. Server tries to start on default port. In my case, it also fails because another daemon is running on port 8000.

**What is the expected behavior?**
taiga-back will start with the api server listening on the port set in local.py.

**Is it happening in taiga.io or in your own instance?**
My own instance, Ubuntu 18.04 on a Google Cloud Compute instance.

-----

I have installed taiga-back according to the instruction at http://taigaio.github.io/taiga-doc/dist/setup-production.html . I have adjusted the SITES config in local.py as follows:

```
SITES = {
    "api": {
       "scheme": "http",
       "domain": "localhost:9000",
       "name": "api"
    },
    "front": {
       "scheme": "http",
       "domain": "localhost:9001",
       "name": "front"
    },
}
```

In other words, I have changed the api server port. (For what it's worth, I also tried changing it in common.py.) I try to start the server woth `python3 manage.py runserver`. The following is returned in the shell:
```
taiga@hostname:/var/www/taiga-back$ python3 manage.py runserver       
Trying import local.py settings...
Trying import local.py settings...
Performing system checks...

System check identified no issues (0 silenced).
January 04, 2019 - 02:44:49
Django version 1.11.16, using settings 'settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Error: That port is already in use.
```

And the server quits. I have also tried with `python manage.py runserver`. I have also tried `/home/taiga/.virtualenvs/taiga/bin/gunicorn --workers 4 --timeout 60 -b 127.0.0.1:8001 taiga.wsgi`, to no avail. The result from that is:

```
taiga@hostname:/var/www/taiga-back$ /home/taiga/.virtualenvs/taiga/bin/gunicorn --workers 4 --timeout 60 -b 127.0.0.1:8001 taiga.wsgi
[2019-01-04 02:55:32 +0000] [25806] [INFO] Starting gunicorn 19.7.1
[2019-01-04 02:55:32 +0000] [25806] [INFO] Listening at: http://127.0.0.1:8001 (25806)
[2019-01-04 02:55:32 +0000] [25806] [INFO] Using worker: sync
[2019-01-04 02:55:32 +0000] [25809] [INFO] Booting worker with pid: 25809
[2019-01-04 02:55:32 +0000] [25810] [INFO] Booting worker with pid: 25810
[2019-01-04 02:55:32 +0000] [25812] [INFO] Booting worker with pid: 25812
[2019-01-04 02:55:32 +0000] [25814] [INFO] Booting worker with pid: 25814
Trying import local.py settings...
Trying import local.py settings...
Trying import local.py settings...
Trying import local.py settings...
```

It stops there. `netstat -al` shows nothing listening on the port configured in local.py (9000).

Any idea why the server isn't respecting the setting in local.py?

Edit: I learned that you can change the port used by Django's runserver by appending it to the command line: `python3 manage.py runserver 9000`. So is it accurate to say that the local.py settings are not supposed to tell the app what port to listen on?

Edit2: Changing the gunicorn command line to have `-b 127.0.0.1:9000` also works. So I'm guessingthis should be closed. Perhaps something could be added to the documentation to make it clearer for people trying to change the port. I will revisit this in a couple days, & if there are no responses, I will close it.

**Comment by theriverman** [comment]
Hi,

manage.py is only for development/testing purposes. You can run the development server on a different port though, see 
https://docs.djangoproject.com/en/2.1/ref/django-admin/#runserver

Whatever you changed in common.py should be reverted — there’s nothing to do there in terms of port changing.
In the documentation it’s stated Taiga sports Django as its backend, therefore, changing the port (and other non-installation actions) are not the scope of the production documentation. It has to be kept short, simple and consistent. :)
