### ISSUE TITLE
Avatars and Project-Logos: Permissions denied 403-Error

### ISSUE THREAD

**Issue by virse** [taigaio/taiga-back#1241]
Hey there,

I installed my own instance of Taiga and would like to organize my projects to start with.
But I have some issues with the avatars and project-logos. I am able to upload the images, but the images don't show up afterwards. I get a 403 permission error.

I already added the user taiga to my www-data group, played also with the folder permissions, but no luck.

I use an apache2-installation as described here: [Apache2 documentation #390](https://github.com/taigaio/taiga-back/issues/390)

I only commented out this part due to running the instance with taiga-taiga:

`<IfModule mpm_itk_module> AssignUserId taiga_ws taiga_ws </IfModule>`

The installation is the newest available an was done via manual installation as described in the Howtos without any errors.

Please let me know if you need some more informations.

Thanks for helping me out,
virse

**Comment by theriverman** [comment]
Hi,
All user uploaded content (project logo, attachments, user profile pictures, etc... are stored in `~/taiga-back/media`

That folder is writable by user taiga, but I believe your www-data user/group has no access to that folder.  
This issue, however, is beyond the scope of Taiga as it’s an infrastructural matter using Taiga in a non-supported environment.

**Comment by virse** [comment]
Thanks for your reply.

I solved the issue by using the apache2 as ReverseProxy and installed Nginx as recommended (listening only on localhost).

I'll close issue.

Regards
