### ISSUE TITLE
Notifications aren't working in production

### ISSUE THREAD

**Issue by virse** [taigaio/taiga-back#1251]
I refer to the issue #894 which is alreday closed:

Hey there,

I reopen this issue cause I'm running in to the same issue, but the recommended solution doesn't work. I also receive the password revovery mails or the invitation mails for a new user. So the mail config is fine and working. But I don't receive for example the team mails in a project or any other notifications (due date).

I see no errors in my mail-log.

I've changed my `CHANGE_NOTIFICATIONS_MIN_INTERVAL` to 120 sec and I use a cron task (as recommended) to call the `send_notifications`.

I am running my own instance in production mode, newest taiga-version.

Here is my

**local.py**

```
from .common import *

MEDIA_URL = "https://taiga.xxx.de/media/"
STATIC_URL = "https://taiga.xxx.de/static/"
SITES["front"]["scheme"] = "https"
SITES["front"]["domain"] = "taiga.xxx.de"

SECRET_KEY = "xyz"

DEBUG = False
PUBLIC_REGISTER_ENABLED = False

ADMINS = (
    ("admin", "admin@xxx.de"),
)

ALLOWED_HOSTS = ['taiga.xxx.de']

DEFAULT_FROM_EMAIL = "taiga@xxx.de"
SERVER_EMAIL = DEFAULT_FROM_EMAIL

EVENTS_PUSH_BACKEND = "taiga.events.backends.rabbitmq.EventsPushBackend"
EVENTS_PUSH_BACKEND_OPTIONS = {"url": "amqp://taiga:PASSWORD_FOR_EVENTS@localhost:5672/taiga"}

CELERY_ENABLED = True

DEFAULT_FROM_EMAIL = "taiga@xxx.de"
CHANGE_NOTIFICATIONS_MIN_INTERVAL = 120 #seconds

# EMAIL SETTINGS EXAMPLE
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False # You cannot use both (TLS and SSL) at the same time!
EMAIL_HOST = 'mail.xxx.de'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'admin@xxx.de'
EMAIL_HOST_PASSWORD = 'xyz'
```

And the `cron task`:

`cd /home/taiga/taiga-back && /home/taiga/.virtualenvs/taiga/bin/python manage.py send_notifications`

When I call the above cron command I receive this error:

```
cd /home/taiga/taiga-back && /home/taiga/.virtualenvs/taiga/bin/python manage.py send_notifications ..
Trying import local.py settings...
/home/taiga/taiga-back/taiga/base/utils/iterators.py:56: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'taiga.projects.notifications.models.HistoryChangeNotification'> QuerySet.
  paginator = Paginator(queryset, itersize)
```

Thx for any help and hints on that.

best regards, virse

**Comment by alexhermida** [comment]
@virse  that message only seems a warning (`UnorderedObjectListWarning`), it doesn't affect the issue. As I can see you have `CELERY_ENABLED = True`. You must have celery service running as well as rabbitmq and redis.

**Comment by Apurv-P** [comment]
I am getting Same Issue, I have Done Setup Taiga in Self-hosted Production Environment,
gmail SMTP configured, Password Reset Email itself working fine, But on mentions in comments like @username no mail is sent.

i have tried with below cron run manually

> cd /home/taiga/taiga-back && /home/taiga/.virtualenvs/taiga/bin/python manage.py send_notifications

getting error

taiga@domain.com:~/taiga-back$ cd /home/taiga/taiga-back && /home/taiga/.virtualenvs/taiga/bin/python manage.py send_notifications
Trying import local.py settings...
Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/core/management/__init__.py", line 338, in execute
    django.setup()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.6/site-packages/django/apps/registry.py", line 116, in populate
    app_config.ready()
  File "/home/taiga/taiga-back/taiga/feedback/apps.py", line 31, in ready
    from taiga.urls import urlpatterns
  File "/home/taiga/taiga-back/taiga/urls.py", line 23, in <module>
    from .routers import router
  File "/home/taiga/taiga-back/taiga/routers.py", line 63, in <module>
    from taiga.projects.api import ProjectViewSet
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 771, in get_code
  File "<frozen importlib._bootstrap_external>", line 482, in _validate_bytecode_header
MemoryError

How can i Fix this?

**Comment by migonzalvar** [comment]
@Apurv-P In your case, the `MemoryError` points that maybe there is no enough resources on the server. How much memory do you have? In any case it doesn't seem a bug in the source code.

**Comment by Apurv-P** [comment]
Thanks for your Reply, We have 1GB of RAM in Server and i have monitor that 850mb used from 985mb, so do i need to upgrade RAM? also do i need to set send_notifications cronjob?

my local.py file as below

from .common import *

MEDIA_URL = "http://domain.com/media/"
STATIC_URL = "http://domain.com/static/"
SITES["front"]["scheme"] = "http"
SITES["front"]["domain"] = "domain.com"

SECRET_KEY = "theveryultratopsecretkey"

DEBUG = False
PUBLIC_REGISTER_ENABLED = True

DEFAULT_FROM_EMAIL = "test@gmail.com"
SERVER_EMAIL = DEFAULT_FROM_EMAIL

EVENTS_PUSH_BACKEND = "taiga.events.backends.rabbitmq.EventsPushBackend"
EVENTS_PUSH_BACKEND_OPTIONS = {"url": "amqp://taiga:PASSWORD_FOR_EVENTS@localhost:5672/taiga"}

# Uncomment and populate with proper connection parameters
# for enable email sending. EMAIL_HOST_USER should end by @domain.tld
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'test@gmail.com'
EMAIL_HOST_PASSWORD = 'password'
EMAIL_PORT = 587

# Uncomment and populate with proper connection parameters
# for enable github login/singin.
#GITHUB_API_CLIENT_ID = "yourgithubclientid"
#GITHUB_API_CLIENT_SECRET = "yourgithubclientsecret"

#DEFAULT_FROM_EMAIL = "test@gmail.com"
CHANGE_NOTIFICATIONS_MIN_INTERVAL = 120
FEEDBACK_ENABLED = True
FEEDBACK_EMAIL = "test@gmail.com"
STATS_ENABLED = True
#WEBHOOKS_ENABLED = True
#WEBHOOKS_BLOCK_PRIVATE_ADDRESS = True


#from .celery import *
#BROKER_URL = 'amqp://taiga:PASSWORD_FOR_EVENTS@localhost:5672/taiga'
#CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ENABLED = True

**Comment by migonzalvar** [comment]
@Apurv-P yes, you need to add a cron job to send notifications

**Comment by Apurv-P** [comment]
Hi,

I have changed EMAIL_USE_TLS to EMAIL_USE_SSL with PORT = 465, and start the cron manually, Emails are working, sudden all the Emails are landing in inbox from starting
@migonzalvar Can you please share the example of the Cronjob set (i.e every minute or else)?

Thanks, AP

**Comment by migonzalvar** [comment]
Every minute is ok


I think I can close the issue. A summary:

1. Mail configuration is critical to make taiga work. Please check it thoroughly. You can use `ython manage.py sendtestemail youremail@example.com` to test it.

1. If CELERY_ENABLED, celery workers must be running.

1. it is up to the system administrator to install a cron job or similar to send email notifications. Something like this should do the job:

   ```
    * * * * cd /home/taiga/taiga-back && /home/taiga/.virtualenvs/taiga/bin/python manage.py send_notifications
   ```

**Comment by ViktorNova** [comment]
Thank you so much! This fixed my issue. Note that there was a few weeks of notifications that had not been set, so everyone on the teams' inbox got flooded with notifications as soon as I ran send_notifications the first time =) 

This should definitely be added to the documentation
