### ISSUE TITLE
All Ajax requests fails on Microsoft Edge

### ISSUE THREAD

**Issue by FrancoG45** [taigaio/taiga-back#1263]
Every request made with Ajax works on Chrome, Firefox and Internet Explorer but, when using Microsoft Edge, all the Ajax requests are retrieved from cache and displays a status 200/OK not matter what. The request and response headers are both empty and the body displays that "This resource has no response payload data". Ajax, expecting a json response, fires an undefined responseJSON, statusText "error" and status 0.

Source: An ASP.net project using IIS Express 10 on Visual Studio 2017. (https://localhost:44334/)
Version: jQuery 3.3.1
Target: An intranet Taiga API (also https)
Browser: Microsoft Edge 44.17763.1.0 / EdgeHTML 18.17763

![taiga04](https://user-images.githubusercontent.com/35610663/53649041-57662a00-3c0f-11e9-8b08-81cfe1348131.png)

**Comment by sergxp** [comment]
Were you able to fix this issue, I'm having the same problem with a project just using jquery ajax.

**Comment by FrancoG45** [comment]
The problem went away after hosting the project on the compagny local intranet. I never found a way to fix the issue when testing on local debug. I guess the issue was with Cross Origin Requests between the intranet API and the local debug environment but I can't say for sure.

**Comment by theriverman** [comment]
https://docs.djangoproject.com/en/2.2/ref/settings/
Look out for `ALLOWED_HOSTS`. I suppose that could solve your issue.
