### ISSUE TITLE
Updating translation

### ISSUE THREAD

**Issue by tocloco** [taigaio/taiga-back#1270]
I am trying to update some of the registration email messages in Taiga.

I have edited taiga-back/taiga/locale/en/LC_MESSAGES/django.po and made a few changes to some of the msgstr lines.

I then run as follows:

workon taiga
python manage.py makemessages -l en
python manage.py compilemessages
sudo systemctl restart 'taiga*'

However the sent emails aren't changing. Am I missing a step somewhere?

**Comment by alexhermida** [comment]
@tocloco if you have celery enabled you must restart taiga_celery.service, otherwise check your if your new strings are in the locales. 
With `python manage.py compilemessages` should be enough.
