### ISSUE TITLE
howto logging taiga-backend

### ISSUE THREAD

**Issue by Pbast** [taigaio/taiga-back#1272]
Hello,
I read taiga documentation but didn't found a way to enable logging on taiga-backend.
I have an authentication issue with LDAP and I don't know how to debug it: https://github.com/Monogramm/taiga-contrib-ldap-auth-ext/issues/24

I have an "internal server error" and "DEBUG = True" in my settings/local.py but have no log files...

If I run "python manage.py runserver"
I have "(Service Unavailable)" from my browser and no console output.
Thxs for any help.

If I launch "service taiga start" I could not find log files either.

Pascal B

**Comment by Pbast** [comment]
Hello, I use this way to displayed authentication logging:
https://github.com/Monogramm/taiga-contrib-ldap-auth-ext/issues/24#issuecomment-474761063

**Comment by alexhermida** [comment]
Thanks for the feedback @Pbast 
Regarding logs. If you use systemctl like it's describe in the docs you can use `journalctl` to check your taiga-back logs.
