### ISSUE TITLE
issue query will not match 

### ISSUE THREAD

**Issue by Pac23** [taigaio/taiga-back#1278]
**Do you want to request a *feature* or report a *bug*?**
i am trying to fetch issues with the api,always end up with no issue matches the given query even though i put in the right project slug. 

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

curl -X GET \
-H "Content-Type: application/json" \
-H "Authorization: Bearer ${AUTH_TOKEN}" \
-s https://api.taiga.io/api/v1/issues/by_ref?ref=1\&project=1

This ends up with {"_error_message": "No Issue matches the given query."} 

**What is the expected behavior?**
Returns the issue in json format.

**Is it happening in taiga.io or in your own instance?**
taiga.io

**What browser/version are you using?**
bash/shell

Thanks for reporting!

**Comment by alexhermida** [comment]
@Pac23 make sure you're using the correct reference. Make a list request previously to check it (https://taigaio.github.io/taiga-doc/dist/api.html#issues-list)

**Comment by Pac23** [comment]
@alexhermida nvm figured out what i was doing wrong. Had put the taiga project ref no wrong.

**Comment by Pac23** [comment]
> @Pac23 make sure you're using the correct reference. Make a list request previously to check it (https://taigaio.github.io/taiga-doc/dist/api.html#issues-list)

@alexhermida retrieving issue lists works fine,retrieval using issue reference and project id returns a error.

for example 
https://api.taiga.io/api/v1/issues/by_ref?ref=1\&project=315827 

returns a 401 

All other queries with same auth token and project id return 200.
