### ISSUE TITLE
i18n: poor german translation of ready

### ISSUE THREAD

**Issue by carlos22** [taigaio/taiga-back#1281]
Current Translaton: 

https://github.com/taigaio/taiga-back/blob/bd385ddb5c94595ee5be46d267a3a0294c1e8323/taiga/locale/de/LC_MESSAGES/django.po#L4230-L4231

Better would be `Bereit`. As `Fertig` means `done`! In the same file there is a much better translaton for ready in the context of `Ready for test`, which is totally correct.

 https://github.com/taigaio/taiga-back/blob/bd385ddb5c94595ee5be46d267a3a0294c1e8323/taiga/locale/de/LC_MESSAGES/django.po#L4246-L4247

This needs to be changed as german speakers otherwise get "done" as second state by default which is very confusing (as there is another done state).

**Comment by alexhermida** [comment]
@carlos22 Taiga uses Transifex to manage the i18n files. You can contribute to the translations at https://www.transifex.com/organization/taiga-agile-llc/ Thank you!
