### ISSUE TITLE
Cannot register user via API

### ISSUE THREAD

**Issue by tocloco** [taigaio/taiga-back#1288]
We are using the API on a private server to create and register a user on a private project.

Whenever we try to register a user we get the following message:

{
    "_error_message": "You must accept our terms of service and privacy policy",
    "_error_type": "taiga.base.exceptions.BadRequest"
}

Can we specify that this is accepted? Or can we disable the need for this policy?

**Comment by alexhermida** [comment]
@tocloco currently you must send the `accepted_terms` attribute for registration.
