### ISSUE TITLE
Imported project from Trello is empty

### ISSUE THREAD

**Issue by vasyugan** [taigaio/taiga-back#1297]
**Do you want to request a *feature* or report a *bug*?**

Looks like a bug to me. 

**What is the current behavior?**

After importing a project from Trello, it is empty. It has nothing except for the name and the title. All the cards, attachments, etc, everything is missing.

**If the current behavior is a bug, please provide the steps to reproduce.**
Enable the trello importer in the backend and the frontend, log on to the taiga instance, choose create project, then import project, then import from trello, then choose one of the projects there, go through the import dialogue and save.

**What is the expected behavior?**

Result should resemble what it looks like on trello, cards should be there at least.

**Is it happening in taiga.io or in your own instance?**

Own instance. Tried to test this on taiga.io, but due to plan limitations I could not import a project with over three member
**What browser/version are you using?**

Firefox 66

**Are there any console errors *(Ctrl + F12)* in red?**

Thanks for reporting!

**Comment by alexhermida** [comment]
@vasyugan currently the Trello importation it's limited, you can check it at https://tree.taiga.io/support/importers/trello-importer/  "Which data is imported, and how?"

If you didn't import those data, you must check Taiga logs looking for some import error. If you followed the documentation you could check the logs with:

`journalctl --user-unit taiga_back`
`journalctl --user-unit taiga_celery `

**Comment by vasyugan** [comment]
Thank you for your response. As far as I am concerned, I have now opted
for Wekan, as it pretty much is an exact clone of Trello. In Wekan,
import from Trello works by manually exporting the JSON from Trello
first and then pasting the JSON code into the importer. However, the
result is flawless, complete. Maybe you can look at how Wekan
<https://github.com/wekan/wekan> manages it, code-wise. (for my part,
for the moment, I won't experiment with Taiga further, as I have found
an easier alternative)
