### ISSUE TITLE
Bitbucket integration does not work

### ISSUE THREAD

**Issue by Gim6626** [taigaio/taiga-back#1311]
Faced following bug with Bitbucket integration on my own Taiga instance (last commit f74cf365b2d54f30ca152621a4c7c192db502918).

1. Added webhook to Bitbucket according to https://tree.taiga.io/support/integrations/bitbucket-integration/ manual
2. Added Bitbucket and Atlassian IPs from https://confluence.atlassian.com/bitbucket/what-are-the-bitbucket-cloud-ip-addresses-i-should-use-to-configure-my-corporate-firewall-343343385.html to Taiga whitelist:
`34.232.25.90/32,35.155.178.254/32,35.160.177.10/32,52.54.90.98/32,52.202.195.162/32,34.218.168.212/32,35.171.175.212/32,104.192.136.0/21,34.236.25.177/32,34.199.54.113/32,52.204.96.37/32,103.233.242.0/24,185.166.140.0/22,2401:1d80::/32,2406:da18:809:e00::/56,2406:da1c:1e0:a200::/56,2600:1f14:824:300::/56,2600:1f18:2146:e300::/56,2600:1f1c:cc5:2300::/56,2a05:d014:f99:dd00::/56,52.215.192.128/25,2a05:d018:34d:5800::/56,2a0a:ea00::/32,52.203.14.55/32,52.41.219.63/32,34.232.119.183/32,18.184.99.128/25,18.136.214.0/25,13.236.8.128/25,13.52.5.0/25,18.234.32.128/25,18.246.31.128/25,34.216.18.129/32,34.218.156.209/32,18.205.93.0/27,18.205.93.0/25,18.234.32.128/25,13.52.5.0/25,2406:da00:ff00::22cd:e0db,2406:da00:ff00::6b17:d1f5,2406:da00:ff00::3403:4be7,2406:da00:ff00::22c3:9b0a,2406:da00:ff00::22c5:2ef4,2406:da00:ff00::22c2:0513,2406:da00:ff00::34cc:ea4a,2406:da00:ff00::22e9:9f55,2406:da00:ff00::22c0:3470 ,2406:da00:ff00::34c8:9c5c,2406:da00:ff00::12d0:47c8,2406:da00:ff00::22ed:a9a3,2406:da00:ff00::23a8:5071,2406:da00:ff00::36ec:9434,2406:da00:ff00::3416:7161,2406:da00:ff00::36ec:bea6,2406:da00:ff00::12cd:ae3d,2406:da00:ff00::12cc:b432 ,2406:da00:ff00::1714:aa06,2406:da00:ff00::342d:4312,2406:da00:ff00::22ee:e721,2406:da00:ff00::34cf:03c4,2406:da00:ff00::3657:a859,2406:da00:ff00::1716:0c22,2406:da00:ff00::36ec:507a,2406:da00:ff00::3448:67ee,2406:da00:ff00::36ad:fb4d,2406:da00:ff00::22ce:9394,2406:da00:ff00::12d0:5d6e,2406:da00:ff00::3402:732e,2406:da00:ff00::36d1:8b98,2406:da00:ff00::3414:6492,2406:da00:ff00::3437:b4cb,2406:da00:ff00::22e2:3a76,2406:da00:ff00::34c9:c443,2406:da00:ff00::3405:6cad,2406:da00:ff00::12ea:0a19,2406:da00:ff00::23a8:6621,2406:da00:ff00::3401:9341,2406:da00:ff00::3654:c786,2406:da00:ff00::3448:4e57,2406:da00:ff00::36a4:e08c,2406:da00:ff00::36a4:f8a6,2406:da00:ff00::22c8:ada3,2406:da00:ff00::34cd:a4b9,2406:da00:ff00::23a8:b9b1,2406:da00:ff00::3402:affc,2406:da00:ff00::12cd:d438,2406:da00:ff00::34ce:b43b,2406:da00:ff00::342d:1804,2406:da00:ff00::36ae:07e7,2406:da00:ff00::3456:314c,2406:da00:ff00::36af:42a0,2406:da00:ff00::3414:0248`
3. Tried to push commits with TG-REF in commit message.
4. Bitbucket request logs shows "repo:push" events, but with HTTP 400 errors.
5. Taiga nginx.access.log shows messages like this:
`18.234.32.224 - - [28/May/2019:14:20:51 +0000] "POST /api/v1/bitbucket-hook?project=1&key=PRIVATE_KEY HTTP/1.1" 400 86 "-" "Bitbucket-Webhooks/2.0"`

Tried to add `SITES["api"]["scheme"] = "http"` to `settings/local.py` and restart `taiga` service as it was suggested at https://github.com/taigaio/taiga-back/issues/1002 - didn't help.

Could anybody help with it?

**Comment by Gim6626** [comment]
Hey, really need help on this case

**Comment by nevernet** [comment]
i got same issue, if you find any solution,  let me know please :)

**Comment by Gim6626** [comment]
Finally Bitbucket request details page started to work and I could attach request payload example:
```
{
  "push": {
    "changes": [
      {
        "forced": false,
        "old": {
          "name": "master",
          "links": {
            "commits": {
              "href": "https://api.bitbucket.org/2.0/repositories/Gim6626/permlug/commits/master"
            },
            "self": {
              "href": "https://api.bitbucket.org/2.0/repositories/Gim6626/permlug/refs/branches/master"
            },
            "html": {
              "href": "https://bitbucket.org/Gim6626/permlug/branch/master"
            }
          },
          "default_merge_strategy": "merge_commit",
          "merge_strategies": [
            "merge_commit",
            "squash",
            "fast_forward"
          ],
          "type": "branch",
          "target": {
            "rendered": {},
            "hash": "dc93f9037e0fcd6976de8071e32b016dffe39a74",
            "links": {
              "self": {
                "href": "https://api.bitbucket.org/2.0/repositories/Gim6626/permlug/commit/dc93f9037e0fcd6976de8071e32b016dffe39a74"
              },
              "html": {
                "href": "https://bitbucket.org/Gim6626/permlug/commits/dc93f9037e0fcd6976de8071e32b016dffe39a74"
              }
            },
            "author": {
              "raw": "Dmitriy Vinokurov <gim6626@gmail.com>",
              "type": "author",
              "user": {
                "display_name": "Dmitriy Vinokurov",
                "account_id": "557058:04717bf7-95c5-487e-8f15-9d294c043f83",
                "links": {
                  "self": {
                    "href": "https://api.bitbucket.org/2.0/users/%7Ba9c38850-1065-4bcb-a865-84df5c05e5e7%7D"
                  },
                  "html": {
                    "href": "https://bitbucket.org/%7Ba9c38850-1065-4bcb-a865-84df5c05e5e7%7D/"
                  },
                  "avatar": {
                    "href": "https://secure.gravatar.com/avatar/bf9bd86c19a2d0683968b17777a58f0c?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FDV-3.png"
                  }
                },
                "nickname": "Дмитрий Винокуров",
                "type": "user",
                "uuid": "{a9c38850-1065-4bcb-a865-84df5c05e5e7}"
              }
            },
            "summary": {
              "raw": "Новые media файлы\n",
              "markup": "markdown",
              "html": "<p>Новые media файлы</p>",
              "type": "rendered"
            },
            "parents": [
              {
                "hash": "50af66e18d7faf88f91a645a416a06ad961398ea",
                "type": "commit",
                "links": {
                  "self": {
                    "href": "https://api.bitbucket.org/2.0/repositories/Gim6626/permlug/commit/50af66e18d7faf88f91a645a416a06ad961398ea"
                  },
                  "html": {
                    "href": "https://bitbucket.org/Gim6626/permlug/commits/50af66e18d7faf88f91a645a416a06ad961398ea"
                  }
                }
              }
            ],
            "date": "2019-06-07T06:26:28+00:00",
            "message": "Новые media файлы\n",
            "type": "commit",
            "properties": {}
          }
        },
        "links": {
          "commits": {
            "href": "https://api.bitbucket.org/2.0/repositories/Gim6626/permlug/commits?include=3b356f8815469334659719899d8082dcb49b67ee&exclude=dc93f9037e0fcd6976de8071e32b016dffe39a74"
          },
          "html": {
            "href": "https://bitbucket.org/Gim6626/permlug/branches/compare/3b356f8815469334659719899d8082dcb49b67ee..dc93f9037e0fcd6976de8071e32b016dffe39a74"
          },
          "diff": {
            "href": "https://api.bitbucket.org/2.0/repositories/Gim6626/permlug/diff/3b356f8815469334659719899d8082dcb49b67ee..dc93f9037e0fcd6976de8071e32b016dffe39a74"
          }
        },
        "created": false,
        "commits": [
          {
            "rendered": {},
            "hash": "3b356f8815469334659719899d8082dcb49b67ee",
            "links": {
              "self": {
                "href": "https://api.bitbucket.org/2.0/repositories/Gim6626/permlug/commit/3b356f8815469334659719899d8082dcb49b67ee"
              },
              "comments": {
                "href": "https://api.bitbucket.org/2.0/repositories/Gim6626/permlug/commit/3b356f8815469334659719899d8082dcb49b67ee/comments"
              },
              "patch": {
                "href": "https://api.bitbucket.org/2.0/repositories/Gim6626/permlug/patch/3b356f8815469334659719899d8082dcb49b67ee"
              },
              "html": {
                "href": "https://bitbucket.org/Gim6626/permlug/commits/3b356f8815469334659719899d8082dcb49b67ee"
              },
              "diff": {
                "href": "https://api.bitbucket.org/2.0/repositories/Gim6626/permlug/diff/3b356f8815469334659719899d8082dcb49b67ee"
              },
              "approve": {
                "href": "https://api.bitbucket.org/2.0/repositories/Gim6626/permlug/commit/3b356f8815469334659719899d8082dcb49b67ee/approve"
              },
              "statuses": {
                "href": "https://api.bitbucket.org/2.0/repositories/Gim6626/permlug/commit/3b356f8815469334659719899d8082dcb49b67ee/statuses"
              }
            },
            "author": {
              "raw": "Дмитрий Винокуров <VinokurovDA@morion.ru>",
              "type": "author"
            },
            "summary": {
              "raw": "TG-7 Проверка синхронизации Тайги с Bitbucket\n",
              "markup": "markdown",
              "html": "<p>TG-7 Проверка синхронизации Тайги с Bitbucket</p>",
              "type": "rendered"
            },
            "parents": [
              {
                "hash": "dc93f9037e0fcd6976de8071e32b016dffe39a74",
                "type": "commit",
                "links": {
                  "self": {
                    "href": "https://api.bitbucket.org/2.0/repositories/Gim6626/permlug/commit/dc93f9037e0fcd6976de8071e32b016dffe39a74"
                  },
                  "html": {
                    "href": "https://bitbucket.org/Gim6626/permlug/commits/dc93f9037e0fcd6976de8071e32b016dffe39a74"
                  }
                }
              }
            ],
            "date": "2019-06-14T09:28:10+00:00",
            "message": "TG-7 Проверка синхронизации Тайги с Bitbucket\n",
            "type": "commit",
            "properties": {}
          }
        ],
        "truncated": false,
        "closed": false,
        "new": {
          "name": "master",
          "links": {
            "commits": {
              "href": "https://api.bitbucket.org/2.0/repositories/Gim6626/permlug/commits/master"
            },
            "self": {
              "href": "https://api.bitbucket.org/2.0/repositories/Gim6626/permlug/refs/branches/master"
            },
            "html": {
              "href": "https://bitbucket.org/Gim6626/permlug/branch/master"
            }
          },
          "default_merge_strategy": "merge_commit",
          "merge_strategies": [
            "merge_commit",
            "squash",
            "fast_forward"
          ],
          "type": "branch",
          "target": {
            "rendered": {},
            "hash": "3b356f8815469334659719899d8082dcb49b67ee",
            "links": {
              "self": {
                "href": "https://api.bitbucket.org/2.0/repositories/Gim6626/permlug/commit/3b356f8815469334659719899d8082dcb49b67ee"
              },
              "html": {
                "href": "https://bitbucket.org/Gim6626/permlug/commits/3b356f8815469334659719899d8082dcb49b67ee"
              }
            },
            "author": {
              "raw": "Дмитрий Винокуров <VinokurovDA@morion.ru>",
              "type": "author"
            },
            "summary": {
              "raw": "TG-7 Проверка синхронизации Тайги с Bitbucket\n",
              "markup": "markdown",
              "html": "<p>TG-7 Проверка синхронизации Тайги с Bitbucket</p>",
              "type": "rendered"
            },
            "parents": [
              {
                "hash": "dc93f9037e0fcd6976de8071e32b016dffe39a74",
                "type": "commit",
                "links": {
                  "self": {
                    "href": "https://api.bitbucket.org/2.0/repositories/Gim6626/permlug/commit/dc93f9037e0fcd6976de8071e32b016dffe39a74"
                  },
                  "html": {
                    "href": "https://bitbucket.org/Gim6626/permlug/commits/dc93f9037e0fcd6976de8071e32b016dffe39a74"
                  }
                }
              }
            ],
            "date": "2019-06-14T09:28:10+00:00",
            "message": "TG-7 Проверка синхронизации Тайги с Bitbucket\n",
            "type": "commit",
            "properties": {}
          }
        }
      }
    ]
  },
  "actor": {
    "display_name": "Dmitriy Vinokurov",
    "account_id": "557058:04717bf7-95c5-487e-8f15-9d294c043f83",
    "links": {
      "self": {
        "href": "https://api.bitbucket.org/2.0/users/%7Ba9c38850-1065-4bcb-a865-84df5c05e5e7%7D"
      },
      "html": {
        "href": "https://bitbucket.org/%7Ba9c38850-1065-4bcb-a865-84df5c05e5e7%7D/"
      },
      "avatar": {
        "href": "https://secure.gravatar.com/avatar/bf9bd86c19a2d0683968b17777a58f0c?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FDV-3.png"
      }
    },
    "nickname": "Дмитрий Винокуров",
    "type": "user",
    "uuid": "{a9c38850-1065-4bcb-a865-84df5c05e5e7}"
  },
  "repository": {
    "scm": "git",
    "website": "",
    "name": "PermLUG",
    "links": {
      "self": {
        "href": "https://api.bitbucket.org/2.0/repositories/Gim6626/permlug"
      },
      "html": {
        "href": "https://bitbucket.org/Gim6626/permlug"
      },
      "avatar": {
        "href": "https://bytebucket.org/ravatar/%7B84a2f7fe-3594-4479-94af-ce43f2f57b1c%7D?ts=2218204"
      }
    },
    "full_name": "Gim6626/permlug",
    "owner": {
      "display_name": "Dmitriy Vinokurov",
      "account_id": "557058:04717bf7-95c5-487e-8f15-9d294c043f83",
      "links": {
        "self": {
          "href": "https://api.bitbucket.org/2.0/users/%7Ba9c38850-1065-4bcb-a865-84df5c05e5e7%7D"
        },
        "html": {
          "href": "https://bitbucket.org/%7Ba9c38850-1065-4bcb-a865-84df5c05e5e7%7D/"
        },
        "avatar": {
          "href": "https://secure.gravatar.com/avatar/bf9bd86c19a2d0683968b17777a58f0c?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FDV-3.png"
        }
      },
      "nickname": "Дмитрий Винокуров",
      "type": "user",
      "uuid": "{a9c38850-1065-4bcb-a865-84df5c05e5e7}"
    },
    "type": "repository",
    "is_private": true,
    "uuid": "{84a2f7fe-3594-4479-94af-ce43f2f57b1c}"
  }
}
```

Response:
```
{
  "_error_type": "taiga.base.exceptions.BadRequest",
  "_error_message": "Bad signature"
}
```

**Comment by alexhermida** [comment]
@Gim6626 @nevernet, after in-depth review it seems to work well. 

You must make sure you add valid IP addresses/range to your config and taking care of not adding any white space or invalid IP/range. Some wrong format could make to fail the validation.

Additionally, if it is your custom instance, you must make sure you have the bitbucket user created during the initial migrations https://github.com/taigaio/taiga-back/blob/master/taiga/hooks/bitbucket/migrations/0001_initial.py#L16

Also, check the taiga-back logs looking for some additional information about the validation and attach it here.

**Comment by Gim6626** [comment]
@alexhermida, thanks for review. Problem really was in two redundant spaces. Correct list is `62.16.51.65,34.232.25.90/32,35.155.178.254/32,35.160.177.10/32,52.54.90.98/32,52.202.195.162/32,34.218.168.212/32,35.171.175.212/32,104.192.136.0/21,34.236.25.177/32,34.199.54.113/32,52.204.96.37/32,103.233.242.0/24,185.166.140.0/22,2401:1d80::/32,2406:da18:809:e00::/56,2406:da1c:1e0:a200::/56,2600:1f14:824:300::/56,2600:1f18:2146:e300::/56,2600:1f1c:cc5:2300::/56,2a05:d014:f99:dd00::/56,52.215.192.128/25,2a05:d018:34d:5800::/56,2a0a:ea00::/32,52.203.14.55/32,52.41.219.63/32,34.232.119.183/32,18.184.99.128/25,18.136.214.0/25,13.236.8.128/25,13.52.5.0/25,18.234.32.128/25,18.246.31.128/25,34.216.18.129/32,34.218.156.209/32,18.205.93.0/27,18.205.93.0/25,18.234.32.128/25,13.52.5.0/25,2406:da00:ff00::22cd:e0db,2406:da00:ff00::6b17:d1f5,2406:da00:ff00::3403:4be7,2406:da00:ff00::22c3:9b0a,2406:da00:ff00::22c5:2ef4,2406:da00:ff00::22c2:0513,2406:da00:ff00::34cc:ea4a,2406:da00:ff00::22e9:9f55,2406:da00:ff00::22c0:3470,2406:da00:ff00::34c8:9c5c,2406:da00:ff00::12d0:47c8,2406:da00:ff00::22ed:a9a3,2406:da00:ff00::23a8:5071,2406:da00:ff00::36ec:9434,2406:da00:ff00::3416:7161,2406:da00:ff00::36ec:bea6,2406:da00:ff00::12cd:ae3d,2406:da00:ff00::12cc:b432,2406:da00:ff00::1714:aa06,2406:da00:ff00::342d:4312,2406:da00:ff00::22ee:e721,2406:da00:ff00::34cf:03c4,2406:da00:ff00::3657:a859,2406:da00:ff00::1716:0c22,2406:da00:ff00::36ec:507a,2406:da00:ff00::3448:67ee,2406:da00:ff00::36ad:fb4d,2406:da00:ff00::22ce:9394,2406:da00:ff00::12d0:5d6e,2406:da00:ff00::3402:732e,2406:da00:ff00::36d1:8b98,2406:da00:ff00::3414:6492,2406:da00:ff00::3437:b4cb,2406:da00:ff00::22e2:3a76,2406:da00:ff00::34c9:c443,2406:da00:ff00::3405:6cad,2406:da00:ff00::12ea:0a19,2406:da00:ff00::23a8:6621,2406:da00:ff00::3401:9341,2406:da00:ff00::3654:c786,2406:da00:ff00::3448:4e57,2406:da00:ff00::36a4:e08c,2406:da00:ff00::36a4:f8a6,2406:da00:ff00::22c8:ada3,2406:da00:ff00::34cd:a4b9,2406:da00:ff00::23a8:b9b1,2406:da00:ff00::3402:affc,2406:da00:ff00::12cd:d438,2406:da00:ff00::34ce:b43b,2406:da00:ff00::342d:1804,2406:da00:ff00::36ae:07e7,2406:da00:ff00::3456:314c,2406:da00:ff00::36af:42a0,2406:da00:ff00::3414:0248`

**Comment by Gim6626** [comment]
Could not decide whether write here or open new issue. Decided to write here cause could not say that Bitbucket integration works completely.

Fixed IP's list, tried to push and see `This issue has been mentioned by @None in the BitBucket commit "TG-7 ..."` message in Taiga issue. Why `@None`? Searched in sources, found line 45 in `taiga/hooks/bitbucket/event_hooks.py`: `"user_name": self.payload.get('actor', {}).get('username', None),`, but when I look in Bitbucket request body, I see no `actor->username` field there:
```
"actor": {
    "display_name": "Dmitriy Vinokurov",
    "account_id": "557058:04717bf7-95c5-487e-8f15-9d294c043f83",
    "links": {
      "self": {
        "href": "https://api.bitbucket.org/2.0/users/%7Ba9c38850-1065-4bcb-a865-84df5c05e5e7%7D"
      },
      "html": {
        "href": "https://bitbucket.org/%7Ba9c38850-1065-4bcb-a865-84df5c05e5e7%7D/"
      },
      "avatar": {
        "href": "https://secure.gravatar.com/avatar/bf9bd86c19a2d0683968b17777a58f0c?d=https%3A%2F%2Favatar-management--avatars.us-west-2.prod.public.atl-paas.net%2Finitials%2FDV-3.png"
      }
    },
    "nickname": "Дмитрий Винокуров",
    "type": "user",
    "uuid": "{a9c38850-1065-4bcb-a865-84df5c05e5e7}"
  },
```

**Comment by alexhermida** [comment]
Yes, it's weird. I'll review it. Feel free to open a specific issue for this.

**Comment by Gim6626** [comment]
Done - https://github.com/taigaio/taiga-back/issues/1344
