### ISSUE TITLE
Having difficulty with email export

### ISSUE THREAD

**Issue by jwir3** [taigaio/taiga-back#1312]
I'm having some difficulty with a self-hosted instance of taiga. I have gitlab integration connected, and when I make a commit that references a ticket, I receive an email from taiga notifying me of this. Thus, I am fairly certain that email is working and connected. 

However, when I go to my project settings -> Export -> Click the 'Export' button, it never sends me an email with the appropriate file. Instead, the following is shown in the system logs:

```
May 28 10:20:06 mustafar celery[631]: [2019-05-28 15:20:06,853: INFO/MainProcess] Received task: taiga.export_import.tasks.dump_project[0569ca0f-8f80-4597-9eee-c1bb41d78ea0]
May 28 10:20:06 mustafar celery[631]: [2019-05-28 15:20:06,870: INFO/MainProcess] Received task: taiga.export_import.tasks.delete_project_dump[a26763dc-4bfd-4364-a595-c659655fbbef]  ETA:[2019-05-29 17:20:06.861968+02:00]
May 28 10:20:15 mustafar postfix/smtpd[7563]: connect from localhost[127.0.0.1]
```

My taiga-back email configuration, for reference:
```
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_USE_TLS = False
EMAIL_HOST = "localhost"
EMAIL_HOST_USER = ""
EMAIL_HOST_PASSWORD = ""
EMAIL_PORT = 25
```

My localhost email server is using Postfix.

I'm wondering if perhaps the file is too big?

**Comment by jwir3** [comment]
Also, I've verified that `python manage.py dump_project project_slug` works as expected and produces a `project_slug.json` file that seems to be correct.

**Comment by jwir3** [comment]
I've verified that I can send a message on my local machine with an attachment using `mutt`, as well.

**Comment by alexhermida** [comment]
@jwir3 did you check `/var/log/mail.log` or `/var/log/syslog` looking for them?

**Comment by jwir3** [comment]
@alexhermida Yes, `/var/log/syslog` shows the following:
```
Jun  3 10:00:11 mustafar celery[631]: [2019-06-03 15:00:11,002: INFO/MainProcess] Received task: taiga.export_import.tasks.dump_project[85eebc19-6cb6-4692-b560-40d6fc1e54f0]
Jun  3 10:00:11 mustafar celery[631]: [2019-06-03 15:00:11,024: INFO/MainProcess] Received task: taiga.export_import.tasks.delete_project_dump[0a0702ef-890f-4386-b3af-b3a24073a608]  ETA:[2019-06-04 17:00:11.013220+02:00]
Jun  3 10:00:19 mustafar postfix/smtpd[13650]: connect from localhost[127.0.0.1]
```

`/var/log/mail.log` shows just the last line:
```
Jun  3 10:00:19 mustafar postfix/smtpd[13650]: connect from localhost[127.0.0.1]
```

It appears to only be happening with export, though, as I'm getting emails from the project when tickets are updated.

**Comment by alexhermida** [comment]
As long as you have the tasks in your log, celery it is working ok, and It seems an email server configuration issue. Although you receive the connection in Postfix the server doesn't process it, is there any additional info in the main log? 

You can test Taiga emails with the command `./manage.py test_emails <your_email>`. This command will send you email samples synchronously. 

If this works ok you could check your celery configuration, just in case you had modified the queues or anything related.

You can use `$journalctl --user-unit taiga_celery.service` to review only "taiga_celery" related logs.

**Comment by jwir3** [comment]
Hm, yeah, I think it might be an email server configuration issue. What's odd about this, though is that emails seem to send fine from Taiga (and other web services - I have a couple of Rails sites on the same server), as long as they don't have attachments. For some reason, it's the attachment that's messing things up. Attachments seem to be sending fine from the command line, so I suspect it might be something with Postfix's connection to the Django mail processor.

When I use the `manage.py test_emails` command, it sends me a bunch of test emails, including some about export both succeeding and failing. I assume these are just dummy emails, so I basically ignored them (in other words, I don't think it's actually doing anything behind the scenes, other than sending the emails, correct?)

One thing I _did_ notice is that it looks like the email for export success shows a link to download the project data, rather than attaching it to the email itself. I was wondering if perhaps where taiga is trying to store this file doesn't have the correct permissions or something similar, so I performed another export, and I've verified that the file is being created in a subdirectory of the `media/exports` directory. 

I seem to recall that when developing my Rails applications, I had to force flush the email queue somehow in order to get it to send. Do I need to set up something similar for Django? (Sorry, I'm unfamiliar with this framework)

It seems that the `journalctl` command was of no help, since it just gave:
```
-- Logs begin at Mon 2019-01-28 16:39:20 CST, end at Sat 2019-06-08 10:05:40 CDT. --
-- No entries --
```

**Comment by jwir3** [comment]
After further investigation, I think what might be happening is that the taiga-back instance is connecting to the email server in this case, but it isn't performing any other tasks after the connection. For example, successful email sends look like this in the `mail.log`:
```
Jun  8 10:00:28 mustafar postfix/smtpd[7203]: connect from localhost[127.0.0.1]
Jun  8 10:00:28 mustafar postfix/smtpd[7203]: 3DA04439B5: client=localhost[127.0.0.1]
Jun  8 10:00:28 mustafar postfix/cleanup[7206]: 3DA04439B5: message-id=<20190608150028.7154.22837@mustafar>
Jun  8 10:00:28 mustafar postfix/qmgr[8465]: 3DA04439B5: from=<no-reply@taiga.foamfactory.io>, size=15062, nrcpt=1 (queue active)
Jun  8 10:00:28 mustafar postfix/smtpd[7203]: disconnect from localhost[127.0.0.1] ehlo=1 mail=1 rcpt=1 data=1 quit=1 commands=5
```

But, when I trigger the email export, I see only this:
```
Jun  8 10:15:35 mustafar postfix/smtpd[8101]: connect from localhost[127.0.0.1]
Jun  8 10:20:35 mustafar postfix/smtpd[8101]: timeout after EHLO from localhost[127.0.0.1]
Jun  8 10:20:35 mustafar postfix/smtpd[8101]: disconnect from localhost[127.0.0.1] ehlo=1 commands=1
```

It's almost like taiga-back is connecting to the email server, then triggering the export, which takes too long, and finally trying to send the email message.

**Comment by jwir3** [comment]
I was able to figure this issue out. As suggested in https://github.com/taigaio/taiga-back/issues/649#issuecomment-315518384 I needed to change
```
EMAIL_USE_TLS = False
```

to 

```
EMAIL_USE_SSL = False
```

In `settings/local.py`. *HOWEVER* (and this is the important part that I neglected), after doing this, you must restart _both_ `taiga` (via `sudo service taiga restart`) _and_ `taiga_celery` (via `sudo service taiga_celery restart`). I originally ttri

**Comment by jwir3** [comment]
@alexhermida One weird thing is that the subject says `[Test Project]`, when all I see in the project's `.json` export file is `FoamFactory` for the name of the project. It looks like the `project.name` is different from `project` in the jinja file. Thoughts on where this is coming from and how to change it?
