### ISSUE TITLE
Use of redis

### ISSUE THREAD

**Issue by Nox-404** [taigaio/taiga-back#1313]
Hello,
How is redis used in taiga ?

I used the production deployment guide and I don't see where or what uses the values stored in redis...

It seems celery stores results there. but what is using these results ?

Thanks and sorry for that noob question :)

**Comment by alexhermida** [comment]
@Nox-404 every question is welcome :-) 
It is included to use as result backend for Celery 
https://github.com/taigaio/taiga-back/blob/master/settings/celery.py#L22, but currently, there is no use for those results in Taiga code.  You may want to use by yourself with an external tool.
