### ISSUE TITLE
joyride PUT 401 on fresh install (mod_wsgi)

### ISSUE THREAD

**Issue by luzik** [taigaio/taiga-back#1320]
After fresh install I can browse sample projects (from `python manage.py sample_data`), download issue attachments everything working as expected
But after successful login with admin/123123 when I click any project, my profile or whatever I got this in my browser <-> taiga-back communication no 200 pages

404 on Request URL: http://192.168.0.3:8020/%7B%7B%20'
and after that there is
401 on Request URL: http://192.168.0.3:8020/api/v1/user-storage/joyride
and then taiga-front redirect me to
http://192.168.0.3:8020/login?unauthorized

My installation is bit different from that in tutorial because I use mod_wsgi with apache

Configuration is very strait forward 

```
<VirtualHost *:8020>
        DocumentRoot /home/taiga/taiga-front-dist/dist
        ErrorLog ${APACHE_LOG_DIR}/taiga_error.log

        # Possible values include: debug, info, notice, warn, error, crit,
        # alert, emerg.
        LogLevel warn

        CustomLog ${APACHE_LOG_DIR}/taiga_access.log combined
        <IfModule mpm_itk_module>
                AssignUserId taiga taiga
        </IfModule>
        <Directory /home/taiga/taiga-front-dist/dist>
                Require ip 127.0.0.1
                Require ip 192.168.0
        </Directory>
        <Directory /home/taiga/taiga-back>
                <Files wsgi.py>
                        Require ip 127.0.0.1
                        Require ip 192.168.0
                </Files>
        </Directory>
        <Directory /home/taiga/taiga-back/static>
                        Require ip 127.0.0.1
                        Require ip 192.168.0
        </Directory>
        <Directory /home/taiga/taiga-back/media>
                        Require ip 127.0.0.1
                        Require ip 192.168.0
        </Directory>
        Alias /static /home/taiga/taiga-back/static
        Alias /media /home/taiga/taiga-back/media
        WSGIDaemonProcess taiga python-path=/home/taiga/taiga-back python-home=/home/taiga/taiga-back/taiga-venv socket-user=taiga
        WSGIProcessGroup taiga
        WSGIScriptAlias /api /home/taiga/taiga-back/taiga/wsgi.py/api
        WSGIScriptAlias /admin /home/taiga/taiga-back/taiga/wsgi.py/admin
</VirtualHost>
```

**Comment by andreashaerter** [comment]
Can confirm and provide a bit of additional data. Using nginx, Python 3.6 on CentOS7. Taiga backend version: 4.2.4, frontend version: 4.2.5-stable


### Fresh install without sample data -> Error

I ran the installation and the needed migrations:

```sh
python manage.py migrate --noinput
python manage.py loaddata initial_user
python manage.py loaddata initial_project_templates
python manage.py compilemessages
python manage.py collectstatic --noinput
```

**Results in your error**:

* login as predefined `admin:123123`: -> `PUT https://taiga.example.com/api/v1/user-storage/joyride 404 (Not Found)`
* created a new project, invited a user, logged in as user: -> `PUT https://taiga.example.com/api/v1/user-storage/joyride 404 (Not Found)`

### Fresh install with sample data -> Working

When I run the migrations including sample data (`python manage.py sample_data`), the error is not present.

I can login as `admin:123123` and **joyride loads and is working** -> `GET https://taiga.example.com/api/v1/user-storage/joyride 200 (OK)`

And I see the joyride actually working in the browser, for sure.

**Comment by andreashaerter** [comment]
Same error with the just release 4.2.6...

*in principle*. However, the error goes away and joyride workd if I do the install an re-execute:

```
workon taiga
python manage.py migrate --noinput
python manage.py compilemessages
python manage.py collectstatic --noinput
```

Seems to be the same for 4.2.5. So I guess something in the migration or so does not work on the first try.

**Comment by luzik** [comment]
This is quite different. I believe that 404 is a way to tell that there is no user-storage data. My error is 401. With PUT payload as `{key: "joyride", value: {backlog: false, kanban: false, dashboard: false}}`

**Comment by luzik** [comment]
And this is definitely connected to mod_wsgi, because when run with `manage.py runserver` there is no 401 (Unauthorized) error.

**Comment by luzik** [comment]
Ah got it ! It was WSGIPassAuthorization On directive. My complete working apache conf with mod_wsgi is:

```
<VirtualHost *:8020>
        DocumentRoot /home/taiga/taiga-front-dist/dist
        <IfModule mpm_itk_module>
                AssignUserId taiga taiga
        </IfModule>
        <Directory /home/taiga/taiga-front-dist/dist>
                Require ip 127.0.0.1
                Require ip 192.168.0
        </Directory>
        <Directory /home/taiga/taiga-back>
                <Files wsgi.py>
                        Require ip 127.0.0.1
                        Require ip 192.168.0
                </Files>
        </Directory>
        <Directory /home/taiga/taiga-back/static>
                        Require ip 127.0.0.1
                        Require ip 192.168.0
        </Directory>
        <Directory /home/taiga/taiga-back/media>
                        Require ip 127.0.0.1
                        Require ip 192.168.0
        </Directory>
        Alias /static /home/taiga/taiga-back/static
        Alias /media /home/taiga/taiga-back/media
        WSGIDaemonProcess taiga python-path=/home/taiga/taiga-back python-home=/home/taiga/taiga-back/taiga-venv socket-user=taiga
        WSGIProcessGroup taiga
        WSGIScriptAlias /api /home/taiga/taiga-back/taiga/wsgi.py/api
        WSGIScriptAlias /admin /home/taiga/taiga-back/taiga/wsgi.py/admin
        WSGIPassAuthorization On

        RewriteEngine on
        RewriteCond %{REQUEST_URI} !^/admin(.*)
        RewriteCond %{REQUEST_URI} !^/api(.*)
        RewriteCond %{REQUEST_URI} !^/events(.*)
        RewriteCond %{REQUEST_URI} !^/static(.*)
        RewriteCond %{REQUEST_URI} !^/media(.*)
        RewriteCond %{DOCUMENT_ROOT}/%{REQUEST_FILENAME} !-f
        RewriteRule . /index.html [L]

        ErrorLog ${APACHE_LOG_DIR}/taiga_error.log
        CustomLog ${APACHE_LOG_DIR}/taiga_access.log combined
</VirtualHost>
```

**Comment by andreashaerter** [comment]
@luzik You are right. My error is unrelated (but vanishes as described). So: sorry for noise.
