### ISSUE TITLE
Unable to configure taiga with aws SES

### ISSUE THREAD

**Issue by thegtagamer** [taigaio/taiga-back#1335]
I have setup taiga in my ec2 instance (t2.medium) running on Ubuntu 18. However, when I configure my local.py to use AWS SES as mailing service it does not seems to work. Any help is appreciated.

**Comment by alexhermida** [comment]
@thegtagamer we need more details about the issue. You must review in detail https://taigaio.github.io/taiga-doc/dist/setup-production.html and check your taiga-back log and taiga-celery log. After that attach any errors to your message.

**Comment by alexhermida** [comment]
@thegtagamer it is solved? can you attach your log files to review it?

**Comment by DeamonMV** [comment]
@thegtagamer did you get success with AWS SES? 

we have such problems `smtplib.SMTPAuthenticationError: (535, b'Authentication Credentials Invalid')  `

for case when:

```
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_SSL = True
EMAIL_HOST = 'email-smtp.us-east-1.amazonaws.com'
EMAIL_HOST_USER = 'BASE64_Encoded_USERNAME'
EMAIL_HOST_PASSWORD = 'BASE64_Encoded_PAssword'
EMAIL_PORT = 587
```

**Comment by linchar** [comment]
Not sure if BASE64 encoding would work. I just enter user name and password in plain text and specify the host name of the correct AWS region. The following works for me:

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_USE_TLS = True
EMAIL_HOST = "email-smtp.us-east-1.amazonaws.com"
EMAIL_HOST_USER = "USERNAME"
EMAIL_HOST_PASSWORD = "PLAINTEXTPASSWORD"
EMAIL_PORT = 25

**Comment by migonzalvar** [comment]
I'm going to close this issue as is not related to taiga-back but to a specific email service configuration.

Thank you @linchar for your help.

**Comment by meakshayraut** [comment]
> I have setup taiga in my ec2 instance (t2.medium) running on Ubuntu 18. However, when I configure my local.py to use AWS SES as mailing service it does not seems to work. Any help is appreciated.



> I have setup taiga in my ec2 instance (t2.medium) running on Ubuntu 18. However, when I configure my local.py to use AWS SES as mailing service it does not seems to work. Any help is appreciated.

Can you please tell me how to setup taiga on ec2? It will be very helpful for me

**Comment by bboyadao** [comment]
Sandbox ses right? Have to verify or you have to enter receiver (email
list) in to it at the aws ses.
