### ISSUE TITLE
SMTP integration does not work

### ISSUE THREAD

**Issue by shashankjayajain** [taigaio/taiga-back#1336]
Hello Team,

I am trying to enable email sending using gmail smtp properties, the local.py file looks like this,
.....
DEFAULT_FROM_EMAIL = "something@gmail.com"
SERVER_EMAIL = DEFAULT_FROM_EMAIL

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_USE_TLS = False
EMAIL_HOST = "smtp.gmail.com"
EMAIL_HOST_USER = "something@gmail.com"
EMAIL_HOST_PASSWORD = "password"
EMAIL_PORT = 587
....

**I tried resetting password from the front end, received following response**

![Capture](https://user-images.githubusercontent.com/48466924/60096205-fd651380-976d-11e9-85c6-64724ac0719d.PNG)

**Taiga-back logs for the same**

![Capture](https://user-images.githubusercontent.com/48466924/60096302-32716600-976e-11e9-9ab0-980350ee5e23.PNG)

Can you please help?

**Comment by migonzalvar** [comment]
Try to set `EMAIL_USE_TLS` to `True`

**Comment by shashankjayajain** [comment]
Tried with EMAIL_USE_TLS = True, logs following error

![Capture](https://user-images.githubusercontent.com/48466924/60152921-33eb6e80-9800-11e9-8831-182f01183e96.PNG)

**Comment by alexhermida** [comment]
@shashankjayajain  Did you have 2-Step verification activated? If it's the case, you must create the password and use it instead of your regular password. You can review how to create app passwords at https://support.google.com/accounts/answer/185833.

**Comment by migonzalvar** [comment]
Taiga SMTP integration is working fine. I'm pretty sure this issue is related with your Gmail configuration.
