### ISSUE TITLE
admin's password is incorrect

### ISSUE THREAD

**Issue by jianghong3** [taigaio/taiga-back#1352]
**Before adding an issue**
Please ensure that your issue is not already reported in our [issues list](https://tree.taiga.io/project/taiga/issues?order_by=-created_date).
If this issue was already reported, remember that you can upvote it to raise its importance.

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

when login with "admin 123123", it displays "your username or email or password are incorrect"

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Is it happening in taiga.io or in your own instance?**

**What browser/version are you using?**

**Are there any console errors *(Ctrl + F12)* in red?**

Thanks for reporting!

**Comment by alexhermida** [comment]
@jianghong3 did you run `./manage.py loaddata initial_user --traceback`? You can also recreate the database with all sample data and the initial user with the script `regenerate.sh`. 
Nevertheless, check the development documentation carefully https://taigaio.github.io/taiga-doc/dist/setup-development.html
