### ISSUE TITLE
minor adjustments to requirements.txt, for py 3.7 compat

### ISSUE THREAD

**Issue by benzkji** [taigaio/taiga-back#1354]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
Running taiga-back on python 3.7 throws an error because of the kombu library

**If the current behavior is a bug, please provide the steps to reproduce.**
Run on python 3.7. Alos, the steps to fix it (kombu has the problem solved):
https://groups.google.com/forum/#!topic/taigaio/6dHwvg-bkbM

**What is the expected behavior?**
It works.

**Is it happening in taiga.io or in your own instance?**
Own.

**Comment by benzkji** [comment]
would be nice if you could craft a release soon.

**Comment by benzkji** [comment]
thx!

**Comment by migonzalvar** [comment]
@benzkji , you can use the current master branch with the libraries updated

**Comment by benzkji** [comment]
thx, yes I will!
