### ISSUE TITLE
GET, POST & DELETE errors on /api/v1

### ISSUE THREAD

**Issue by athuscavalini** [taigaio/taiga-back#1361]
I'm getting errors accessing pages from my taiga instance:
```
Failed to load resource: the server responded with a status of 404 (Not Found)
GET http://taiga.prt17.mpt.mp.br/api/v1/user-storage/69e3a5e… 404 (Not Found)
```

It also happens when I try to create a new story:
```
POST http://taiga.prt17.mpt.mp.br/api/v1/userstories 500 (Internal Server Error)
```

Or when trying to delete a story (In this case, I also see an Oompa Loompa error):
```
DELETE http://taiga.prt17.mpt.mp.br/api/v1/userstories/182 500 (Internal Server Error)
```

I also noticed that the frontend is not responding to user interactions. You must refresh the page whenever I take any action to insert or remove any information.

**Comment by athuscavalini** [comment]
I noticed that when calling `coffe index.coffee` I get `error uncaughtException: listen EADDRINUSE :::: 8888` too. Seems to me the reason for the problem, but I couldn't fix it.

**Comment by migonzalvar** [comment]
With that info it is difficult to diagnose the problem. I would review the services status in order to gain more insight:

```
sudo systemctl status taiga
sudo systemctl status taiga_events
```
Maybe it helps if could go through https://taigaio.github.io/taiga-doc/dist/setup-production.html step by step again.

I'm closing because at this moment it doesn't seem an issue with taiga-back.

**Comment by 24thsaint** [comment]
Hello, are you able to solve this? 
I'm experiencing this now and it has been 2 days and it seems like I'm going nowhere. 😅

I experience this on migration to Taiga v6. The API just times-out.
However, if I refresh the page, the content is actually there. It's just that the API does not respond.

I'm also getting a `[CRITICAL] WORKER TIMEOUT` message on the console.

Any ideas?

https://user-images.githubusercontent.com/8315544/123659731-93543d00-d865-11eb-8c58-7f68380542c8.mp4
