### ISSUE TITLE
Request: Autosearch torrent for "episode not found".

### ISSUE THREAD

**Issue by Doomwhite** [taigaio/taiga-back#1366]

**Comment by Doomwhite** [comment]
> I searched for "torrent" on https://tree.taiga.io/project/taiga/issues?order_by=-created_date and didn't find anything, so I'm assuming it wasn't requested before.
> Ok, so what I "want" is a option that when, for instance, I select a episode from an anime and it says "not found", I have an option that will search torrents for that anime with the episode that I clicked.
> Simply put:
> 
> > I press episode 01 of Detective Conan.
> > It says not found
> > an option appears asking if I want to search for torrents of that episode.
> 
> This would be EXTREMELY useful, really.

**Comment by andreashaerter** [comment]
I guess you are posting to the completely wrong project. Taiga.io is a agile project management software and has nothing to do with Taiga.moe. ;-)

**Comment by Doomwhite** [comment]
> I guess you are posting to the completely wrong project. Taiga.io is a agile project management software and has nothing to do with Taiga.moe. ;-)

You are right, lmfao.
