### ISSUE TITLE
Add prefix access to Taiga.io??

### ISSUE THREAD

**Issue by dasarro23** [taigaio/taiga-back#1374]
It is possible to add a prefix or context for access to Taiga.io and not directly the root "/"

For example: taigaio.domain.com/taiga

Thank you

**Comment by migonzalvar** [comment]
@dasarro23 I'm afraid currently it would be a difficult task. Taiga config options does not include this option out of the box.

You can share the same domain or have different domains for front and back. But I'm afraid a lot of thing will break on a prefix scenario.
