### ISSUE TITLE
No email send for invitation

### ISSUE THREAD

**Issue by syahwanius** [taigaio/taiga-back#1376]
Hi all 
Thanks for build this perfect project firstly, after spending a couples weeks taiga in my server i can't invite someone to my own taiga server (from email)
The case was 
1. Can't send invitation email for new user to join the project (but can invite directly if he already register on the server)
2. Can't forgot password 

this is my taiga-back/setting/local.py configuration

----
from .common import *

MEDIA_URL = "http://taiga.example.com/media/"
STATIC_URL = "http://taga.example.com/static/"
SITES["front"]["scheme"] = "http"
SITES["front"]["domain"] = "taiga.example.com"

SECRET_KEY = "mysecretkey"

DEBUG = False
PUBLIC_REGISTER_ENABLED = True

DEFAULT_FROM_EMAIL = "taiga@email.com"
SERVER_EMAIL = DEFAULT_FROM_EMAIL

#CELERY_ENABLED = True

EVENTS_PUSH_BACKEND = "taiga.events.backends.rabbitmq.EventsPushBackend"
EVENTS_PUSH_BACKEND_OPTIONS = {"url": "amqp://taiga:StrongPassword@localhost:5672/taiga"}

#Uncomment and populate with proper connection parameters
#for enable email sending. EMAIL_HOST_USER should end by @domain.tld
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_USE_TLS = True
EMAIL_HOST = "smtp.gmail.com"
EMAIL_HOST_USER = "taiga@example.com"
EMAIL_HOST_PASSWORD = "passwordemailtaiga@example.com"
EMAIL_PORT = 587

#Uncomment and populate with proper connection parameters
#for enable github login/singin.
#GITHUB_API_CLIENT_ID = "yourgithubclientid"
#GITHUB_API_CLIENT_SECRET = "yourgithubclientsecret"

But i make it comment first, because when i uncomment it can't invite member directly and can't create new user too 

#DEFAULT_FROM_EMAIL = "taiga@email.com"
#SERVER_EMAIL = DEFAULT_FROM_EMAIL
#EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
#EMAIL_USE_TLS = True
#EMAIL_HOST = "smtp.gmail.com"
#EMAIL_HOST_USER = "taiga@example.com"
#EMAIL_HOST_PASSWORD = "passwordemailtaiga@example.com"
#EMAIL_PORT = 587

any solution?

----

**Comment by migonzalvar** [comment]
Probably, your email configuration is wrong so when taiga tries to send an email it breaks and that is the reason you can't create new users nor invite members.

As soon as you fix the email config everything is going to work.

You can test the email configuration with this Django admin command:

```
cd ~/taiga-back
workon  taiga
python manage.py sendtestemail youremail@example.com
```

**Comment by syahwanius** [comment]
> Probably, your email configuration is wrong so when taiga tries to send an email it breaks and that is the reason you can't create new users nor invite members.
> 
> As soon as you fix the email config everything is going to work.
> 
> You can test the email configuration with this Django admin command:
> 
> ```
> cd ~/taiga-back
> workon  taiga
> python manage.py sendtestemail youremail@example.com
> ```

I'm using gmail for my email did you know how to config the email?
and when running the command for testing email:
`
taiga@taiga:~/taiga-back$ workon  taiga
ERROR: Environment 'taiga' does not exist. Create it with 'mkvirtualenv taiga'.
taiga@taiga:~/taiga-back$ python manage.py sendtestemail myemail@gmail.com
Traceback (most recent call last):
  File "manage.py", line 27, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named django.core.management
taiga@taiga:~/taiga-back$
`

**Comment by migonzalvar** [comment]
Configuring a GMail account depends on a lot of things. Sorry I can't help.

The command `sendtestemail` is similar to the other Django administrative commands as `migrate` that you have done to setup the taiga server. Please, use the same python virtual environment.
