### ISSUE TITLE
webhook for "promote to us"

### ISSUE THREAD

**Issue by skob** [taigaio/taiga-back#1400]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
"promote to us" dont send webhook api

**If the current behavior is a bug, please provide the steps to reproduce.**
just create issue and promote it to us 

**What is the expected behavior?**
1. get webhook
2. get info about user who run promote

**Is it happening in taiga.io or in your own instance?**
my instance

**What browser/version are you using?**
any

**Are there any console errors *(Ctrl + F12)* in red?**
no :-(

Thanks for reporting!

**Comment by migonzalvar** [comment]
Please @dangarbar, could you take a look?

**Comment by ilstreltsov** [comment]
+1

**Comment by deniskabalkin** [comment]
+1
