### ISSUE TITLE
django.db.utils.OperationalError: could not connect to server: No such file or directory         Is the server running locally and accepting         connections on Unix domain socket "/tmp/.s.PGSQL.5432"?

### ISSUE THREAD

**Issue by suxianglun** [taigaio/taiga-back#1403]
when i run  " python manage.py migrate --noinput"
then, i get this:

psycopg2.OperationalError: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/tmp/.s.PGSQL.5432"?

please help me, thank you very much

**Comment by minrock** [comment]
Looks like either your postgreSQL database is not accepting connection or is not running. You need to install postgreSQL and run it, are you running Linux, windows or Mac OS?

**Comment by migonzalvar** [comment]
I think this is a related with a installation issue. Plase check doc at https://taigaio.github.io/taiga-doc/dist/setup-production.html.

**Comment by suxianglun** [comment]
> Looks like either your postgreSQL database is not accepting connection or is not running. You need to install postgreSQL and run it, are you running Linux, windows or Mac OS?

yes, you are right ,tank you very much!
