### ISSUE TITLE
Upgrade to Django 2.2 LTS

### ISSUE THREAD

**Issue by pauloxnet** [taigaio/taiga-back#1412]
**Do you want to request a *feature* or report a *bug*?**

Now a feature, a bug in few days ([April 1 2020](https://www.djangoproject.com/download/#supported-versions)).

**What is the current behavior?**

Django 1.11 has been [tagged EOL](https://github.com/django/djangoproject.com/pull/979/files) and after April 1 2020 will not have update any security fixes and data loss bugs.

**What is the expected behavior?**

Have all security fixes and data loss bugs (e.g. using a Django 2.2 LTS)

**Comment by niccolomineo** [comment]
Agreed. This should definitely be addressed in due time.

**Comment by pauloxnet** [comment]
It seems there's a first PR #1414 to migrate to Django 2.2

**Comment by muellert** [comment]
In the PR, Github says "All tests have failed." So I guess there's still some work to do.

**Comment by jespino** [comment]
@muellert yes, still some work to do (I don't know if it is a lot or is not that much). I'll keep working, but if anybody want to pass the tests locally and try to fix problems related to the changes in the Django API, is very welcome :)

**Comment by migonzalvar** [comment]
We have just merged the Django 2.2 branch to master branch.
