### ISSUE TITLE
Attachments clean-up

### ISSUE THREAD

**Issue by alexander-potemkin** [taigaio/taiga-back#1442]
**Before adding an issue**

Checked with a keyword 'attach', got nothing on that.

**Do you want to request a *feature* or report a *bug*?**

Feature probably

**What is the current behavior?**

Unclear

**If the current behavior is a bug, please provide the steps to reproduce.**

On self-hosted TaigaPM: one upload the file (screenshot, video, etc. - to illustrate the issue) and the attach remains there forever, consuming disk space.

**What is the expected behavior?**

cron script / instruction how to clean up attachments, older than X days (ideally, replacing them to a placeholder picture / video)

**Is it happening in taiga.io or in your own instance?**

Yes

**What browser/version are you using?**

Any

**Are there any console errors *(Ctrl + F12)* in red?**

N/A

Thanks for reporting!

**Comment by bameda** [comment]
Hi @alexander-potemkin in taiga6 there is a periodic celery task to remove deleted attachments by default. 

You can upgrade your instance following the documentation at https://taigaio.github.io/taiga-doc/dist/#upgrading-guide

Best regards
