### ISSUE TITLE
Getting ModuleNotFoundError: No module named 'resource' in Windows OS 

### ISSUE THREAD

**Issue by mhraza95** [taigaio/taiga-back#1445]
**Before adding an issue**
Please ensure that your issue is not already reported in our [issues list](https://tree.taiga.io/project/taiga/issues?order_by=-created_date).
If this issue was already reported, remember that you can upvote it to raise its importance.

**Do you want to request a *feature* or report a *bug*?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**Is it happening in taiga.io or in your own instance?**

**What browser/version are you using?**

**Are there any console errors *(Ctrl + F12)* in red?**

Thanks for reporting!

**Comment by migonzalvar** [comment]
Taiga-back is not tested in Windows OS, sorry.

**Comment by mhraza95** [comment]
I've Fixed the issue now it's working properly, Can i submit my code for review??

**Comment by mhraza95** [comment]
> Taiga-back is not tested in Windows OS, sorry.

I've fixed the issue, now it's working properly. Can i submit my code for review??

**Comment by migonzalvar** [comment]
Sure! In this case I think is just an import that can be safely removed. But take into account we do not plan to support Windows specifically.

**Comment by mhraza95** [comment]
> Sure! In this case I think is just an import that can be safely removed. But take into account we do not plan to support Windows specifically.

I've not removed the import, Just placed a check for windows OS. 
Anyway Thanks for quick response.

**Comment by HengyueLi** [comment]
still see this problem. What do i need to update?

**Comment by ViesLink** [comment]
> > Taiga-back is not tested in Windows OS, sorry.
> 
> I've fixed the issue, now it's working properly. Can i submit my code for review??

Can you describe the specific steps to fix this error
