### ISSUE TITLE
 invalid credentials for Rabbitmq

### ISSUE THREAD

**Issue by ichasco** [taigaio/taiga-back#1493]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
It works normally (for the moment) but there is a warning message in rabbitmq:
```
[warning] <0.2785.0> HTTP access denied: user 'taiga' - invalid credentials
```
If you set the RABBIT_PASSWORD variable with 'password' value. It doesn't appear. So there is somewhere hardcoded.

**If the current behavior is a bug, please provide the steps to reproduce.**

Run with docker and set different password from default in Rabbit

**What is the expected behavior?**

Work everything as expected.

**Comment by bameda** [comment]
Hi @Ichag could you upgrade to the new taiga6 docker images? those problems should be resolved. 

You can find resources at https://resources.taiga.io/30min-setup/ and https://taigaio.github.io/taiga-doc/dist/
