### ISSUE TITLE
Error for Office360/Outlook smpt email sender configuration

### ISSUE THREAD

**Issue by Ahamedo** [taigaio/taiga-back#1499]
Hello,

I'd like to report a Bug with the smpt email configurations for Office360/Outlook when used as a email notification sender. So there is an error when making any change that fires the email notification like a comment for example. 

**Error log** - When using **EMAIL_USE_TLS = True**:
gunicorn[470412]:     return email.send()
gunicorn[470412]:   File "/home/taiga/.virtualenvs/taiga/lib/python3.8/site-packages/django/core/mail/message.py", line 306, in send
gunicorn[470412]:     return self.get_connection(fail_silently).send_messages([self])
gunicorn[470412]:   File "/home/taiga/.virtualenvs/taiga/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 110, in send_messages
gunicorn[470412]:     sent = self._send(message)
gunicorn[470412]:   File "/home/taiga/.virtualenvs/taiga/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 126, in _send
gunicorn[470412]:     self.connection.sendmail(from_email, recipients, message.as_bytes(linesep='\r\n'))
gunicorn[470412]:   File "/usr/lib/python3.8/smtplib.py", line 892, in sendmail
gunicorn[470412]:     raise SMTPDataError(code, resp)
gunicorn[470412]: smtplib.SMTPDataError: (554, b'5.2.0 STOREDRV.Submission.Exception:SendAsDeniedException.MapiExceptionSendAsDenied; Failed to process message due to a permanent exception with message Cannot submit message. 0.35250:03020000, 1.36674:0A000000, 1.61250:00000000, 1.45378:02000000, 1.44866:68600000, 1.36, 0.22753:0A005136, 255.21817:DC040000, 0.64418:0A00F565, 4.39842:DC040000, 0.41586:B9000000, 4.60547:DC040000, 0.21966:0A00F565, 4.30158:DC040000 [Hostname=AM9PR03MB6931.eurprd03.prod.outlook.com]')

**Error log** - When using **EMAIL_USE_TLS = False**:
gunicorn[472597]:     return email.send()
gunicorn[472597]:   File "/home/taiga/.virtualenvs/taiga/lib/python3.8/site-packages/django/core/mail/message.py", line 306, in send
gunicorn[472597]:     return self.get_connection(fail_silently).send_messages([self])
gunicorn[472597]:   File "/home/taiga/.virtualenvs/taiga/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 103, in send_messages
gunicorn[472597]:     new_conn_created = self.open()
gunicorn[472597]:   File "/home/taiga/.virtualenvs/taiga/lib/python3.8/site-packages/django/core/mail/backends/smtp.py", line 70, in open
gunicorn[472597]:     self.connection.login(self.username, self.password)
gunicorn[472597]:   File "/usr/lib/python3.8/smtplib.py", line 700, in login
gunicorn[472597]:     raise SMTPNotSupportedError(
gunicorn[472597]: smtplib.SMTPNotSupportedError: SMTP AUTH extension not supported by server.

**settings/local.py**
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_USE_TLS = True
EMAIL_HOST = "smtp.office365.com"
EMAIL_HOST_USER = "some@domain.tld"
EMAIL_HOST_PASSWORD = "asecurepassword"
EMAIL_PORT = 587

**Office360 SMTP settings**
Server: smtp.office365.com
Port: 587
Encryption: STARTTLS

Thank you for your help

**Comment by bameda** [comment]
Hi @Ahamedo 

try to set your office360 email address as the default from address and enable TLS again

```
DEFAULT_FROM_EMAIL = "some@domain.tld"
EMAIL_USE_TLS = True
```

**Comment by JeroenJADS** [comment]
@bameda Thank you, the DEFAULT_FROM_EMAIL saved me as well!
