### ISSUE TITLE
comment field is not interpreting the markdown correctly

### ISSUE THREAD

**Issue by cinco** [taigaio/taiga-back#1558]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
comment field is not interpreting the markdown correctly

**If the current behavior is a bug, please provide the steps to reproduce.**
1) open comment box
2) change to markdown
3) write some markdown tags, mainly for code blocks
5) save the comment
6) after saved, comment doesnt show code block

**What is the expected behavior?**
markdown correctly interpreting

**Is it happening in taiga.io or in your own instance?**
my own instance

**What browser/version are you using?**
Google Chrome Version 87.0.4280.88
Firefox version 84.0

**Are there any console errors *(Ctrl + F12)* in red?**
No

Here a gif with error reproduce:
![taiga-markdown-error](https://user-images.githubusercontent.com/125763/104488587-593ff900-55ad-11eb-9b11-820e3fb6f8c6.gif)

**Comment by bameda** [comment]
Hi @cinco 

this issue should be fixed in Taiga6 since the 2nd of Februarry. You can upgrade you server following the documentation at https://taigaio.github.io/taiga-doc/dist/#upgrading-guide

Best regards
