### ISSUE TITLE
Taiga front doesn't render some custom Fields : number type

### ISSUE THREAD

**Issue by jerem-ie** [taigaio/taiga-back#1565]
**Before adding an issue**
Please ensure that your issue is not already reported in our [issues list](https://tree.taiga.io/project/taiga/issues?order_by=-created_date).
If this issue was already reported, remember that you can upvote it to raise its importance.

**Do you want to request a *feature* or report a *bug*?**
report a bug

**What is the current behavior?**
Taiga doesn't render your custom fields when its' a number type one. (the data is here as it appears when you modify the field )

**If the current behavior is a bug, please provide the steps to reproduce.**
1. create a number custom field
2. put any value in that custom field. 
3. the data of the custom field won't be displayed.

**What is the expected behavior?**

**Is it happening in taiga.io or in your own instance?**
both

**What browser/version are you using?**
Firefox, chrome

**Are there any console errors *(Ctrl + F12)* in red?**
no
Thanks for reporting!

**Comment by miryamgduque** [comment]
Hi!
Thanks for letting us know! It is already solved.
