### ISSUE TITLE
Unable to create user from the Django admin

### ISSUE THREAD

**Issue by gabrieletassoni** [taigaio/taiga-back#1569]
Hi,
I'm trying to create a user from the Django admin in order to not have the invitation or register workflow, but just add a user and let him in.

By accessing the Django admin interface I'm able to reach the new user page, but upon clicking on the Save button, a 500 error is thrown, looking at the logs, I think the problem lies here:

```
Exception Type: IntegrityError at /admin/users/user/add/
Exception Value: null value in column "verified_email" violates not-null constraint
DETAIL:  Failing row contains (87, pbkdf2_sha256$36000$eh1G46YGAEaj$wQO5MMEJdTiKJDqy6Lis+e4Wdkq59xy..., null, f, user-name, , t, , #f406cb, , , 2021-02-02 09:54:50.935805+00, , , f, null, null, null, f, , null, null, null, null, 726d14f3fff2413d9b270004f1a1cb0c, t, f, null).
```

There's a constraint violated: the UI just lets me to create a username and password at this stage, so I cannot fill that field manually to avoid,
Before going directly to Postgres, I'd like to know how to add a user manually without having that 500 error thrown.

thank you very much,
Gabriele Tassoni

**Comment by yamila-moreno** [comment]
hi @gabrieletassoni there is a bug in this process, thanks for reporting.

Meanwhile, you can use the UI front, or you can use the shell:

```
(taiga-back) /taiga-back ‹stable› » DJANGO_SETTINGS_MODULE=settings.config python manage.py shell    
Python 3.9.1 (default, Dec 13 2020, 11:55:53) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from taiga.users.models import User
>>> new_user = User.objects.create(username='username', email='my@email.com')
>>> new_user.set_password('password')
>>> new_user.save()
```

let us know if this works as expected and close the issue if it does.

**Comment by yamila-moreno** [comment]
@gabrieletassoni we just released a patch with this fix.

If you've installed Taiga from source code, update the code and launch the service again.
If you've installed Taiga from docker, just pull taiga-back again and `./launch-taiga.sh`

**Comment by gabrieletassoni** [comment]
> hi @gabrieletassoni there is a bug in this process, thanks for reporting.
> 
> Meanwhile, you can use the UI front, or you can use the shell:
> 
> ```
> (taiga-back) /taiga-back ‹stable› » DJANGO_SETTINGS_MODULE=settings.config python manage.py shell    
> Python 3.9.1 (default, Dec 13 2020, 11:55:53) 
> [GCC 10.2.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> (InteractiveConsole)
> >>> from taiga.users.models import User
> >>> new_user = User.objects.create(username='username', email='my@email.com')
> >>> new_user.set_password('password')
> >>> new_user.save()
> ```
> 
> let us know if this works as expected and close the issue if it does.

Thank you very much, didn't know about the python console way, I love it.

**Comment by gabrieletassoni** [comment]
> @gabrieletassoni we just released a patch with this fix.
> 
> If you've installed Taiga from source code, update the code and launch the service again.
> If you've installed Taiga from docker, just pull taiga-back again and `./launch-taiga.sh`

Wow! I'll check it Mine is at 5.5.9 from docker I'll close this right after the test. Thank you again

**Comment by yamila-moreno** [comment]
we just released taiga 6 (the fix is in taiga6) and we strongly encourage you to update to this new version.
You can upgrade following [these instructions](https://taigaio.github.io/taiga-doc/dist/upgrades-5to6.html)

**Comment by yamila-moreno** [comment]
I understand the main issue is solved, so I'm closing this. Feel free to reopen if you find it's not working.
