### ISSUE TITLE
Login with github doesn't respect PUBLIC_REGISTER_ENABLED

### ISSUE THREAD

**Issue by andresazp** [taigaio/taiga-back#1578]
The "login with github" and probably all oauth authentication options are not respecting other account registration limits.

The oauth ignores PUBLIC_REGISTER_ENABLED: "false" and USER_EMAIL_ALLOWED_DOMAINS options.

This is a serious security issue as it violates the security expectations in a taiga installation.

Taiga can be used with the expectation that only trusted people can login but want to use their Oauth provider for login, for convenience and/or extra security (as Taiga does not support multi-factor authentication).

These plugins should respect both PUBLIC_REGISTER_ENABLED: "false" and USER_EMAIL_ALLOWED_DOMAINS options.

**Comment by yamila-moreno** [comment]
Hi @andresazp thanks for reporting.
We've checked the issue and seen:
- when PUBLIC_REGISTER_ENABLED is False, we'll prevent the user from accessing `/register`
- when PUBLIC_REGISTER_ENABLED is False, you should not use Github/Gitlab oauth as oauth is both register/login and we cannot prevent this. We're adding a condition for official and default installations where if PUBLIC_REGISTER_ENABLED is False, you cannot use Github/Gitlab buttons
- we're going to consider the option of enforcing that the user registered/logged through github/gitlab must have one of the USER_EMAIL_ALLOWED_DOMAINS

Meanwhile, for your own installation, if it's **from source code**:
- (taiga-back) edit your config.py and convert this:
```
INSTALLED_APPS += [
    "taiga_contrib_slack",
    "taiga_contrib_github_auth",
    "taiga_contrib_gitlab_auth"
]
```
into this:
```
INSTALLED_APPS += [
    "taiga_contrib_slack"
]
```
- (taiga-front) edit your config.json and convert this:
```
    "contribPlugins": [
      "/plugins/slack/slack.json",
      "/plugins/github-auth/github-auth.json",
      "/plugins/gitlab-auth/gitlab-auth.json"
    ], 
```
into this:
```
    "contribPlugins": [
      "/plugins/slack/slack.json"
    ], 
```

If it's a **docker installation**, you have to get a [`config.py`](https://github.com/taigaio/taiga-back/blob/master/settings/config.py.prod.example) and a [`conf.json`](https://github.com/taigaio/taiga-front/blob/master/docker/conf.json.template) and map them as bind mounts into the taiga-back and taiga-front services respectively.

**Comment by zeigerpuppy** [comment]
I don't understand the logic of allowing `PUBLIC_REGISTER_ENABLED`=`true` to use Github/Gitlab auth.

In my case I have a private gitlab server where registration is by invite only (self register tuned off).

Therefore, I would like Taiga to authenticate against my private Gitlab while not allowing users to register via other means.

Could this please be supported?

**Comment by Fabyao** [comment]
@zeigerpuppy I have the same use case. Its odd that the `PUBLIC_REGISTER_ENABLED` flag also controls the behaviour of the login process. To me they are different concerns. The code below enforces it. One could change the condition but I suspect this will not be enough to prevent public registration while having the "login with gitlab" button. I suspect the `PUBLIC_REGISTER_ENABLED` is used somewhere in the code.
```
# GITLAB AUTH
    # WARNING: If PUBLIC_REGISTER_ENABLED == False, currently Taiga by default prevents the OAuth
    # buttons to appear for both login and register
    ENABLE_GITLAB_AUTH = os.getenv('ENABLE_GITLAB_AUTH', 'False') == 'True'
    if PUBLIC_REGISTER_ENABLED and ENABLE_GITLAB_AUTH:
        INSTALLED_APPS += [
            "taiga_contrib_gitlab_auth"
        ]
        GITLAB_API_CLIENT_ID = os.getenv('GITLAB_API_CLIENT_ID')
        GITLAB_API_CLIENT_SECRET = os.getenv('GITLAB_API_CLIENT_SECRET')
        GITLAB_URL = os.getenv('GITLAB_URL')
```

**Comment by Fabyao** [comment]
@zeigerpuppy I have managed to disable the "Registration" process in the backend only. There is a compromise as the UI still shows the register form. However if you try to register, the backend will reject the request with `400: Public registration is disabled.` . 
Steps to reproduce:

1. Set `PUBLIC_REGISTER_ENABLED` to False in the backend
2. Set `PUBLIC_REGISTER_ENABLED` to true in the front end
3. Change the `config.py` file in the backend from ``` if PUBLIC_REGISTER_ENABLED and ENABLE_GITLAB_AUTH ``` to ```  if ENABLE_GITLAB_AUTH```

The above will configure the backend to reject ALL registrations but as mentioned the UI still shows both the registration form and link.

**Comment by develop-Greenant** [comment]
Thanks @Fabyao for the tip.  I will definitely give that a try.  

@yamila-moreno, I do believe this issue should be re-opened as it is a major issue for people who want to use Taiga integrated with a self-hosted Gitlab instance, but don't want to allow any person to register.

Hopefully the tip above (although a workaround) provides a relatively simple path forward to solving the issue.
