### ISSUE TITLE
config.py read only mount problem

### ISSUE THREAD

**Issue by burtsevyg** [taigaio/taiga-back#1583]
Good night!

After uncommenting  mount of config.py

`- ./config.py:/taiga-back/settings/config.py:ro`

in [docker-compose.yml](https://raw.githubusercontent.com/taigaio/taiga-docker/master/docker-compose.yml) 
I get error in taiga-back:
```
Running migrations:
  Applying projects.0064_swimlane... OK
  Applying projects.0065_swimlaneuserstorystatus... OK
  Applying projects.0066_project_default_swimlane... OK
  Applying projects.0067_auto_20201230_1237... OK
  Applying taiga_contrib_slack.0001_initial... OK
  Applying taiga_contrib_slack.0002_slackhook_channel... OK
  Applying taiga_contrib_slack.0003_auto_20150923_1620... OK
  Applying taiga_contrib_slack.0004_auto_20160914_1420... OK
  Applying telemetry.0001_initial... OK
  Applying users.0030_auto_20201119_1031... OK
  Applying users.0031_auto_20210108_1430... OK
  Applying userstories.0020_userstory_swimlane... OK
  Applying userstories.0021_auto_20201202_0850... OK
Load default templates
Installed 2 object(s) from 1 fixture(s)
Give permission to taiga:taiga
chown: changing ownership of '/taiga-back/settings/config.py': Read-only file system
```
I think problem in [entrypoint.sh](https://raw.githubusercontent.com/taigaio/taiga-back/master/docker/entrypoint.sh):

`chown -R taiga:taiga /taiga-back`

Best wishes,
Yuriy.

**Comment by burtsevyg** [comment]
As a workaround I change ro to rw:

`- ./config.py:/taiga-back/settings/config.py:rw`

 in the config.py

**Comment by yamila-moreno** [comment]
hi @burtsevyg thanks for reporting! you're rigth, we've already fixed it.
