### ISSUE TITLE
conf.json invalid

### ISSUE THREAD

**Issue by burtsevyg** [taigaio/taiga-back#1584]
In browser console get that my conf.json invalid

Check file:

https://raw.githubusercontent.com/taigaio/taiga-front/f5b5fe77d4374926282c5acade7ec6874509a890/docker/conf.json.template

in https://jsonformatter.curiousconcept.com/# 
online validator.

Add "" to all ${} variables fix the problem.

**Comment by burtsevyg** [comment]
As I understand now I need replace variables with real value.

**Comment by yamila-moreno** [comment]
Hi @burtsevyg if you're installing from source code, you may use [this example file](https://github.com/taigaio/taiga-front/blob/master/conf/conf.example.json).

If you're using docker-compose, you can:
- use a file and mount it (and yes, replace variables)
- use the environment variables (default installation) and it will automatically replace them

Good luck!

**Comment by burtsevyg** [comment]
@yamila-moreno Thank you for your reply, but in docker-compose I have default read only mount

    volumes:
      - ./conf.json:/usr/share/nginx/html/conf.json:ro
Should I replace ro to rw?
And I think this issue related to taiga-front repo.

**Comment by yamila-moreno** [comment]
you can remove the mode:

```
volumes:
  - ./conf.json:/usr/share/nginx/html/conf.json
 ```

**Comment by burtsevyg** [comment]
Oh I see you completely remove  access modifier.

**Comment by burtsevyg** [comment]
Thank you! @yamila-moreno

**Comment by burtsevyg** [comment]
@yamila-moreno now I get in browser console:

app.js:3354 WebSocket connection to 'ws://taigaio.site.com/$%7BTAIGA_WEBSOCKETS_URL%7D/events' failed: Error during WebSocket handshake: Unexpected response code: 200

I found in https://raw.githubusercontent.com/taigaio/taiga-front/master/docker/config_env_subst.sh
```
FILE=/usr/share/nginx/html/conf.json
if [ ! -f "$FILE" ]; then
    envsubst < /usr/share/nginx/html/conf.json.template \
             > /usr/share/nginx/html/conf.json
fi
```

I think I should mount not conf.json but conf.json.template with my config:

`"loginFormType": "ldap"`

**Comment by yamila-moreno** [comment]
config_env_subst is used when you're using environment variables instead of mapping the file.
If you want to install "ldap" nonetheless, you need to compile your own docker images.

I'd suggest you open a new issue explaining what do you want to achieve, so we can better help you.

**Comment by burtsevyg** [comment]
@yamila-moreno Must I rebuild frontend only for adding config file or something else?
