### ISSUE TITLE
Cross-project epic and timeline security

### ISSUE THREAD

**Issue by vauxia** [taigaio/taiga-back#1586]
**Describe the bug**
When a story within a private project is linked to an epic within a public project, updates to the private story appear in the public timeline. This is an information exposure / security issue.

**To Reproduce**
1. Create or access a project that is marked as 'public' 
2. In the public project, go to 'Epics' and add a new epic
3. Create or access a project that is NOT marked as 'public'
4. Create a new user story in the second, private project.
5. Access the user story and click on 'Link to Epic'
6. Under "What's the project", choose the public epic. Under "What's the epic", choose the epic from the public project.
7. Log out and access the site as an anonymous user.
8. Access the public epic and note that the private story is not listed on the epic (this is expected behavior)
9. Access the public timeline and note the messages that read, "$user has related the user story $story to the epic $epic"

**Expected behavior**
Updates to a private/unavailable story should not appear in the public timeline. Stories/issues that a user cannot access should not appear in any timeline that the user can see. This is a potential information exposure risk.

Working as expected:
* The story is correctly listed on the epic when the user can access both projects
* The story is correctly NOT listed when the user cannot access the private project
* Clicking on the story's link with insufficient access results in a 404 error.

**Taiga environment**
Self-hosted Taiga, version 6.x, installed/upgraded from source.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox

**Additional context**
The surrounding use case is to make high-level information about a project publicly available to all users while keeping sensitive or overly-detailed stories behind authentication. This allows my project team to communicate transparently with clients without inundating them with too many details.

AFAIK there's no way to implement access control within a project so that different groups have access to different stories within an overarching project. Cross-project epics are a useful workaround.

**Comment by miryamgduque** [comment]
Hi, @vauxia!
Thanks for reporting! ! You're totally right. We have increased the priority to solve it, and we'll keep you up to date.

**Comment by tdelatorre** [comment]
Hi, @vauxia
We've been reviewing your issue and we're sorry to tell you that it doesn't have a quick fix. We have in mind to refactor the timeline to solve these kind of problems but it is not immediate.

With great regret, right now we can only recommend you modify the title of the private user stories that are linked to an Epic in a public project, with a less sensitive title. You would only have to modify the title because the details of these user stories will never be accessible for others without permissions.

We hope we won't take long to give you a better answer.

Thanks for reporting and for your patience.

**Comment by daniel-herrero** [comment]
Hi, @vauxia!,

The fix has already been merged, and this issue will be fixed in our next release. 

Thank you for reporting!

**Comment by NatachaMenjibar** [comment]
We have included the same fix in user profile timeline. Both project and user profile timeline are now displaying the proper information, so I'm closing the issue.

This changes will be available in the next patch release,

Thanks!
