### ISSUE TITLE
Has Asana import been removed?

### ISSUE THREAD

**Issue by hirusi** [taigaio/taiga-back#1587]
**Describe the bug**
I am exploring Taiga at https://tree.taiga.io/, and the New Project screen does not have Asana import.

**Expected behavior**
The [marketing website](https://taiga.io/) lists Asana, so I expected the import page to have it.

**Taiga environment**
https://tree.taiga.io/

**Additional information**
The [CHANGELOG](https://github.com/taigaio/taiga-back/blob/master/CHANGELOG.md) does not list removal of Asana as an import target.

**Screenshots**
[The relevant bit from the marketing page](https://imgur.com/a/Qh2j89M)
[The import page](https://imgur.com/a/agUwJWs)

**Comment by yamila-moreno** [comment]
Hi @hirusi you're right we missed this in the changelog. Asana API changed and it broke the importers. We're working on them and we'll release it as soon as it's ready again.

**Comment by khuuwinnie** [comment]
Hi, is Asana import available for self-hosted environment?
