### ISSUE TITLE
Error sending email

### ISSUE THREAD

**Issue by unbranched** [taigaio/taiga-back#1593]
I'm using Taiga docker on Ubuntu 20.04 and the server has a working Postfix configuration.

This is the relevant section in my docker-compose.yml :
```
  # Email settings. Uncomment following lines and configure your SMTP server
  EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
  # DEFAULT_FROM_EMAIL: "no-reply@example.com"
  EMAIL_USE_TLS: "True"
  # EMAIL_USE_SSL: "False"
  EMAIL_HOST: "localhost"
  EMAIL_PORT: 25
  # EMAIL_HOST_USER: "user"
  # EMAIL_HOST_PASSWORD: "password"
```

Any moment an email should be sent (e.g. forgot password) I see this in taiga-back logs:
```
ERROR:2021-02-16 14:49:07,806: Internal Server Error: /api/v1/users/password_recovery
Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/opt/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/opt/venv/lib/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/taiga-back/taiga/base/api/viewsets.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/venv/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/taiga-back/taiga/base/api/views.py", line 458, in dispatch
    response = self.handle_exception(exc)
  File "/taiga-back/taiga/base/api/views.py", line 456, in dispatch
    response = handler(request, *args, **kwargs)
  File "/taiga-back/taiga/users/api.py", line 177, in password_recovery
    email.send()
  File "/opt/venv/lib/python3.7/site-packages/django/core/mail/message.py", line 306, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/opt/venv/lib/python3.7/site-packages/django/core/mail/backends/smtp.py", line 103, in send_messages
    new_conn_created = self.open()
  File "/opt/venv/lib/python3.7/site-packages/django/core/mail/backends/smtp.py", line 63, in open
    self.connection = self.connection_class(self.host, self.port, **connection_params)
  File "/usr/local/lib/python3.7/smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "/usr/local/lib/python3.7/smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "/usr/local/lib/python3.7/smtplib.py", line 307, in _get_socket
    self.source_address)
  File "/usr/local/lib/python3.7/socket.py", line 728, in create_connection
    raise err
  File "/usr/local/lib/python3.7/socket.py", line 716, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address
```

/var/log/syslog and /var/log/mail.log don't report anything.

**Comment by brett-stanley** [comment]
Same symptoms for me, using taigaio/taiga-back:6.0.4

**Comment by brett-stanley** [comment]
@unbranched I was able to get this working by making these environment variables on the taiga-async container as well.

Connect to console of taiga-back and use sendtestemail command to verify:

python manage.py sendtestemail

This gave me more information when there were failures, for example when I had TLS and SSL both True in my config.

**Comment by unbranched** [comment]
@brett-stanley still doesn't work, what did you change exactly?

**Comment by brett-stanley** [comment]
I had modified the docker-compose from the repo (&default-back-environment), copying the settings into both taiga-back and taiga-async. When I did so, I originally neglected to have the EMAIL_ variables in the taiga-async config.

Here's my final working config for those two containers - ${VARS} are environment variables coming from the host:

`taiga-async:
    image: taigaio/taiga-back:6.0.4
    container_name: taiga-async
    entrypoint: ["/taiga-back/docker/async_entrypoint.sh"]
    environment: 
      POSTGRES_DB: ${TAIGA_DB_DBNAME}
      POSTGRES_USER: ${TAIGA_DB_USER}
      POSTGRES_PASSWORD: ${TAIGA_DB_PASSWORD}
      POSTGRES_HOST: taiga-db
      TAIGA_SECRET_KEY: ${TAIGA_BACK_SECRET_KEY}
      TAIGA_SITES_DOMAIN: "project.**REMOVED**"
      TAIGA_SITES_SCHEME: "https"
      RABBITMQ_USER: ${TAIGA_EVENTS_RABBITMQ_USER}
      RABBITMQ_PASS: ${TAIGA_EVENTS_RABBITMQ_PASSWORD}
      ENABLE_TELEMETRY: "True"
      DEFAULT_FROM_EMAIL: ${SMTP_USER}
      EMAIL_USE_TLS: "True"
      EMAIL_USE_SSL: "False"
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_HOST_USER: ${SMTP_USER}
      EMAIL_HOST_PASSWORD: ${SMTP_PASSWORD}
      EMAIL_BACKEND: 'django.core.mail.backends.smtp.EmailBackend'
    volumes:
      - /**REMOVED**/taiga/static:/taiga-back/static
      - /**REMOVED**/taiga/media:/taiga-back/media
    depends_on:
      - taiga-db
      - taiga-back
      - taiga-async-rabbitmq
  taiga-back:
    image: taigaio/taiga-back:6.0.4
    container_name: taiga-back
    ports:
      - "19001:8000"
    expose:
      - 19001
    environment:
      POSTGRES_DB: ${TAIGA_DB_DBNAME}
      POSTGRES_USER: ${TAIGA_DB_USER}
      POSTGRES_PASSWORD: ${TAIGA_DB_PASSWORD}
      POSTGRES_HOST: taiga-db
      TAIGA_SECRET_KEY: ${TAIGA_BACK_SECRET_KEY}
      TAIGA_SITES_DOMAIN: "project.**REMOVED**"
      TAIGA_SITES_SCHEME: "https"
      RABBITMQ_USER: ${TAIGA_EVENTS_RABBITMQ_USER}
      RABBITMQ_PASS: ${TAIGA_EVENTS_RABBITMQ_PASSWORD}
      ENABLE_TELEMETRY: "True"
      PUBLIC_REGISTER_ENABLED: "False"
      ENABLE_SLACK: "True"
      ENABLE_GITHUB_IMPORTER: "True"
      ENABLE_JIRA_IMPORTER: "False"
      ENABLE_TRELLO_IMPORTER: "True"
      DEFAULT_FROM_EMAIL: ${SMTP_USER}
      EMAIL_USE_TLS: "True"
      EMAIL_USE_SSL: "False"
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_HOST_USER: ${SMTP_USER}
      EMAIL_HOST_PASSWORD: ${SMTP_PASSWORD}
      EMAIL_BACKEND: 'django.core.mail.backends.smtp.EmailBackend'
    volumes:
        - /**REMOVED**/taiga/static:/taiga-back/static
        - /**REMOVED**/taiga/media:/taiga-back/media
        - /**REMOVED**/taiga/back/config.py:/taiga-back/settings/config.py
    depends_on:
      - taiga-db
      - taiga-events-rabbitmq
      - taiga-async-rabbitmq`
      
      Side note: one other "gotcha" for me was the difference between Python-style "True/False" in the taiga-back and taiga-async vs Javascript-style "true/false" in the taiga-front environment variables.

**Comment by dpineiden** [comment]
I have some similar.

With:

./manage.py check --deploy

```
?: (security.W001) You do not have 'django.middleware.security.SecurityMiddleware' in your MIDDLEWARE so the SECURE_HSTS_SECONDS, SECURE_CONTENT_TYPE_NOSNIFF, SECURE_BROWSER_XSS_FILTER, and SECURE_SSL_REDIRECT settings will have no effect.
?: (security.W003) You don't appear to be using Django's built-in cross-site request forgery protection via the middleware ('django.middleware.csrf.CsrfViewMiddleware' is not in your MIDDLEWARE). Enabling the middleware is the safest approach to ensure you don't leave any holes.
?: (security.W019) You have 'django.middleware.clickjacking.XFrameOptionsMiddleware' in your MIDDLEWARE, but X_FRAME_OPTIONS is not set to 'DENY'. The default is 'SAMEORIGIN', but unless there is a good reason for your site to serve other parts of itself in a frame, you should change it to 'DENY'
```

How correct that on the taiga back container?

**Comment by yamila-moreno** [comment]
@brett-stanley glad you figured it out. I'm closing the issue

@dpineiden your issue doesn't seem related to he original. Please, consider opening a new one.
