### ISSUE TITLE
Celery connection error in Taiga's docker

### ISSUE THREAD

**Issue by alefbragin** [taigaio/taiga-back#1598]
**Describe the bug**

Celery connection error. Repeating error is in the log:

```
taiga-async_1            | [2021-02-22 14:52:55,324: ERROR/Beat] beat: Connection error: failed to resolve broker hostname. Trying again in 28.0 seconds...
taiga-async_1            | [2021-02-22 14:53:41,511: ERROR/MainProcess] consumer: Cannot connect to amqp://guest:**@None:5672//: failed to resolve broker hostname.
```

This bug was introduced in the commit https://github.com/taigaio/taiga-back/commit/180ac8bf2ad54a428d7d6aa4e53b2434df2b9680 .

Let's take a look at this code: 

```python
CELERY_BROKER_URL = f"{ os.getenv('CELERY_BROKER_URL') }"
if not CELERY_BROKER_URL:
    CELERY_BROKER_URL = f"amqp://{ os.getenv('RABBITMQ_USER') }:{ os.getenv('RABBITMQ_PASS') }@taiga-async-rabbitmq:5672/taiga"
```
If `CELERY_BROKER_URL` is not setup `f"{ os.getenv('CELERY_BROKER_URL') }"` evaluate to string `'None'`. Then `not CELERY_BROKER_URL` evaluate to `False`.

It is similar problem with `EVENTS_PUSH_BACKEND_URL` located several line above.

**To Reproduce**

Execute `docker-compose up` for [taiga-docker](https://github.com/taigaio/taiga-docker), and see the log.

**Taiga environment**

- Self-hosted Taiga
- Installed with docker

**Comment by yamila-moreno** [comment]
Hi @alefbragin ! thanks for reporting! We've fixed it and pushed a new taigaio/taiga-back:latest; please pull it again and test it.

Let us know if everything was ok.

**Comment by alefbragin** [comment]
Hi @yamila-moreno ! I pulled the latest image, and the error is gone. Thanks for fixing!

**Comment by ngiafeno** [comment]
I encounter the same issue, but form me, I cloned the taiga-back repo. What can I do? I have pulled the latest version

**Comment by yamila-moreno** [comment]
@ngiafeno open an issue in taiga-back repository detailing the problem. This was related to docker configuration which is different from source configuration, so we may find a different solution.
