### ISSUE TITLE
Integrating Gmail with Taiga does not work

### ISSUE THREAD

**Issue by hadiasheri** [taigaio/taiga-back#1604]
I have install taiga from source according to [this](https://taigaio.github.io/taiga-doc/dist/setup-production.html#_introduction).
I have successfully logged in with admin account. However, when I want to invite members, no email is sent.
I have configured config.py in taiga-back/settings as follows:

DEFAULT_FROM_EMAIL = 'myusername@gmail.com'
#EMAIL_USE_TLS = True
EMAIL_USE_SSL = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'myusername@gmail.com'
EMAIL_HOST_PASSWORD = 'mypassword'

I've tried with and without EMAIL_USE_TLS.
I've also turned on "Less secure apps" in my Gmail account.
I'd be grateful if anyone could help.

**Comment by bameda** [comment]
Try with [this tutorial](https://dev.to/abderrahmanemustapha/how-to-send-email-with-django-and-gmail-in-production-the-right-way-24ab), it works for me.

1. Go to your gmail account and click on **Manage your google account**
    
![image](https://user-images.githubusercontent.com/877218/113690295-88a56400-96cb-11eb-9a1b-4fd445331e85.png)

2. now click on the Security tab

![image](https://user-images.githubusercontent.com/877218/113690436-af639a80-96cb-11eb-8693-3a8828ad9128.png)

3. make sure to enable two steps verification

![image](https://user-images.githubusercontent.com/877218/113690461-b8546c00-96cb-11eb-9fb8-d04b004b78f0.png)

4. now click on App passwords

![image](https://user-images.githubusercontent.com/877218/113690618-e8037400-96cb-11eb-82f6-7271aa46cb1e.png)

5. click on select app choose *** other (Custome Name) *** and give a name to you app

![image](https://user-images.githubusercontent.com/877218/113690689-f782bd00-96cb-11eb-8948-3e59cfc209de.png)

6. the last step click on generate and Gmail will generate a key or an app password make sure to copy this key or save it in a text file

![image](https://res.cloudinary.com/practicaldev/image/fetch/s--Od2oNBNn--/c_limit%2Cf_auto%2Cfl_progressive%2Cq_auto%2Cw_880/https://lh3.googleusercontent.com/pw/ACtC-3cch9URVsSAod-iG5bYAr4eitVATszD4mQkDXSuJEKfEkB587rrhKT409WahJTbYRH8Oz6_6EL4B_Jbhb6q70vRVDnn8Rqht2nkn0EgQfzr6usptPsXf4wnhjPV-XU2qgumfxRCs3mLNGFCYMkVYyGW%3Dw1916-h866-no%3Fauthuser%3D0)

7.  edit your config.py file (at "taiga-back/settings/config.py") with your google account and your new passwor like this:
```python
#gmail_send/settings.py
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'yoorusername@gmail.com'
EMAIL_HOST_PASSWORD = 'key' #past the key or password app here
EMAIL_PORT = 587
EMAIL_USE_TLS = True
DEFAULT_FROM_EMAIL = 'default from email'
```

You can test it runnning this this command in your taiga server:

```bash
$ DJANGO_SETTINGS_MODULE=settings.config ./manage.py test_emails yourgmailaccount@gmail.com
```
