### ISSUE TITLE
Can't Login Django Admin 

### ISSUE THREAD

**Issue by RiajulKashem** [taigaio/taiga-back#1605]
Installed taiga on Manjaro Linux via [this](https://taigaio.github.io/taiga-doc/dist/setup-development.htm) tutorial.
After starting the development server I wanted to login with admin 123123 but it doesn't work

**Comment by yamila-moreno** [comment]
Hi @RiajulKashem the url gives me a 404.

The admin/123123 was deprecated, and now you should create your own superuser. The official documentation you can follow is here: https://resources.taiga.io/30min-setup/

cheers!
