### ISSUE TITLE
Unable to upload file as attachment more than 1 MB

### ISSUE THREAD

**Issue by Apurv-P** [taigaio/taiga-back#1612]
Unable to upload any file more than 1Mb as attachment in taiga, as client_max_body_size 100M; in taiga.conf

Error:
![Untitled](https://user-images.githubusercontent.com/57949373/114691906-c6426680-9d35-11eb-9b9b-f0a29933420f.png)

this issue happen suddenly, I have tested with many test projects and different files but no luck

please Help

Thanks,
Apurv P

**Comment by yamila-moreno** [comment]
Hi @Apurv-P 
- do you have taiga installed from source code or docker?
- did you change anything in the nginx or taiga settings?

**Comment by Apurv-P** [comment]
do you have taiga installed from source code or docker?
- Source Code

did you change anything in the nginx or taiga settings?
- recently installed SSL certificate (let's encrypt) and made some changes in taiga.conf 

Here are config file (/etc/nginx/conf.d/taiga.conf)

server {
    listen 80 default_server;
    server_name xyz.com;
    return 301 https://$server_name$request_uri;

    large_client_header_buffers 4 32k;
    client_max_body_size 100M;
    charset utf-8;

    access_log /home/taiga/logs/nginx.access.log;
    error_log /home/taiga/logs/nginx.error.log;
}

server {
    listen 443 ssl;
    server_name xyz.com;

    # Frontend
    location / {
        root /home/taiga/taiga-front-dist/dist/;
        try_files $uri $uri/ /index.html;
    }

    # Backend
    location /api {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://127.0.0.1:8001/api;
        proxy_redirect off;
    }

    # Admin access (/admin/)
    location /admin {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://127.0.0.1:8001$request_uri;
        proxy_redirect off;
    }

    # Static files
    location /static {
        alias /home/taiga/taiga-back/static;
    }

    # Media files
    location /media {
        alias /home/taiga/taiga-back/media;
    }

    # Events
    location /events {
        proxy_pass http://127.0.0.1:8888/events;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_connect_timeout 7d;
        proxy_send_timeout 7d;
        proxy_read_timeout 7d;
        }

    #SSL
    ssl on;
    ssl_certificate /etc/letsencrypt/live/xyz.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/xyz.com/privkey.pem;
}

**Comment by Apurv-P** [comment]
Hi,

It's Resolved,
I have just added client_max_body_size 100M; in 443 server block

server {
    listen 443 ssl;
    server_name xbytepms.com;
    client_max_body_size 100M;

Thanks,
Apurv P.
