### ISSUE TITLE
404 error with /api/v1/user-storage/ on clean install

### ISSUE THREAD

**Issue by cmseal** [taigaio/taiga-back#1615]
**Describe the bug**
I've got a clean install from source, with no data in it (not even sample/demo), but viewing the kanban after creating a project yields:
`GET /api/v1/user-storage/319e... 404 (not found)` in the developer console/web server log

I've tried with adding in the sample data and the same thing occurs.  Everything seems to work, so I'm unsure why this is occurring.

**To Reproduce**
1. Clean installation from stable source
2. Create new project
3. View kanban

**Expected behavior**
No error

**Taiga environment**
Self-hosted from latest stable source, on Ubuntu 20.04 LTS, using Apache without the `taiga-protected` service (config below).

```apache
  DocumentRoot "/var/www/taiga/dist"

  Alias /media "/var/taiga/backend/media"
  Alias /static "/var/taiga/backend/static"

  <Directory "/var/taiga/backend/static">
    AllowOverride None
    Require all granted
  </Directory>

  <Directory "/var/taiga/backend/media">
    Header always set Content-disposition attachment
    AllowOverride None
    Require all granted
  </Directory>


  ProxyRequests Off
  ProxyPreserveHost On

  ProxyPass /api http://localhost:8001/api
  ProxyPassReverse /api http://localhost:8001/api

  ProxyPass /admin http://localhost:8001/admin
  ProxyPassReverse /admin http://localhost:8001/admin


  RewriteEngine On

  RewriteCond %{HTTP:UPGRADE} ^WebSocket$           [NC,OR]
  RewriteCond %{HTTP:CONNECTION} ^Upgrade$          [NC]
  RewriteRule /events ws://localhost:8888/events  [P,QSA,L]

  RewriteCond %{REQUEST_URI} !^/admin(.*)
  RewriteCond %{REQUEST_URI} !^/api(.*)
  RewriteCond %{REQUEST_URI} !^/events(.*)
  RewriteCond %{REQUEST_URI} !^/static(.*)
  RewriteCond %{REQUEST_URI} !^/media(.*)
  RewriteCond %{DOCUMENT_ROOT}/%{REQUEST_FILENAME} !-f
  RewriteRule . /index.html [L]
```

**Desktop (please complete the following information):**
Doesn't matter which browser, OS combination (have tried with macOS and Safari/Chrome/FF, and Ubuntu with Chrome)

**Additional context**
Auth is set to use LDAP by default, but the same occurs when using a locally created superuser.

**Comment by f5-bit** [comment]
I can confirm this issue, also self-hosted from latest stable source, on Ubuntu 20.04.2 LTS, and tested with Firefox. Moreover, I cannot add members to any project, but this may not be related to this issue.

**Comment by hypervtechnics** [comment]
I can confirm this. I have the protected-service enabled. I also can't delete or modify tasks on a kanban board, which might have a similar cause.

**Comment by bameda** [comment]
Hi @cmseal 

404 responses for user-storage api endpoint is within the expected behavior. You ara asking to the api for some data, in this case if there is some custom filter saved for your user, this key is not present in user-storage (a key-value store services for taiga users, like the localstorage in the browser) so the api return not found, nothings here about this key.

Best regards.
