### ISSUE TITLE
Some tests are skipped due to duplicate names

### ISSUE THREAD

**Issue by code-review-doctor** [taigaio/taiga-back#1618]
Test names must be unique per scope otherwise the second test overrides the first one with the same name.

For example if you had a test file that does:

```
def test_a():
    pass

def test_a():
    pass
```

Then only the second `test_a` will be ran. More details [here](https://codereview.doctor/features/python/best-practice/avoid-duplicate-unit-test-names).

These are the tests that are overriding previously defined tests due to this problem:

https://github.com/taigaio/taiga-back/blob/60ccd74c80e12056d0385b2900fd180d0826e21c/tests/integration/test_memberships.py#L640
https://github.com/taigaio/taiga-back/blob/60ccd74c80e12056d0385b2900fd180d0826e21c/tests/integration/test_userstories_update_kanban_order.py#L740
https://github.com/taigaio/taiga-back/blob/60ccd74c80e12056d0385b2900fd180d0826e21c/tests/integration/test_userstories_update_kanban_order.py#L770
https://github.com/taigaio/taiga-back/blob/60ccd74c80e12056d0385b2900fd180d0826e21c/tests/integration/test_userstories_update_kanban_order.py#L801
https://github.com/taigaio/taiga-back/blob/60ccd74c80e12056d0385b2900fd180d0826e21c/tests/integration/test_userstories_update_kanban_order.py#L832
https://github.com/taigaio/taiga-back/blob/60ccd74c80e12056d0385b2900fd180d0826e21c/tests/integration/test_hooks_bitbucket.py#L568
https://github.com/taigaio/taiga-back/blob/60ccd74c80e12056d0385b2900fd180d0826e21c/tests/integration/test_hooks_gitlab.py#L1107

I found this issue automatically, see other issues [here](https://codereview.doctor/taigaio/taiga-back)

**Comment by juanfran** [comment]
https://github.com/kaleidos-ventures/taiga-back/issues/81
