### ISSUE TITLE
swimlanes in Kanban template

### ISSUE THREAD

**Issue by rodrigobraga** [taigaio/taiga-back#181]
Hi guys

Our team wants try Taiga; and for us, _swimlanes_ is very important. This feature appear on the road map? (sorry if already exists and I did not find)

**Comment by plesatejvlk** [comment]
I would also appreciate some kind of scoping of User Stories since having more than a few in single column makes board hard to use (lots of scrolling on my 1920x1200 display).

**Comment by superalex** [comment]
Thanks for your suggestion @plesatejvlk  :+1:

**Comment by colinodell** [comment]
+1

**Comment by ph-One** [comment]
:+1:

**Comment by HeneryH** [comment]
Swimlanes important here too.  I want to track several 'initiatives' on the same Kanban.

**Comment by turingmachine** [comment]
:+1:

**Comment by Polymathronic** [comment]
+1

**Comment by ilconfa** [comment]
+1

**Comment by ecocode** [comment]
hello. is this feature request considered to be implemented or is it for any reason not to be implemented ?

**Comment by kdaun** [comment]
+1

**Comment by skre** [comment]
+1

**Comment by SAThomsen** [comment]
+1

**Comment by robinklaassen** [comment]
+1

**Comment by oechslein** [comment]
+1

**Comment by v-francoise** [comment]
+1

**Comment by thavidu** [comment]
Any word on this? or has anyone written any sort of plugin that would provide similar functionality?

**Comment by mboogert** [comment]
+1

**Comment by wpnzach** [comment]
+1

**Comment by Souriya** [comment]
+1

**Comment by cbeauhilton** [comment]
+1

**Comment by benboeck** [comment]
+1

**Comment by xkoma** [comment]
I would like to get this feature too ! ;-) I think it's really important in Kanban.

**Comment by danieldram** [comment]
I would also like swimlanes..

**Comment by Jason-Scott-23** [comment]
+1

**Comment by almereyda** [comment]
Swimlanes have been released with Taiga 6.

- https://blog.taiga.io/taiga6-release.html

This issue can be closed.

**Comment by yamila-moreno** [comment]
thanks @almereyda for noticing it. Closing the issue. Hope you all enjoy swimlanes :)
