### ISSUE TITLE
Support realtime updating

### ISSUE THREAD

**Issue by chrisdrobison** [taigaio/taiga-back#206]
Support realtime updating of the UI, specifically when new comments, tasks, attachments, etc. are added. Also when things are moved around on the board.

**Comment by superalex** [comment]
Hello @chrisdrobison,

Taiga actually supporints realtime updateing for backlog, kanban and taskboard, are you missing it anywhere more?

**Comment by chrisdrobison** [comment]
I was trying the demo online earlier and didn't see the board items updating their position in another account realtime.

**Comment by superalex** [comment]
I've just checked in tree.taiga.io and is working fine (chrome 39.0.2171.95 (64-bit)), what browser are you using?, could you please detail a bit more the steps you have done to reproduce the issue?

Thanks!
