### ISSUE TITLE
[Q] Importing a project dump into a new taiga instance loses users 

### ISSUE THREAD

**Issue by velis74** [taigaio/taiga-back#21]
I'm spinning off part of a dedicated Taiga server to another server transferring only some of the projects. The old taiga instance is set up from GIT repositories, the new one with containers. Technically both should be the same as the container was set up days ago and the repository one was upgraded at the same time as per instructions. Both seem to function perfectly.

I export my desired project at the old instance.
I import the project at the new instance

I immediately notice the the project at the new instance has issues with users: some have empty names, some are just not there.
The sprints "lose" the user stories assigned to the missing people.

I then make an export from the new project.

I compare export from old server and the new server: they are exactly the same except for lost user information.

examples:

```
"memberships": [
  {"user": null, ... (the rest of the fields remain as they were on the old server)
...
]
```

```
"user_stories": [
  {
    history: [
      "user": [null, "Missing User"],
      ...
    ],
    "owner": "changed to the project owner"
      ...
    }
  }
]
```

I expect this is because the users are not in the database at the time of import. I looked all over the place for documentation on how to handle this, but I can find none. Nor any issues.

Have I identified the problem sufficiently? What would be the best way to migrate users between the server instances then? Preferably such that they wouldn't have to re-register.

**Comment by velis74** [comment]
Confirm: I dumped users table from old instance and loaded it into the new one and now the imports work.

I'm beginning to wonder whether I'm just a poor docs reader sice I couldn't find any issues on the subject.

Edit: I have now transferred all projects except for one which has issues only and lots of attachments (JSON is about 450MB). Trying to figure out what's wrong with that one...

Edit 2: I have successfully imported the project via the taiga-back management command. No issues. No idea why it wouldn't work over the browser. Since this was the last project to be transferred, I'll give it a rest, but I would have loved some logs telling me why the job gets aborted in seconds from being started with no indication that something went wrong. I looked at all the containers' logs with none having anything of note.

**Comment by bameda** [comment]
Usually the problems of importing large projects (large files) are related to the configuration of the nginx (web server). By default the file transfer size is limited, sometimes the request time too.

The best way to import projects between instances in taiga is to copiying the `media/` directory and using pg_dump / pg_restore to clone the data base. When you import a project from the interface, you clone the project data and its membership information but not all the user information (or user profile). This is the reason you need to create users in the new instance.

Here (https://docs.taiga.io/backup-and-restore.html#docker) you can find information about how to backup and restore taiga instances (or migrate data between them).

**Comment by velis74** [comment]
Well, until I set client buffer sizes I was getting a 403, I think, clearly stated that the uploaded file was too big.Taiga handled that one more gracefully, though not graceful. As least I could see what the problem was in network pane because the actual response told me what was wrong. Taiga itself just errored-out.

But this large dump is different: HTOP clearly shows that processing begins, but them immediately stops. The appropriate celery task starts, but immediately stops. Followed by two more queue-related tasks that also stop shortly afterwards.

**Comment by yamila-moreno** [comment]
Hi there!

Do you know that we have [Taiga Community](https://community.taiga.io/) for questions? Please, check there; maybe another user has already ask something similar. If not, create your own. There are people there willing to help, members of the Taiga team members and other users.

To simplify  the process, we will systematically close all issues that are general support questions and redirect people to Taiga Community.

Taiga Team
