### ISSUE TITLE
Invitation link not working

### ISSUE THREAD

**Issue by kain-jy** [taigaio/taiga-back#213]
"ACCEPT YOUR INVITATION" button in invitation mail not working.

**Comment by superalex** [comment]
Hello @kain-jy,

Thanks for reporting, I've tested it right now in https://tree.taiga.io and it's working properly, what isn't working exactly?

Regards,

**Comment by kain-jy** [comment]
@superalex Thank you for replying quickly!

https://github.com/taigaio/taiga-back/blob/master/taiga/projects/templates/emails/membership_invitation-body-html.jinja#L10

I found above code missing `final_url`.

**Comment by superalex** [comment]
Thank you very much for detecting the issue @kain-jy!, it's a bug we introduced yesterday in a merge, we are redesigning all the emails of the platforms. At least in stable (https://tree.taiga.io) it's still working correctly. 

We are fixing it as soon as possible.

Regards,

**Comment by kain-jy** [comment]
:+1:

**Comment by superalex** [comment]
Should be working again: https://github.com/taigaio/taiga-back/commit/e81cafb3e36df46e1d49704245d8e27b4b032dd7 :+1:

**Comment by Zhomart** [comment]
I got link without "href" too using stable branch. When I tried second time I got this kind of url `http:/%0D%20/taiga.mycompany.com/invitation/6ab24878-bcb6-11e4-b49b-040140f49301`

Also, at the beginning invitation didn't work. I had to add `cssutils==1.0` and `cssselect==0.9.1` into `requirements.txt`.

**Comment by jespino** [comment]
can you paste here the SITES variable of your settings/local.py?

**Comment by Zhomart** [comment]
Sure

```
SITES["front"]["scheme"] = "http"
SITES["front"]["domain"] = "taiga.mycompany.com"
```

**Comment by jespino** [comment]
This behavior is really strange. First of all, the cssutils and cssselect must be installed the premailer requirement you don't have to install it by hand. Receive the invitation without the href filled, is strange too, and receive the email as raw html is another time, strange (which mail client you use?)

The gunicorn.stderr.log have some warnings and errors related to premailer, but are known errors, they aren't a problem.

Which process do you follow for the installation?

**Comment by Zhomart** [comment]
I followed this one http://taigaio.github.io/taiga-doc/dist/setup-production.html

In the process of installation, `pip install` crashed because of not enough RAM. I added swap file and restarted again.

I just got, I'll try to remove all packages and reinstall again.

**Comment by jespino** [comment]
Great, after that, if the error persist, contact again, please. :smiley:
