### ISSUE TITLE
Allow estimation of stories in hours.

### ISSUE THREAD

**Issue by bpaz** [taigaio/taiga-back#230]
I think we should be able to estimate stories, not only in story points but also in hours.

**Comment by jespino** [comment]
Hi @bpaz, 

you can redefine the points as you want in the admin panel. If you use hours, you can change the current points estimations to 1, 2, 4, 8, 16, 24, 36, 48, and say to the team "1" point means "1" hour.

If you want to have points + hours, you will have to use the custom fields feature which will be available in the next weeks.
