### ISSUE TITLE
When adding a new member to a project you cannot send personalised text longer than 253 characters

### ISSUE THREAD

**Issue by nmilnercollabora** [taigaio/taiga-back#234]
When adding new members to my project in Taiga I am finding that I get an oompa lompas error message when I write more than 253 characters of personalised text.

**Comment by superalex** [comment]
Thanks @nmilnercollabora, it's a bug, the web app should control the length of the text

**Comment by superalex** [comment]
Solved here -> https://github.com/taigaio/taiga-front/commit/8934861cc7df76d8cc22888836c173921557c4e9
