### ISSUE TITLE
missing cssselect and cssutils in requirements.txt

### ISSUE THREAD

**Issue by edweip3** [taigaio/taiga-back#245]
I had to manually install these. otherwise, i can't post comments, as that triggers an email to be send.  That code seem to use cssutils and cssselect modules.  Here's a log snippet:

 from .premailer import Premailer, transform
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/premailer/premailer.py", line 32, in <module>
    import cssutils
ImportError: No module named 'cssutils'

and also:

ImportError: cssselect seems not to be installed. See http://packages.python.org/cssselect/
ERROR:2015-02-06 15:14:26,509: Internal Server Error: /api/v1/issues/313
Traceback (most recent call last):
  File "/home/ubuntu/.virtualenvs/taiga/lib/python3.4/site-packages/lxml/cssselect.py", line 16, in <module>
    external_cssselect = __import__('cssselect')
ImportError: No module named 'cssselect'

**Comment by superalex** [comment]
Hello @edweip3 cssselect should via installed via premailer requirement. Did you update your instance?, if so...did you update your virtualenv packages?

Here (http://taigaio.github.io/taiga-doc/dist/setup-production.html#faq-maintain-update) you can find a list with the detailed steps for updating an instance.

**Comment by edweip3** [comment]
Yeah, i did follow all of the instructions on that page.  somehow it didn't include those dependencies.

**Comment by zwarmapapa** [comment]
It gave errors for me as well when trying to invite people into a project. 
I fixed it by running this: pip install cssselect --upgrade
