### ISSUE TITLE
ImportError: cannot import name 'smart_text'

### ISSUE THREAD

**Issue by psgganesh** [taigaio/taiga-back#249]
We get ImportError: cannot import name 'smart_text' whenever we execute the below command
python manage.py migrate --noinput

**Comment by superalex** [comment]
smart_text is part of rest_framework, one of the basic packages taiga-back needs to work. Is it a fresh installation?, did you activate the virtualenv before executing the command? (workon taiga)

**Comment by psgganesh** [comment]
oh ok let me check,,, gimme a sec

**Comment by psgganesh** [comment]
yup cheked it is still the same... :(

**Comment by superalex** [comment]
did you execute the "pip install" command, in the virtualenv?

**Comment by psgganesh** [comment]
no all installs as root user

**Comment by psgganesh** [comment]
you want me to ,, then i will have to re-install the OS and get back.....k will do

**Comment by psgganesh** [comment]
Yippee,,, almost there..just one thing which version of django-transactional-cleanup is needed as we get the following when we do a pip install django-transactional-cleanup
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1314: ordinal not in range(128)

**Comment by psgganesh** [comment]
Almost there Super, just that above if we fix i think we will get it right :+1:  the version which is needed for pip install django-transactional-cleanup, it tried with 0.1.12, 0.1.11, 0.1.12 but no luck i get the same  above message

**Comment by superalex** [comment]
The ascii seems to happen because you are using python 2.7, taiga needs python 3. It's fully recommended that you do the installation in a virtual without root user, are you following our installing documentation? http://taigaio.github.io/taiga-doc/dist/

**Comment by psgganesh** [comment]
Yes, we are using python 3.4

![image](https://cloud.githubusercontent.com/assets/2221525/6131987/c70e9fb4-b175-11e4-855e-b922a8a065fd.png)

**Comment by jespino** [comment]
Hi, this is a problem with the setup.py in django-transactional-cleanup. I will fix it and upload again the 0.1.12 version fixed.

**Comment by jespino** [comment]
Hi, can you try it with the 0.1.13 version?

**Comment by psgganesh** [comment]
yup one moment

**Comment by psgganesh** [comment]
No errors while installing but errors when migrating

![image](https://cloud.githubusercontent.com/assets/2221525/6132464/b8dc3836-b178-11e4-97e0-d59086f201b9.png)

**Comment by jespino** [comment]
I think you don't installed it correctly, test to run
```
pip install django-transactional-cleanup
```

without the version

**Comment by psgganesh** [comment]
You are write @jespino no problems in django-transactional-cleanup, but now problems in migrating....this python manage.py migrate --noinput for which this issue was raised still did not solve it though...
![image](https://cloud.githubusercontent.com/assets/2221525/6132968/a44f98aa-b17c-11e4-9cfa-f8549b3ff9f6.png)

**Comment by jespino** [comment]
Now the problem is related with your postgresql credential, you need to configure your postgresql user (the error is that you are trying to enter in your taiga database as root user, and the root user doesn't exists in postgresql).

**Comment by psgganesh** [comment]
i have the user created under the name taiga with a database, but from which file is this root being picked up...?

**Comment by psgganesh** [comment]
Found out from this ref, https://help.ubuntu.com/community/PostgreSQL that the username would be your own login name, and you don't even need a password, working it out..

**Comment by psgganesh** [comment]
Its done :100:  Thanks to the team, closing this issue

**Comment by jespino** [comment]
Great! :smile: You are welcome
