### ISSUE TITLE
Enabling HTTPS breaks current users login action

### ISSUE THREAD

**Issue by Ferixz** [taigaio/taiga-back#253]
Hi everyone.

First of all, I need to thank you for you efforts and the great application. I could only enjoy working with Taiga. :)

Here's the problem: After I enabled HTTPS, I couldn't login with neither of my users (admin and the other thing). I deleted caches and cookies but it didn't work.

I was able to register a new user. I was able to recover password for my secondary user and access my account again, but my admin is lost (email was not set).

This is the response I received from Django server:
```json
{
   "_error_message": "Username or password does not matches user.", 
   "_error_type": "taiga.base.exceptions.WrongArguments"
}
```

Maybe I'm missing something from the documentation. I just wanted to make sure it's not a bug.

**Comment by superalex** [comment]
Hello @Ferixz 

I think it's not possible that only enabling https makes your old users stop working. Did you change the default password from user admin?, you could access to the django admin to check your users (and update manually their passwords) going to /admin/.

**Comment by Ferixz** [comment]
Hi @superalex,

Unfortunately, I had changed my password and it wasn't working for admin area either. I had a backup and I was able to restore my setup to its previous state. Everything's fine right now (with HTTPS enabled :dancer: ).

I've been thinking about it. Is it possible that somehow session data stored on server is not being invalidated (client is provided with same cookie from before enabling ssl encryption) and is causing this issue?

**Comment by superalex** [comment]
Hmmmm, if you are using Taiga in a normal way session data is not stored in on the server, we use self-contained stateless authentication, all the session data is stored in the token.

From taiga-back folder you can use the command "python manage.py changepassword username" for restoring manually a password ;)
