### ISSUE TITLE
HipChat Integration

### ISSUE THREAD

**Issue by AndrewDryga** [taigaio/taiga-back#256]
HipChat is also great as Slack, many companies use it. And it would be grate to have such integration.

Also HipChat have pretty simple API.

**Comment by superalex** [comment]
It should be really easy to do basing it on the existing code for slack: https://github.com/taigaio/taiga-contrib-slack or hall: https://github.com/taigaio/taiga-contrib-hall

It's in our roadmap but it's also an easy entry point for developing things in Taiga, is anyone interested in working on it?

**Comment by astagi** [comment]
Can I work on hipchat integration? I've just integrated it with an internal custom CI service for Android.

**Comment by superalex** [comment]
Sure @astagi, I think taiga-contrib-slack could a good code base for it :+1:

**Comment by astagi** [comment]
Thanks I'll have a look at it :) could you please assign me this task?

**Comment by astagi** [comment]
Thank you, and thanks for adding me :)

**Comment by superalex** [comment]
Thank you for developing it!, :+1:

**Comment by astagi** [comment]
hey @superalex could you open a dedicated repo to work on, please? thanks! :)

**Comment by jespino** [comment]
I create it. One minute :smiley:

**Comment by jespino** [comment]
@astagi Done! :sparkles:

**Comment by astagi** [comment]
Thank you @jespino :)

**Comment by astagi** [comment]
@AndrewDryga it's time for testing :) https://github.com/taigaio/taiga-contrib-hipchat

I'll add some documentation during the next days.

**Comment by Xaviju** [comment]
:cool:

**Comment by sgnl** [comment]
I would love to see this Integration service be available on taiga.io :D

**Comment by astagi** [comment]
HipChat plugin has been released! (https://pypi.python.org/pypi/taiga-contrib-hipchat/ more info here: https://github.com/taigaio/taiga-contrib-hipchat). This issue can be closed :)

**Comment by bameda** [comment]
and https://taiga.io/support/hipchat-integration/

**Comment by astagi** [comment]
Yes :)
