### ISSUE TITLE
Problem with django-transactional-cleanup

### ISSUE THREAD

**Issue by livingstonef** [taigaio/taiga-back#259]
There is an issue with setting up the django-transactional-cleanup==0.1.13 requirement. 

In this module  File "/var/www/taiga-back/build/django-transactional-cleanup/setup.py", line 22, Fails with TypeError: 'encoding' is an invalid keyword argument for this function. Even the taiga-scripts fail at this point for me. 

    long_description = open('README.markdown', 'r', encoding='utf8').read(),

More here https://github.com/jespino/django-transactional-cleanup/issues/1

How did you guys get past this without manually modifying then installing the module?

**Comment by jespino** [comment]
Sorry, now fixed. Thanks for your feedback.
