### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by whodafly** [taigaio/taiga-back#261]
Just cloned Taigo, and started running through the installation instructions, but I came up against the following issues.

Firstly, it seems there are two missing two dependencies from your requirements.txt file: kombu and billiard. Once I installed those, things moved on (a bit).

Secondly, on the initial "migrate", I get the following error:

psycopg2.OperationalError: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

I went and had a brief look in settings/common.py and it appears that you're trying to use PostgreSQL, but there are no instructions that mention that, nor mention of where to put the username and password I'll inevitably need.

I'm a Python dev, but not a Django dev, so I am a bit lost as to where to go from here.

**Comment by superalex** [comment]
Hello @whodafly,

Welcome to Taiga! :)

kombu and billiard should be installed by the celery package (included in the requirements), could you have any problem installing the package so you didn't install those dependencies?

```
pip show celery
---
Name: celery
Version: 3.1.17
Location: /home/superalex/Envs/taiga/lib/python3.4/site-packages
Requires: billiard, pytz, kombu
```
In our installation guides (both for development and production) http://taigaio.github.io/taiga-doc/dist/#_installation_guide we explain that postgresql is a requirement. The default authentication system of postgresql doesn't need user and password, it's based on the logged user on the machine ;)

Regards!,

**Comment by whodafly** [comment]
Hi @superalex 

The only other installation issue I had with requirements.txt was that you require a higher version of lxml than I had installed, so I had to install some dev packages and then re-run pip.

Ah, I was going by your readme, not the installation guides. I'll check that out, thanks.

**Comment by superalex** [comment]
You are welcome!, I think we should make our README clearer about this topic :+1: 

Thanks!
