### ISSUE TITLE
API limits returned user stories to 30

### ISSUE THREAD

**Issue by nmilnercollabora** [taigaio/taiga-back#268]
I am using the API to GET the user stories in a particular project i.e.:

curl -X GET \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer ${AUTH_TOKEN}" \
  https://api.taiga.io/api/v1/userstories/1

However, I only get 30 user stories returned when there are more than that in the project.

Is this a bug or is it the case that I can increase the number of returned user stories somewhere?

**Comment by jespino** [comment]
Hi @nmilnercollabora ,

This isn't a but, is the normal behavior because we use pagination by default, you can see more about it in the pagination section of the API documentation (http://taigaio.github.io/taiga-doc/dist/api.html#_pagination). And you can disable it using HTTP headers.

Regards.

**Comment by bameda** [comment]
Hi @nmilnercollabora, it's not a bug because the results are paginated. See http://taigaio.github.io/taiga-doc/dist/api.html#_pagination to get more info about this.

**Comment by nmilnercollabora** [comment]
Thanks for your responses and agree that this is not a bug but user error.
