### ISSUE TITLE
is there an API to manipulte issues?

### ISSUE THREAD

**Issue by alexandre** [taigaio/taiga-back#269]
Hi guys,

I want to close taiga issue when I (automatically) close a issue on GitHub. Something that to allow I send a POST would be enough (I would create an app to talk between taigaio and github if necessary).

P.S -> I'm sorry for the low english skill

[ ]'s (hugs)

**Comment by bameda** [comment]
Hi @alexandre 

You have an API at https://api.taiga.io/api/v1/ and you can find the documentation at http://taigaio.github.io/taiga-doc/dist/api.html

But if you only want to close issues (user stories and tasks too) or change its status you can use the commit messages configuring the integration with GitHub in taiga.io. You can find the  instructions in our support page https://taiga.io/support/github-integration/

Regards.

**Comment by alexandre** [comment]
That's enough to me. Thank you, @bameda

**Comment by bameda** [comment]
You're welcome, I hope you find taiga as a useful and enjoyable tool.

**Comment by alexandre** [comment]
Yeah. Taiga is much love. <3
