### ISSUE TITLE
Error on master branch AttributeError: 'DatabaseWrapper' object has no attribute 'on_commit'

### ISSUE THREAD

**Issue by gaikwad411** [taigaio/taiga-back#272]
Hi there,
    I wanted to try "custom fields" feature, so I pulled latest udpates from master branch. 
    Server is running but, while posting userstories, I get following error

    AttributeError: 'DatabaseWrapper' object has no attribute 'on_commit'

    Please help.

**Comment by superalex** [comment]
hello @gaikwad411,

Is your instance working with stable branch?, are you using posgresql?, what version?

Regards!,

**Comment by ttf** [comment]
Same problem here.
```
Internal Server Error: /api/v1/userstories
…
  File "/usr/local/lib/python3.4/dist-packages/django/db/__init__.py", line 40, in __getattr__
    return getattr(connections[DEFAULT_DB_ALIAS], item)
AttributeError: 'DatabaseWrapper' object has no attribute 'on_commit'
```
Running 336d1416 with postgresql 9.4.1

Haven't tested stable regarding this issue; switched away from it, as it turned out to have a larger authentication issue (non existing user with valid session information seemingly was allowed to access the sample data), which seems to be fixed on `master` by now.

**Comment by jespino** [comment]
Hi, wich ENGINE you use in your local.py DATABASE configuration?

**Comment by ttf** [comment]
```
'ENGINE': 'django.db.backends.postgresql_psycopg2',
```

**Comment by ttf** [comment]
Good call.

Changing this to `transaction_hooks.backends.postgresql_psycopg2` (as mentioned in https://django-transaction-hooks.readthedocs.org/en/latest/) worked for me.

https://github.com/taigaio/taiga-back/blob/master/settings/local.py.example#L21 is still on the old engine.

Thank you very much.

**Comment by superalex** [comment]
You are absolutely right, we didn't update that file in master branch, updated in the commit https://github.com/taigaio/taiga-back/commit/d98455744943f88717f116bd1c1331bef63cc802

Thank you very much @ttf
