### ISSUE TITLE
Search for a tag does not find the tagged US

### ISSUE THREAD

**Issue by RubenKelevra** [taigaio/taiga-back#276]
I added a tag "node-info" to a US, now I search for node-info and does not get any result...

I would expect that tags are searched to.

**Comment by superalex** [comment]
Thanks for your suggestion @RubenKelevra

**Comment by RubenKelevra** [comment]
Welcome! :)

**Comment by 1IfByLAN2IfByC** [comment]
agreed! tag searching would be a very helpful feature, specifically for grouping sprints

**Comment by superalex** [comment]
You are right, improving the searching system is one of the enhancements we would like to implement soon!

**Comment by 1IfByLAN2IfByC** [comment]
I'm working on developing it now (boss is impatient). 

From the looks of */tagia-back/taiga/searches/services.py*, its looks like it should be as simple as adding the tag field to each of the routines. However, since tags are stored as a text array the query will have to be modified. 

something along the lines of 
``` 
sqlQ = "SELECT * FROM user_stories WHERE tags @> array[{text}]".format(text = text)
```

should work. 

any ideas?

**Comment by superalex** [comment]
Hello @1IfByLAN2IfByC 

I think something like that could work!. If you make a PR for that part that would be great. Will that approach consider the capitalized tags?

**Comment by volans-** [comment]
@superalex I've submitted a quick PR ( #608 ) to allow to search into tags, following the same approach used already for the other fields.

It basically explode the tags array with spaces and add them to the tsvector like the other fields.

I'm wondering how this search approach works with different languages, given that the tsvector is based on the english one.
