### ISSUE TITLE
Invalid cookie data, logout instead of 401

### ISSUE THREAD

**Issue by zwarmapapa** [taigaio/taiga-back#289]
Could Taiga just log the user out when the data in the cookie (username / password) is invalid? Currently it gives a 401 and it doesn't seem to be doing anything else.

**Comment by superalex** [comment]
Hello @zwarmapapa,

Taiga API returns 401 (unauthorized) if it receives invalid credentials. If the web app detects 401 error in one of the API calls it shows you to the login page. Taiga uses stateless authentication (http://www.kaleidos.net/blog/295/stateless-authentication-with-api-rest/). What do you mean exactly exactly with login the user out?

**Comment by zwarmapapa** [comment]
Well, I kept getting a 401 error until I cleared all my cookies, only then I saw the login screen.

**Comment by superalex** [comment]
But Taiga web app doesn't use cookies for authentication, it's using local storage.

**Comment by zwarmapapa** [comment]
Hmm, that's interesting... What could've caused the 401? The app just keeps loading and in the javascript console it shows the 401 error.

**Comment by superalex** [comment]
I don't know but if it happens again, could you check your cookies for taiga.io and remove them one by one instead of clearing all of them.

By the way, this happened in tree.taiga.io or in a custom instance?, what browser and version are you using?

**Comment by bameda** [comment]
Hi @zwarmapapa, have you been able to solve it?
