### ISSUE TITLE
Use token-based auth instead of cookies

### ISSUE THREAD

**Issue by Crawleyprint** [taigaio/taiga-back#295]
https://auth0.com/blog/2014/01/07/angularjs-authentication-with-cookies-vs-token/ has plenty of info about tokens, how to implement them and why they are better solution than cookies. 

However, I would like to hear if there are any reasons why cookies are used here - either security or anything else. Thanks

**Comment by superalex** [comment]
Hello @Crawleyprint ,

We are not using cookies, we are using tokens for authentication...

**Comment by Crawleyprint** [comment]
My bad, but this is from the cookie-notification link on taiga.io:

    We use cookies to record current session information, but do not use permanent cookies. 
    You are required to re-login to your Taiga account after a certain period of time has
    elapsed to protect you against others accidentally accessing your account contents.

I glanced at resources panel and I can see you're using both, which is not necessary IMO. I'd opt in for localStorage only. What do you think?

**Comment by Crawleyprint** [comment]
However, this might be more of a frontend issue and you can close this if that is the case, @superalex

**Comment by superalex** [comment]
Yes, the cookie notification is about the cookies we are using for google analytics, not for the site authentication ;)

Regards!,

**Comment by Crawleyprint** [comment]
Thanks for the explanation. However, you should re-check that last bit as the only two keys in cookie are `cookieConsent` and `i18next`, which I don't think has anything to do with Google Analytics.

And last, but not least - thanks for the awesome tool! Really a refreshment in terms of speed and performance

**Comment by superalex** [comment]
We are really happy that you are enjoying taiga!.

We are using the cookieConsent and i18next cookies but not related to authentication, just in the front app.
