### ISSUE TITLE
Regular user (w/ admin rights) cannot invite new members

### ISSUE THREAD

**Issue by jasperla** [taigaio/taiga-back#296]
An invited user who has admin rights in a project is unable to invite new members:

       smtplib.SMTPAuthenticationError: (535, b'5.7.8 Error: authentication failed: authentication failure')

Which is odd since the user itself was invited through this mailserver. Finding this actual error took a bit more effort than it should've since the red error bar with a message about sad oompa loompas is not helpful at all...

Whilst trying to debug this I noticed that setting `DEBUG = False` and an `ADMINS` tuple did not result in the traceback being mailed to the admins. Is this something that is known not to work?

**Comment by superalex** [comment]
Hello @jasperla,

It sounds like your email server isn't working properly, if it's a local one typically you should check /var/log/mail.log. 

ADMINS are notified via email too so if your email isn't going out neither you will be notified.

Regards,
