### ISSUE TITLE
UnicodeEncodeError 'ascii' codec can't encode character

### ISSUE THREAD

**Issue by lbanas** [taigaio/taiga-back#297]
Hello

when i try add new comment with chars (żąśćł)  to users story i have error:
````
UnicodeEncodeError: 'ascii' codec can't encode character '\u017c' in position 757: ordinal not in range(128)
````

Python 3.4.1
Django 1.7.6

**Comment by superalex** [comment]
Hello @lbanas,

I've just tested it in tree.taiga.io and it's working properly:

![test](https://cloud.githubusercontent.com/assets/1579633/6940196/a6164c32-d874-11e4-9e4b-cbc2da05bdd7.png)

If you are using your own taiga instance it means that it's using python2 and not python3.4, you should indicate it when creating the virtualenv.
