### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by yjarosz** [taigaio/taiga-back#298]
Hi,
When using the `Setup production environment` doc I have this error:
`UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 3925: ordinal not in range(128)`
when executing `python manage.py sample_data` (same error with `python3.4 manage.py sample_data`)

All previous command worked:
```bash
python manage.py migrate --noinput
python manage.py loaddata initial_user
python manage.py loaddata initial_project_templates
python manage.py loaddata initial_role
python manage.py collectstatic --noinput
```

**Comment by superalex** [comment]
Hello @yjarosz,

This error is becaouse you are using python2 and not python3.4. Taiga needs python3.4 for working properly.

Regards,

**Comment by yjarosz** [comment]
I tried with python3.4 and get the same error.

**Comment by superalex** [comment]
Those ascii errors are always related to python2, are you using a virtualenv with python3.4 on it and it's activated?.

If you are having problems with the installation you could use taiga-scripts for an automated one -> http://taigaio.github.io/taiga-doc/dist/setup-alternatives.html

Regards,

**Comment by yjarosz** [comment]
I know. This is why I don't understand...
I just followed the doc and yes, I'm under virtualenv. 
And yes it is activated otherwise manage.py doesn't work at all as I have installed django only in the venv. 
I will try again on a fresh VM. But I did it already twice: just copy paste from the doc. 

Yohan Jarosz

**Comment by superalex** [comment]
Just one more idea, could you check if your machine and user have utf-8 locale support?

**Comment by yjarosz** [comment]
Will check in a while. I keep you updated. Thank you. 

Yohan Jarosz

**Comment by yjarosz** [comment]
```bash
export LANG=en_US.UTF-8
export LC_TYPE=en_US.UTF-8
```
in the taiga user `.bashrc` fixed the issue. Thanks

**Comment by superalex** [comment]
Great! :+1:
