### ISSUE TITLE
AMQP URI parse issue

### ISSUE THREAD

**Issue by ss-abramchuk** [taigaio/taiga-back#304]
Hello! It seems that there is a problem with parsing EVENTS_PUSH_BACKEND_OPTIONS in taiga-back settings file. 

I tried to configure taiga-events using documentation. In local.py I have:
```
EVENTS_PUSH_BACKEND_OPTIONS = {"url": "amqp://taiga:***@localhost:5672/taiga"}
```
In taiga-events/config.json there is the same url, but it does not work. In rabbitmq log file i found this record:
```
=ERROR REPORT==== 11-Apr-2015::19:38:28 ===
closing AMQP connection <0.279.0> ([::1]:39160 -> [::1]:5672):
{handshake_error,opening,0,
                 {amqp_error,access_refused,
                             "access to vhost '/taiga' refused for user 'taiga'",
                             'connection.open'}}
```

I think the problem is in taiga-back/taiga/events/backends/rabbitmq.py. `parse_result.path` returns vhost value with leading slash, so taiga-back tries to connect to "/taiga", while taiga-events using "taiga", and "/taiga" also doesn't exist.

If i create "/taiga" vhost and use `amqp://taiga:***@localhost:5672//taiga` as url in config.json it works normally. Please check it.

**Comment by ss-abramchuk** [comment]
Ahh.. I was too hasty, it was already fixed. `git pull` was enough for me.

**Comment by superalex** [comment]
Great! :)
