### ISSUE TITLE
500 Internal Server Error After initial installation

### ISSUE THREAD

**Issue by s0lt4r** [taigaio/taiga-back#308]
After following the Production setup. I'm still unable to get any content on the nginx server,
Running ubuntu 14.04 on VMWare

**Comment by superalex** [comment]
Hello @s0lt4r, 

Did you check your ~/logs folder to see if there are any errors?. 

You could try to make a fully automated install in a clean environment using taiga-scripts -> https://github.com/taigaio/taiga-scripts

Regards,

**Comment by s0lt4r** [comment]
Yes I got a "Permission Denied" error. I'm assuming I sudo'ed when I shouldn't have. I'm attempting a fresh install now. I'll post the results.

**Comment by s0lt4r** [comment]
The fresh install with the script did the trick. Thanks.

I do have one other issue which I'm sure is my own fault. 
I'm unable to login to the page and attempting to create a user fails silently.

**Comment by s0lt4r** [comment]
Scratch that, a fresh install fixed it. I believe I interrupted the script while it was in progress and that caused the backend to fail.

**Comment by superalex** [comment]
Great! :+1:
