### ISSUE TITLE
[Q] Taiga not starting after enabling Importer

### ISSUE THREAD

**Issue by arpanr** [taigaio/taiga-back#32]
Hi 

After enabling importer

IMPORTERS["jira"] = {
    "active": True, # Enable or disable the importer
    "consumer_key": "proporjectstaiga",
    "cert": open('private_key.pem').read(),
    "pub_cert": open('public_key.pem').read(),
}

taiga not starting, private_key.pem and public_key.pem both are in the  ~/taiga-back/settings/ folder with taiga ownership

taiga@vmi621932:~/taiga-back$ sudo systemctl stop taiga
taiga@vmi621932:~/taiga-back$ sudo systemctl start taiga
taiga@vmi621932:~/taiga-back$ sudo systemctl status taiga
● taiga.service - taiga_back
     Loaded: loaded (/etc/systemd/system/taiga.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Thu 2021-07-08 10:34:02 CEST; 1s ago
    Process: 138392 ExecStart=/home/taiga/taiga-back/.venv/bin/gunicorn --workers 4 --timeout 60 --log-level=info --access-logfile - --bind 0.0.0.0:8001 taiga.wsgi (code=exited, status=3)
   Main PID: 138392 (code=exited, status=3)

**Comment by yamila-moreno** [comment]
Hi there!

Do you know that we have [Taiga Community](https://community.taiga.io/) for questions? Please, check there; maybe another user has already ask something similar. If not, create your own. There are people there willing to help, members of the Taiga team members and other users.

To simplify  the process, we will systematically close all issues that are general support questions and redirect people to Taiga Community.

Taiga Team
