### ISSUE TITLE
Url in email contains http instead of https when taiga is served over https

### ISSUE THREAD

**Issue by florisvanwoudenberg** [taigaio/taiga-back#332]
Just a minor issue: The invitation url contains the http url, this should be the https url when taiga is served over https

**Comment by superalex** [comment]
Hello @florisvanwoudenberg,

I'm checking the emails sent by tree.taiga.io in invitations and the https link is sent...If it's happening in your own instance you should check your SITES["front"]["scheme"] settings in local.py

Regards!,

**Comment by florisvanwoudenberg** [comment]
Ok, in that case there is an error in de documentation. I submitted an issue here: https://github.com/taigaio/taiga-doc/issues/71

**Comment by florisvanwoudenberg** [comment]
I can confirm adding SITES["front"]["scheme"] = "https" to local.py solved the problem.
