### ISSUE TITLE
Allow users to enter a ref number in the search

### ISSUE THREAD

**Issue by artlepool** [taigaio/taiga-back#336]
Hi guys - we'd find it really useful to be able to quickly find a Taiga item by entering the ref number in the Search box, eg. "344"  to find a user story, task or issue with this project reference number.

Think it is just a case of adding an extra search column in taiga-back/taiga/searches/services.py (line 26):

```
where_clause = ("to_tsvector(coalesce(userstories_userstory.subject) || ' ' || "
                    "coalesce(userstories_userstory.ref) || ' ' || "
                    "coalesce(userstories_userstory.description)) @@ plainto_tsquery(%s)")
```

Would need to do this for tasks and issues too. Maybe not wiki articles though.
The ref value may need to be shown in the search results to link what is searched for with what is returned.

What do you think? Would you accept a pull request for this?

**Comment by superalex** [comment]
Hello @artlepool,

Sure!, we would accept such a pull request :)

Actually the issues section allows searching by ref so it would be great if it works that way in other places of the app. 

About showing the ref value...I'm not sure is absolutely necessary, we are also indexing the full description and it's not shown in the listing...

**Comment by artlepool** [comment]
So the global Search uses taiga/searches/services.py to search user stories, tasks and issues. My approach would be to enhance this existing code to just allow searching by ref.
The search in the issues section looks like it uses the Issues API?

Do you mean that you want to change the global search to use the API instead of the existing code in searches/services.py?

Happy to take your guidance on this!

**Comment by superalex** [comment]
That's it: global Search uses taiga/searches/services.py to search user stories, tasks and issues. You would enhance this code to allow searching by ref but not using the API. The search in the issues section would keep working as it is (using the API).

I think your idea about updating taiga-back/taiga/searches/services.py is great, I was talking about the issues API just to show that it allows ref searching too :)

**Comment by artlepool** [comment]
Thanks @superalex 

Created pull request 337.

My point about showing the Ref in the search results is that maybe you have two user stories.
One user story could have a Ref of "2", and a subject of "Implement authentication"
Another user story could have a Ref of "5", and a subject of "Add 2 more stylesheets"

If the user searched for "2", then they would get both user stories back but wouldn't be able to tell which one is the user story that has the Ref of "2"?

**Comment by superalex** [comment]
Yes, it makes sense in that scenario, taiga-front is an independant repo so it could be done in another pull request :+1:

**Comment by artlepool** [comment]
Cool - just created pull request 480 on taiga-front :+1:

**Comment by superalex** [comment]
Merged!, thank you very much :)
