### ISSUE TITLE
No email send

### ISSUE THREAD

**Issue by sophy** [taigaio/taiga-back#339]
Hi Team,

After spend a few day to configure Taiga in my server every thing work correctly excerpt sending email not work.

Every thing task that require email nothing send to my email. Ex: I forget password and I request new password. After fill my email and  click button "Reset Password"  message "Check your inbox!" and click button "Accept".

Go to check my email no thing send to me.

How can test to make sure my server can send email via Taiga or Python? (I also host wordpress email normally work) 

Thank you in advance

**Comment by superalex** [comment]
Hello @sophy 

By default Taiga assumes you have a running email server on localhost port 25, if that's the point you could check your email logs (usually you can find them in /var/log/mail.log) to see what's happening. If you are using another email server you should change your email settings in local.py file from taiga-back.

Regards!,

**Comment by brycefisher** [comment]
@sophy I recently (as in ten minutes ago!) figured this out myself. I highly recommend using google for SMTP as described here: https://support.google.com/a/answer/176600?hl=en

I ended up having success with using these settings in my ~/taiga-back/settings/local.py file:

```python
EMAIL_USE_TLS=True
EMAIL_HOST="aspmx.l.google.com"
EMAIL_HOST_USER=""
EMAIL_HOST_PASSWORD=""
EMAIL_HOST_PORT=25
```

This is great for my use case, where I have a small number of users I want to email, all of whom use google apps for their email. If you want to email non-google email addresses, you'll have to try a different option listed in that link above.

Best of luck!

**Comment by superalex** [comment]
Thanks @brycefisher! ;)

**Comment by IvanJijon** [comment]
Hi everyone !

Just as a complement, after editing ~/taiga-back/settings/local.py file, you must restart taiga via :
`circusctl restart taiga`

**Comment by superalex** [comment]
Thanks @IvanJijon :+1:

**Comment by valiantjiang** [comment]
`
taiga@taiga:~$ vim ~/taiga-back/settings/local.py
change   the value of DEFAULT_FROM_EMAIL as your email address: taiga.push@xxx.com
DEFAULT_FROM_EMAIL = "taiga.push@xxx.com"
SERVER_EMAIL = DEFAULT_FROM_EMAIL

Uncomment  the following 6 lines:
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_USE_TLS = False
EMAIL_HOST = "192.168.192.60"
EMAIL_HOST_USER = "taiga.push"
EMAIL_HOST_PASSWORD = "taiga.push's password"
EMAIL_PORT = 25
`
and then restart:
`circusctl restart taiga`

**Comment by balay80** [comment]
I am using below configs but still i am not receiving mails
DEFAULT_FROM_EMAIL = "taiga@example.com"
SERVER_EMAIL = DEFAULT_FROM_EMAIL

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_USE_TLS = False
EMAIL_HOST = "localhost"
EMAIL_HOST_USER = "taiga"
EMAIL_HOST_PASSWORD = "taiga"
EMAIL_PORT = 25

getting below error

ERROR:2017-02-10 18:02:29,174: Internal Server Error: /api/v1/users/password_recovery
Traceback (most recent call last):
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/viewsets.py", line 106, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 446, in dispatch
    response = self.handle_exception(exc)
  File "/home/taiga/taiga-back/taiga/base/api/views.py", line 443, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/taiga/taiga-back/taiga/users/api.py", line 171, in password_recovery
    email.send()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/mail/message.py", line 292, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/mail/backends/smtp.py", line 100, in send_messages
    new_conn_created = self.open()
  File "/home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages/django/core/mail/backends/smtp.py", line 67, in open
    self.connection.login(self.username, self.password)
  File "/usr/lib/python3.5/smtplib.py", line 729, in login
    raise last_exception
  File "/usr/lib/python3.5/smtplib.py", line 720, in login
    initial_response_ok=initial_response_ok)
  File "/usr/lib/python3.5/smtplib.py", line 641, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'5.7.0 authentication failed'

please help me to resolve this

**Comment by bameda** [comment]
@balay80 the problem is related with your smtp server, are you sure that you are using a valid credentials (taiga/taiga)?

**Comment by ssuess** [comment]
I can't get email working no matter what I do. I have verified that postfix is working and I can telnet to port 25 on localhost and send an email without a problem. But Taiga refuses to send. Can anyone offer any advice? 

For example, should this line be enabled or not when using localhost?
`EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"`

I have also tried connecting to smtp.gmail.com with my credentials: FAIL
I have tried smtp gmail with 465 and 587: FAIL
I have tried smtp gmail with TLS true and false: FAIL
I have tried localhost with no user or pass : FAIL
I have tried localhost with my local taiga user and pass: FAIL
I have tried localhost with EMAIL backend uncommented: FAIL
I have tried localhost with EMAIL BACKEND commented out: FAIL

is there some step by step for getting smtp working on local postfix with taiga somewhere?

**Comment by ssuess** [comment]
Well, I hope the following is useful to someone else, I finally got it working with the following settings:

`EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_USE_TLS = True #VERY IMPORTANT APPARENTLY
EMAIL_HOST = "localhost"
MAIL_HOST_USER = "taiga@mywebdomain.com"
EMAIL_HOST_PASSWORD = "mytaigapassword"
EMAIL_PORT = 25`

**Comment by sistemmsn** [comment]
> @sophy Hace poco (¡como hace diez minutos!) lo descubrí yo mismo. Recomiendo usar Google para SMTP como se describe aquí: [https://support.google.com/a/answer/176600?hl=es](https://support.google.com/a/answer/176600?hl=en)
> 
> Terminé teniendo éxito usando estas configuraciones en mi archivo ~ / taiga-back / settings / local.py:
> 
> ```python
> EMAIL_USE_TLS = Verdadero 
> EMAIL_HOST = " aspmx.l.google.com "
>  EMAIL_HOST_USER = " "
>  EMAIL_HOST_PASSWORD = " "
>  EMAIL_HOST_PORT = 25
> ```
> 
> Esto es excelente para mi caso de uso, donde tengo un pequeño número de usuarios que quiero enviar por correo electrónico, todos los cuales usan aplicaciones de Google para su correo electrónico. Si desea enviar direcciones de correo electrónico que no sean de Google, tendrá que probar una opción diferente que aparece en el enlace anterior.
> 
> ¡La mejor de las suertes!



> Bueno, espero que lo siguiente sea útil para otra persona, finalmente lo conseguí trabajando con la siguiente configuración:
> 
> `EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"`
> `EMAIL_USE_TLS = True #VERY IMPORTANT APPARENTLY`
> `EMAIL_HOST = "localhost"`
> `MAIL_HOST_USER = "taiga@mywebdomain.com"`
> `EMAIL_HOST_PASSWORD = "mytaigapassword"`
> `EMAIL_PORT = 25`




En el default EMAIL lo tienes descomentado ???... Me puedes auxiliar por favor yo lo tengo de esta manera 

#DEFAULT_FROM_EMAIL = "taiga"
#SERVER_EMAIL = DEFAULT_FROM_EMAIL
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_USE_TLS = True
EMAIL_HOST = "localhost"
EMAIL_HOST_USER = "taiga@kreasys.ddns.net"
EMAIL_HOST_PASSWORD = "Pa$$w0rd"
EMAIL_PORT = 25

**Comment by sistemmsn** [comment]
> Bueno, espero que lo siguiente sea útil para otra persona, finalmente lo conseguí trabajando con la siguiente configuración:
> 
> `EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"`
> `EMAIL_USE_TLS = True #VERY IMPORTANT APPARENTLY`
> `EMAIL_HOST = "localhost"`
> `MAIL_HOST_USER = "taiga@mywebdomain.com"`
> `EMAIL_HOST_PASSWORD = "mytaigapassword"`
> `EMAIL_PORT = 25`

En el default EMAIL lo tienes descomentado ???... Me puedes auxiliar por favor yo lo tengo de esta manera 

#DEFAULT_FROM_EMAIL = "taiga"
#SERVER_EMAIL = DEFAULT_FROM_EMAIL
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_USE_TLS = True
EMAIL_HOST = "localhost"
EMAIL_HOST_USER = "taiga@kreasys.ddns.net"
EMAIL_HOST_PASSWORD = "Pa$$w0rd"
EMAIL_PORT = 25
