### ISSUE TITLE
Non-ASCII character '\xc3'

### ISSUE THREAD

**Issue by pandres95** [taigaio/taiga-back#343]
SyntaxError: Non-ASCII character '\xc3' in file /var/django/taiga-back/settings/__init__.py on line 2, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

Please, update files where non-ASCII characters are included (I have seen is because of some accents in the credits comments), otherwise tell me how to get it running.

**Comment by superalex** [comment]
Hello @pandres95 

Taiga requires python3.4 for working if you see those ASCII errors probably you are using python2 or your machine locale isn't supporting UTF-8. You could check a similar issue here -> https://github.com/taigaio/taiga-back/issues/298

Regards!

**Comment by pandres95** [comment]
Although I'm using python3.4, I'm getting issues like this
```bash
Running setup.py bdist_wheel for django-sr
  Complete output from command /root/.virtualenvs/taiga/bin/python3.4 -c "import setuptools;__file__='/tmp/pip-build-gjhimwo9/django-sr/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpr_cs47grpip-wheel-:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/root/.virtualenvs/taiga/lib/python3.4/encodings/ascii.py", line 26, in decode
      return codecs.ascii_decode(input, self.errors)[0]
  UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 268: ordinal not in range(128)
```
and this:
```bash
Running setup.py bdist_wheel for django-transactional-cleanup
  Complete output from command /root/.virtualenvs/taiga/bin/python3.4 -c "import setuptools;__file__='/tmp/pip-build-gjhimwo9/django-transactional-cleanup/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmpe8wwt_wppip-wheel-:
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/root/.virtualenvs/taiga/lib/python3.4/encodings/ascii.py", line 26, in decode
      return codecs.ascii_decode(input, self.errors)[0]
  UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 110: ordinal not in range(128)
```
while installing dependencies.

What can I do?

**Comment by superalex** [comment]
I see you are doing the installation under root user, it's not recommended at all, it should be better if you create a normal "taiga" user and reproduce all the steps under that user.

Also, did you check https://github.com/taigaio/taiga-back/issues/298 and the possible problems with locale settings?

Regards!

**Comment by pandres95** [comment]
I already checked them, everything worked at last. Thanks a lot!

**Comment by superalex** [comment]
Great! you are welcome! :+1:
