### ISSUE TITLE
Make the Kanban board flexible to insert new collumns

### ISSUE THREAD

**Issue by decko** [taigaio/taiga-back#345]
The kanban board nowadays are fixed in a kind of classic work style. There are only six categories, and you can't create new ones.

So, there's any possibility to make the kanban board on Taiga be flexible enough to create any kind of category like Trello do?

**Comment by paultag** [comment]
IIRC you can create a new one (or rename existing ones) in settings for the
project :)

On Tue, Jun 2, 2015 at 1:45 PM, André Filipe de Assunção e Brito <
notifications@github.com> wrote:

> The kanban board nowadays are fixed in a kind of classic work style. There
> are only six categories, and you can't create new ones.
>
> So, there's any possibility to make the kanban board on Taiga be flexible
> enough to create any kind of category like Trello do?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/taigaio/taiga-back/issues/345>.
>



-- 
:wq

**Comment by bameda** [comment]
Of course that you can customize the columns. You have to know the Kanban contains User Stories and a US has an status. Every US status is a columns

So you have to go to Admin > Attributes and play with US Statuses (create, edit o delete statuses) to customize the Kanban in your project.

![image](https://cloud.githubusercontent.com/assets/877218/7943019/40efa8a2-0962-11e5-965e-3227b7711147.png)
