### ISSUE TITLE
Role API Endpoint

### ISSUE THREAD

**Issue by gabeos** [taigaio/taiga-back#349]
Just wondering if you plan on exposing a Role API Endpoint. Currently it is a bit roundabout to access the role IDs to add appropriate memberships.

**Comment by superalex** [comment]
Hello @gabeos,

We hadn't that in mind...we are using the API from the Taiga web interface and we weren't missing it...

Regards! ;)

**Comment by gabeos** [comment]
Ah, okay, no worries. thanks for the heads up. I ran into it writing a slack bot to automatically add new slack users to our projects on taiga, and had trouble getting the right role id. 

Actually I think this was an issue with the python-taiga library not being full featured with respect to the API yet. I believe it only exposes the project list objects and not the full project detail objects.

**Comment by superalex** [comment]
Hmmmmmm, yes, it's possible that python-taiga library isn't fully featured with that part, @astagi is the one who is more involved in its development, may he could help you with that ;)

**Comment by gabeos** [comment]
ah, thanks for the mention. I worked around the issue by adding a dummy user to all the projects in the role we want new users to be added, so the script just takes the role id from the dummy user. this was actually just made possible via a PR last night that added some of the memberships API in, haha.

I'd try to make some PRs myself, but i'm trying to finish up grad school right now..

**Comment by superalex** [comment]
Great! And by the way: good luck finishing your grad school!  :+1:
