### ISSUE TITLE
[Q] Changing user's password programmatically

### ISSUE THREAD

**Issue by dralexk** [taigaio/taiga-back#35]
I am writing a script to change a user's password programmatically.

There is API request for that purpose, https://docs.taiga.io/api.html#users-change-password. However that request requires the user's token.

I see that there is a normal login request (https://docs.taiga.io/api.html#auth-normal-login), which returns "User authentication-detail" (https://docs.taiga.io/api.html#object-auth-user-detail), which includes "auth_token".

Is that the token I can use to change the password?

**Comment by bameda** [comment]
Yes, you are right, @dralexk, you need to be authenticated to change the user password. In 
```
-H "Authorization: Bearer ${AUTH_TOKEN}" \
```
`${AUTH_TOKEN}` is the auth token from the login response.
