### ISSUE TITLE
UX Request: Don't require sign-in after email verification

### ISSUE THREAD

**Issue by brycefisher** [taigaio/taiga-back#351]
I'm trying to get Taiga setup on my own server atm, and I really like it so far. However, getting email addresses working has been the only big pain point for me so far.

It feels like a big ask for users to re-authenticate after:

 1. Signing in to Taigaio
 2. Digging into their personal profile to find & change their email address
 3. Discovering that their email address did not actually update when they clicked "save"
 4. Checking their email and clicking the link (which includes a secure-looking nonce)

I'm sure there are plenty of apps that both do and do not require re-authentication after a user clicks an email verification link. My request (on behalf of myself and other users) is that you consider the user verified after simply clicking the link without signing in again. 

In terms of security, my gut feeling is that this is an acceptable tradeoff between usability and security. I don't think that requiring additional sign in is providing much additional security, but I leave that question in the hands of the AppSec wizards on your team ;-)

**Comment by superalex** [comment]
Hello @brycefisher ,

Actually users doesn't need to re-authenticate for updating their email after they click on the email verification link. If you were still seeing your old email after confirming the email link, could you please check if you were having a cache problem?

Regards!,

**Comment by brycefisher** [comment]
The reason this happened to me was that I tried to click the email verification link from my phone, whereas I was logged into Taiga in my laptop. When I tried clicking the link from my laptop with an active session, I wasn't required to re-authenticate.

So, this issue is less likely to occur than I originally supposed. However, I do think there may still be value for users that open the verification on a different browser or machine.

**Comment by superalex** [comment]
You are right, I wasn't considering that scenario.

I've done two pull requests so that you could use the link even if you are not logged in :)

I hope they are approved soon!

https://github.com/taigaio/taiga-back/pull/352
https://github.com/taigaio/taiga-front/pull/515

**Comment by brycefisher** [comment]
Whoa! You move fast @superalex Thanks so much!
