### ISSUE TITLE
Enumerated type Custom Fields

### ISSUE THREAD

**Issue by lordloh** [taigaio/taiga-back#356]
I would like to have custom fields where I can specify possible values. The user may then use a dropdown list or type with auto complete (if the list is too long) to select one of the preset values.

I think this may span both taiga-back and taiga-front.

**Comment by superalex** [comment]
Thanks @lordloh it's something that was already in our TODO list and yesterday we received a PR related to this feature -> https://github.com/taigaio/taiga-front/issues/451
