### ISSUE TITLE
Include commit comments and link to gitlab/github/etc. commit in status update comment

### ISSUE THREAD

**Issue by rbaverstock** [taigaio/taiga-back#360]
When I see status update resulting from a commit, it would be good to see the commit comments and a reference (change number or a link to gitlab/github/etc.) to the change that caused that update in the comments.

Both the actual commit comment and a link to the change would provide answers to the questions that come to my mind when I see the status update comment - what changed, what files were affected, and who changed it. Right now, none of that information is easily available for US, tasks or issues. Instead, I need to search through commit logs to find out what the change was.

This also makes it easier to hand off a task or issue to someone else, since all existing changes for the task/issue can be easily looked up.

**Comment by superalex** [comment]
Thanks @rbaverstock, this one has been in our enhancements todo list for a while, I hope we can implement it soon :+1:

**Comment by guardezi** [comment]
please

**Comment by Edvinas01** [comment]
It would be also really useful if you could include commit messages without updating the task status. 

For example a commit "TG-111 some comment", would appear in the activity log with link to that commit.

**Comment by daneov** [comment]
Both the original and @Edvinas01 s' suggestion would be awesome

**Comment by bameda** [comment]
Thanks for the feedback

**Comment by rashtao** [comment]
+1

**Comment by jvautier** [comment]
+1

**Comment by emelianovoe** [comment]
+1

**Comment by usersxm** [comment]
+1

**Comment by saiaman** [comment]
+1

**Comment by bameda** [comment]
it will be in the next release https://github.com/taigaio/taiga-back/pull/782
