### ISSUE TITLE
[Q] Can new member creation create a user?

### ISSUE THREAD

**Issue by dralexk** [taigaio/taiga-back#37]
I am looking for a way to create a new Taiga user through the API.

There is a an API request to create a new member, https://docs.taiga.io/api.html#memberships-create.

Does it create a new user if he/she was not a Taiga user?

**Comment by dralexk** [comment]
A continuation question:

Once I create the new member, can I set its initial password using the API?

**Comment by yamila-moreno** [comment]
Hi there!

Do you know that we have [Taiga Community](https://community.taiga.io/) for questions? Please, check there; maybe another user has already ask something similar. If not, create your own. There are people there willing to help, members of the Taiga team members and other users.

To simplify  the process, we will systematically close all issues that are general support questions and redirect people to Taiga Community.

Taiga Team
