### ISSUE TITLE
[Q] Setting up SMTP - SMTP AUTH extension not supported by server.

### ISSUE THREAD

**Issue by itmmdj** [taigaio/taiga-back#39]
I have tried multiple settings to try and get email working. I have other services on the same server running in docker and they are able to send out email.

I have tried these settings with no success

  EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
  DEFAULT_FROM_EMAIL: "taiga@intouch.org"
  EMAIL_HOST: "10.10.100.90"
  EMAIL_PORT: "25"
  ----
  EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
  DEFAULT_FROM_EMAIL: "taiga@intouch.org"
  EMAIL_HOST: 10.10.100.90
  EMAIL_PORT: 25
---
  EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
  DEFAULT_FROM_EMAIL: "taiga@intouch.org"
  EMAIL_HOST: "servername.domain.org"
  EMAIL_PORT: "25"
  ---
  EMAIL_BACKEND: "django.core.mail.backends.smtp.EmailBackend"
  DEFAULT_FROM_EMAIL: "taiga@intouch.org"
  EMAIL_USE_TLS: "False"
  EMAIL_USE_SSL: "False"
  EMAIL_HOST: "servername.domain.org"
  EMAIL_PORT: "25"
---
And many other possibilities

I this error in the logs:
  
  File "/taiga-back/taiga/projects/api.py", line 1070, in resend_invitation,
  File "/taiga-back/taiga/projects/services/invitations.py", line 23, in send_invitation,
    services.send_invitation(invitation=invitation),
    email.send(),
  File "/opt/venv/lib/python3.7/site-packages/django/core/mail/message.py", line 306, in send,
    return self.get_connection(fail_silently).send_messages([self]),
  File "/opt/venv/lib/python3.7/site-packages/django/core/mail/backends/smtp.py", line 103, in send_messages,
    new_conn_created = self.open(),
  File "/opt/venv/lib/python3.7/site-packages/django/core/mail/backends/smtp.py", line 70, in open,
    self.connection.login(self.username, self.password),
  File "/usr/local/lib/python3.7/smtplib.py", line 697, in login,
    "SMTP AUTH extension not supported by server."),
smtplib.SMTPNotSupportedError: SMTP AUTH extension not supported by server.

What am I missing?

Thanks for any help that you can give.

**Comment by yamila-moreno** [comment]
Hi there!

Do you know that we have [Taiga Community](https://community.taiga.io/) for questions? Please, check there; maybe another user has already ask something similar. If not, create your own. There are people there willing to help, members of the Taiga team members and other users.

To simplify  the process, we will systematically close all issues that are general support questions and redirect people to Taiga Community.

Taiga Team
