### ISSUE TITLE
Apache2 documentation

### ISSUE THREAD

**Issue by smarek** [taigaio/taiga-back#390]
Hello,

I know that officially Taiga doesn't support Apache2 web server, however, it should be at least documented that it's possible to run Taiga with Apache.

- This config will setup secure VirtualHost with redirect from HTTP to HTTPS
- Taiga-Front separated under taiga_ws/taiga_ws (user/group) permissions
- Correctly passing Taiga-Events through proxy_wstunnel module

Used versions of Taiga modules:
- Taiga-Back **1.8.0** (https://github.com/taigaio/taiga-back/commit/212e21449322d84bff8a38c5f699a6d25a2c185b)
- Taiga-Front-Dist **stable** (https://github.com/taigaio/taiga-front-dist/commit/58a926d553be1664e500ecd61c259fbbcf674a02)
- Taiga-Events **stable** (https://github.com/taigaio/taiga-events/commit/0e3acf99db2c302fb78fd62c4dd8c1c9391d2478)

Used versions of software (Debian Jessie)
- Apache/2.4.10
- PostgreSQL 9.4.3
- RabbitMQ 3.5.1
- Redis Server 2:3.0.2-2

```apache
<VirtualHost *:443>
        ServerAdmin {admin@hostname.tld}
        ServerName {hostname}

        SSLEngine On
        SSLCertificateChainFile         /etc/ssl/certs/{chain certificate file}
        SSLCACertificateFile           /etc/ssl/certs/{CA certificate file}
        SSLCertificateFile             /etc/ssl/certs/{hostname certificate file}
        SSLCertificateKeyFile           /etc/ssl/private/{hostname certificate key file}

        DocumentRoot /home/taiga/taiga-front-dist/dist/

        Alias /static /home/taiga/taiga-back/static
        Alias /media /home/taiga/taiga-back/media

        <Directory /home/taiga/taiga-front-dist/dist/>
                AllowOverride All
                Require all granted
        </Directory>

        # If you have taiga directory under separate user
        # use MPM ITK and run the VirtualHost under correct user/group permissions
        <IfModule mpm_itk_module>
                AssignUserId taiga_ws taiga_ws
        </IfModule>

        # For proxying you need modules "proxy", "proxy_http", "remoteip"
        ProxyPreserveHost On
        RemoteIPHeader X-Real-IP
        RemoteIPInternalProxy 127.0.0.0/8 ::1

        <Location /api>
                ProxyPass http://127.0.0.1:8001/api
                ProxyPassReverse http://127.0.0.1:8001/api

                <IfModule mod_expires.c>
                        ExpiresActive On
                        ExpiresDefault "now"
                </IfModule>
                <IfModule mod_headers.c>
                        Header set Cache-Control "no-cache, must-revalidate"    env=no-cache-headers
                        Header set Pragma        "no-cache"                     env=no-cache-headers
                        Header set Expires       "Sat, 1 Jan 2000 00:00:00 GMT" env=no-cache-headers
                </IfModule>
        </Location>

        # For "ws://" and "wss://" you need to have proxy_wstunnel module enabled
        <Location /events>
                ProxyPass ws://127.0.0.1:8888/events
        </Location>

        # Will redirect all requests non-static, non-media, non-api and non-events (websocket) to index.html
        # You need mod_rewrite to be enabled
        RewriteEngine On
        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteCond %{REQUEST_URI} !^/static/
        RewriteCond %{REQUEST_URI} !^/media/
        RewriteCond %{REQUEST_URI} !^/api/
        RewriteCond %{REQUEST_URI} !^/events/
        RewriteRule ^ index.html [L]

        ErrorLog '|/usr/bin/rotatelogs /home/taiga/logs/taiga.apache.error.log 86400'
        LogLevel warn
        CustomLog '|/usr/bin/rotatelogs /home/taiga/logs/taiga.apache.access.log 86400' combined
</VirtualHost>

<VirtualHost *:80>
        ServerName {hostname}

        # Important to keep the last slash so the redirect passes relative URL correctly
        RedirectPermanent / https://{hostname}/
</VirtualHost>
```

**Comment by superalex** [comment]
Thank you very much @smarek, could you please make a pull request with this info to https://github.com/taigaio/taiga-doc?

Regards,

**Comment by bxabi** [comment]
Hi. Thanks for this, it worked for me, but I have 2 problems, one of them I'm unable to solve.
1. I had to add a section for the /admin part, similarly as the /api is handled.
2. The main problem is, that it only works if I go from the domain name. If the URL has something after the domain name as https://xxx/projects/yyyy/, it does not work anymore.
Apache can not interpret the part after the first /, and the redirecting to the index.html doesn't seem to help.
It would be great to get this working, because this way no direct links are accessible, for example invitations doesn't work.

**Comment by bxabi** [comment]
I found the correct redirect setup!

https://github.com/sftd/taiga-doc/blob/master/setup-production-centos-apache.adoc

**Comment by superalex** [comment]
Great! :)

**Comment by smarek** [comment]
Yes, thanks, I've ommited those, because I've put `.htaccess` directly into `taiga-front-dist/dist` directory

For those interested, as I was upgrading today, I fixed the configuration with these lines:

```
        RewriteEngine on
        RewriteCond %{REQUEST_URI} !^/admin(.*)
        RewriteCond %{REQUEST_URI} !^/api(.*)
        RewriteCond %{REQUEST_URI} !^/events(.*)

        RewriteCond %{DOCUMENT_ROOT}/%{REQUEST_FILENAME} !-f
        RewriteRule . /index.html [L]
```

**Comment by smarek** [comment]
Also I've updated first comment, with working VirtualHost definition, where handling static/media/events is fixed, and /admin relative path works correctly

**Comment by superalex** [comment]
Thanks @smarek !

**Comment by siliconalchemy** [comment]
@smarek thanks!  did you get events actually working?  I've got everything running but i can't see any events and don't get anything in the event logs:
https://github.com/taigaio/taiga-events/issues/9

**Comment by smarek** [comment]
Yes, I did, when I got Circus manager and RabbitMQ daemon running, events are correctly passing back and forth.

**Comment by siliconalchemy** [comment]
Do you get a 500 if you go to /events in a browser?

**Comment by smarek** [comment]
No, the error is `400` which is in my opinion standard response when REST API is used wrong

**Comment by siliconalchemy** [comment]
@smarek Ok I didn't realise events were dependent on celery as well, I can see messages flowing through MQ now but I don't see anything in the frontend.  What should happen, should updates to tasks get immediately reflected in connected browsers?
