### ISSUE TITLE
no member commit hour info in sprint

### ISSUE THREAD

**Issue by LightZam** [taigaio/taiga-back#393]
it will be awesome to have info about total commit hour and task hour to evaluate sprint effort.

In Scrum, we usually estimate total hour from every team member commit hour each sprint.
by doing so, we are capable of knowing how many story we can afford by estimate task hour

**Comment by superalex** [comment]
Hello @LightZam,

You could use the custom fields (https://taiga.io/support/custom-fields/) for tracking all this info and then use the csv reports feature for extracting that information (https://taiga.io/support/csv-reports/). Here you can see a video example of a custom Taiga report: https://www.youtube.com/watch?v=tdt7nqXVf_E

Regards!,

**Comment by bameda** [comment]
...and more info about why we don't support time tracking (or believe in
it) https://taiga.io/support/why-is-there-no-time-tracking/

On Wed, Jul 15, 2015 at 1:06 PM, Alejandro <notifications@github.com> wrote:

> Hello @LightZam <https://github.com/LightZam>,
>
> You could use the custom fields (https://taiga.io/support/custom-fields/)
> for tracking all this info and then use the csv reports feature for
> extracting that information (https://taiga.io/support/csv-reports/). Here
> you can see a video example of a custom Taiga report:
> https://www.youtube.com/watch?v=tdt7nqXVf_E
>
> Regards!,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/taigaio/taiga-back/issues/393#issuecomment-121583565>.
>



-- 

---


   *David Barragán Merino*
* Engineer *
<david.barragan@kaleidos.net>
 david.barragan@kaleidos.net  | Tel: (+34) 913562995
www.kaleidos.net/FFF8E7

**Comment by LightZam** [comment]
Thanks for replying. maybe i can use workaround to do that.

I just wondering without member's available commit hours and task time estimate in planning, 

How team member cable to know how many story or task would be able to do in a sprint

**Comment by superalex** [comment]
Actually not, you only can see them in the detail page.

**Comment by LightZam** [comment]
Does this issue would be a feature in taiga ?
it will be awesome, if it provides both way in detail view and new/edit task popup view.
or does taiga team has other concern about this?

**Comment by superalex** [comment]
Hello @LightZam,

We don't plan adding time tracking on Taiga core, there are other tools much better than Taiga for tracking time, for example you could use https://www.toggl.com/, they have a plugin for Taiga.

Regards!,
