### ISSUE TITLE
Login with GitLab

### ISSUE THREAD

**Issue by ayr-ton** [taigaio/taiga-back#397]
Taiga today supports login with GitHub.
As there a lots of people using gitlab out there, a good enhancement would be add login with GitLab OAuth system.

**Comment by ayr-ton** [comment]
If you guys enjoy this idea :+1:, I will be happy to help with the code implementation.

**Comment by superalex** [comment]
It sounds good!, I'm talking with the development team about it to check if we have any extra considerations/comments/ideas about the implementation and will write again as soon as possible! :+1:

**Comment by ayr-ton** [comment]
@superalex Thank you x)

**Comment by superalex** [comment]
Hello @ayr-ton 

We all agree it's a really good idea, the development could be based in https://github.com/taigaio/taiga-contrib-github-auth so it's a pluggable app. Let us know if you need any thing! :+1:

**Comment by nsrosenqvist** [comment]
This would be a great feature. Thanks @ayr-ton!

**Comment by dionysiusmarquis** [comment]
+1

**Comment by LewisWatson** [comment]
+1

**Comment by johnmmcparland** [comment]
+1

**Comment by deviousgeek** [comment]
+1

**Comment by unixfox** [comment]
:+1:

**Comment by drf** [comment]
People interested in this and willing to get their hands dirty might take a look at this https://github.com/taigaio/taiga-contrib-github-auth/pull/5

currently working on our servers (with a small modification to the frontend URL)

**Comment by ayr-ton** [comment]
Working in progress. o/

**Comment by franck-roland** [comment]
+1

**Comment by llonchj** [comment]
+1 any update on this?

**Comment by superalex** [comment]
Sorry but still no news

**Comment by jayvdb** [comment]
This appears to be done.
I can log in with GitHub , and then log out and log back in using GitLab, and I am in the same account.
