### ISSUE TITLE
Make possible to create levels for kanban projects

### ISSUE THREAD

**Issue by ayr-ton** [taigaio/taiga-back#398]
In a Kanban project, is natural to create levels sometimes, like:

    --------------Backlog-------------  ---- On doing -----
    Non priorizated - Priorizated         Level1
                                       -------------
                                          sticker
                                          sticker
                                        ------------
                                          Level2
                                             ....
                                         -----------
                                          Blocks

It is a killing feature to kill some tools like:
http://info.leankit.com/product-demo

An easier way to organize the information would be save in the database like this:
Backlog
Backlog:Non priorizated
Backlog:Priorizated

When the frontend parse this, it will look like levels.

**Comment by superalex** [comment]
Thanks for your ideas @ayr-ton 

Isn't it the same than swimlanes?, I've added your comments to the existing user story we had on Taiga for this one -> https://tree.taiga.io/project/taiga/us/1723

Regards!,

**Comment by ayr-ton** [comment]
@superalex That's right! :dart: 

What do you think about the suggestion for organize the swimlanes?

**Comment by superalex** [comment]
I like the idea! :+1:

**Comment by ayr-ton** [comment]
The related user history at taiga kanban:
https://tree.taiga.io/project/taiga/us/1723
