### ISSUE TITLE
Due date on issues

### ISSUE THREAD

**Issue by florisvanwoudenberg** [taigaio/taiga-back#400]
When an issue is added, it would be nice to an option for a due-date. This due date can be entered manually or calculated based on the sla. https://github.com/taigaio/taiga-back/issues/401

**Comment by superalex** [comment]
Hello @florisvanwoudenberg,

I really like the idea, I'm posting here the Taiga link for this enhancement so it's easy to track its progress -> https://tree.taiga.io/project/taiga/issue/3069

We will review it and study if it can be included in Taiga core and when it could be done.

Regards!,

**Comment by 8levels** [comment]
Taiga definitely needs a date feature. +1

**Comment by thiagomiqueias** [comment]
:+1:

**Comment by kringon** [comment]
I am investigating combining this with a calendar view of all tasks. Is there any plan on working with this from the projects side?

**Comment by superalex** [comment]
There is a user who started working in this feature: https://tree.taiga.io/project/taiga/us/3909 but we have to check if there is any progress.

Regards!,

**Comment by kringon** [comment]
I can help him out with this. I'll take a look at it :)

**Comment by diacritica** [comment]
Hi @kringon we'd love to have a proposal for this. We actually have an ongoing paid gig on our beta Tribe platform :) Check it here: https://beta-tribe.taiga.io/gigs/56
Unfortunately, it looks lik we have radio silence from the selected gigster and we were going to cancel the gig and reopen it. Would you be interested?
Also, please take a look at this other gig, still open to select a candidate
https://beta-tribe.taiga.io/gigs/54

What do you think? wink wink! :)

**Comment by kringon** [comment]
Hi @diacritica  :)

I can aid anyone developing it, but i cannot do it alone at the moment. Too much on my plate.

The Tribe platform looks great! I really hope someone picks this up. If i get my company to endorse me working on this, then i will have a lot more time :)

**Comment by lordloh** [comment]
It would be great if a due date (and time :-) could trigger a script that would send an email. This would allow people to develop alternative scripts - such as to send messages via SMS or [pushbullet](https://docs.pushbullet.com/). It would be useful to trigger an event on adding a due date - something that can be used to add the event to watcher's calendars or modify existing events.

**Comment by mikaoelitiana** [comment]
This is a feature I am really looking forward to! I hope it will be available soon. If not, I am willing to help here.

**Comment by alexhermida** [comment]
Hello @florisvanwoudenberg this feature is ready and will be included in the next release 😃
