### ISSUE TITLE
Search for cyrillic in names

### ISSUE THREAD

**Issue by cheptil** [taigaio/taiga-back#402]
In countries where cyrillic is native - it's very not cool to translite such names as Kuz'ma Borschov
--
Rebzya podsobite, a to daje bezblagodatno kak-to

**Comment by superalex** [comment]
Hello @cheptil 

Sorry but I don't fully understand your comment, we use transifex for managing translations (https://www.transifex.com/organization/taiga-agile-llc) but Taigateam only translate Taiga to spanish and the rest of translations are managed by the community, if you are interested you could use that platform for translating Taiga strings you consider wrong.

Regards!,
