### ISSUE TITLE
User invitation uses wrong source for hostname

### ISSUE THREAD

**Issue by dpanth3r** [taigaio/taiga-back#406]
I've just setup a stable taiga, and upon testing the invitation feature I received a link pointing to “localhost:8001” instead of my domain.

The only place one can get these settings is in the gunicorn arguments, as I have HOST="http://domain" in settings/local.py :-)

**Comment by bameda** [comment]
Hi @dpanth3r 

in settings/local.py update or add this:

```
SITES["front"] = {
       "scheme": "http",                       # http or https
       "domain": "localhost:9001",       # Your domain
       "name": "front"
}
```
and restart taiga-back


Regards.

**Comment by dpanth3r** [comment]
I kinda feel stupid I did not find this before. Thanks, it works.

**Comment by bameda** [comment]
Great!!, you are welcome.
