### ISSUE TITLE
Implement message-id in email notifications so clients can properly thread notifications

### ISSUE THREAD

**Issue by brettp** [taigaio/taiga-back#409]
Currently, email clients like Thunderbird and Outlook cannot thread notifications about the same item. Adding message-id headers will allow this. Taiga can be noisy with notifications, and threaded messages will help make them more manageable and less daunting.

**Comment by superalex** [comment]
Hello @brettp,

Thank you very much for your suggestion, we had an existing enhancement in Taiga for this one, I've just added your comment there. I'm closing this one and leaving the Taiga one open: https://tree.taiga.io/project/taiga/issue/1719

Regards!,

**Comment by brettp** [comment]
Thanks for the info. For future reference, should I use GitHub or your Taiga instance to search for / report bugs?

**Comment by superalex** [comment]
You can use github for reporting and our Taiga instance for consulting the existing userstories, bugs, tasks...

**Comment by brettp** [comment]
@superalex: I took a shot at this one in PR #430. I wasn't sure which branch to submit the PR against, so I just went for stable. Let me know if I need to rebase to master, or there are any other changes.

**Comment by superalex** [comment]
Thanks @brettp it looks fantastic!

If you please could submit the PR to master it would be great :)

Regards!,

**Comment by brettp** [comment]
@superalex: Done. Should PRs go against master for both taiga-back and taiga-front?

**Comment by superalex** [comment]
Yes please, PR's should go against master for any taiga repo :+1: 

Regards!,
