### ISSUE TITLE
Automatic point sum of project, automatic sprint count

### ISSUE THREAD

**Issue by segler-alex** [taigaio/taiga-back#416]
Out main core project is a kind of endless scrum project. sprints just get added every week. so we always have to add new sprints manually and add the point sum of the new sprint to the project settings. I personally used "PivotalTracker" in my old company and we never had to input any number of sprint points for a project. it just got calculated automatically. it also did move tasks from the backlog automatically to the new sprint on every sprint start (just as much as points were available, old unfinished storys did not change, until we finally finished them)
i never knew on a new project how many story points it would need. this number should be calculated automatically after some time. after maybe 2 or 3 sprints you could caluclate a velocity that will give you point count for new sprints.
also most of out other projects don't have a fixed number of sprints. Please could you do more math magic ? ;)

**Comment by superalex** [comment]
Hello @segler-alex,

Our point of view is that usually if you use scrum with a backlog you should know how many points your project has and when it should be finished. If you don't have those requests the backlog graph (it shows if your speed is ok, if your backlog is growing...) is useless. We had an existing user story related to your idea (https://tree.taiga.io/project/taiga/issue/2015) I'm adding your comment there and closing this one.

Thank you very much for the feedback and for using Taiga!

Regards!,
