### ISSUE TITLE
Consider tracking task.neighbors

### ISSUE THREAD

**Issue by skaulana** [taigaio/taiga-back#423]
Often the tasks for a given story have a logical order of execution, but currently there doesn't seem to be a way to set/change their order as you can for a US in the backlog. Effectively you need to delete and recreate tasks to change their UI order.

On the backend, the User Story details JSON returns neighbors.next & neighbors.previous values. Would it make sense to track similar values for a Task parented under a US, to allow order to be captured and (eventually) updated?

**Comment by superalex** [comment]
Hello @skaulana 

We had an enhancement opened for this one, I've just added your comment there (https://tree.taiga.io/project/taiga/issue/2443) and closed this one.

Regards!,
