### ISSUE TITLE
Email problems on first project with default admin settings. 

### ISSUE THREAD

**Issue by Pablohn26** [taigaio/taiga-back#428]
I have installed my own taiga and I have had problems adding new members with default admin account. The confirmation email was not sent, as I reported at mailing list here: https://groups.google.com/d/msg/taigaio/57qwWQXug3o/nUcUE6c8MQAJ

Could somebody perform an installation following the setup production guide http://taigaio.github.io/taiga-doc/dist/setup-production.html  to confirm the bug? 

The fix was to change the email admin from admin@admin.com to an actual email account on email server.

**Comment by superalex** [comment]
Thanks @Pablohn26 

I think we should add the email update for the default admin to the taiga docs. Thanks for reporting!

**Comment by dottorblaster** [comment]
Upvoting this :+1:

**Comment by superalex** [comment]
The easiest way should be accessing directly to the django admin interface

**Comment by Pablohn26** [comment]
I made the change on taiga front end.

**Comment by hanu18** [comment]
can u please explain the solution what should be done to fix this issue, m still facing this.
Even not able to change admin mail from front end edit option.

**Comment by superalex** [comment]
Hello @hanu18 you can manually update the admin user email via de django interface, depending on the installation method you chose it should be on /admin url

Regards!

**Comment by hanu18** [comment]
@superalex Not helped me,
I have installed taiga when i am adding new user it's not sending any mail request, I have change local.py as per my requirement i.e. host IP.
can u plz explain how can i change admin e-mail using docker command or file name where i need to change it.

**Comment by bameda** [comment]
- access to http://<your url of taiga-back>/admin/
- type admin user and passowrd.
- access to Users list
- click over the user 'admin'
- change email
- save the form.

**Comment by hanu18** [comment]
Thanks a lot @bameda 
My issues may be silly, I am new bee to docker and taiga.
As suggested solution for Email problems on first project with default admin settings. #428
I have changed email admin from admin@admin.com to an actual email account on email server still while creating new user it is not sending any request mail to user mail id.

**Comment by bameda** [comment]
Sorry but I'm not very familiar with dockers. To get taiga-back sending emails you need to configure email server settings in```taiga-back/settings.local.py ```. You can use postfix, your email server, gmail to test it...

Here there are two examples https://github.com/taigaio/taiga-back/blob/master/settings/local.py.example#L55

**Comment by superalex** [comment]
As @bameda said Taiga will try to use a local email server listening on port 25. You could try to log in into your virtual machine and check the email logs in the file /var/log/mail.log to check if there is any problem with the email

**Comment by NikosAlexandris** [comment]
@bameda @superalex Changing the pre-set `admin@admin.com` to a custom one, causes taiga to stop working. The error logged in `logs/gunicorn.stderr.log` is:
```
Raven is not configured (logging is disabled). Please see the documentation for more information.
ERROR:2015-12-12 03:03:45,524: Internal Server Error: /api/v1/users/4
Traceback (most recent call last):
  File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/vagrant/taiga-back/taiga/base/api/viewsets.py", line 81, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/vagrant/taiga-back/taiga/base/api/views.py", line 420, in dispatch
    response = self.handle_exception(exc)
  File "/home/vagrant/taiga-back/taiga/base/api/views.py", line 417, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/vagrant/taiga-back/taiga/users/api.py", line 121, in partial_update
    email.send()
  File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/mail/message.py", line 303, in send
    return self.get_connection(fail_silently).send_messages([self])
  File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/mail/backends/smtp.py", line 107, in send_messages
    sent = self._send(message)
  File "/home/vagrant/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/mail/backends/smtp.py", line 123, in _send
    self.connection.sendmail(from_email, recipients, message.as_bytes(linesep='\r\n'))
  File "/usr/lib/python3.4/smtplib.py", line 792, in sendmail
    raise SMTPRecipientsRefused(senderrs)
smtplib.SMTPRecipientsRefused: {'admin@taiga.grid.unep.ch': (550, b'5.1.1 <admin@taiga.grid.unep.ch>: Recipient address rejected: User unknown in local recipient table')}
```

I need to re-start each time the whole virtual machine to make Taiga work again. It seems that `circusctl restart taiga` does not help. Any ideas?

**Comment by bameda** [comment]
This is postfix configuration problem, I find this in google:

http://serverfault.com/questions/179419/postfix-recipient-address-rejected-user-unknown-in-local-recipient-table
and more more results:

https://www.google.es/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=SMTPRecipientsRefused+550+Recipient+address+rejected+User+unknown+in+local+recipient+table

I hope this can help.
