### ISSUE TITLE
Import user story with role points results in an IntegrityError

### ISSUE THREAD

**Issue by mlq** [taigaio/taiga-back#429]
Importing a user story with defined role_points I will end up with an IntegrityError caused by a duplicate key value violates unique constraint:

> duplicate key value violates unique constraint "userstories_rolepoints_user_story_id_176812a03cfb458d_uniq"
> DETAIL:  Key (user_story_id, role_id)=(68, 7) already exists.

The exception is triggered by the `serialized.save()` call in the `store_role_point` function in `taiga-back/taiga/export_import/service.py:390` which is called in the `store_user_story` function.

I am not familiar with the code base but I think that this could be caused by saving the user story object first with default values for the role points. In `store_role_point` the relation is then saved instead of being updated.

**Comment by superalex** [comment]
Hello @mlq ,

Are you using the last stable release?, I've just tested to import/export a project with user stories with role points in tree.taiga.io and it's working ok...Could you please check if it's happening too in our instance? (I assume you are using your own one).

Regards!,

**Comment by mlq** [comment]
Hi @superalex,

Yes, I am using the stable branch (with the latest commits) on my machine and I am using the importer API to migrate the projects from my previous bug tracker (so I am not importing the whole project at once). I've tried to run my migration script on tree.taiga.io, but I receive an "Server Application error" if I try to import a user story on `http://api.taiga.io/api/v1/importer/<ID>/us`. Therefore I think the error happens there as well.

A user story that I try to import looks like the following:

```
{'assigned_to': 'mlq@pwmt.org',
 'attachments': [],
 'created_date': '2012-02-09T03:13:11',
 'description': u'Make the continious pages mode optional',
 'finish_date': None,
 'history': [{'comment': u'It is important, because you we have two types of PDF file\r\n1) good for continuous reading. You scroll it quickly, like newspaper\r\n2) good for page-by-page slow reading. Like presentation. You want to concentrate and think about each page separately.',
              'created_at': '2014-02-09T23:59:55',
              'type': 1,
              'user': ['github@mlq.me', 'Moritz Lipp']}],
 'milestone': None,
 'modified_date': '2014-02-09T23:59:55',
 'owner': 'github@mlq.me',
 'project': 61105,
 'role_points': [{'points': '3', 'role': 'Product Owner'}],
 'status': 'In progress',
 'subject': 'Optional continious pages',
 'tags': None,
 'watchers': ['mlq@pwmt.org']}
```

Best regards!

**Comment by superalex** [comment]
Hello @mlq,

I looks like a bug, let me get a glimpse of it and will tell you something as soon as possible. Sorry for the inconvenience!

**Comment by superalex** [comment]
Hello @mlq 

You were right, there was a bug in this part, it should be solved right now -> https://github.com/taigaio/taiga-back/commit/1350167cec0e3910fc66df6ffec090cb1d3f8f81

Regards!,
