### ISSUE TITLE
Adding a zoom option for Taskboard (or similar)

### ISSUE THREAD

**Issue by rephiscorth** [taigaio/taiga-back#431]
I'm working on a Macbook Air 11", and it is kind of complicate to visualize tasks on the Taskboard since, due to the fixed size of the title, I am able to visualize a maximum of 2 tasks (2 and a half to be precise) and 4 (out of 6) columns. Basically the header title and the table column headers covers about 40% - 45% of the screen. 

It would be awesome to have an option to zoom out or some way to visualize it in an easier way. Thanks in advance!

**Comment by superalex** [comment]
Hello @rephiscorth 

We have an existing user story highly prioritized in our kanban (https://tree.taiga.io/project/taiga/us/3166), I'm closing this one and adding your comment to the existing one.

Thank you very much for the feedback! ;)
