### ISSUE TITLE
Invitation link doesn't work

### ISSUE THREAD

**Issue by kGielo** [taigaio/taiga-back#436]
I've got email with invitation link (example.org/invitation/cb80cb5e-432d-11e5-9980-00224dae0fc3)
For every ivitation links server says 404.

**Comment by superalex** [comment]
Hello @kGielo,

Could you check if the domain used for that invitation links is the same used for accessing the platform or they are different?.

Regards!,

**Comment by kGielo** [comment]
Hi!

Yes, the domain is everywere example.org (for security reasons I don't post actual adres :/)

Greetings from Poland :)

**Comment by superalex** [comment]
Hello @kGielo 

The 404 error is the Taiga one or the default web server?, could you please attach a screenshot?, both links use the same protocol? (http or https). You could also check the javascript console errors to see if something is happening.

Regards!,

**Comment by kGielo** [comment]
![Screenshot](http://kgielo.pl/s/000022e.png)

**Comment by superalex** [comment]
It seems your web server isn't working correctly (it's not the page taiga uses for 404, it seems the request just goes to your web server but doesn't hit taiga front), you should check the configuration, for example if you go directly to /login there is a 404 error page too.

**Comment by kGielo** [comment]
Hmm.. I'll try to figure it out. Thank you.

**Comment by superalex** [comment]
Did you configure nginx as recommended in the official doc?

**Comment by kGielo** [comment]
No.. I must use Apache instead.

**Comment by superalex** [comment]
One of our users configured it properly in apache -> https://github.com/taigaio/taiga-back/issues/390

I hope it helps

Regards,

**Comment by kGielo** [comment]
Yes, I've found this and I've configurated this, so I write this issue.

**Comment by superalex** [comment]
Sorry but our instance is installed using nginx so we can't help you with this one.

**Comment by kGielo** [comment]
I know, thank you.
