### ISSUE TITLE
Hipchat / slack integrations bug

### ISSUE THREAD

**Issue by kGielo** [taigaio/taiga-back#437]
Can't add slack / hipchat integrations beacouse, nothing happends on click "Save".

Only in console there is:
`Uncaught TypeError: $loading is not a function` on line 103 in slack.js / hipchat.js

**Comment by superalex** [comment]
Hello @kGielo ,

I assume you are using your own taiga instance and taiga-front-dist for the front app, if I'm right, could you please check if your local copy is updated (git pull from the front folder) and try again?

Regards!,

**Comment by kGielo** [comment]
Hi!
Thank you for advice, and sorry for my bad language, I'm from Poland.
So, I pull taiga-front-dist repo again and plugins now works! Thank you, but performace of speed of site has dropdown.

**Comment by kGielo** [comment]
So.. I test the funciontality of these plugins, and still doesn't work. 
Taiga saids that everything are ok, but in Slack, or Hipchat I don't see anything.

**Comment by superalex** [comment]
If you save the changes and you click on "TEST" button, isn't anything shown in your slack channel?

**Comment by kGielo** [comment]
Yes, now its everything working, thank you very much.

**Comment by superalex** [comment]
Great! :)
