### ISSUE TITLE
REST API "400 Bad Request" / custom us_status with order=0

### ISSUE THREAD

**Issue by maerten** [taigaio/taiga-back#443]
I have updated my project through the webapp with an additional status (called "Backlog") and put it at the top of the list. Because of this the status has gotten order=0, and it appears that updating existing tasks with status:0 gives a 400 Bad Request error.

**Comment by bameda** [comment]
task.status must be the status.id and not status.order. The status with id 0 does not exists. 

PS: please, for API bug/questions try to give us the request.

**Comment by maerten** [comment]
Makes sense, sorry about that. Will attach request data from now on.
