### ISSUE TITLE
Front-end can't connect to the Backend

### ISSUE THREAD

**Issue by mcanovas** [taigaio/taiga-back#446]
Hello,

I've installed Taiga with the "Production Guide" and I can't connect to the backend side from the frontend.

I've configured the frontend in the port 8081 and the backend is set to the port 8000 at the same machine. Frontend side seams work well, but can't connect to the backend. I've tried to execute a "curl" command to the API and only seams work within the host machine (i've tried to launch some queries from the browser in other machine and it didn't answer).

I've used the verification commands 

workon taiga
python manage.py runserver

and the server seams to start, but the api is not answering (only with the curl command from inside the VPS).

Could you give a hint what is happening?
Do you need some specific information about my configuration?

Thanks

**Comment by mcanovas** [comment]
Ok, I've solved the problem. it was a configuration both backend and frontend related to the port, because I have Taiga in the port 8081. Furthermore, I had to configure the nginx backend part taking into account that the api is 'api/v1/' instead of 'api/v1'. The last '/' matters.

Thank you for everything.

**Comment by bameda** [comment]
Thanks to you for using Taiga.

**Comment by adebayo-dealdey** [comment]
How did you get the problem solved, please
