### ISSUE TITLE
Attach a file to an issue

### ISSUE THREAD

**Issue by heyalbert** [taigaio/taiga-back#448]
I would like to have the possibility to attach files, most of it screenshots of this issue, when I'm creating an issue in taiga.io.

![attachfile](https://cloud.githubusercontent.com/assets/7317458/9655689/49136c7a-5233-11e5-813a-8c0f5c6fa79e.png)

**Comment by superalex** [comment]
Hello @heyalbert 

@juanfran is just now working on this one -> https://tree.taiga.io/project/taiga/issue/1096 (I'm closing the github issue and leaving the taiga one open)

Regards!,

**Comment by heyalbert** [comment]
@juanfran Thank you for your response. But what is about the custom fields in the creation step? And why no full wysiwyg editor in the description textarea? A full wysiwyg editor is waiting for me in the comments section. Thank you in advance for any answer.
