### ISSUE TITLE
User story - Progress tracking

### ISSUE THREAD

**Issue by marmanan** [taigaio/taiga-back#455]
It would be useful to have the option to register points burnt to track progress of a story

**Comment by superalex** [comment]
Hello @marmanan,

Taiga doesn't support "tasks tracking" by default but you can add custom fields to your tasks if you need them. Related to this point we have an article here: https://taiga.io/support/why-is-there-no-time-tracking/ describing why Taiga doesn't support time tracking and the alternatives for it.

Regards,

**Comment by dromer** [comment]
I'd argue that 'task tracking' is not the same as 'time tracking'.
It would be very nice to be able to have a simple bar to track the progress on a project (ie. in Trello 'stories' have a checklist with tasks and a progress-bar that fills up as tasks are marked done).

**Comment by Xaviju** [comment]
@dromer we have plans for it soon for US in upcoming story cards redesign https://tree.taiga.io/project/taiga/us/2928

Full Project progress will also be visible in backlog and probably in kanban.
