### ISSUE TITLE
User story - Story grouping

### ISSUE THREAD

**Issue by marmanan** [taigaio/taiga-back#457]
It would be useful to add the option to group stories under a common grouping story as Epics.

Current option for grouping is tagging, but it becomes too confusing when too many tags are used.

**Comment by superalex** [comment]
Thanks @marmanan 

We had two existing userstories about this feature (epics and us grouping) -> https://tree.taiga.io/project/taiga/us/1563 and https://tree.taiga.io/project/taiga/us/58. I've just added your comments there.

Regards!,
