### ISSUE TITLE
[Q] Any instructions/tips on setting up Taiga with Docker/Traefik

### ISSUE THREAD

**Issue by crabdancing** [taigaio/taiga-back#46]
I am trying to set up Docker with Taiga, but I'm struggling a lot with bad gateway errors to `wss://[my domain]/events`. Are there instructions for how to properly reconfigure settings to fix this issue for Traefik or some other similar reverse proxy?

**Comment by yamila-moreno** [comment]
Hi there!

Do you know that we have [Taiga Community](https://community.taiga.io/) for questions? Please, check there; maybe another user has already ask something similar. If not, create your own. There are people there willing to help, members of the Taiga team members and other users.

To simplify  the process, we will systematically close all issues that are general support questions and redirect people to Taiga Community.

Taiga Team
