### ISSUE TITLE
drop authorization throw hipchat

### ISSUE THREAD

**Issue by r1se** [taigaio/taiga-back#465]
Hello.
When i open story throw link from hipchat, story don't have information about create user.
And any action drop to /notfound.
Until relogin i don't see my project.

Any suggestion about how can i fix it?

**Comment by superalex** [comment]
Hello @r1se 

Could you paste here an url example of the link generated in hipchat and a normal one you would use for accessing taiga?

**Comment by r1se** [comment]
@superalex 

not work : from hipchat http://192.168.0.107/project/admin-sproject/us/7
work fine : from backlog http://192.168.0.107/project/admin-sproject/us/7?no-milestone=1

From hipchat created by external user
From backlog create by gooduser

**Comment by superalex** [comment]
Sorry but I don't understand what you mean when you say "From hipchat created by external user", could you please attach screenshots?

**Comment by r1se** [comment]
![2015-09-17_14-05-57](https://cloud.githubusercontent.com/assets/5337780/9931571/7624a2b6-5d45-11e5-8760-44141224d516.png)

First picture with right user, second from hipchat.
Also from hipchat very long loading.
and drop to /notfound, when i try open backlog.

**Comment by bameda** [comment]
External user is because the hipchat user has no account in taiga or is imposible to taiga knows who is the author of this issue. An example in our platform https://tree.taiga.io/project/taiga/issue/3264

Could you paste the output of the js console of your browser?

**Comment by r1se** [comment]
@bameda 

libs.js:14 Initialize navigation urls
libs.js:14 Initialize api urls
libs.js:14 Using the default logging exception handler.
libs.js:14 Initialize resources
libs.js:14 Initialize application
libs.js:14 Analytics: no acount id provided. Disabling.
7:1 Failed to decode downloaded font: http://192.168.0.107/fonts/OpenSans-Light.woff
7:1 OTS parsing error: invalid version tag

**Comment by r1se** [comment]
Also, i have 2 problem:
1.When simple user(not admin), try open Backlog, taiga return him /not-found
2. When simple user(not admin), open "Team" he see empty list, without another user.

**Comment by r1se** [comment]
@bameda but i'm logged on taiga. If i open new tab on browser, paste link on story i cant see my logged profile, but not information about user owner?

**Comment by bameda** [comment]
So sorry but the error you're describing are difficult to reproduce. 

What browser are you using?
Have you tried with other browsers?
Have you changed the role permissions in your project?

And I don't understand how Hipchat can send request to your instance if you are using a private ip address.

I think that your taiga-back server can't communicate properly with your taiga-front client. Maybe it's a configuration problem.

**Comment by r1se** [comment]
Browser: chrome latest stable version

When i try get Team list from simple user i got error:
TypeError: member.get is not a function
    at project.controller.coffee:20
    at libs.js?v=1441879683125:35
    at List.__iterate (libs.js?v=1441879683125:37)
    at IndexedIterable.filterSequence.__iterateUncached (libs.js?v=1441879683125:35)
    at seqIterate (libs.js?v=1441879683125:35)
    at IndexedIterable.IndexedSeq.__iterate (libs.js?v=1441879683125:36)
    at IndexedIterable.mixin.forEach (libs.js?v=1441879683125:37)
    at libs.js?v=1441879683125:36
    at List.src_Map__Map.withMutations (libs.js?v=1441879683125:37)
    at new List (libs.js?v=1441879683125:36)
    at reify (libs.js?v=1441879683125:36)
    at List.mixin.filter (libs.js?v=1441879683125:38)
    at project.controller.coffee:20
    at processQueue (libs.js?v=1441879683125:14)
    at libs.js?v=1441879683125:14
    at Scope.$eval (libs.js?v=1441879683125:15)(anonymous function) @ libs.js?v=1441879683125:14(anonymous function) @ raven-logger.coffee:39processQueue @ libs.js?v=1441879683125:14(anonymous function) @ libs.js?v=1441879683125:14Scope.$eval @ libs.js?v=1441879683125:15Scope.$digest @ libs.js?v=1441879683125:15Scope.$apply @ libs.js?v=1441879683125:15(anonymous function) @ libs.js?v=1441879683125:14completeOutstandingRequest @ libs.js?v=1441879683125:12(anonymous function) @ libs.js?v=1441879683125:12

When i try open backlog from simple user i got:
GET http://192.168.0.107:8000/api/v1/userstories/filters_data [HTTP/1.1 404 NOT FOUND 12мс]

**Comment by r1se** [comment]
@bameda hipchat send me message with href to story, which have my external(private) ip.
inside my LAN i can open this link.

**Comment by bameda** [comment]
We are lost with your strange errors. I recommend to install taiga again. Maybe try first to use our vagrant instance or taiga-script and then install and configure a real production env from the first one.

Use always the stable branches to get the latest stable versions.

We are very sorry.

**Comment by r1se** [comment]
@bameda i'm used stable branch, and got pull to back and front.
This error, floating, not in all computer.

**Comment by superalex** [comment]
Sorry @r1se but we still don't understand what's the problem exactly, what do you mean with "floating"?

As @bameda suggests probably the best idea would be that you install a working copy of Taiga, the best approach should be using taiga-script so that you have a fully working instance (http://taigaio.github.io/taiga-doc/dist/setup-alternatives.html#setup-taiga-scripts)

It seems you have different problems not necessary related to hipchat. For example "http://192.168.0.107:8000/api/v1/userstories/filters_data" sounds like the API URL you configured and it should never fail with a 404 error. It sounds like you have errors in your front/back/web-server configuration so starting with a working instance should be the best option.

Regards!,

**Comment by Lord-Evil** [comment]
Yeah, right, "filters_data" not in stable backend version! At all!
