### ISSUE TITLE
admin account doesnt work

### ISSUE THREAD

**Issue by MAGICCC** [taigaio/taiga-back#471]
Installed taiga on Ubuntu 14.04 LTS via [this](http://taigaio.github.io/taiga-doc/dist/setup-production.html) tutorial.
After starting nginx I wanted to login with ```admin``` ```123123``` but it doesnt work

**Comment by superalex** [comment]
Hello @MAGICCC,

According to our doc the admin user is created with the command "python manage.py sample_data" in the section "Populate the database with initial basic data", did you run this command?, could you execute it again to check if it works?

Regards!,

**Comment by MAGICCC** [comment]
Regarding the doc the admin user is creating before this command:

Populate the database with initial basic data

    python manage.py migrate --noinput
    python manage.py loaddata initial_user
    python manage.py loaddata initial_project_templates
    python manage.py loaddata initial_role
    python manage.py compilemessages
    python manage.py collectstatic --noinput

This creates a new user ```admin``` with password ```123123```.

If you want some example data, you can execute the following command, which populates the database with sample projects and random data; useful for demos:

    python manage.py sample_data


Anyway, I gonna test it again

**Comment by superalex** [comment]
Sorry, you are right, the admin command should be created with the "python manage.py loaddata initial_user".

To execute those commands you must enable your virtualenv before with something like "workon taiga".

Regards!,

**Comment by MAGICCC** [comment]
It did something, but still can't login due wrong username or password

>(taiga)taiga@maguc:~/taiga-back$ python manage.py loaddata initial_user
>Trying import local.py settings...
>Installed 1 object(s) from 1 fixture(s)

**Comment by superalex** [comment]
I think you could check two different things:
 - Your javascript console to see if the auth request isn't working problems
 - The logs folder from your taiga user in the filesystem

Another option could be doing a fully automated install using taiga-scripts http://taigaio.github.io/taiga-doc/dist/setup-alternatives.html this way you could have a working instance and later customize anything you want

**Comment by MAGICCC** [comment]
```
XMLHttpRequest cannot load http://taiga.kthx.at/api/v1/auth. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://taiga.kthx.at:8888' is therefore not allowed access. The response had HTTP status code 405.
```

Seems the backend isn't running. I will reinstall with that script

**Comment by superalex** [comment]
It seems more related to serving the web app in http://taiga.kthx.at:8888 and accessing the API in a different domain (for most browsers a different port will be a different domain and it's considered as a security problem). If you serve your web an in taiga.kthx.at insted of taiga.kthx.at:8888 it should work.

Regards!
