### ISSUE TITLE
As a SCRUM Master I would like a query language to allow better search results

### ISSUE THREAD

**Issue by johnmmcparland** [taigaio/taiga-back#473]
I would like to search on a range of fields which stories, ticket and issues in Taiga have.  For example, assignee, status, type, blocked, iocaine dosed taken.   

However I currently cannot do this - it's simply a text search on the description and/or title.

I would like something much more like JIRA Query Language, both in terms of the ability to search (on individual fields with SQL-like operators) but also in the display of those results (tabular, with customizable columns and sorting).

**Comment by superalex** [comment]
Thank you very much for the feedback @johnmmcparland . We had an existing enhancement request for this one (https://tree.taiga.io/project/taiga/issue/1490), I've just added your comments there. I'm closing this github issue but leaving the Taiga one open.

Regards!,
