### ISSUE TITLE
Set any field via git

### ISSUE THREAD

**Issue by meredrica** [taigaio/taiga-back#477]
Right now, only the status can be changed. It would be awesome to set any field via the git comment (including custom fields). Possible syntax would be ``TG-123 status:'done' my_field: '12:20' comment: 'oh this is a comment'`` or alternatively a line per field (with the issue#)

The only thing that keeps me back from using taiga is that i can't log time via git. it's one of the best features that redmine has. This could be solved in the proposed change
I understand that some people think this is against agile development, but I run a 1 man company and mostly charge time&material, so this is essential. So far I could not find a Kanban board that has git+timetracking and no ugly ui.

**Comment by bameda** [comment]
Thanks for your feedback @meredrica, we've got it at https://tree.taiga.io/project/taiga/issue/3308
