### ISSUE TITLE
Empty old sprints are not moved to the closed sprints section

### ISSUE THREAD

**Issue by SyRenity** [taigaio/taiga-back#480]
After I reopened a closed sprint task, the sprint is now hanging above my current one, together with all the following ones, and no sprints are getting moved any more to the "closed sprints" once they closed:

http://take.ms/MfqnN

Any ideas if this was fixed in latest versions?

**Comment by superalex** [comment]
Hello @SyRenity,

That's right, you have a sprint with zero points and none of them are closed so they are not considered as closed. You should have at least something "closed" inside them so they appear in the "closed sprints" section.

Regards,

**Comment by SyRenity** [comment]
So just add any story to them and close them afterwards?

**Comment by superalex** [comment]
Yes, a closed sprint should contain closed user stories ;)
