### ISSUE TITLE
TemplateDoesNotExist at /api/v1/

### ISSUE THREAD

**Issue by astagi** [taigaio/taiga-back#487]
Request Method:	GET
Request URL:	http://localhost:8000/api/v1/
Django Version:	1.8.5
Exception Type:	TemplateDoesNotExist
Exception Value:	
api/api.html

**Comment by superalex** [comment]
I think @bameda knows something about this one...

**Comment by astagi** [comment]
Fixed @superalex I'll send a PR ;)

**Comment by superalex** [comment]
Thanks! ;)
