### ISSUE TITLE
OSError at /api/v1/auth/register

### ISSUE THREAD

**Issue by FlorianBruniaux** [taigaio/taiga-back#499]
Hello, I can't register a new user (neither on front with form nor back with api)

I've a **500** err.

Here are some screenshots.
Do you have any idea for the origine of the problem ?

Thanks

<img width="1439" alt="capture d ecran 2015-10-28 a 09 40 05" src="https://cloud.githubusercontent.com/assets/3902606/10783449/3d16c002-7d58-11e5-87aa-26841a05229f.png">

<img width="568" alt="capture d ecran 2015-10-28 a 09 40 55" src="https://cloud.githubusercontent.com/assets/3902606/10783455/43f7594a-7d58-11e5-9a25-320954db45ba.png">

<img width="1437" alt="capture d ecran 2015-10-28 a 09 46 19" src="https://cloud.githubusercontent.com/assets/3902606/10783538/c8dc2384-7d58-11e5-8eaf-057083ad29de.png">

<img width="1242" alt="capture d ecran 2015-10-28 a 09 41 04" src="https://cloud.githubusercontent.com/assets/3902606/10783457/48057774-7d58-11e5-82bc-3d7f26264cdd.png">

**Comment by superalex** [comment]
Is it possible that your hard disk is full?

**Comment by FlorianBruniaux** [comment]
I think no.

![capture d ecran 2015-10-28 a 09 52 03](https://cloud.githubusercontent.com/assets/3902606/10783643/940f01a2-7d59-11e5-8272-f416adc34f76.png)
![capture d ecran 2015-10-28 a 09 51 13](https://cloud.githubusercontent.com/assets/3902606/10783632/8793d4ca-7d59-11e5-83e0-0c6eeb43c65c.png)

**Comment by jespino** [comment]
Looks like is a IO error on django console mail backend. This means you can't write to the stdout (this can means that your circus is writting the output of the server to a log file without permissions, or in a not existing directory).

**Comment by FlorianBruniaux** [comment]
It's strange

I managed to create a new user directly in DJANGO
http://myIP/admin/

After that, we could login in Taiga (front / back) with this user.

**Comment by FlorianBruniaux** [comment]
The problem was due to a wrong config.

Taiga user could'nt access to gunicorn logs so there was an exception;
We granted access to this user on logs and now it works...

Thanks for your advices and for this awesome app !

**Comment by superalex** [comment]
Great! :)
