### ISSUE TITLE
Email notification with EXCHANGE

### ISSUE THREAD

**Issue by FlorianBruniaux** [taigaio/taiga-back#502]
Hello,

I have a problem with notification emails. I do not receive anything.

I work with an exchange server

My taiga-back/settings/local.py
```python
# Uncomment and populate with proper connection parameters
# for enable email sending. EMAIL_HOST_USER should end by @domain.tld
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_USE_TLS = False
EMAIL_HOST = "mail.mydomain.fr" 
EMAIL_HOST_USER = "taiga@mydomain.fr"
EMAIL_HOST_PASSWORD = "myPassword"
EMAIL_PORT = 25
```
Should I set EMAIL_HOST_USER with **DOMAIN\userName** ?

Thanks

**Comment by FlorianBruniaux** [comment]
The mail event is logged in **logs/gunicorn.stdout.log**

But exchange server did not receive anything.

Any idea ?

**Comment by bameda** [comment]
Sorry @FlorianBruniaux but we only use open source software.

Are you sure that the username is an email? I think  EMAIL_HOST_USER must be the exchange user (without domain according to http://stackoverflow.com/questions/24684317/django-send-mail-and-exchange-server)

**Comment by FlorianBruniaux** [comment]
We've found a solution.

```python
DEFAULT_FROM_EMAIL = "taiga@mydomain.fr" 
SERVER_EMAIL = "taiga@mydomain.fr" 

# Uncomment and populate with proper connection parameters 
# for enable email sending. EMAIL_HOST_USER should end by @domain.tld 
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend" 
#EMAIL_USE_TLS = False 
EMAIL_HOST = "192.168.1.12" #XCS SERVER IP
#EMAIL_HOST_USER = "taiga@mydomain.fr" 
#EMAIL_HOST_PASSWORD = "myPassword" 
EMAIL_PORT = 25 
```

We send the notification with django to another server (xcs via exchange) with the good rights level

**Comment by superalex** [comment]
Great! :+1:
