### ISSUE TITLE
AttributeError at /admin/projects/project/add/ 'OneToOneRel' object has no attribute 'parent_model'

### ISSUE THREAD

**Issue by DaSpawn** [taigaio/taiga-back#512]
I just setup Taiga on a fresh Ubuntu 14.04 install, followed install docs, and all seamed to be working till trying to admin  projects from /admin/.  Anything related to projects (add/edit) returns same failures except for list of projects

    AttributeError at /admin/projects/project/add/

    'OneToOneRel' object has no attribute 'parent_model'

    Request Method: GET
    Request URL:    http://oberon-taiga/admin/projects/project/add/
    Django Version: 1.8.5
    Exception Type: AttributeError
    Exception Value:  'OneToOneRel' object has no attribute 'parent_model'
    Exception Location: /home/taiga/taiga-back/taiga/projects/admin.py in formfield_for_foreignkey, line 55
    Python Executable:  /home/taiga/.virtualenvs/taiga/bin/python3.4
    Python Version: 3.4.3
    Python Path:    
        ['/home/taiga/taiga-back',
        '/home/taiga/taiga-back',
        '/home/taiga/.virtualenvs/taiga/bin',
        '/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages',
        '/home/taiga/.virtualenvs/taiga/lib/python3.4',
        '/home/taiga/.virtualenvs/taiga/lib/python3.4/plat-x86_64-linux-gnu',
        '/home/taiga/.virtualenvs/taiga/lib/python3.4/lib-dynload',
        '/usr/lib/python3.4',
        '/usr/lib/python3.4/plat-x86_64-linux-gnu',
        '/home/taiga/taiga-back']
    Server time:    Wed, 4 Nov 2015 13:50:57 +0000

**Comment by superalex** [comment]
Thanks for reporting @DaSpawn we will review it and try to solve it as soon as possible.

Regards!,

**Comment by superalex** [comment]
Fixed here -> https://github.com/taigaio/taiga-back/pull/524
