### ISSUE TITLE
Export project then import destroyed the attachments

### ISSUE THREAD

**Issue by fish-ball** [taigaio/taiga-back#516]
After export an import, all the attachment sizes was trimmed to 8KB, so many of them were destroyed.

**Comment by superalex** [comment]
Hello @fish-ball we are currently working to fix this one. The attachmets data is included in the json but the importing process isn't reading them properly. We will try to solve it as soon as possible.

Sorry for the inconvenience.

**Comment by superalex** [comment]
Hello @fish-ball we finally solved the issue, if you import again your old json files all the files should be respected (no need to re-export them). Sorry for the inconvenience!
