### ISSUE TITLE
404 Console log, Why?

### ISSUE THREAD

**Issue by fish-ball** [taigaio/taiga-back#517]
When I open the issue page of a project, I got the below 404 error on console log

> GET http://taiga.easecloud.cn/api/v1/user-storage/a539483760f31ea78090937ded6871be4282f3ae 404 (NOT FOUND)

### PS:

However, this error did not make any problem, I just want to report and know why.

And more, I was just installed new taiga 1.9.0 then imported some previous projects inside.

**Comment by bameda** [comment]
this call is to get the saved custom filters. if you don't have any, the request return a 404

**Comment by fish-ball** [comment]
Thank you, it do.
