### ISSUE TITLE
[Q] How to force Django admin interface to be in English. 

### ISSUE THREAD

**Issue by dralexk** [taigaio/taiga-back#52]
We have a self-managed Taiga installation in Germany. When we open Django admin interface, it automatically displays in German, and that display is incorrect (see the bug report at https://github.com/kaleidos-ventures/taiga-back/issues/51).

How can we switch to the English interface?

**Comment by yamila-moreno** [comment]
Hi there!

Do you know that we have [Taiga Community](https://community.taiga.io/) for questions? Please, check there; maybe another user has already ask something similar. If not, create your own. There are people there willing to help, members of the Taiga team members and other users.

To simplify  the process, we will systematically close all issues that are general support questions and redirect people to Taiga Community.

Taiga Team
