### ISSUE TITLE
Running Taiga behind Reverse Proxy

### ISSUE THREAD

**Issue by swiffer** [taigaio/taiga-back#522]
What settings have do i have do place in nginx.conf for using IIS & ARR in front of nginx as reverse proxy / ssl offloading ?

iis / arr is listening on: https://taiga.example.com/

forwarded to nginx http://internal_ip/

front end renders fine but running api requests results in 502 Bad Request

**Comment by swiffer** [comment]
sorry! forgot to run 

sudo service circus start

**Comment by superalex** [comment]
Great! :+1:
