### ISSUE TITLE
Question: is it possible to globally manage users in Taiga?

### ISSUE THREAD

**Issue by queeno** [taigaio/taiga-back#525]
Hi there, Taiga community!

Just a quick question for you: is there a way to globally manage (add/remove/change) users in Taiga?

Thanks for your help and time!

**Comment by superalex** [comment]
Hello @queeno,

If you have your own instance then yes, you can use the django admin interface directly to manage almost everything in Taiga but as Uncle Ben said "“With great power comes great responsibility" so be careful :)

If you are using our own instance then you can only manage users per project if you have admin privileges for that project from the admin area.

Regards!,

**Comment by queeno** [comment]
Thanks @superalex 

Sure, the django admin interface! I was hoping there was a built-in page somewhere, but I guess that will do either!

Thanks very much for your help!

**Comment by superalex** [comment]
You are welcome! ;)
