### ISSUE TITLE
Task change webhook does not contain 'is_closed'

### ISSUE THREAD

**Issue by tpavlek** [taigaio/taiga-back#526]
Tasks have an open/closed state, and the userstory change webook includes 'is_closed' => true/false. It would be helpful to include that in the task change webhook.

**Comment by superalex** [comment]
Hello @tpavlek in the user_stories the situation is a bit different. They have two different attributes:
 - is_closed
 - status (that has a is_closed attribute too).

Tasks have got only status attribute (that has a is_closed attribute too).

We could include the status__is_closed attribute in the webhook data but you actually have that info (the project API list the task statuses and if they are closed or not).

Regards!,
