### ISSUE TITLE
`OneToOneRel' object has no attribute 'parent_model` at project's admin

### ISSUE THREAD

**Issue by hgfischer** [taigaio/taiga-back#532]
Hi,

I'm using the stable branch of Taiga and got this error when accessing a project's admin page.

![screen shot 2015-11-20 at 10 04 12](https://cloud.githubusercontent.com/assets/120860/11295762/17f8dfd0-8f6e-11e5-9319-5d85f2d75fb1.png)

Thanks!

**Comment by superalex** [comment]
Hello @hgfischer this issue was solved some days ago, could you please check if you are using the last stable release?.

Regards

**Comment by hgfischer** [comment]
Hi,

I was already using the last stable version (9c0cae890955f6dd4030f911ff6b228d2b36b30b). Just to be sure everything was fine, I executed the migrations again and restarted the services and not it is working. Thanks.

The database was not updated:

```
Operations to perform:
  Synchronize unmigrated apps: locale, mdrender, django_jinja, _humanize, raven_contrib_django, messages, searches, django_transactional_cleanup, api, stats, staticfiles, front, export_import, base, events, sr, sitemaps
  Apply all migrations: timeline, users, tasks, wiki, votes, history, github, contenttypes, easy_thumbnails, custom_attributes, djmail, issues, bitbucket, gitlab, references, milestones, feedback, sessions, webhooks, projects, auth, userstories, attachments, external_apps, likes, userstorage, admin, notifications
Synchronizing apps without migrations:
  Creating tables...
    Running deferred SQL...
  Installing custom SQL...
Running migrations:
  Rendering model states... DONE
  Applying notifications.0006_auto_20151103_0954... OK
  Applying tasks.0009_auto_20151104_1131... OK
```

**Comment by superalex** [comment]
Great! :)
