### ISSUE TITLE
Versioning for wiki

### ISSUE THREAD

**Issue by jaywink** [taigaio/taiga-back#540]
How does Taiga intend to deal with page versioning for the wiki? Does it exist in some form in the backend? In the frontend at least I can't see a way to view or restore previous versions - only the count is visible.

I think this feature is a real blocker for wiki usage. All wikis have versioning, and need to have, by their definition.

It would be awesome if the wiki pages we're exposed as a git repo like on GitHub, so project admins can backup the pages easily and even do offline editing. But this is optional of course, the most important thing would be that Taiga;
* stores revisions of wiki page edits
* allows diffs to be viewed
* allows restoring old versions

Thanks for an awesome tool!

**Comment by bameda** [comment]
Hi Jason, our backend support this, and you can use the API to view and revert the changes, but is not implemented yet in our frontend. I hope we'll can do soon.

Thanks for your feedback

**Comment by jaywink** [comment]
Thanks for the info, I suspected as much! :) Also found a [user story](https://tree.taiga.io/project/taiga/us/1621) regarding this, so I'll close this issue. Thanks!
