### ISSUE TITLE
ImportError: No module named 'django'

### ISSUE THREAD

**Issue by greenled** [taigaio/taiga-back#541]
Hi. I tried installing in afresh Ubuntu 14.04 following [the guide](http://taigaio.github.io/taiga-doc/dist/setup-production.html). As I am behind a proxy, I had to install a more recent python-pip from Wily to get the version 1.6 and be able to download packages. Now, after installing django, when I have to run "python manage.py XXX" I get this:

```
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    from django.core.management import execute_from_command_line
ImportError: No module named 'django'
```

I am not a python developer, and don't know about details of it's build system. Docs says Taiga needs python 3.4, but I found django files go to ~/.local/lib/python2.7 after resolving dependencies. Could that be the problem? What else if not?

**Comment by bameda** [comment]
yes, you have to use the instructions to create the virtualenv with python 3.4, and install django inside the virtualenv.

**Comment by greenled** [comment]
Hi @bameda , and thanks for the quick answer. Well, I think I did exactly that. I created the virtualenv, and inside it ```python -V``` says I am using ```3.4```. But when I execute pip, django goes to ~/.local/lib/python2.7 for no aparent reason. It should go to my virtualenv directory instead, right? I also tried installing pip trough [get-pip.py](https://bootstrap.pypa.io/get-pip.py), and still the same.

**Comment by bameda** [comment]
Try to do this

```
cd taiga-back
workon taiga
pip --version
```

this is the output:

```
    pip 7.1.2 from /home/taiga/.virtualenvs/taiga/lib/python3.5/site-packages (python 3.5)
```

So you can do

```
pip install -r requirements.txt
```

**Comment by greenled** [comment]
Hey, I found a way out! I didn't use the ```python-pip``` and  ```virtualenvwrapper```  packages from Ubuntu 14.04. Instead, I [installed ```pip``` from source](https://pypi.python.org/packages/source/p/pip/pip-7.1.2.tar.gz) and as root, and then [installed](http://virtualenvwrapper.readthedocs.org/en/latest/install.html) ```virtualenvwrapper``` from ```pip``` as root too. Now I can see I am using pip 7.1.2 and python 3.4, and the routes point to my virtualenv. Thanks for your help.

**Comment by bameda** [comment]
You are welcome. But if you don't use the setup instruction we can't help you :-(
