### ISSUE TITLE
Issue creation event triggered if issue is promoted to user story

### ISSUE THREAD

**Issue by mlq** [taigaio/taiga-back#542]
If I promote an issue to a user story an additional event is triggered (to the web hook as well as in the timeline) that the issue itself has been created as well although it already existed. I think this is rather confusing and would suggest to omit this second event or to change it to a modified event.

**Comment by superalex** [comment]
Thanks for reporting @mlq we'll try to solve it as soon as possible.

Regards!,

**Comment by ffwd-txnx** [comment]
Has this been fixed? Just tried manually via web UI, on our installation of taiga 3.0.0, not seeing issue itself being re-created in timeline. Didn't test web hooks.

The promoted user story has the same name, true, and can be confused with the original issue, e.g. issue 1111 and user story 1112, but that is human factor.

**Comment by superalex** [comment]
I cannot reproduce that either, I think it was solved some time ago. Thanks @ffwd-txnx
