### ISSUE TITLE
404 for css in django admin interface

### ISSUE THREAD

**Issue by allan-simon** [taigaio/taiga-back#547]
I've set up a local instance following the setup instruction, everything is working fine, at the exception of the css for the  django admin panel, which is giving me 404 for `/static/admin/css/base.css` and the other css

**Comment by allan-simon** [comment]
somewhat somehow  , I've forgotten the  ./mange.py collectstatic  my bad.

**Comment by bameda** [comment]
Good,  enjoy taiga ;-)
