### ISSUE TITLE
Complexity numbers not following fibonnaci sequence

### ISSUE THREAD

**Issue by allan-simon** [taigaio/taiga-back#548]
especially the 10,  especially as these numbers are normally chosen to avoid overthinking "is it a a 8 or a 10"

**Comment by bameda** [comment]
Hi @allan-simon you can edit story points, add modify or remove, in ```Admin > Attributes > Points```

![image](https://cloud.githubusercontent.com/assets/877218/11805961/14a35576-a310-11e5-9b15-ac2728fc54e5.png)

**Comment by allan-simon** [comment]
thanks for the help.

**Comment by bameda** [comment]
you are welcome
