### ISSUE TITLE
dev environment question

### ISSUE THREAD

**Issue by gaoyanzeng** [taigaio/taiga-back#553]
I take windows 10 as development OS and pycharm as IDE, how to set the dev environment? thank you verymuch

**Comment by superalex** [comment]
Hello @gaoyanzeng ,

Sorry but we don't support windows, the easiest way to create a development environment should be following our doc about it -> http://taigaio.github.io/taiga-doc/dist/setup-development.html

Regards!,

**Comment by gaoyanzeng** [comment]
thank u, how about Mac?

**Comment by superalex** [comment]
Sorry @gaoyanzeng but we don't have any official doc about deploying Taiga on Mac, you could try following the official doc over it. It should be possible but actually the only system we have documented is Ubuntu 14.04 (you could use a virtual machine or use a docker image over your Mac system).

Regards,
