### ISSUE TITLE
Support custom storage backends like django-storages (S3, Azure, CloudFiles, etc)

### ISSUE THREAD

**Issue by jeffbaier** [taigaio/taiga-back#554]
I am using [Deis](http://deis.io/) to host my own Taiga installation. I am running it all on Amazon Web Services, and using S3 for file storage. For my other Django projects I use django-storages' S3BotoStorage as the storage backend. However, when I enabled it in the taiga-back project I ran into a few problem areas. 

When deleting avatars and when creating a project export I would receive the following error.

`NotImplementedError: This backend doesn't support absolute paths.`

There were 3 places in the code that were using [Storage.path](https://docs.djangoproject.com/en/1.8/ref/files/storage/#django.core.files.storage.Storage.path) which raises NotImplementedError for non-local storage systems. 

I have fixed these files in my local fork. Only 3 lines needed changed that I have found so far. I'd like to discuss contributing back these changes to the main project, but I am hesitant to open a Pull Request because while the changes work on my system, I'm not sure how they would affect installations using the default local filesystem.

**Comment by bameda** [comment]
Hi @jeffbaier, you can make the PR and we can test it in our local and preproduction envs.

**Comment by jeffbaier** [comment]
Ok thanks @bameda . I'm just getting back from the holidays, I'll do a little more testing on my side and then submit the PR.

**Comment by jpros** [comment]
@jeffbaier you need to also configure the easy_thumbnails to use Amazon S3 with the THUMBNAIL_DEFAULT_STORAGE setting.

**Comment by jeffbaier** [comment]
@jpros yep I was able to do that in my local settings file though. My other fixes required modifying core taiga files.

**Comment by jpros** [comment]
@jeffbaier I just realized that there is something else that needs to be done. The command "delete_thumbnails" isn't removing from Amazon S3.
