### ISSUE TITLE
github integration: commit not showing in taiga

### ISSUE THREAD

**Issue by specky-rum** [taigaio/taiga-back#555]
Hi,

After following the instructions for integrating a Taiga project with GitHub I committed a change with a commit message including the string "TG-3" expecting this to show in Taiga against US3 but I see nothing.  GitHub reports that the web hook fired and received a 204 - no response error code.  Should this be working?  I was hoping to see the commit listed against the user story?

The GitHub repo is public (it's just for testing) and you can see one of the two commits I tested this with here: https://github.com/specky-rum/specky-test/commit/fc54706288939c70f28e1f1882ec8569feedaefa

The payload URL it was sent to was: https://api.taiga.io/api/v1/github-hook?project=83064

The payload itself is attached (I just edited my email address out, it is otherwise untouched).  Did I miss something?

[payload.txt](https://github.com/taigaio/taiga-back/files/76980/payload.txt)

Cheers.

**Comment by superalex** [comment]
Hello @specky-rum 

Actually the format for commit messages (https://taiga.io/support/changing-elements-status-via-commit-message/) should be:

TG-REF #STATUS-slug

It allows you to change the status of the item, it there was no status in your message nothing extra will happen...

Regards!,

**Comment by usersxm** [comment]
I am committing this "TG-5 #done" (and 5 is the reference of a US) and it doesn't change taigas US status.. The web hook is correctly set (there's a tick when github pinged it)

**Comment by superalex** [comment]
Hello @usersxm are you sure done is a valid status slug?, is this happening in tree.taiga.io or in your own instance?

**Comment by usersxm** [comment]
apparently the problem was when I commit I always used -am flags (I don't know why the a, but I've seen people done that, so I did it too) and with that flag didn't work. Now I just commit using the -m and it works perfectly.
