### ISSUE TITLE
Have the possibility to link a project to a "company" 

### ISSUE THREAD

**Issue by allan-simon** [taigaio/taiga-back#564]
As reported here https://github.com/taigaio/taiga-front/issues/806

Currently all the projects are in the "common space" which mean, as taiga is used as a SaaS services, that each project is currently tightly separated from other projects with no cross-communication 

It will be great to have a "company" entity which will be 

   * a list of users
   * a list of projects 

so that one can join a company and then navigate in the list of projects in this company 

so that it will permit to fix https://github.com/taigaio/taiga-front/issues/806 by permitting to autocomplete on the list of users in said company 

starting from there , a lot of things will then become possible (but more "long term") 

   * permit to configure a SSO system per company (like for example to log-in to gmail we use our internal SSO, which is a requirement for a lot of non-startup company)
   * permit for middle-managemet to have a consolidated view of several projects
   * it will still possible to have "invitation only" projects by doing like in gitlab  "private/protected/public" (protected being "open to every people in the company)
   * permit to have "non-technical-user admin" to manage user in taiga without needing to open the acess to django admin
   etc. etc.
   * plugins for the company view ( for example: plugin to have a knowledge base etc.)

**Comment by superalex** [comment]
Hello @allan-simon we had an existing user story to add the "organization" concept to Taiga :https://tree.taiga.io/project/taiga/us/2129

I've copied all your comments there, closing this and leaving the Taiga one open

Thank you very very much for the feedback!
