### ISSUE TITLE
REST framework licence

### ISSUE THREAD

**Issue by tomchristie** [taigaio/taiga-back#567]
Hi folks,

The REST framework-based position of the codebase oughta include the REST framework license:

https://github.com/tomchristie/django-rest-framework/blob/master/LICENSE.md

Cheers! :smile:

**Comment by superalex** [comment]
You are absolutely right, we are currently working on it.

Regards!,

**Comment by superalex** [comment]
The pull request by @niwinz related to this one: https://github.com/taigaio/taiga-back/pull/568

**Comment by bameda** [comment]
Merged. Thanks @tomchristie

**Comment by tomchristie** [comment]
Grand, thanks!

**Comment by bameda** [comment]
You are welcome :-)
