### ISSUE TITLE
New install 404 on pretty much everything backend related

### ISSUE THREAD

**Issue by mariusv** [taigaio/taiga-back#569]
Heya,

Just finished a installation doing copy/paste from the [Documentation](https://taigaio.github.io/taiga-doc/dist/setup-production.html#circus-and-gunicorn) and everything at least on the server seems to work as expected just that pretty much whatever is not /login gives a 404

```bash
taiga@ip-172-30-1-147:~/taiga-back$ curl -IL 127.0.0.1:8001/api
HTTP/1.1 404 NOT FOUND
Server: gunicorn/19.3.0
Date: Sat, 09 Jan 2016 18:30:35 GMT
Connection: close
Transfer-Encoding: chunked
Access-Control-Allow-Headers: content-type,x-requested-with,authorization,accept-encoding,x-disable-pagination,x-lazy-pagination,x-host,x-session-id
Access-Control-Expose-Headers: x-pagination-count,x-paginated,x-paginated-by,x-pagination-current,x-pagination-next,x-pagination-prev,x-site-host,x-site-register,taiga-info-total-opened-milestones,taiga-info-total-closed-milestones
Access-Control-Max-Age: 3600
Access-Control-Allow-Origin: *
Vary: Accept-Language
Content-Language: en
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: POST,GET,OPTIONS,PUT,DELETE,PATCH,HEAD
Content-Type: text/html
```
Same if you go trough the front-end:

```bash
marius@delirium:~$ curl -IL domain.tld/api
HTTP/1.1 404 NOT FOUND
Server: nginx/1.4.6 (Ubuntu)
Date: Sat, 09 Jan 2016 18:32:17 GMT
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Access-Control-Allow-Headers: content-type,x-requested-with,authorization,accept-encoding,x-disable-pagination,x-lazy-pagination,x-host,x-session-id
Access-Control-Expose-Headers: x-pagination-count,x-paginated,x-paginated-by,x-pagination-current,x-pagination-next,x-pagination-prev,x-site-host,x-site-register,taiga-info-total-opened-milestones,taiga-info-total-closed-milestones
Access-Control-Max-Age: 3600
Access-Control-Allow-Origin: *
Vary: Accept-Language
Content-Language: en
Access-Control-Allow-Credentials: true
Access-Control-Allow-Methods: POST,GET,OPTIONS,PUT,DELETE,PATCH,HEAD
```

This is my `local.py` : 

```python
taiga@ip-172-30-1-147:~/taiga-back$ cat settings/local.py
from .common import *
#from .celery import *

MEDIA_URL = "http://domain.tld/media/"
STATIC_URL = "http://domain.tld/static/"
ADMIN_MEDIA_PREFIX = "http://domain.tld/static/admin/"
SITES["front"]["scheme"] = "http"
SITES["front"]["domain"] = "domain.tld"

SECRET_KEY = "theveryultratopsecretkey"
EVENTS_PUSH_BACKEND = "taiga.events.backends.rabbitmq.EventsPushBackend"
EVENTS_PUSH_BACKEND_OPTIONS = {"url": "amqp://taiga:password@localhost:5672/taiga"}

#BROKER_URL = 'amqp://guest:guest@localhost:5672/'
#CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
#CELERY_ENABLED = True

DEBUG = True
TEMPLATE_DEBUG = True
PUBLIC_REGISTER_ENABLED = True

DEFAULT_FROM_EMAIL = "no-reply@domain.tld"
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Uncomment and populate with proper connection parameters
# for enable email sending. EMAIL_HOST_USER should end by @domain.tld
#EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
#EMAIL_USE_TLS = False
#EMAIL_HOST = "localhost"
#EMAIL_HOST_USER = ""
#EMAIL_HOST_PASSWORD = ""
#EMAIL_PORT = 25

# Uncomment and populate with proper connection parameters
# for enable github login/singin.
#GITHUB_API_CLIENT_ID = "yourgithubclientid"
#GITHUB_API_CLIENT_SECRET = "yourgithubclientsecret"
```

```
Using the URLconf defined in taiga.urls, Django tried these URL patterns, in this order:

    ^api/v1/
    ^api/v1/
    ^api/v1/api-auth/
    ^admin/
    ^static\/(?P<path>.*)$
    ^media\/(?P<path>.*)$
    ^api/v1/

The current URL, api, didn't match any of these.
```

Any idea? Ah, logs are not too helpful too after enabling debug

**Comment by superalex** [comment]
Hello @mariusv 

If nothing is listening in localhost on port 8001 it seems a problem related to circus not serving correctly taiga-back

I think you could use taiga-scripts to have a working Taiga instance with a fully automated installation process and then add the extra configuration you could need.

Regards!,

**Comment by mariusv** [comment]
Heya @superalex 

The funny part is that even with those errors seems like taiga works as expected now...I can create projects and users and all but this worries me as I get those 404s .

**Comment by superalex** [comment]
Sorry @mariusv but now I don't know what's not working exactly...when are you receiving those 404 errors?

**Comment by superalex** [comment]
Hello @mariusv ,any news about this?

**Comment by alex-hutton** [comment]
Hi, I'm having what seems to be the same issue.

I installed taiga into `/opt/taiga/` . So I have `/opt/taiga/taiga-back/` `/opt/taiga/front-dist/`. I basically followed the instructions at https://taigaio.github.io/taiga-doc/dist/setup-production.html . My taiga-back is at `a4b9140c`, which is what stable currently is.

When running with gunicorn, circus or even just `manage.py runserver`, all I am getting are 404s.

For example:

```
$ sudo -u taiga/bin/python manage.py runserver

Trying import local.py settings...
Trying import local.py settings...
Performing system checks...

System check identified no issues (0 silenced).
January 24, 2017 - 05:00:28
Django version 1.9.2, using settings 'settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[24/Jan/2017 05:00:41] "GET / HTTP/1.1" 404 74
[24/Jan/2017 05:00:45] "GET /api HTTP/1.1" 404 77
```

The 404s were prompted by:
`$ curl localhost:8000`
and
`$ curl localhost:8000/api`
respectively

If I run with gunicorn:
```
$ sudo -u taiga taiga/bin/gunicorn -w 3 -t 60 --pythonpath=. -b 127.0.0.1:8001 taiga.wsgi
[2017-01-24 16:13:21 +1100] [8732] [INFO] Starting gunicorn 19.4.5
[2017-01-24 16:13:21 +1100] [8732] [INFO] Listening at: http://127.0.0.1:8001 (8732)
[2017-01-24 16:13:21 +1100] [8732] [INFO] Using worker: sync
[2017-01-24 16:13:21 +1100] [8735] [INFO] Booting worker with pid: 8735
[2017-01-24 16:13:21 +1100] [8737] [INFO] Booting worker with pid: 8737
[2017-01-24 16:13:21 +1100] [8739] [INFO] Booting worker with pid: 8739
Trying import local.py settings...
Trying import local.py settings...
Trying import local.py settings...
```
curl gives:
```
$ curl localhost:8001/
<h1>Not Found</h1><p>The requested URL / was not found on this server.</p>
$ curl localhost:8001/api
<h1>Not Found</h1><p>The requested URL /api was not found on this server.</p>
```

Please let me know if you have any ideas.

**Comment by superalex** [comment]
Hello!,

It's normal to receive a 404 from those urls, try a curl to /api/v1/ (/ and /api aren't existing urls)

Regards,

**Comment by alex-hutton** [comment]
@superalex , thanks for the reply. You are right! I had the urls wrong, /api/v1/ does work, even through nginx. I still don't have the root path working but I will investigate futher

**Comment by alex-hutton** [comment]
I got it working but in the end the problem is that taiga can't run from a subdirectory, which is a separate issue. I made use of sed to replace the paths in taiga-front-dist, and was able to have all the resources load, but then the angular router seems to have had an issue. When visiting `/taiga`, my browser location ends up as `/taiga//taiga//taiga/taiga%2F` and I see a 404 message from taiga. I'm going to going to have to look at using a subdomain for taiga.

**Comment by superalex** [comment]
@alex-hutton you are right, taiga isn't ready to be run from a subdirectory so should enable a subdomain.

**Comment by sivasai519** [comment]
hello @superalex 

i was running this command python manage.py runserver

Trying import local.py settings...
Trying import local.py settings...
Performing system checks...

System check identified no issues (0 silenced).
December 05, 2017 - 14:45:06
Django version 1.10.6, using settings 'settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[05/Dec/2017 14:48:08] "GET /api/v1 HTTP/1.1" 404 80
[05/Dec/2017 14:48:23] "GET / HTTP/1.1" 404 74

while connect with this command 
firefox localhost:8000

console.error:
  [CustomizableUI]
  Custom widget with id loop-button does not return a valid node

could you plz help out

**Comment by theriverman** [comment]
Start the server, then go to
http://127.0.0.1:8000/api/v1/

**Comment by lord-boros** [comment]
como lograron instalarlo correctamente?
