### ISSUE TITLE
Add the ability to import tasks from others Issues Managers (Trello, Jira...)

### ISSUE THREAD

**Issue by jpros** [taigaio/taiga-back#570]
In my company we used JIRA (self-hosted) for about 3 years, the maintenance and cost for a Java application made us migrate to Trello, it was very "painful" to manually migrate every task and project. That made us leave behind every closed project, and we only migrated the open ones.

Now we are using it for about 4 months, but I still missing some features and customization of JIRA. However with taiga I feel like home again. I'm running the backend in a Heroku instance, and the frontend as a subdomain in our webhost. 

All that said, what is left for us is to import all issues and start this new year working on Taiga. We are doing it manually, but would be great to be able to import our cards and boards from Trello to Taiga.

**Comment by superalex** [comment]
Hello @jpros 

We have an existing user story in our Kanban to include this feature in Taiga (https://tree.taiga.io/project/taiga/us/1216), I'm closing this one and adding your comments there.

As a workaround you could use our API to automate the data creation -> https://taigaio.github.io/taiga-doc/dist/api.html. Taiga also support import/export of projects in json format https://taiga.io/support/import-export-projects/, you could download a basic exported project and customize that json with the data from your Trello project.

Regards!,

**Comment by jespino** [comment]
Hi @jpros, we are working on Jira/Trello/Github/Asana/PivotalTracker migrators. You still need this kind of migrations? do you want to collaborate testing the beta version of the migrators?

**Comment by jvreeken** [comment]
@jespino I'm interested in Trello migration.  You say you are working on a migration module?  I'd be interested in helping test your beta version.

**Comment by jespino** [comment]
Yes, we are working on it, currently is a django command (We will have a nice interface in the future), so in the test process the idea is to import your Trello board in my machine, generate a taiga dump, and import it on your taiga instance or in the Taiga service. Please, send a message to support@taiga.io and we can continue the conversation by email, video conference or whatever :)

**Comment by Marina001** [comment]
@jespino We are interested in being able to migrate our existing issues from GitLab.

**Comment by jpros** [comment]
Hey @jespino, sorry for the long delay. Do you still need beta tester?

**Comment by artiebob** [comment]
@jespino we are also about to work on migrating our project from github to taiga. what progress was made on the github import? if you need testing on it let us know.

**Comment by superalex** [comment]
hellp @artiebob we included this feature in the last release you can find the doc about to use it here: https://tree.taiga.io/support/importers/github-importer/

**Comment by pajtai** [comment]
@superalex How do you enable importers on a self hosted Taiga?
I only see the Taiga option, and the docs don't describe enable / disable.

**Comment by pajtai** [comment]
I see that you have to add configs to local.py

https://github.com/taigaio/taiga-back/blob/master/settings/local.py.example#L186

There's comments in there to enable it on the front. How is that accomplished? Are there any docs that cover this?

**Comment by jespino** [comment]
To enable in the front interface you have to add to your conf.json file the "importers" key with a list of enabled importers. Each importer is enabled with a string with the name ("github", "trello", "jira", "asana").

**Comment by pajtai** [comment]
@jespino Thanks for that. I figured that out.

What I'm struggling with now is that they pub cert and cert to be adding to local.py are multi line strings. How can those be added? Are they to be added inline or are they meant to be added as pointers to files.
