### ISSUE TITLE
Webhook missing title on wiki page edit

### ISSUE THREAD

**Issue by fuzzy76** [taigaio/taiga-back#574]
The json my webhook receives when people edit a wikipage does not contain the page title. The closest is the page slug, but that is not enough for presentation.

**Comment by superalex** [comment]
Hello @fuzzy76 

Actually we don't store the wiki page titles, only the wiki links (from the left column). We would like to fully rebuild our wiki and rich content system and we have an existing user story to achieve it (https://tree.taiga.io/project/taiga/us/2114). I'm closing this issue and leaving your comments in the Taiga user story.

Thank you very much for the feedback!
