### ISSUE TITLE
When creating a test scrum project I got two projects named the same.

### ISSUE THREAD

**Issue by davidssonarnor** [taigaio/taiga-back#575]

**Comment by davidssonarnor** [comment]
When creating a test scrum project I got two projects named the same.  The projects seem to be independent of each other as I create Stories and Sprints they are only displayed in that projects not the other.

**Comment by superalex** [comment]
Hello @davidssonarnor 

Is this happening on tree.taiga.io?, I'm trying to reproduce the issue but I can't...

Regards!,

**Comment by superalex** [comment]
Hello @davidssonarnor 

Could you check this one?

**Comment by davidssonarnor** [comment]
Hi, yes on tree.taiga.io. I haven't run into the duplicate issue again.

**Comment by superalex** [comment]
Thanks @davidssonarnor we couldn't reproduce the issue so I'm closing it, please, reopen it if you find the problem again.

Regards!,
