### ISSUE TITLE
Unable to upgrade

### ISSUE THREAD

**Issue by Sauermann** [taigaio/taiga-back#578]
I am unable to upgrade to the latest version of taiga, because "pip install --upgrade -r requirements.txt" fails during lxml compilation.

Here is the log output:
https://gist.github.com/Sauermann/fd2b2e2c02ec519ff998

System: Debian Jessie with gcc 4.9.2.
Previous taiga version was from 2015-12-16.

**Comment by bameda** [comment]
Make sure you have enough memory in the server. Try `dmesg | tail` to see if it outputs something like:

```bash
...
[3778136.277570] Out of memory: Kill process 21267 (cc1) score 557 or sacrifice child
[3778136.277587] Killed process 21267 (cc1) total-vm:365836kB, anon-rss:336228kB
```

You need ~ 1GB of RAM.

There is other tips at http://stackoverflow.com/questions/16149613/installing-lxml-with-pip-in-virtualenv-ubuntu-12-10-error-command-gcc-failed

**Comment by Sauermann** [comment]
@bameda: Thank you for pointing out my problem.

**Comment by bameda** [comment]
You are welcome :-)
