### ISSUE TITLE
I'm deploying taiga and then crash it

### ISSUE THREAD

**Issue by ecardoz** [taigaio/taiga-back#579]
I'm deploying Taiga. In the step in which the requirements are installed:

pip install -r requirements.txt

An accident occurs, the log says:

  Downloading from URL https://pypi.python.org/packages/source/a/anyjson/anyjson-0.3.3.tar.gz#md5=2ea28d6ec311aeeebaf993cb3008b27c (from https://pypi.python.org/simple/anyjson/)
  Running setup.py (path:/tmp/pip_build_ecardoz/anyjson/setup.py) egg_info for package anyjson
    running egg_info
    creating pip-egg-info/anyjson.egg-info
    writing pip-egg-info/anyjson.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/anyjson.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/anyjson.egg-info/dependency_links.txt
    writing manifest file 'pip-egg-info/anyjson.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'pip-egg-info/anyjson.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pip-egg-info/anyjson.egg-info/SOURCES.txt'
  Source in /tmp/pip_build_ecardoz/anyjson has version 0.3.3, which satisfies requirement anyjson>=0.3.3 (from kombu>=3.0.29,<3.1->celery==3.1.19->-r requirements.txt (line 24))
Installing collected packages: Django, django-picklefield, django-sampledatahelper, gunicorn, psycopg2, Pillow, pytz, six, amqp, djmail, django-pgjson, djorm-pgarray, django-jinja, jinja2, pygments, django-sites, Markdown, fn, diff-match-patch, requests, django-sr, easy-thumbnails, celery, redis, Unidecode, raven, bleach, django-ipware, premailer, cssutils, django-transactional-cleanup, lxml, pyjwkest, django-pglocks, sampledata, MarkupSafe, kombu, billiard, contextlib2, cssselect, django-transaction-hooks, pycrypto, future, anyjson
Cleaning up...
  Removing temporary dir /tmp/pip_build_ecardoz...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283, in run
    requirement_set.install(install_options, global_options, root=options.root_path)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1436, in install
    requirement.install(install_options, global_options, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 672, in install
    self.move_wheel_files(self.source_dir, root=root)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 902, in move_wheel_files
    pycompile=self.pycompile,
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 206, in move_wheel_files
    clobber(source, lib_dir, True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 193, in clobber
    os.makedirs(destsubdir)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/django'

**Comment by bameda** [comment]
You are using python 2.7

File "/usr/lib/*python2.7*/os.py", line 157, in makedirs
mkdir(name, mode)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/
dist-packages/django'

And Taiga runs with

[image: Inline image 1]

On Fri, Jan 22, 2016 at 9:52 PM, Ed Cardoz <notifications@github.com> wrote:

> I'm deploying Taiga. In the step in which the requirements are installed:
>
> pip install -r requirements.txt
>
> An accident occurs, the log says:
>
> Downloading from URL
> https://pypi.python.org/packages/source/a/anyjson/anyjson-0.3.3.tar.gz#md5=2ea28d6ec311aeeebaf993cb3008b27c
> (from https://pypi.python.org/simple/anyjson/)
> Running setup.py (path:/tmp/pip_build_ecardoz/anyjson/setup.py) egg_info
> for package anyjson
> running egg_info
> creating pip-egg-info/anyjson.egg-info
> writing pip-egg-info/anyjson.egg-info/PKG-INFO
> writing top-level names to pip-egg-info/anyjson.egg-info/top_level.txt
> writing dependency_links to
> pip-egg-info/anyjson.egg-info/dependency_links.txt
> writing manifest file 'pip-egg-info/anyjson.egg-info/SOURCES.txt'
> warning: manifest_maker: standard file '-c' not found
>
> reading manifest file 'pip-egg-info/anyjson.egg-info/SOURCES.txt'
> reading manifest template 'MANIFEST.in'
> writing manifest file 'pip-egg-info/anyjson.egg-info/SOURCES.txt'
>
> Source in /tmp/pip_build_ecardoz/anyjson has version 0.3.3, which
> satisfies requirement anyjson>=0.3.3 (from
> kombu>=3.0.29,<3.1->celery==3.1.19->-r requirements.txt (line 24))
> Installing collected packages: Django, django-picklefield,
> django-sampledatahelper, gunicorn, psycopg2, Pillow, pytz, six, amqp,
> djmail, django-pgjson, djorm-pgarray, django-jinja, jinja2, pygments,
> django-sites, Markdown, fn, diff-match-patch, requests, django-sr,
> easy-thumbnails, celery, redis, Unidecode, raven, bleach, django-ipware,
> premailer, cssutils, django-transactional-cleanup, lxml, pyjwkest,
> django-pglocks, sampledata, MarkupSafe, kombu, billiard, contextlib2,
> cssselect, django-transaction-hooks, pycrypto, future, anyjson
> Cleaning up...
> Removing temporary dir /tmp/pip_build_ecardoz...
> Exception:
> Traceback (most recent call last):
> File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in
> main
> status = self.run(options, args)
> File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 283,
> in run
> requirement_set.install(install_options, global_options,
> root=options.root_path)
> File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1436, in install
> requirement.install(install_options, global_options, *args, **kwargs)
> File "/usr/lib/python2.7/dist-packages/pip/req.py", line 672, in install
> self.move_wheel_files(self.source_dir, root=root)
> File "/usr/lib/python2.7/dist-packages/pip/req.py", line 902, in
> move_wheel_files
> pycompile=self.pycompile,
> File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 206, in
> move_wheel_files
> clobber(source, lib_dir, True)
> File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 193, in clobber
> os.makedirs(destsubdir)
> File "/usr/lib/python2.7/os.py", line 157, in makedirs
> mkdir(name, mode)
> OSError: [Errno 13] Permission denied:
> '/usr/local/lib/python2.7/dist-packages/django'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/taigaio/taiga-back/issues/579>.
>



-- 

---


*David Barragán Merino*
* Engineer *
<david.barragan@kaleidos.net>
david.barragan@kaleidos.net  | Tel: (+34) 913562995
www.kaleidos.net/FFF8E7

**Comment by ecardoz** [comment]
@bameda I change the python version using this:
http://linuxconfig.org/how-to-change-from-default-to-alternative-python-version-on-debian-linux

**Comment by superalex** [comment]
It seems it didn't work ;)

Before installing the requirements file you must ensure that executing "python --version" should return "python 3".

Regards!,
