### ISSUE TITLE
Error in circusctl 

### ISSUE THREAD

**Issue by ecardoz** [taigaio/taiga-back#581]
(taiga)taiga@taigaserver:~/taiga-back$ circusctl reloadconfig
Timed out.
A time out usually happens in one of those cases:

#1 The Circus daemon could not be reached.
#2 The Circus daemon took too long to perform the operation

For #1, make sure you are hitting the right place
by checking your --endpoint option.

For #2, if you are not expecting a result to
come back, increase your timeout option value
(particularly with waiting switches)

Somebody can helpme?

**Comment by superalex** [comment]
Hello @ecardoz 

Have you got more info about the exact problem?, are you receiving any logs?. 

How did you install Taiga?, you could use taiga-scripts to have a fully working instance and later customize the configuration files if needed -> http://taigaio.github.io/taiga-doc/dist/setup-alternatives.html#setup-taiga-scripts

Regards,

**Comment by superalex** [comment]
Hello @ecardoz any news about this?

**Comment by Mehar-un-nisa** [comment]
mehar-un-nisa@ubuntu:~/taiga-back$ circusctl reloadconfig
Timed out.
A time out usually happens in one of those cases:

#1 The Circus daemon could not be reached.
#2 The Circus daemon took too long to perform the operation

For #1, make sure you are hitting the right place
by checking your --endpoint option.

For #2, if you are not expecting a result to
come back, increase your timeout option value
(particularly with waiting switches)



there is no solutions of this error plzzzzzzzzzzzzz recommend some solution

**Comment by Fatima-Batool** [comment]
is there any solution of this error ??

**Comment by superalex** [comment]
Yes, it's probably related to non using ubuntu 14.04 (the doc assumes that exact version is used), you can find more info about here: https://groups.google.com/d/topic/taigaio/970R1Mq1kDI/discussion

**Comment by Fatima-Batool** [comment]
but i'm using ubuntu 14.04,,,but i'm facing the same problem
tell me what can i do???
