### ISSUE TITLE
Type URL of Custom Field

### ISSUE THREAD

**Issue by astagi** [taigaio/taiga-back#583]
Hi,

I'd like to suggest a new type of custom field: url. Internally we use a lot of text custom fields with an URL and it would be awesome to have these fields clickable.

If interested, can I work to implement this?

**Comment by bameda** [comment]
:+1: 

I like it.

**Comment by Xaviju** [comment]
I like it too!

**Comment by astagi** [comment]
:smile:

**Comment by astagi** [comment]
@bameda do you use any particular library for url validation in taiga?

**Comment by bameda** [comment]
I can't remember but you can use ```django.core.validators.URLValidator``` for example

https://docs.djangoproject.com/en/1.9/ref/validators/#urlvalidator

**Comment by bameda** [comment]
https://github.com/django/django/blob/master/django/core/validators.py#L78

**Comment by astagi** [comment]
Oh sorry @bameda I forgot to specify, in the frontend part :)

**Comment by bameda** [comment]
okkk, in front you can use checksley (a fork of parsley). For example in the Admin > Integration Webhooks we have something like (https://github.com/taigaio/taiga-front/blob/master/app/partials/admin/admin-third-parties-webhooks.jade#L34)

```jade
input(
    type="text"
    name="url"
    data-type="url"
    data-required="true"
    ng-model="webhook.url"
    placeholder="{{'ADMIN.WEBHOOKS.TYPE_PAYLOAD_URL' | translate}}"
)

```

and to save the form (https://github.com/taigaio/taiga-front/blob/master/app/coffee/modules/admin/third-parties.coffee#L144):
```coffee
        save = debounce 2000, (target) ->
            form = target.parents("form").checksley()
            return if not form.validate()
            promise = $repo.save(webhook)
            promise.then =>
                showVisualizationMode()

            promise.then null, (data) ->
                $confirm.notify("error")
                form.setErrors(data)
```

**Comment by astagi** [comment]
Thanks @bameda I'll give it a try :smile:

**Comment by astagi** [comment]
PR opened both on front and back end, for any change required let me know!

**Comment by romolox** [comment]
This would be a very cool feature to have! 
Any news on this?

**Comment by bameda** [comment]
released
