### ISSUE TITLE
Feature request: Schedule reminder for task

### ISSUE THREAD

**Issue by jpros** [taigaio/taiga-back#585]
Hi there,

Congrats on the great work done so far. I'm using the self hosted version of taiga, and it's been great.

It would be nice to be able to schedule a reminder for a given user story, I think many project managers would like that. 

Think of this scenario: I promised to a customer that an user story will be ready on Feb 1st, however I'm managing many projects. 
What do I do now: Go to my calendar and schedule "Remind to check user story's status on Jan, 27". 
What would happen with this feature: Add a reminder on the user story, when that time/date arrives Taiga will send an email to all observers to remind of it.

I know it is not a core feature of Taiga, but it will be nice to have.

Best regards 
João Paulo Ros

**Comment by superalex** [comment]
Hello @jpros 

Thank you very much for the feedback and for sharing your ideas with us. We had an existing enhancement request to include something similar, I've just added your comments there. I'm closing this one and leaving the Taiga one open -> https://tree.taiga.io/project/taiga/issue/3069

Regards!,

**Comment by jpros** [comment]
Great!

Thanks for the reply and keep up with the good work! 

Regards

**Comment by oskarj84** [comment]
Hi @superalex . It is been a long time since the last comment but.. I am using the hosted version and it is a great system. I would like to know what happened with this issue because the link does not work.
Thanks in advance.
Best regards!!
