### ISSUE TITLE
Remenants of deleted projects.

### ISSUE THREAD

**Issue by lordloh** [taigaio/taiga-back#586]
In User > Edit Profile > Notifications, I see a few projects that I have deleted.

I deleted a few old projects, and still see some of them in the notifications for emails.

**Comment by superalex** [comment]
Hello @lordloh 

I'm trying to reproduce it in tree.taiga.io but I can't, could it be a problem with your browser cache?, did you try clearing it and reloading?.

Another thing you should try is checking if that project really exists or not accessing to its old url.

Regards!,

**Comment by lordloh** [comment]
I tried again on an incognito chrome (to remove cache etc.) and it is still there.

![capture2](https://cloud.githubusercontent.com/assets/2434923/12674941/b5a22986-c63b-11e5-86af-2322345b9468.PNG)
![capture](https://cloud.githubusercontent.com/assets/2434923/12674942/b5a2e0ba-c63b-11e5-8f72-f3e580779fbb.PNG)

The above screens show an extra project.

**Comment by lordloh** [comment]
Additional information: Manually typing http://taiga.selfhosted.com/project/bharath-eSkool/ takes me to a not-found page. I created the project and there were two other contributors. I then exported it to JSON and deleted the project.

**Comment by superalex** [comment]
Could you please check in your admin area ( http://taiga.selfhosted.com/admin/) if the project still exists?

**Comment by lordloh** [comment]
Yes... You were right. It was there. After deleting it from the admin area, it vanished :-) I did not even know of /admin/. Perhaps, there should be a link to this in the UI or at least in the footer. The /admin/ did not seem to have any stylesheets. Chrome developer tools shows me that a few CSS failed to load. 

http://ratnavali.h.com:85/static/admin/css/base.css net::ERR_NAME_NOT_RESOLVED

ratnavali.h.com - is a partial url of the self hosted site.

Should I ask this as a separate issue?

**Comment by bameda** [comment]
is a problem with your taiga back settings, `STATIC_URL` could be wrong

**Comment by superalex** [comment]
That django admin interface is something only usefull for super users of the platform and it isn't really needed for anything so we decided not to include that link.

If your admin css files aren't found probably you should update your ADMIN_MEDIA_PREFIX in your local.py file. For example for tree.taiga.io we have something like:

`ADMIN_MEDIA_PREFIX` = "https://static.taiga.io/admin/"

You should use a value valid for your instance.

**Comment by bameda** [comment]
ADMIN_MEDIA_PREFIX is deprecated, use STATIC_URL instead

**Comment by superalex** [comment]
Thanks @bameda
