### ISSUE TITLE
Generate a digest of notifications

### ISSUE THREAD

**Issue by red-hood** [taigaio/taiga-back#592]
Currently, Taiga sends an E-Mail on each change or other action on subscribed issues, leading to a flood of E-Mails in a very short time.

Providing the option to send e.g. a daily digest of all notifications would greatly improve usability and user experience, while reducing load on all involved mail systems.

Are there any plans to implement such a feature?

**Comment by superalex** [comment]
Hello!,

We had an existing enhancement request to include this feature (https://tree.taiga.io/project/taiga/issue/2165), I've just copied your comments there.

**Comment by joskoanicic** [comment]
@superalex 
Sorry for responding on a zombie thread. But wanted to know is this implemented? 
I have seen the feature mentioned in the 4.0.0 changelog but when I updated the project I don't have the Digest time column in the admin screen.
