### ISSUE TITLE
How to run taiga-back as a service

### ISSUE THREAD

**Issue by RobertoDebarba** [taigaio/taiga-back#594]
Hi,

I'm trying to run taiga-back as linux service/daemon. How you can see in [Taiga: Setup prodution environment](http://taigaio.github.io/taiga-doc/dist/setup-production.html), it's possible run circus and front-end as a service, but not show how to run taiga-back (workon taiga && python manage.py runserver).
It's possible to do it?
I use Ubuntu 14.04 x86_64.

Thanks a lot!

**Comment by bameda** [comment]
circus run gunicorn so you don't need to run python manage.py runserver

**Comment by gbrtomio** [comment]
I guess he used circus as example. The question is how to run taiga-back as service.

**Comment by bameda** [comment]
So the question is how to run circus as a service:

For ubuntu  (with init.d) for example you can do this:
http://stackoverflow.com/a/12554332

Or in debian (with systemd) :
https://github.com/taigaio/taiga-front/wiki/install-guides#setup-circus-to-start

**Comment by RobertoDebarba** [comment]
I did not understed that circus start taga-back, but I can see my problem now I solved it.
I write the solution here: #90   

Thanks a lot!

**Comment by bameda** [comment]
Great!! :smiley_cat:
