### ISSUE TITLE
Request : Search should consider values in custom fields/attributes as well

### ISSUE THREAD

**Issue by jwestbrook** [taigaio/taiga-back#597]
As a few people have mentioned, they track the url that the issue is on. The search module doesnt look at the custom attributes so we cant search by page to make other changes at the same time as other work.

Please consider this enhancement, thanks!

**Comment by superalex** [comment]
Thank you very much for your feedback @jwestbrook 

We had this existing enhancement request (https://tree.taiga.io/project/taiga/issue/3058), I'm closing this one and copying your comments there.

Regards!,
