### ISSUE TITLE
Support creating custom roles for Project management

### ISSUE THREAD

**Issue by mdelapenya** [taigaio/taiga-back#598]
It's possible to define story points to several roles: UX, Design, Front, Back

What happen if a team needs a different role, such as Mobile? Is it possible to create a new role, so that we can create tickets and add story points to that recently created role?

If it is already possible, how could I do it?

Thanks!

**Comment by Xaviju** [comment]
Yes, you can edit/delete/add new roles in the project Admin > Permissions > Add new roles

**Comment by mdelapenya** [comment]
Aw, it was always there. and did not see it... :)

Thanks for your quick response!

**Comment by kapoorabhish** [comment]
Is it possible to create a role that is visible in all projects, i.e. global role?

**Comment by superalex** [comment]
@kapoorabhish no, but the next release will include the possibility of creating a new project based on the configuration from another (roles, status, colors...)
