### ISSUE TITLE
[BUG] Can't create a project template while using admin account

### ISSUE THREAD

**Issue by MohamedEssamAdawy** [taigaio/taiga-back#60]
**Describe the bug**
Failed to create `Project template`, because we can't get  `ADMIN_AUTH_TOKEN`, while we are authenticated as admin.
Also, there is nothing in the documentation that refers to how to get the `ADMIN_AUTH_TOKEN`.

**How can we reproduce the behavior**
- Try to create a project template with an admin account.

**Comment by bameda** [comment]
You need to be a superadmin user in taiga, not just an admin in some project. The ADMIN_AUTH_TOKEN is the same token that is obtained by logging in to the app, just with a superadmin user.
