### ISSUE TITLE
Possible to use mysql?

### ISSUE THREAD

**Issue by siliconalchemy** [taigaio/taiga-back#620]
Is it possible to use a mysql django backend?  Is there anything specific to postgresql that taigo uses?
Mysql is a bit easier to use but crucially it has better supported cluster options like Galera (PXC, for example).  I've spent quite a bit of time trying to get taiga working on bdr for postgresql but it's a very poor substitute for the likes of PXC.

**Comment by niwinz** [comment]
Hi @siliconalchemy 

Short answer: No, it is not possible.

Large answer: MySQL maybe has better support for "clustering" but as database is very poor database and a lot of things that taiga backend uses together with postgresql will very very dificult to do with mysql (limited indexes, no partial indexes, no expresion based indexes, schemaless fields like json, atomic seequences, and a lot of other stuff that mysql just lacks.

A great summary that I try to say you can read in more detail here: http://grimoire.ca/mysql/choose-something-else

**Comment by siliconalchemy** [comment]
Lol well I wasn't looking to get into a religious discussion :)

I've no great love for mysql but I do have a great love for hot standby options that mature, supported clustering give you with mysql.  The postgresql options on the other hand look like a bad high school project.  I'll keep going with bdr and look at other options, perhaps I can contribute something back to this great project eventually with a doc for setting it up in a reliable clustered fashion.

**Comment by furai** [comment]
Are there any news on this front? Or mysql (mariadb) won't be ever supported?

**Comment by alexhermida** [comment]
@furai, one of the most critical constraints, is the use of JSON fields from the Django core. As far as I know, latest MySQL versions support JSONFields although Taiga migrations make use of some PostgreSQL dependencies. In the short-term, it isn't in the roadmap. 
If you have a particular case that you need to use it with MySQL maybe you could try it with the latest versions.
