### ISSUE TITLE
JSONField in Django 1.9

### ISSUE THREAD

**Issue by gam-phon** [taigaio/taiga-back#628]
Since you have upgraded to Django 1.9. Do you think it is a good time to change from django_pgjson, the third party library, to Django [JSONField](https://docs.djangoproject.com/es/1.9/ref/contrib/postgres/fields/#jsonfield) that supported by the core team.

What do you think the effect of changing would be?
Is there a need for data migration and how it would be?
No need for JsonField in taiga.base.fields, right?

What do you think?

**Comment by bameda** [comment]
Django JSONField work with PostgreSQL >= 9.4 and Taiga works with PostgreSQL >= 9.3. So we should force everyone to upgrade to 9.4. Ubuntu 14.04 de supported linux distro use 9.3 by default http://packages.ubuntu.com/trusty/database/#postgresql-9.3

But we want to use jsonb as soon as posible so we migrate to 9.4 when a LTS version of ubuntu suppot Postgresql >=9.4 by default.

**Comment by gam-phon** [comment]
Ubuntu 16.04 LTS expected to be released on [April 2016](https://wiki.ubuntu.com/Releases) and most probably will come with Postgres 9.5.

**Comment by bameda** [comment]
So in April we'll can to test Ubuntu 16.04, migrate taiga-script and taiga-vagrant to use it and use native Django JSONFields. Personally, I have really wanted to use jsonb to remove some hacks in taiga-back.

**Comment by bameda** [comment]
We'll migrate to JSONB in the next release (3.1)

**Comment by gam-phon** [comment]
@bameda Is there a pull request for this?

**Comment by bameda** [comment]
Umm a pull request and some commits to fix the migration from json to jsonb.

https://github.com/taigaio/taiga-back/pull/860
https://github.com/taigaio/taiga-back/commit/3d8f637e555ec7061e9d7582caf9c518050973d4
https://github.com/taigaio/taiga-back/commit/6d4a4cca9b32d45025077cb9ac4125670c992a31
