### ISSUE TITLE
user-stories can't be closed by webhooks

### ISSUE THREAD

**Issue by mrichar1** [taigaio/taiga-back#633]
If I link e.g. `gitlab` to a taiga kanban project, then the `test hook` button always returns an error, as do commit messages of the form: `TG-1 #closed` (Where #1 is a `user-story`). However I don't see this problem with webhooks changing `issues`.

Is this a bug? Or do `user-stories` accept a different set of slugs to issues? If so, is there a handy list somewhere?

Thanks!

**Comment by superalex** [comment]
Hello @mrichar1 

The user-stories status are different from the issues and customizable, you can check them on the admin area of your project  in attributes-> status

Regards!,
