### ISSUE TITLE
I install the backed use taiga-script.there is a error? what's wrong?

### ISSUE THREAD

**Issue by NiuXWolf** [taigaio/taiga-back#638]
![capture](https://cloud.githubusercontent.com/assets/8829072/13346264/fe461d26-dc9f-11e5-94e4-7254c561b79a.PNG)

**Comment by NiuXWolf** [comment]
need edit taiga-front/dist/conf.jon

**Comment by superalex** [comment]
Editing that file should affect taiga-back...
