### ISSUE TITLE
Events are not sent to Hip Chat

### ISSUE THREAD

**Issue by marcgadsdon** [taigaio/taiga-back#641]
Adding, Deleting or Updating e.g. a User Story does not fire an event to Hip Chat even though integration is correctly configured with Hip Chat and verified using the test button.

**To repeat:**
1. Prepare Hip Chat for integration and use the test feature in Hip Chat to confirm the end point works OK.
2. Using SaaS Taiga, create a project.
3. In project settings, configure the integration with Hip Chat making sure to enable all notifications etc
4. Press the test button - note that a message appears in the Hip Chat room
5. Add a User Story to the Backlog - note that no message appears in the Hip Chat room

**Expected outcome**
After step 5, I would expect to see a notification in Hip Chat

**Comment by superalex** [comment]
Hello @marcgadsdon 

I've just tests hip chat integration in tree.taiga.io and creating a user story in the backlog area is properly notified to hipchat, if it's still failing could you please write to support@taiga.io indacating your project url?

**Comment by marcgadsdon** [comment]
Hello @superalex 

I can confirm it's working now. It started working shortly after my first post. Sorry, I should have updated this issue.

So the issue definitely existed, but communication to Hip Chat was working due to the test on step 1. I won't close this in case you want to keep it open to track a possible issue.

Thanks for a **really** fantastic project management system :-)

**Comment by superalex** [comment]
You are welcome @marcgadsdon 

Thank you very much for reporting the issue, we will try to reproduce it but at the moment we still couldn't detect any failure on asynchronous tasks in Taiga (the test button work in synchronous mode).

Regards!,
