### ISSUE TITLE
can taiga send updates on telegram messenger ?

### ISSUE THREAD

**Issue by ddonindia** [taigaio/taiga-back#653]
Hi Devs,

Just like email update on watched items is it possible to send update messages through telegram messenger or similar services ?
If someone can guide me I can code it.

Regards

**Comment by superalex** [comment]
Hello @ddonindia I think it could be done and should work in a similar way to https://github.com/taigaio/taiga-contrib-slack or https://github.com/taigaio/taiga-contrib-hipchat

**Comment by mikeroneer** [comment]
Hi @ddonindia, check out taigagram - an easy to use taiga-integration for telegram.
http://taigagram.mikerocode.com/
http://telegram.me/taigagrambot
