### ISSUE TITLE
Max upload size

### ISSUE THREAD

**Issue by br0nsky** [taigaio/taiga-back#657]
Hi,

First of all, thanks for this amazing app, it's really cool ;)

Here's my problem : One of my developers tried to upload a file over 50M so I changed the client max body size in the nginx vhost configuration of Taiga but it still doesn't work. The developer can now upload his file (Taiga says it's OK) but fails to import it in its project.  So I was wondering if there's something else to do to allow uploads of over 50M files or is 50M the max limit ? 

I noticed in the gunicorn logs that the worker was timing out while the upload: [CRITICAL] WORKER TIMEOUT (pid:3612)

Thanks in advance for your help !

**Comment by superalex** [comment]
Hello @br0nsky 

Thank you very much for the feedback!

Could you try importing manually the file from the server to check if there is anything wrong with the file?, something like: 

`python manage.py load_dump  --overwrite PROJECT.json OWNER_EMAIL`
