### ISSUE TITLE
Getting 'false' as value for 'generated_user_stories' for all the issues

### ISSUE THREAD

**Issue by david-caro** [taigaio/taiga-back#663]
For some reason, it started to show 'false' as the value for that field when requesting issue info, that led to duplicated (and triplicated) user stories creation, an example of the result of a GET to /issues:

    {
    "is_voter"=>false,
    "total_voters"=>0,
    "is_watcher"=>true,
    "total_watchers"=>1,
    "watchers"=>[116598],
    "tags"=>nil,
    "external_reference"=>["github", "https://github.com/lago-project/lago/issues/159"],
    "is_closed"=>false,
    "comment"=>"",
    "generated_user_stories"=>false,
    "blocked_note_html"=>"",
    "status_extra_info"=>{
        "name"=>"New",
        "color"=>"#999999"
    },
    "assigned_to_extra_info"=>nil,
    "owner_extra_info"=>{
        "username"=>"david-caro",
        "full_name_display"=>"David Caro",
        "photo"=>"//www.gravatar.com/avatar/13639b57dd73e1d49da28929841b6516?default=https%3A%2F%2Fstatic.taiga.io%2Fimg%2Fuser-noimage.png&size=80",
        "big_photo"=>"//www.gravatar.com/avatar/13639b57dd73e1d49da28929841b6516?default=https%3A%2F%2Fstatic.taiga.io%2Fimg%2Fuser-noimage.png&size=300",
        "is_active"=>true
    },
    "id"=>231548,
    "version"=>3,
    "is_blocked"=>false,
    "blocked_note"=>"",
    "ref"=>1,
    "owner"=>116598,
    "status"=>799811,
    "severity"=>570050,
    "priority"=>343208,
    "type"=>344677,
    "milestone"=>nil,
    "project"=>114180,
    "created_date"=>"2016-03-07T12:45:21+0000",
    "modified_date"=>"2016-03-15T17:24:48+0000",
    "finished_date"=>nil,
    "subject"=>"Add a way to export/import a full prefix",
    "assigned_to"=>nil
    }

**Comment by superalex** [comment]
Hello @david-caro 

It's very strange I'm checking (tree.taiga.io) with the last stable release and that field is correct, is this happening in your own instance?

**Comment by david-caro** [comment]
Nop, I was using the public tree.taiga.io. It was showing ok before that, but at some point it stopped showing empty lists or lists with elements, and started showing that false value.

**Comment by superalex** [comment]
Could you please write to support@taiga.io indicating what's the failing user story so we can check what's happening?

**Comment by david-caro** [comment]
done!
