### ISSUE TITLE
[api] Undocumented option 'generated_from_issue' for the user story creation endpoint

### ISSUE THREAD

**Issue by david-caro** [taigaio/taiga-back#664]

**Comment by bameda** [comment]
Is this bug for [taigaio/taiga-doc](https://github.com/taigaio/taiga-doc)?

**Comment by david-caro** [comment]
yep, sorry, still getting to know which repos are there

**Comment by david-caro** [comment]
Moved to https://github.com/taigaio/taiga-doc/issues/119

**Comment by bameda** [comment]
Thanks @david-caro for report this.
