### ISSUE TITLE
Add item url in webhook

### ISSUE THREAD

**Issue by mikaoelitiana** [taigaio/taiga-back#667]
We are building a Taiga webhook to reference issues, tasks and US as gitlab issues and we would like to add a url to the taiga item directly in the issue body. For that, we need to get the item url from the webhook or a permalink syntax we can build from reference and project id (something like `http://taiga.example.com?ref=X&type=issue&project=Y`)
Thanks

**Comment by superalex** [comment]
Thanks for the suggestion @mikaoelitiana we had an existing enhancement request for this one (https://tree.taiga.io/project/taiga/issue/3755), I've just copied your comments.
