### ISSUE TITLE
Change issues state when related user story changes state

### ISSUE THREAD

**Issue by david-caro** [taigaio/taiga-back#672]
For example, when moving a user story in the kanban board to 'done' or 'archive' the issues bound to it should move to closed

**Comment by bameda** [comment]
We have an enhancement to define custom workflows.

Thanks for your feedback

**Comment by david-caro** [comment]
I is already released? Does it have a bug/rfe I can watch?

**Comment by bameda** [comment]
https://tree.taiga.io/project/taiga/issue/3281

and this is your issue: https://tree.taiga.io/project/taiga/issue/3993
