### ISSUE TITLE
Close taiga issue when github issue is closed

### ISSUE THREAD

**Issue by david-caro** [taigaio/taiga-back#673]

**Comment by bameda** [comment]
Right  now github integration is one-way, we have a story to implement two-way integration in the future.

https://tree.taiga.io/project/taiga/us/1516?kanban-status=27

Thanks for your feedback

**Comment by david-caro** [comment]
I know, the flow I'm requesting is from github->taiga. When closing an issue on github, then close it on taiga to (right now it remains open)

**Comment by bameda** [comment]
Yes, the story talk about this too

![image](https://cloud.githubusercontent.com/assets/877218/13920791/10d4042a-ef75-11e5-8aea-a8506dbdafec.png)


but it is now so simple because someone have more than one close status in taiga so you have to match every status in github with one status in Taiga.

**Comment by david-caro** [comment]
So the issue is not that it should be bidirectional, but that it has not yet been implemented right? (as the current unidirectional sync is already github->taiga)

**Comment by bameda** [comment]
Yes, right now you only can
- create new issues from github to taiga.
- crete new comments from github to taiga.
