### ISSUE TITLE
ASCII encoding on Pytho 3.4

### ISSUE THREAD

**Issue by vitak** [taigaio/taiga-back#675]
Hi all,
I have problem with this error message, only when i want to add new member with special chars in name to project.
Every answer to this message says i have to run taiga under 3.4 which i have(see in message).
I thing in Python 3.4 is no ecoding called 'ASCII' right? i recursivly search all /hom/taiga folder for string 'ascii' a iam not able find and useful results.

Error Message:
UnicodeEncodeError at /api/v1/memberships/bulk_create
'ascii' codec can't encode character '\xfd' in position 486: ordinal not in range(128)
Request Method:	POST
Request URL:	http://dev.netlion.cz:8000/api/v1/memberships/bulk_create
Django Version:	1.8.9
Exception Type:	UnicodeEncodeError
Exception Value:	
'ascii' codec can't encode character '\xfd' in position 486: ordinal not in range(128)
Exception Location:	/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/mail/backends/console.py in write_message, line 23
Python Executable:	/home/taiga/.virtualenvs/taiga/bin/python3.4
Python Version:	3.4.2
Python Path:	
['/home/taiga/taiga-back',
 '/home/taiga/taiga-back',
 '/home/taiga/.virtualenvs/taiga/bin',
 '/home/taiga/.local/lib/python3.4/site-packages',
 '/home/taiga/.virtualenvs/taiga/lib/python3.4',
 '/home/taiga/.virtualenvs/taiga/lib/python3.4/plat-x86_64-linux-gnu',
 '/home/taiga/.virtualenvs/taiga/lib/python3.4/lib-dynload',
 '/usr/lib/python3.4',
 '/usr/lib/python3.4/plat-x86_64-linux-gnu',
 '/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages',
 '/home/taiga/taiga-back']
Server time:	Sun, 27 Mar 2016 18:22:04 +0000

I search answer now third day. Iam greatful for any answers. Thank you

**Comment by superalex** [comment]
Hello @vitak 

This kind of ascii encoding errors can also be related to the utf-8 locale support of your machine, could you check if your machine and user have utf-8 locale support?

In https://github.com/taigaio/taiga-back/issues/298 a user solved it by adding: 

```bash
export LANG=en_US.UTF-8
export LC_TYPE=en_US.UTF-8
```
in the taiga user `.bashrc` fixed the issue.

Regards!,

**Comment by vitak** [comment]
Hi,
i successfully fixed this error myself.
I add line:
`msg_data = msg_data.encode('utf-8')`
to file: /home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/djang                                                                                                                                                             o/core/mail/backends/console.py

I know this is very dirty fix, but its working.
Thank you

`
 def write_message(self, message):
        msg = message.message()
        msg_data = msg.as_bytes()
        if six.PY3:
            charset = msg.get_charset().get_output_charset() if msg.get_charset() else 'utf-8'
            msg_data = msg_data.decode(charset)
        msg_data = msg_data.encode('utf-8')
        self.stream.write('%s\n' % msg_data)
        self.stream.write('-' * 79)
        self.stream.write('\n')
`

**Comment by superalex** [comment]
Regards!,

**Comment by lifenautjoe** [comment]
I'm experiencing the same issue. @merglv is a temp fix. 

The console email backend produces this error, so if the application is configured to smtp it will never show up.

This has been fixed on recent django versions.

**Comment by lpilz** [comment]
@superalex  I don't think this issue is closed, I just encountered the same problem. It would be great if someone could merge an updated requirements.txt with a new django version (1.11.29 is really old) into the repo.
