### ISSUE TITLE
Creating a task fails if sending the email fails

### ISSUE THREAD

**Issue by rmmcnulty9** [taigaio/taiga-back#677]
My email server was down for a period today and the taiga backend failed to create any tasks, just because the code that sends emails was raised an exception.

I think a better behavior would be to create the task and display an error message. Currently, the server responds with 500 status and something like `SMTPRecipientsRefused at /api/v1/userstories
{'some.email@example.com': (451, b'4.3.5 Server configuration problem')}` and nothing is displayed in the UI and no task was created.

I assume this happens for other resources like issues.

**Comment by superalex** [comment]
Hello @rmmcnulty9 

If Taiga is working in synchronous mode and the email server fails the action trying to send the email will also fail (save, delete...)

You can make Taiga notifications work in asynchronous mode if you set "CHANGE_NOTIFICATIONS_MIN_INTERVAL" to a value different than 0, this setting assumes you are manually calling the send_notifications command "python manage.py send_notifications" (the easiest way should be doing it from a cron job)

Regards!,

**Comment by melizeche** [comment]
I think this issue should be re opened.
The creation of the task is more important than the notification(also is not catching the exception)
For example, in my case the error is: 
`smtplib.SMTPDataError: (550, b'5.4.6 Mail rate exceeded limit')`
That's a temporal issue with my external email provider, it shouldn't prevent the creation of the task IMHO

**Comment by Pitel** [comment]
Same problem here, and exactly same thinking: sending simple notification email should definitely not prevent any manipulation of US/task/whatever. Pls reopen and fix!
