### ISSUE TITLE
Belong to Multiple Roles

### ISSUE THREAD

**Issue by smichel17** [taigaio/taiga-back#681]
I'd like to be able to assign team members to multiple roles. Someone might do both UX and development work, and it's a really weird workflow to create a separate role, "UX-developer" just so they can get the combined permissions of both roles.

Here's a previous issue I found on the subject: https://tree.taiga.io/project/taiga/issue/803

**Comment by bameda** [comment]
Right now multiple roles don't have a lot of sense because you can't define or manage workflows, so roles only are useful to manage basic permission over objects (create permissions profiles).

In your case, an UX and a Developer have the same permissions CRUD over all object types (issues, tasks, user stories,...) or in the worst case one role contains other.

**Comment by smichel17** [comment]
Okay, fair. In retrospect this was an issue I'm anticipating, not one I've run into -- closing this, will re-open if I actually run into it.

**Comment by bameda** [comment]
My comment is only to explain how roles work right now.

Nonetheless we register your suggestion as an enhancement https://tree.taiga.io/project/taiga/issue/4034 to see if can earn votes to be included in our roadmap.

Thank you very much @smichel17

**Comment by smichel17** [comment]
@bameda I haven't fully thought this through yet, but here is a related suggestion: only allow a person to estimate US points for roles they are assigned to. It's not someone else's job to tell me how much work a certain thing is going to take.

If you did that right now, it'd be bad for people who fill multiple roles, but if the original enhancement is implemented, it'd be a nice addition.

Side note: I'm part of an organization using Holacracy, so people regularly fill multiple roles; it'd be nice if Taiga's structure matched our governance structure, even if there's no functional benefit (just clarity).

**Comment by bameda** [comment]
totally agree, even in my companies (kaleidos.net, taiga.io) holacracy  is in our genes too.

**Comment by hgomersall** [comment]
I'd like to echo this point. Each individual on our team has multiple roles.

**Comment by localpcguy** [comment]
If roles are going to exist, users have to be able to fill multiple roles. Too many startups or even larger companies have people that wear multiple hates and won't fit into a cookie cutter set of roles.
