### ISSUE TITLE
unable to login: connection refused/bad gateway

### ISSUE THREAD

**Issue by Frutal1ty** [taigaio/taiga-back#683]
I'm using taiga in docker from a DockerHub image (https://hub.docker.com/r/htdvisser/taiga-back/) the problem was that taiga was not at the last version, and I need the last version to import some projects from another taiga.
I've done this exact steps to upgrade http://taigaio.github.io/taiga-doc/dist/upgrades.html
I've initialized the users & projects & roles
`circusctl start taiga` is done
my conf.json is:
`
{
  "api": "http://XXX.XXX.XXX.XXX:8000/api/v1/",

  "eventsUrl": null,

  "debug": false,

  "publicRegisterEnabled": true,

  "feedbackEnabled": true,

  "privacyPolicyUrl": null,

  "termsOfServiceUrl": null,

  "maxUploadFileSize": null,

  "gitHubClientId": null,

  "contribPlugins": [ ]
}

`
and its located at .../taiga/taiga-front/dist/ out of the folder js
With port 8000 in the api I get ERR_CONNECTION_REFUSED if I omit the port in the api (XXX.XXX.XXX.XXX/api/v1/) the error becomes 502 Bad Gateway.
I can't access to :8000/api/v1 neither from the localhost.
I know is a very common issue but I've spend some hour trying solutions to similar issues and nothing works.

**Comment by superalex** [comment]
Hello @Frutal1ty 

The ERR_CONNECTION_REFUSED means the port 8000 isn't exposed, are you sure that port was exposed before you updated?, what was your previous conf.json file?.

You could check the nginx logs to see if there is any error when you try accessing to XXX.XXX.XXX.XXX/api/v1/

Did you also post about this on the docker site?

**Comment by Frutal1ty** [comment]
Solved months ago... I'll post my solution just in case someone has the same problem and it's still stuck.

**Check if all the needed ports are binded between the host and the container.**

My mistake was not binding port 8000 from the host to the container, so the backend-server was unreachable.

Thanks to @superalex for the answer.

**Comment by superalex** [comment]
You are welcome @Frutal1ty
