### ISSUE TITLE
Something wrong with the server

### ISSUE THREAD

**Issue by velis74** [taigaio/taiga-back#684]
I don't have permission to my own project. My dashboard says I have no projects. Some links lead to pages that have serious content issues.
Have you been hacked?

**Comment by superalex** [comment]
Hello @velis74. I assume you are talking about our instance (tree.taiga.io), we have been updating the server, could you check if everything is working ok?

**Comment by velis74** [comment]
Yes, now it's OK

**Comment by bameda** [comment]
Coool
