### ISSUE TITLE
Possibility for using Sparkpost as smtp service

### ISSUE THREAD

**Issue by florisvanwoudenberg** [taigaio/taiga-back#686]
Sparkpost is a good alternative for Mandrill, since Mandrill is changing its terms and requires a paid Mailchimp subscription.
But when I configure the smtp for Sparkpost, the mail are not send nor visible in Sparkpost.

**Comment by superalex** [comment]
Hello @florisvanwoudenberg 

Have you got any more info about what's happening?, is Sparkpost smtp server missing something from Taiga?

**Comment by florisvanwoudenberg** [comment]
Ah, my fault. I removed EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' yesterday because of the update issue.
Issue closed, works fine with Sparkpost

**Comment by superalex** [comment]
Great! :)

**Comment by mlamarque** [comment]
Hello @florisvanwoudenberg 
Can you add your sparkpost configuration in taiga ? since the update email doesn't send anymore.
