### ISSUE TITLE
How can I forbid people see my team public project? #25

### ISSUE THREAD

**Issue by xfight0** [taigaio/taiga-back#688]
Dear developers,
I installed taiga on my team server in public network. I want to make projects public to all teammate.
But the default permission allow anyone see our projects  as long as anyone visit our website.
I changed the file `taiga-back/taiga/permissions/permission.py`:
```
ANON_PERMISSIONS = [
]

USER_PERMISSIONS = [
    ('view_project', _('View project')),
    ('view_milestones', _('View milestones')),
    ('view_us', _('View user stories')),
    ('view_tasks', _('View tasks')),
    ('view_issues', _('View issues')),
    ('view_wiki_pages', _('View wiki pages')),
    ('view_wiki_links', _('View wiki links')),
    ('view_project', _('View project')),
    ('view_milestones', _('View milestones')),
    ('view_us', _('View user stories')),
    ('view_issues', _('View issues')),
    ('view_tasks', _('View tasks')),
    ('view_wiki_pages', _('View wiki pages')),
    ('view_wiki_links', _('View wiki links')),
    ('request_membership', _('Request membership')),
    ('add_us_to_project', _('Add user story to project')),
    ('add_comments_to_us', _('Add comments to user stories')),
    ('add_comments_to_task', _('Add comments to tasks')),
    ('add_issue', _('Add issues')),
    ('add_comments_to_issue', _('Add comments to issues')),
    ('add_wiki_page', _('Add wiki page')),
    ('modify_wiki_page', _('Modify wiki page')),
    ('add_wiki_link', _('Add wiki link')),
    ('modify_wiki_link', _('Modify wiki link')),
]
```
then I killed runserver progress and restart it and nginx.
But  It does not seem to take effect.
Can you help me? thanks.

**Comment by bameda** [comment]
This change in the code has no sense because apply only in new projects.

You have to set current projects as private in the project detail admin panel and send invitations to your teammate in the members admin panel.

**Comment by xfight0** [comment]
Hello @bameda ,is there any way to restrict that people who login in has the right to see  the discover page?

**Comment by bameda** [comment]
No. but private projects aren't discoverable
