### ISSUE TITLE
Taiga not running on 8001 

### ISSUE THREAD

**Issue by fatagun** [taigaio/taiga-back#697]
Hello, 

I am unable to connect to port 8001. Getting the error below. 

2016/04/11 16:53:14 [error] 30460#30460: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 172.25.26.13, server: _, request: "GET /api/v1/projects?discover_mode=true&is_featured=true HTTP/1.1", upstream: "http://127.0.0.1:8001/api/v1/projects?discover_mode=true&is_featured=true", host: "taiga.foo.gov", referrer: "http://taiga.foo.gov/discover"

my hostname is `taiga.foo.gov` below is the nginx conf.

    location /api {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://127.0.0.1:8001/api;
        proxy_redirect off;
    }
Below is app-loader.js

  window.taigaConfig = {
    "api": "http://taiga.foo.gov:8000/api/v1/",
    "eventsUrl": null,
    "eventsMaxMissedHeartbeats": 5,
    "eventsHeartbeatIntervalTime": 60000,
    "debug": true,
    "defaultLanguage": "en",
    "themes": ["taiga", "material-design", "high-contrast"],
    "defaultTheme": "taiga",
    "publicRegisterEnabled": true,
    "feedbackEnabled": true,
    "privacyPolicyUrl": null,
    "termsOfServiceUrl": null,
    "maxUploadFileSize": null,
    "contribPlugins": []
  };

I am unable to connect to API.

Can you please show some pointer on how to debug or what might be the problem. 

Thanks.

**Comment by fatagun** [comment]
Even though I have install circus. `Failed to start circus.service: Unit circus.service failed to load: No such file or directory.` I am receiving this error. I am running on the suggest ubuntu version.

**Comment by superalex** [comment]
It sounds like circus isn't launching properly taiga-back (I assume you configured circus for serving taiga-back on port 8001), did you check the taiga user logs folder?, what installation method did you follow?.

Regards,

**Comment by fatagun** [comment]
I used scripts method. Indeed circus is not running. 
`# service circus start`
gives me following:
`Failed to restart circus.service: Unit circus.service failed to load: No such file or directory.`
I am not able to start circus, even in the circus installation directory. 
```
./circusctl start
Times out because of the following....
```
In the logs folder there is only logs for nginx. Which the error reported above. 

Thanks.

**Comment by superalex** [comment]
Probably something have failed during the installation, could you try executing the install script again?

**Comment by fatagun** [comment]
sure. I will. I tried twice at my vmware instances both worked like a charm with scripts. However, with the production server, for example: postgres wasnt in the repo.

Here is the output of the script again

```
Trying import local.py settings...

0 static files copied to '/home/taiga/taiga-back/static', 945 unmodified.
Failed to restart circus.service: Unit circus.service failed to load: No such file or directory.
~ ~/taiga-scripts
~/taiga-scripts
Requirement already satisfied (use --upgrade to upgrade): circus in /home/taiga/.local/lib/python2.7/site-packages
Requirement already satisfied (use --upgrade to upgrade): iowait in /home/taiga/.local/lib/python2.7/site-packages (from circus)
Requirement already satisfied (use --upgrade to upgrade): psutil in /home/taiga/.local/lib/python2.7/site-packages (from circus)
Requirement already satisfied (use --upgrade to upgrade): pyzmq>=13.1.0 in /home/taiga/.local/lib/python2.7/site-packages (from circus)
Requirement already satisfied (use --upgrade to upgrade): tornado>=3.0 in /home/taiga/.local/lib/python2.7/site-packages (from circus)
Requirement already satisfied (use --upgrade to upgrade): backports.ssl-match-hostname in /home/taiga/.local/lib/python2.7/site-packages (from tornado>=3.0->circus)
Requirement already satisfied (use --upgrade to upgrade): singledispatch in /home/taiga/.local/lib/python2.7/site-packages (from tornado>=3.0->circus)
Requirement already satisfied (use --upgrade to upgrade): certifi in /home/taiga/.local/lib/python2.7/site-packages (from tornado>=3.0->circus)
Requirement already satisfied (use --upgrade to upgrade): backports-abc>=0.4 in /home/taiga/.local/lib/python2.7/site-packages (from tornado>=3.0->circus)
Cleaning up...
Failed to start circus.service: Unit circus.service failed to load: No such file or directory.
touch: `touch' `/home/taiga/.setup/circus' failed: No such file or directory
```

What do you recommend?

**Comment by superalex** [comment]
postgres wasn't in the repo?, that's very very strange, are you sure it's an ubuntu 14.04 instance?

**Comment by fatagun** [comment]
Bummer. Turns out it is 
```
 taiga@taiga:~/taiga-scripts$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 15.10
Release:	15.10
Codename:	wily
```
I asked the system team for 14.04 and trusted them. 

I will have 14.04 installed. My question is the hostname and username? What should be the hostname and username? I want to run the app on taiga.foo.gov

Thanks.

**Comment by superalex** [comment]
The hostname for the system is irrelevant and the username assumed in all our installs is taiga so it should be easier if using that user.

After the installation you should update your conf.json file for taiga-front and your local.py for taiga-back so it fits  taiga.foo.gov
