### ISSUE TITLE
Large File Attachment Memory Issues on Self-Hosted Instance

### ISSUE THREAD

**Issue by ClashTheBunny** [taigaio/taiga-back#708]
I'm just playing around with Taiga's wiki, so I dragged a random file into the text area.  It was a 600MB WAV file (uncompressed audio).  The file quickly uploaded, but then Taiga became unresponsive.  The responses for projects and by_slug both took 6.3 minutes to complete and the memory on my machine ballooned to over 1.5GB and started swapping.

I don't have an exact reason for this happening, but it took a few iterations of the 6.3 minute waits in order to get the file deleted; the load page took that long, and then the delete file dialog popped up immediately and then after the delete click, it took a while again.

**Comment by superalex** [comment]
Hello @ClashTheBunny 

I assume this happening on your own Taiga instance, isn't it?, did it happen only with wav files or also with other extensions?, did you try to upload again the file in other page in case it was a problem from your filesystem just in that moment?
