### ISSUE TITLE
Add comment to Issue using API

### ISSUE THREAD

**Issue by pawaryogesh1989** [taigaio/taiga-back#712]
How can I add comment to an Issue using TAIGA API?

I did not find any documentation/information regarding it in the API documentation. (https://taigaio.github.io/taiga-doc/dist/api.html)

Can you please let me know whether it is possible? If yes then please can you provide an example?

Thanks

**Comment by bameda** [comment]
Is like if you update an issue but you have to add the "comment" in the
data.

curl -X PATCH \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer ${AUTH_TOKEN}" \
  -d '{
          "subject": "Patching subject",
          "version": "1",
          "comment": "I update the subject"
      }' \
  https://api.taiga.io/api/v1/issues/1



curl -X PATCH \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer ${AUTH_TOKEN}" \
  -d '{
          "version": "2",
          "comment": "only a comment"
      }' \
  https://api.taiga.io/api/v1/issues/1

On Wed, May 4, 2016 at 1:18 PM, Yogesh <notifications@github.com> wrote:

> How can I add comment to an Issue using TAIGA API?
>
> I did not find any documentation/information regarding it in the API
> documentation. (https://taigaio.github.io/taiga-doc/dist/api.html)
>
> Can you please let me know whether it is possible? If yes then please can
> you provide an example?
>
> Thanks
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/taigaio/taiga-back/issues/712>
>



-- 

---


*David Barragán Merino*
* Engineer *
<david.barragan@kaleidos.net>
david.barragan@kaleidos.net  | Tel: (+34) 913562995
www.kaleidos.net/FFF8E7

**Comment by pawaryogesh1989** [comment]
Hi,

Tried your solution and it does not work. It gives the following error.

stdClass Object
(
    [_error_type] => taiga.base.exceptions.PermissionDenied
    [_error_message] => You do not have permission to perform this action.
)

Note:- I am doing all the API calls with admin account and the user is the project Owner.

Thanks

**Comment by superalex** [comment]
Hello @pawaryogesh1989 

Did you try using CURL and not using your own code?, we should discard where the error is.

Regards,

**Comment by pawaryogesh1989** [comment]
Yes, I have tried using a PHP SDK and every thing works fine excepts the comment functionality.

Following is the PHP code used by me.

$Taiga_RestClient->request('PATCH', 'issues/886', array('comment' => "This is comment", "version" => 1)))

Thanks

**Comment by superalex** [comment]
But it's not a CURL command, could you please try first the CURL command to check if you receive the same problem (taiga-php-sdk is not supported by the Taiga development team)

**Comment by pawaryogesh1989** [comment]
Yes I understand your concern. But this SDK also uses CURL as you see there is a function call which uses CURL from the function defined in the classes.

You can see in the attached file CURL functions are used.

Thanks
[AbstractCurl.zip](https://github.com/taigaio/taiga-back/files/250025/AbstractCurl.zip)

**Comment by superalex** [comment]
I know, but please, try the CURL and if failing paste here the CURL command you are using so we can help you to fix the issue ;)

**Comment by pawaryogesh1989** [comment]
Yes we had used CURL commands only. we had created functions for CURL calls which we have attached in the previous thread. It doesn't matter in PHP if you directly execute CURL command or execute it using function calls.

All information related to CURL commands that we have used and their sequence it given in the attached file in the previous comment.

Thanks

**Comment by superalex** [comment]
In that file there is php code, please, first try to use the CURL command suggested by @bameda, that way you could know if the problem is in the Taiga API or in the php side

**Comment by pawaryogesh1989** [comment]
Hi @superalex 

Please see the attached image. We had executed curl request and still we are getting the same error.

Thanks.
![taiga_error](https://cloud.githubusercontent.com/assets/3761152/15042631/599fbfa0-12e3-11e6-902a-47bad4f6b670.png)

**Comment by superalex** [comment]
I'm missing a B at the beginning of the Authorization header

**Comment by pawaryogesh1989** [comment]
Hi @superalex 

The B is present there in the field. As the string is long B is hidden in the text field.

Thanks

**Comment by superalex** [comment]
I can confirm that Taiga endpoint works correctly. I just did:

```
curl -X PATCH \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" \
  -d '{
          "version": "1",
          "comment": "I just add a comment"
      }' \
  https://api.taiga.io/api/v1/issues/293976
```

And you can see the result in https://tree.taiga.io/project/alejandroalonso-test-1/issue/2

Just one question, did you try doing a GET request to the API url?, is it possible that you aren't really using the issue ID and using the REF instead?

**Comment by pawaryogesh1989** [comment]
Hi @superalex 

Sorry, yes I was using reference ID instead of issue ID. I thought the ID present in the URL is Issue ID.

Now everything is working fine. Thank you for your help and sorry for the inconvenience caused.

Thanks

**Comment by superalex** [comment]
You are welcome ;)

**Comment by pawaryogesh1989** [comment]
Hi @superalex 

Thanks for your help.

Just one 2 last questions

1) How can i add multiple comments to a issue but every comment must have different user?

2) While adding issue through API Project Owner is set as the issue creator, how can I change the creator of the issue. Can you let me know the field name?

Thanks

**Comment by superalex** [comment]
1) You have to do different PATCH requests with different authentication tokens for each user
2) You can't, the owner/creator is assigned to the user doing the request (you could use different authentication tokens for different users), Taiga must trace all the info about the elements so that info is auto generated

**Comment by pawaryogesh1989** [comment]
Hi @superalex 

Thanks for the information. Really Appreciate it!

**Comment by superalex** [comment]
You are welcome! ;)

**Comment by bameda** [comment]
You can do what you want, but you should use other endpoint:
https://api.taiga.io/api/v1/importer/issue but this endpoint is not
documented (I don't know why). This endpoint is usefull to import data from
other system, for example to import data from redmine to Taiga.

https://github.com/taigaio/taiga-importer-api-client
https://github.com/taigaio/taiga-java-importer-example
http://taigaio.github.io/taiga-importer-api-client/
https://github.com/taigaio/redmine-migrator

On Fri, May 6, 2016 at 8:37 AM, Alejandro <notifications@github.com> wrote:

> You are welcome! ;)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/taigaio/taiga-back/issues/712#issuecomment-217358807>
>



-- 

---


*David Barragán Merino*
* Engineer *
<david.barragan@kaleidos.net>
david.barragan@kaleidos.net  | Tel: (+34) 913562995
www.kaleidos.net/FFF8E7

**Comment by pawaryogesh1989** [comment]
@bameda 

Do you have any importer api client available for PHP? If yes can you please provide link?

Thanks

**Comment by bameda** [comment]
No, sorry :disappointed:  
We don't use PHP.

**Comment by pawaryogesh1989** [comment]
Oh.. NP. :smile:

**Comment by bameda** [comment]
But the importer works like the Taiga inporter so if you see an example of an exported taiga project (js file) you can know how this endpoint works. For example, for issues a valid body will be 

```
{
    "owner": "support+proberts@taiga.io",
    "status": "In progress",
    "assigned_to": "support+imontoya@taiga.io",
    "priority": "High",
    "severity": "Important",
    "type": "Bug",
    "milestone": null,
    "votes": [],
    "modified_date": "2015-06-17T21:07:51+0000",
    "tags": "[\"fencing\", \"feint\", \"challenge\", \"you fight like a dairy farmer\"]",
    "version": 17,
    "is_blocked": false,
    "blocked_note": "",
    "ref": 10,
    "created_date": "2015-06-17T16:28:21+0000",
    "finished_date": null,
    "subject": "Dropping the sword when left-handed",
    "description": "It appears that more than 50% of the time, switching from right to left hand will result in the sword hitting the ground. It might be terrible under extreme circumstances or edge use cases (no pun intended).",
    "external_reference": null,
    "watchers": [
        "support+proberts@taiga.io"
    ],
    "attachments": [],
    "custom_attributes_values": {},
    "history": [
        {
            "user": [
                "support+proberts@taiga.io",
                "The Man In Black"
            ],
            "diff": {},
            "snapshot": null,
            "values": {},
            "comment": "And what is that?",
            "delete_comment_date": null,
            "delete_comment_user": [],
            "created_at": "2015-06-17T21:01:52+0000",
            "type": 1,
            "is_hidden": false,
            "is_snapshot": false
        },
        {
            "user": [
                "support+imontoya@taiga.io",
                "\u00ed\u00f1igo Montoya"
            ],
            "diff": {},
            "snapshot": null,
            "values": {},
            "comment": "I am not left-handed.",
            "delete_comment_date": null,
            "delete_comment_user": [],
            "created_at": "2015-06-17T21:02:59+0000",
            "type": 1,
            "is_hidden": false,
            "is_snapshot": false
        },
        {
            "user": [
                "support+proberts@taiga.io",
                "The Man In Black"
            ],
            "diff": {},
            "snapshot": null,
            "values": {},
            "comment": "You're amazing!",
            "delete_comment_date": null,
            "delete_comment_user": [],
            "created_at": "2015-06-17T21:04:07+0000",
            "type": 1,
            "is_hidden": false,
            "is_snapshot": false
        }
    ]
}
```

**Comment by pawaryogesh1989** [comment]
@bameda 

Thanks for the information.

we have been able to create a PHP API client to import issues and project and all data related to project by referring your Python API and its documentation.

Till now, Projects, Issues, comments and user stories are being imported from other systems to TAIGA using the PHP API that we built.

Thanks

**Comment by bameda** [comment]
Cool you can do all that you want with the API but maybe we'll can improve the documentation because there are some secctions a little confusing.

**Comment by pawaryogesh1989** [comment]
@bameda 

Yes in the documentation some sections are confusing and some links are referring to same old links instead of their own.

By the way is there any method to check if a issue already exists in TAIGA while adding it through API?

Thanks

**Comment by bameda** [comment]
ummmm, maybe filtering issues by subject /api/v1/issues?subject=blablabla

**Comment by pawaryogesh1989** [comment]
ok, will try.

Thanks

**Comment by pawaryogesh1989** [comment]
@bameda , @superalex 

Can't we pass user_id  while adding comment to the issue (curl patch request) like the JIRA API?

Thanks

**Comment by bameda** [comment]
No for a security reason: you could comment as another user. 

For that we create other endpoint to import data.

**Comment by pawaryogesh1989** [comment]
@bameda 

ok. thanks for the information.

**Comment by pawaryogesh1989** [comment]
@bameda 

Regarding "The only mehtod to do, comment in the name of other person, is using the importers endpoints"

Can you please give an example here or an link to example?

Thanks

**Comment by bameda** [comment]
https://github.com/taigaio/taiga-back/issues/719#issuecomment-218101156

_Please, use only one issue, The team recive your messages 8 times (2 github issues, 2 taiga.io sincronized issues, 4 emails)_

**Comment by pawaryogesh1989** [comment]
@bameda 

ok.
