### ISSUE TITLE
Add comment to Issue using API

### ISSUE THREAD

**Issue by pawaryogesh1989** [taigaio/taiga-back#715]
As the previous issue is closed I am opening a new one.

With reference to issue #712 

Tried your solution and it does not work. It gives the following error.

stdClass Object
(
[_error_type] => taiga.base.exceptions.PermissionDenied
[_error_message] => You do not have permission to perform this action.
)

Note:- I am doing all the API calls with admin account and the user is the project Owner.

Thanks

**Comment by superalex** [comment]
I think it's better keeping the conversation in the other thread.
