### ISSUE TITLE
Changing user role fails

### ISSUE THREAD

**Issue by fatagun** [taigaio/taiga-back#718]
Hello,

I have an on premise install and when I change **a member to admin** in a project, the system fails. I dont see anything in the logs, but subsequent requests fails. Then i wait for a while until the system comes back up. 

Why is this happening?

**Comment by ShalbafZadeh** [comment]
is everything ok in your app logs ?
could you please put taiga app log of when you want to make that member admin here ?
Thanks @fatagun
