### ISSUE TITLE
API - Generate user Token

### ISSUE THREAD

**Issue by pawaryogesh1989** [taigaio/taiga-back#719]
Hi,

Can we generate user token using email address only.

**Scenario:** I have a project in TAIGA and I am the project Owner. I have 4 members assigned with "back" role to the project. I am using API to add issues to the project. Some issues and comments are created by these members, but while adding it through API they are assigned to the project Owner and also the comments.

So, in Order to create it with there name and assign the comments to them I need their Authentication Token.

Using the API I can get email, TAIGA user ID, project and other details.

I know to generate token we need username and password. But in this case I have only user id, email and other details of the user but not password.

Is there a way I can generate a token for these users so that it can be used in the API while adding issues to their names?

Thanks

**Comment by bameda** [comment]
No, you can do that with the API because is dangerous to create objects on behalf of another person or create comments. The only mehtod to do, comment in the name of other person, is using the importers endpoints (https://github.com/taigaio/taiga-back/issues/712#issuecomment-217774749)

Regards

**Comment by pawaryogesh1989** [comment]
@bameda 

Regarding "The only mehtod to do, comment in the name of other person, is using the importers endpoints"  

Can you please give an example here or an link to example?

Thanks

**Comment by bameda** [comment]
```
curl -X POST \
       -H "Content-Type: application/json" \
       -H "Authorization: Bearer XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" \
       -d '{
               "owner": "support+proberts@taiga.io",
               "status": "In progress",
               "assigned_to": "support+imontoya@taiga.io",
               "priority": "High",
               "severity": "Important",
               "type": "Bug",
               "modified_date": "2015-06-17T21:07:51+0000",
               "tags": "[\"fencing\", \"feint\", \"challenge\", \"you fight like a dairy farmer\"]",
               "is_blocked": false,
               "blocked_note": "",
               "created_date": "2015-06-17T16:28:21+0000",
               "finished_date": null,
               "subject": "Dropping the sword when left-handed",
               "description": "It appears that more than 50% of the time, switching from right to left hand will result in the sword hitting the ground. It might be terrible under extreme circumstances or edge use cases (no pun intended).",
               "watchers": [
                   "support+proberts@taiga.io"
               ],
               "attachments": [],
               "custom_attributes_values": {},
               "history": [
                   {
                       "user": [
                           "support+proberts@taiga.io",
                           "The Man In Black"
                       ],
                       "comment": "And what is that?",
                       "created_at": "2015-06-17T21:01:52+0000",
                   },
                   {
                       "user": [
                           "support+imontoya@taiga.io",
                           "\u00ed\u00f1igo Montoya"
                       ],
                       "comment": "I am not left-handed.",
                       "created_at": "2015-06-17T21:02:53+0000",
                   },
                   {
                       "user": [
                           "support+proberts@taiga.io",
                           "The Man In Black"
                       ],
                       "comment": "You're amazing!",
                       "created_at": "2015-06-17T21:03:54+0000",
                   }
               ]
           }' \
       https://api.taiga.io/api/v1/api/v1/importer/3/issue
```

Other urls for different resources are:

- wikiPage: `/api/v1/importer/${projectId}/wiki_page`
- wikiLink: `/api/v1/importer/${projectId}/wiki_link`
- userStory: `/api/v1/importer/${projectId}/us`
- milestone: `/api/v1/importer/${projectId}/milestone`
- task: `/api/v1/importer/${projectId}/task`
