### ISSUE TITLE
Problem serving dist frontend

### ISSUE THREAD

**Issue by sergiosantamaria** [taigaio/taiga-back#726]
Mi situation: 
I have been instaling taiga for 2 days. Finally I got the backend installed. When I make

curl 127.0.0.1:8000/api/v1/

It answer properly but when I do the same with my public ip it answer with a connection error.

In other way I want to access to the frontend. The official guide says that you have to Expose the dist directory under a static file web server

I'm installing it on my Centos 6.5 Vps with apache as a http server.

I have tried creating /etc/httpd/conf.d/taiga.conf as

<VirtualHost *:9000>
    ServerName emilio
    ServerAdmin mail@mail.com
    DocumentRoot /home/taiga/taiga-front-dist/dist/
    ErrorLog logs/redmine_error_log
    <Directory "/home/taiga/taiga-front-dist/dist/">
            Options Indexes ExecCGI FollowSymLinks
            Order allow,deny
            Allow from all
            AllowOverride all
    </Directory>

But when I access to miip:9000 it doesn't show the index.html or anything.

so, my question is **how I make to serve anything the frontend in this port?** Any help will be apreciated.

Greetings

**Comment by superalex** [comment]
I'm sorry but this issue looks like a centos/apache config one (not directly related to Taiga). Some users configured Taiga with apache correctly, you can find more info about it on this issue: https://github.com/taigaio/taiga-back/issues/390
