### ISSUE TITLE
Searching for Application Id

### ISSUE THREAD

**Issue by SGuillard** [taigaio/taiga-back#727]
Hi Guys,

For the application token authentication, an "application id" is requested. It seems (if I am not wrong) that we have to create it by ourself directly in the django admin interface. However, I have no idea about how to do it. If you could help me, I would be more than gratefull.

Thanks in advance,

Sylvain

**Comment by bameda** [comment]
In http://<API_URL>/admin/external_apps/application/ but why do you need an app id? Are you creating a system that use the taiga auth system instead its own one?

**Comment by SGuillard** [comment]
I just want to get data from a user, and to display them in my interface. I can get a user auth_token, but I can't get the data of this user (like userstories for example). That's why I need an application authentication token (and so the application id). But maybe I am going in the wrong way. 
Thanks for your help

**Comment by bameda** [comment]
Yes, because If you have the auth_toke of an user you can get all the information that he can see. what call are you doing?

**Comment by SGuillard** [comment]
I'm setting the auth token in the header of my "Get" request, but I only get data of the "discover project " in javascript:
$http({method: 'GET', url: 'https:/192.168.0.50/api/v1/applications/5c8515c2-4fc4-11e5-9a5e-68f72800aadd/token', contentType: 'application/json',  beforeSend: function(xhr) {
	                 xhr.setRequestHeader("Authorization: Bearer" +self.token); 
	            },

**Comment by SGuillard** [comment]
Sorry, the url is: http:/192.168.0.50/api/v1/userstories

**Comment by bameda** [comment]
try to add an space after Beare

xhr.setRequestHeader("Authorization: Bearer " +self.token);

**Comment by SGuillard** [comment]
same result

**Comment by bameda** [comment]
and this call return discover projects?

**Comment by SGuillard** [comment]
Yes all the userstories of the discover projects

**Comment by SGuillard** [comment]
But the auth_token (or self.token in my script) is the user's with all his auth info

**Comment by bameda** [comment]
ok this url return user stories from all the project the user can see, so return all the user stories from all the public projects and from all the private project where the user is a member.

You have to apply a filter `?assigned_to=<user_id>`

**Comment by bameda** [comment]
and be careful because most of the responses are paginated

**Comment by SGuillard** [comment]
Already done. In my case, the user id is 25, and as there is no projects that is assigned to this id in the discover projects, the result is an empty object. It seems that we are always redirected to the discover projects

**Comment by bameda** [comment]
It should be works, because this is the call that Taiga do to render the user dashboard. Maybe the problem is with you code or with the auth token.  Try to do the examples in the documentation with curl to compare the responses.

![image](https://cloud.githubusercontent.com/assets/877218/15388087/84770328-1db0-11e6-9c58-51c49496c26b.png)

**Comment by SGuillard** [comment]
Ok thanks it works with Curl. But I still don't understand why it is'nt working with my javascript

**Comment by bameda** [comment]
Umm try with

```js
$http({
    method: 'GET', 
    url: 'https:/192.168.0.50/api/v1/userstoriers/?assigned_to=25', 
    headers: {
        'Content-Type': 'application/json',
        'Authorization': 'Bearer ' + self.token
    } 
});
```

**Comment by SGuillard** [comment]
Ok it works! Thanks a lot for your help!

**Comment by bameda** [comment]
Great!! \o/
