### ISSUE TITLE
Reduce email notification noise

### ISSUE THREAD

**Issue by tanc** [taigaio/taiga-back#731]
Love Taiga! Hate the notifications!

The number one complaint we get from people interacting with Taiga is the volume of email noise they get.

Would it be possible to define finer grained email preferences. For instance I might only want to receive an email notification if I'm watching a user story and someone adds a comment but not if the status is changed. Or even only receive an email notification if someone mentions me by name.

It would also be great if there was some kind of queue, so an email was sent out if a user is doing a few actions on a user story, like assigning to someone, then moving it into a different column, all within say 10 seconds, only one email containing all these changes is sent out, rather than an email per change.

Otherwise loving Taiga, thanks so much for the effort put in so far!

**Comment by superalex** [comment]
Hello @tanc we had an existing enhancement request for this one (https://tree.taiga.io/project/taiga/issue/2165), I've just added your comments there.

Right now Taiga is mixing the different changes in one only email, it depends on the setting CHANGE_NOTIFICATIONS_MIN_INTERVAL

**Comment by tanc** [comment]
Thanks @superalex!

**Comment by superalex** [comment]
You are welcome! ;)

**Comment by tanc** [comment]
@superalex would you mind explaining what the setting does? From other issues around the place I gather that if CHANGE_NOTIFICATIONS_MIN_INTERVAL is set to anything other than 0 then the notifications need to be triggered in some other way. On a self-hosted system, what would be the cron command to trigger the email?

If I were to set the CHANGE_NOTIFICATIONS_MIN_INTERVAL value to 5 minutes and had cron running every two minutes, would all changes related to a single user story be compiled into one email and sent out after 5 minutes had passed from the last change to the user story?

Any advice greatly appreciated

**Comment by superalex** [comment]
Sure!,

As you comment a crontab entry calling the "python manage.py send_notifications" under the virtualenv should do the job.

It should works exactly as you described, all the changes related should be compiled into one email and sent after 5 minutes had passed (but it will probably on the minute 6 if the crontab task is called every 2 minutes).

**Comment by tanc** [comment]
Perfect! This should drastically reduce email noise, thanks!

**Comment by superalex** [comment]
You are welcome @tanc  ;)
