### ISSUE TITLE
Please use PEP 263 encoding comments to avoid all the ugly locale problems leading to UnicodeDecodeErrors

### ISSUE THREAD

**Issue by JonasT** [taigaio/taiga-back#737]
There are multiple tickets around like #298 or #343 where the solution was suggested to set a specific locale or other workarounds to make the code run properly due to non-ascii characters in the code's comment section.

However, as far as my knowledge goes the proper way to solve this is described here: https://www.python.org/dev/peps/pep-0263/
In short, all the source code affected should be changed to have this line at the top, or right below the ```#!/usr/bin/python``` interpreter line if it is a runnable script:
```# -*- coding: utf-8 -*-``` (or respectively a similar comment for whatever encoding was used for the non-ascii characters in the source)

This should solve everyone's issues instantly without the required workaround hacks (IMHO) based on changing locale or clever virtualenv use just to get python to load the code properly. Therefore, please make use of this to get rid of this install issue for everyone.

**Comment by bameda** [comment]
Thanks for your feedback @JonasT I just made the PR.
