### ISSUE TITLE
[Q] How to change the Taiga URL?

### ISSUE THREAD

**Issue by sibin-aeione** [taigaio/taiga-back#74]
Hi,

Please let me know the steps needed to change the Taiga URL. Our taiga is running on a Ubuntu 18.04 instance.

**Comment by yamila-moreno** [comment]
Hi there!

Do you know that we have [Taiga Community](https://community.taiga.io/) for questions? Please, check there; maybe another user has already ask something similar. If not, create your own. There are people there willing to help, members of the Taiga team members and other users.

To simplify  the process, we will systematically close all issues that are general support questions and redirect people to Taiga Community.

Taiga Team
