### ISSUE TITLE
Multiple webhooks are not ran the same way

### ISSUE THREAD

**Issue by mikaoelitiana** [taigaio/taiga-back#754]
We use Taiga webhook to sync tickets to Gitlab and we recently added a new one to send tickets information to Odoo. 
After we added a second webhook, the first would not receive data anymore. Only the new one receive them but if we check the webhook endpoint, it works fine. 

<img width="1081" alt="capture d ecran 2016-06-08 a 10 49 21" src="https://cloud.githubusercontent.com/assets/674667/15886754/5aa7f0f4-2d67-11e6-87de-2fccfbe65c81.png">

**Comment by superalex** [comment]
Hello @mikaoelitiana 

This issue was solved 8 days ago: https://github.com/taigaio/taiga-back/commit/fc20d6c8f562f92577d4bcc99185fd14555694f3 and included in the stable branch.

Are you running the last taiga-back stable release?

**Comment by mikaoelitiana** [comment]
Hello, 

Alright, we didn't update Taiga yet for the last few weeks. We will do so. Thanks

**Comment by mikaoelitiana** [comment]
I updated Taiga but it doen't work yet. I checked commit is already there : 

`taiga@taiga:~/taiga-back$ git cat-file -t fc20d6c8f562f92577d4bcc99185fd14555694f3
commit`

<img width="1054" alt="capture d ecran 2016-06-08 a 15 15 28" src="https://cloud.githubusercontent.com/assets/674667/15894010/0dabe7ae-2d8c-11e6-9f4f-a1a066ec51a7.png">


Do I need to add again the webhooks?

**Comment by mikaoelitiana** [comment]
Oh sorry it was my falt, the service wasn't correctly restarted. It's working fine

**Comment by superalex** [comment]
Great! :+1:
