### ISSUE TITLE
[Django] ERROR (EXTERNAL IP): Internal Server Error

### ISSUE THREAD

**Issue by Shishir20** [taigaio/taiga-back#756]
I'm still having trouble config. the email settings. I'm receiving this error when Im trying to send emails.
Thanks.

**Comment by bameda** [comment]
What is the content of the email?

**Comment by Shishir20** [comment]
Internal Server Error: /api/v1/memberships/bulk_create

SMTPException at /api/v1/memberships/bulk_create No suitable authentication method found.

Request Method: POST
Request URL: http://***node177.***home.local:8000/api/v1/memberships/bulk_create
Django Version: 1.9.2
Python Executable: /home/taiga/.virtualenvs/taiga/bin/python3.4
Python Version: 3.4.3
Python Path: ['/home/taiga/taiga-back', '/home/taiga/taiga-back', '/home/taiga/.virtualenvs/taiga/bin', '/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages', '/home/taiga/.virtualenvs/taiga/lib/python3.4', '/home/taiga/.virtualenvs/taiga/lib/python3.4/plat-x86_64-linux-gnu', '/home/taiga/.virtualenvs/taiga/lib/python3.4/lib-dynload', '/usr/lib/python3.4', '/usr/lib/python3.4/plat-x86_64-linux-gnu', '/home/taiga/taiga-back'] Server time: Fri, 10 Jun 2016 11:11:06 +0000 Installed Applications:
['django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.admin',
 'django.contrib.staticfiles',
 'django.contrib.sitemaps',
 'taiga.base',
 'taiga.base.api',
 'taiga.locale',
 'taiga.events',
 'taiga.front',
 'taiga.users',
 'taiga.userstorage',
 'taiga.external_apps',
 'taiga.projects',
 'taiga.projects.references',
 'taiga.projects.custom_attributes',
 'taiga.projects.history',
 'taiga.projects.notifications',
 'taiga.projects.attachments',
 'taiga.projects.likes',
 'taiga.projects.votes',
 'taiga.projects.milestones',
 'taiga.projects.userstories',
 'taiga.projects.tasks',
 'taiga.projects.issues',
 'taiga.projects.wiki',
 'taiga.searches',
 'taiga.timeline',
 'taiga.mdrender',
 'taiga.export_import',
 'taiga.feedback',
 'taiga.stats',
 'taiga.hooks.github',
 'taiga.hooks.gitlab',
 'taiga.hooks.bitbucket',
 'taiga.webhooks',
 'djmail',
 'django_jinja',
 'django_jinja.contrib._humanize',
 'sr',
 'easy_thumbnails',
 'raven.contrib.django.raven_compat']
Installed Middleware:
['taiga.base.middleware.cors.CoorsMiddleware',
 'taiga.events.middleware.SessionIDMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware']


Traceback:

File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/handlers/base.py" in get_response
  149.                     response = self.process_exception_by_middleware(e, request)

File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/handlers/base.py" in get_response
  147.                     response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/taiga/taiga-back/taiga/base/api/viewsets.py" in view
  105.             return self.dispatch(request, *args, **kwargs)

File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/views/decorators/csrf.py" in wrapped_view
  58.         return view_func(*args, **kwargs)

File "/home/taiga/taiga-back/taiga/base/api/views.py" in dispatch
  445.             response = self.handle_exception(exc)

File "/home/taiga/taiga-back/taiga/base/api/views.py" in dispatch
  442.             response = handler(request, *args, **kwargs)

File "/home/taiga/taiga-back/taiga/projects/api.py" in bulk_create
  653.                                                       precall=self.pre_save)

File "/home/taiga/taiga-back/taiga/projects/services/members.py" in create_members_in_bulk
  49.     db.save_in_bulk(members, callback, precall)

File "/usr/lib/python3.4/contextlib.py" in inner
  30.                 return func(*args, **kwds)

File "/home/taiga/taiga-back/taiga/base/utils/db.py" in save_in_bulk
  96.         callback(instance, created=created)

File "/home/taiga/taiga-back/taiga/projects/api.py" in post_save
  693.         services.send_invitation(invitation=object)

File "/home/taiga/taiga-back/taiga/projects/services/invitations.py" in send_invitation
  16.     email.send()

File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/mail/message.py" in send
  292.         return self.get_connection(fail_silently).send_messages([self])

File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/mail/backends/smtp.py" in send_messages
  100.             new_conn_created = self.open()

File "/home/taiga/.virtualenvs/taiga/lib/python3.4/site-packages/django/core/mail/backends/smtp.py" in open
  67.                 self.connection.login(self.username, self.password)

File "/usr/lib/python3.4/smtplib.py" in login
  627.             raise SMTPException("No suitable authentication method found.")

Exception Type: SMTPException at /api/v1/memberships/bulk_create Exception Value: No suitable authentication method found.
Request information:
GET: No GET data

POST: No POST data

FILES: No FILES data

COOKIES: No cookie data

META:
REMOTE_PORT = '32780'
QUERY_STRING = ''
CONTENT_TYPE = 'application/json'
wsgi.multithread = False
wsgi.input = <gunicorn.http.body.Body object at 0x7ffa69171630> HTTP_X_FORWARDED_PROTO = 'http'
HTTP_ACCEPT_LANGUAGE = 'en'
SERVER_SOFTWARE = 'gunicorn/19.4.5'
SERVER_PROTOCOL = 'HTTP/1.0'
HTTP_USER_AGENT = 'Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.79 Safari/537.36'
wsgi.errors = <gunicorn.http.wsgi.WSGIErrorsWrapper object at 0x7ffa69171128> HTTP_HOST = '***node177.***home.local:8000'
HTTP_X_SCHEME = 'http'
HTTP_X_SESSION_ID = '1e5e179a67f9c64552635f2a5af15206c5c2049f'
HTTP_ORIGIN = 'http://taiga.***home.local'
REMOTE_ADDR = '127.0.0.1'
REQUEST_METHOD = 'POST'
PATH_INFO = '/api/v1/memberships/bulk_create'
RAW_URI = '/api/v1/memberships/bulk_create'
SERVER_NAME = '127.0.0.1'
SERVER_PORT = '8001'
wsgi.run_once = False
SCRIPT_NAME = ''
HTTP_AUTHORIZATION = 'Bearer eyJ1c2VyX2F1dGhlbnRpY2F0aW9uX2lkIjoxN30:1bBKKr:PuRY2XZwAF-EaM5RpBsdn0MWbnU'
gunicorn.socket = <socket.socket fd=11, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0, laddr=('127.0.0.1', 8001), raddr=('127.0.0.1', 32780)> HTTP_X_REAL_IP = '192.168.1.3'
HTTP_CONNECTION = 'close'
wsgi.url_scheme = 'http'
wsgi.version =
wsgi.multiprocess = True
wsgi.file_wrapper = ''
CONTENT_LENGTH = '89'
HTTP_ACCEPT_ENCODING = 'gzip, deflate'
HTTP_REFERER = 'http://taiga.***home.local/project/shishir***-test-project/admin/memberships'
HTTP_X_FORWARDED_FOR = '192.168.1.3'
HTTP_ACCEPT = 'application/json, text/plain, */*'

Settings:
Using settings module settings
SITES = {'api': {'scheme': 'http', 'domain': '***home.local', 'name': 'api'}, 'front': {'scheme': 'http', 'domain': '***node177.***home.local', 'name': 'front'}} FILE_CHARSET = 'utf-8'
LANGUAGE_COOKIE_AGE = None
MAX_MEMBERSHIPS_PRIVATE_PROJECTS = None
SECURE_REDIRECT_EXEMPT = []
SECURE_CONTENT_TYPE_NOSNIFF = False
SECURE_SSL_REDIRECT = False
TEMPLATE_STRING_IF_INVALID = ''
FIXTURE_DIRS = []
THN_LOGO_SMALL_SIZE = 80
STATIC_URL = 'http://***node177.***home.local:8000/static/'
DEFAULT_TABLESPACE = ''
CHANGE_NOTIFICATIONS_MIN_INTERVAL = 0
CELERY_QUEUES =
SESSION_COOKIE_AGE = 1209600
CELERY_ENABLED = True
CSRF_COOKIE_SECURE = False
THN_LOGO_BIG_SIZE = 300
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
THN_CARD_IMAGE_HEIGHT = 200
CACHE_MIDDLEWARE_ALIAS = 'default'
CSRF_FAILURE_VIEW = 'django.views.csrf.csrf_failure'
EMAIL_TIMEOUT = None
CSRF_COOKIE_HTTPONLY = False
ADMINS = ('Admin', 'shishir@***infotech.com') EVENTS_PUSH_BACKEND_OPTIONS = {'url': 'amqp://taiga:PASSWORD@localhost:5672/taiga'}
PROJECT_MODULES_CONFIGURATORS = {'gitlab': 'taiga.hooks.gitlab.services.get_or_generate_config', 'github': 'taiga.hooks.github.services.get_or_generate_config', 'bitbucket': 'taiga.hooks.bitbucket.services.get_or_generate_config'}
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
SESSION_COOKIE_HTTPONLY = True
FRONT_SITEMAP_CACHE_TIMEOUT = 86400
EMAIL_SSL_CERTFILE = None
TIME_FORMAT = 'P'
SOUTH_MIGRATION_MODULES = {'easy_thumbnails': 'easy_thumbnails.south_migrations'}
SECURE_BROWSER_XSS_FILTER = False
DATETIME_INPUT_FORMATS = ['%Y-%m-%d %H:%M:%S', '%Y-%m-%d %H:%M:%S.%f', '%Y-%m-%d %H:%M', '%Y-%m-%d', '%m/%d/%Y %H:%M:%S', '%m/%d/%Y %H:%M:%S.%f', '%m/%d/%Y %H:%M', '%m/%d/%Y', '%m/%d/%y %H:%M:%S', '%m/%d/%y %H:%M:%S.%f', '%m/%d/%y %H:%M', '%m/%d/%y'] CSRF_COOKIE_PATH = '/'
SESSION_CACHE_ALIAS = 'default'
DEFAULT_FILE_STORAGE = 'taiga.base.storage.FileSystemStorage'
DJMAIL_TEMPLATE_EXTENSION = 'jinja'
SEND_BROKEN_LINK_EMAILS = True
DEFAULT_INDEX_TABLESPACE = ''
CSRF_TRUSTED_ORIGINS = []
MAX_AGE_CANCEL_ACCOUNT = 2592000
SECURE_PROXY_SSL_HEADER =
PUBLIC_REGISTER_ENABLED = True
TEMPLATES = [{'OPTIONS': {'context_processors': ['django.contrib.auth.context_processors.auth', 'django.template.context_processors.request', 'django.template.context_processors.i18n', 'django.template.context_processors.media', 'django.template.context_processors.static', 'django.template.context_processors.tz', 'django.contrib.messages.context_processors.messages'], 'match_extension': '.jinja'}, 'APP_DIRS': True, 'BACKEND': 'django_jinja.backend.Jinja2', 'DIRS': ['/home/taiga/taiga-back/templates']}, {'OPTIONS': {'context_processors': ['django.contrib.auth.context_processors.auth', 'django.template.context_processors.request', 'django.template.context_processors.i18n', 'django.template.context_processors.media', 'django.template.context_processors.static', 'django.template.context_processors.tz', 'django.contrib.messages.context_processors.messages']}, 'APP_DIRS': True, 'BACKEND': 'django.template.backends.django.DjangoTemplates', 'DIRS': ['/home/taiga/taiga-back/templates']}]
LOGIN_REDIRECT_URL = '/accounts/profile/'
SIGNING_BACKEND = 'django.core.signing.TimestampSigner'
SECRET_KEY = '********************'
DATE_INPUT_FORMATS =
USE_TZ = True
CELERY_DEFAULT_QUEUE = 'tasks'
SESSION_FILE_PATH = None
STATIC_ROOT = '/home/taiga/taiga-back/static'
SR = {'social': {'twitter_url': 'https://twitter.com/taigaio', 'github_url': 'https://github.com/taigaio'}, 'taigaio_url': 'https://taiga.io', 'support': {'url': 'https://taiga.io/support', 'email': 'support@taiga.io', 'mailing_list': 'https://groups.google.com/forum/#!forum/taigaio'}}
DECIMAL_SEPARATOR = '.'
FEEDBACK_EMAIL = 'support@taiga.io'
DATE_FORMAT = 'N j, Y'
GRAVATAR_AVATAR_SIZE = 80
DEBUG = False
AUTH_USER_MODEL = 'users.User'
MEDIA_URL = 'http://***node177.***home.local:8000/media/'
PREPEND_WWW = False
MAX_PRIVATE_PROJECTS_PER_USER = None
THN_ATTACHMENT_CARD = 'card-image'
TEST_NON_SERIALIZED_APPS = []
MONTH_DAY_FORMAT = 'F j'
DJMAIL_REAL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
DJMAIL_SEND_ASYNC = True
THN_LOGO_BIG = 'logo-big'
LANGUAGES = [('ca', 'Català'), ('de', 'Deutsch'), ('en', 'English (US)'), ('es', 'Español'), ('fi', 'Suomi'), ('fr', 'Français'), ('it', 'Italiano'), ('nl', 'Nederlands'), ('pl', 'Polski'), ('pt-br', 'Português (Brasil)'), ('ru', 'Русский'), ('sv', 'Svenska'), ('tr', 'Türkçe'), ('zh-hant', '中文(香港)')]
SESSION_COOKIE_NAME = 'sessionid'
LOGGING = {'handlers': {'null': {'class': 'logging.NullHandler', 'level': 'DEBUG'}, 'console': {'class': 'logging.StreamHandler', 'level': 'DEBUG', 'formatter': 'simple'}, 'mail_admins': {'class': 'django.utils.log.AdminEmailHandler', 'level': 'ERROR', 'filters': ['require_debug_false']}}, 'loggers': {'taiga.export_import': {'handlers': ['mail_admins', 'console'], 'level': 'ERROR', 'propagate': False}, 'django': {'handlers': ['null'], 'level': 'INFO', 'propagate': True}, 'django.request': {'handlers': ['mail_admins', 'console'], 'level': 'ERROR', 'propagate': False}, 'taiga': {'handlers': ['console'], 'level': 'DEBUG', 'propagate': False}}, 'version': 1, 'filters': {'require_debug_false': {'()': 'django.utils.log.RequireDebugFalse'}}, 'formatters': {'complete': {'format': '%(levelname)s:%(asctime)s:%(module)s %(message)s'}, 'null': {'format': '%(message)s'}, 'simple': {'format': '%(levelname)s:%(asctime)s: %(message)s'}}, 'disable_existing_loggers': True} WEBHOOKS_ENABLED = False SECURE_SSL_HOST = None LANGUAGE_COOKIE_NAME = 'django_language'
CELERY_DEFAULT_EXCHANGE_TYPE = 'topic'
IGNORABLE_404_URLS = []
FILE_UPLOAD_TEMP_DIR = None
SHORT_DATE_FORMAT = 'm/d/Y'
LANGUAGE_COOKIE_DOMAIN = None
CELERY_TIMEZONE = 'Europe/Madrid'
FILE_UPLOAD_HANDLERS = ['django.core.files.uploadhandler.MemoryFileUploadHandler', 'django.core.files.uploadhandler.TemporaryFileUploadHandler']
DJMAIL_MAX_RETRY_NUMBER = 3
THOUSAND_SEPARATOR = ','
USE_X_FORWARDED_PORT = False
APPEND_SLASH = False
TEMPLATE_DIRS = []
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
CSRF_HEADER_NAME = 'HTTP_X_CSRFTOKEN'
USE_L10N = True
DISALLOWED_USER_AGENTS = []
SEARCHES_MAX_RESULTS = 150
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.StaticFilesStorage'
EMAIL_HOST_PASSWORD = '********************'
CELERY_ENABLE_UTC = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
FILE_UPLOAD_DIRECTORY_PERMISSIONS = None SESSION_SERIALIZER = 'django.contrib.sessions.serializers.JSONSerializer'
EMAIL_USE_SSL = False
FILE_UPLOAD_PERMISSIONS = None
TEST_RUNNER = 'django.test.runner.DiscoverRunner'
THN_AVATAR_BIG_SIZE = 300
WSGI_APPLICATION = 'taiga.wsgi.application'
FORCE_SCRIPT_NAME = None
TIME_ZONE = 'UTC'
EMAIL_SSL_KEYFILE = '********************'
TIME_INPUT_FORMATS = ['%H:%M:%S', '%H:%M:%S.%f', '%H:%M'] GRAVATAR_DEFAULT_AVATAR = ''
SESSION_COOKIE_DOMAIN = None
SESSION_COOKIE_PATH = '/'
PASSWORD_HASHERS = '********************'
EMAIL_HOST_USER = 'shishir@***infotech.com'
SHORT_DATETIME_FORMAT = 'm/d/Y P'
LANGUAGE_COOKIE_PATH = '/'
CELERY_DEFAULT_EXCHANGE = 'tasks'
FIRST_DAY_OF_WEEK = 0
THN_AVATAR_SIZE = 80
FORMAT_MODULE_PATH = 'taiga.base.formats'
LANGUAGE_CODE = 'en-us'
THN_AVATAR_BIG = 'big-avatar'
FEEDBACK_ENABLED = True
DEFAULT_PROJECT_TEMPLATE = 'scrum'
STATICFILES_DIRS =
CSRF_COOKIE_DOMAIN = None
TEMPLATE_DEBUG = False
CACHE_MIDDLEWARE_SECONDS = 600
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
BITBUCKET_VALID_ORIGIN_IPS = ['131.103.20.165', '131.103.20.166', '104.192.143.192/28', '104.192.143.208/28'] MIGRATION_MODULES = {} BASE_DIR = '/home/taiga/taiga-back'
THN_TIMELINE_IMAGE_SIZE = 640
EVENTS_PUSH_BACKEND = 'taiga.events.backends.rabbitmq.EventsPushBackend'
EXTRA_BLOCKING_CODES = []
LOGIN_URL = '/auth/login/'
DEBUG_PROPAGATE_EXCEPTIONS = False
USE_THOUSAND_SEPARATOR = False
DATETIME_FORMAT = 'N j, Y, P'
ADMIN_MEDIA_PREFIX = 'http://***node177.***home.local:8000/static/admin/'
STATS_CACHE_TIMEOUT = 3600
DEFAULT_FROM_EMAIL = 'shishir@***infotech.com'
EXPORTS_TTL = 86400
USE_X_FORWARDED_HOST = True
USE_I18N = True
THN_AVATAR_SMALL = 'avatar'
X_FRAME_OPTIONS = 'SAMEORIGIN'
LOGGING_CONFIG = 'logging.config.dictConfig'
CACHE_MIDDLEWARE_KEY_PREFIX = '********************'
LOGOUT_URL = '/accounts/logout/'
INTERNAL_IPS = []
THUMBNAIL_ALIASES = {'': {'big-avatar': {'crop': True, 'size': (300, 300)}, 'timeline-image': {'crop': True, 'size': (640, 0)}, 'card-image': {'crop': True, 'size': (300, 200)}, 'logo-big': {'crop': True, 'size': (300, 300)}, 'avatar': {'crop': True, 'size': (80, 80)}, 'logo-small': {'crop': True, 'size': (80, 80)}}} AUTHENTICATION_BACKENDS = 'django.contrib.auth.backends.ModelBackend'
ALLOWED_INCLUDE_ROOTS = []
SERVER_EMAIL = 'shishir@***infotech.com'
BROKER_URL = 'amqp://guest:guest@localhost:5672//'
DEFAULT_CONTENT_TYPE = 'text/html'
IGNORABLE_404_STARTS = '/phpmyadmin/'
FRONT_SITEMAP_ENABLED = False
SESSION_SAVE_EVERY_REQUEST = False
SETTINGS_MODULE = 'settings'
ABSOLUTE_URL_OVERRIDES = {}
CACHES = {'default': {'LOCATION': 'unique-snowflake', 'BACKEND': 'django.core.cache.backends.locmem.LocMemCache'}}
THN_ATTACHMENT_TIMELINE = 'timeline-image'
SECURE_HSTS_SECONDS = 0
STATICFILES_FINDERS = ['django.contrib.staticfiles.finders.FileSystemFinder', 'django.contrib.staticfiles.finders.AppDirectoriesFinder']
TEMPLATE_LOADERS = ['django.template.loaders.filesystem.Loader', 'django.template.loaders.app_directories.Loader']
FILE_UPLOAD_MAX_MEMORY_SIZE = 2621440
TAGS_PREDEFINED_COLORS = ['#fce94f', '#edd400', '#c4a000', '#8ae234', '#73d216', '#4e9a06', '#d3d7cf', '#fcaf3e', '#f57900', '#ce5c00', '#729fcf', '#3465a4', '#204a87', '#888a85', '#ad7fa8', '#75507b', '#5c3566', '#ef2929', '#cc0000', '#a40000', '#2e3436'] NUMBER_GROUPING = 0 CSRF_COOKIE_NAME = 'csrftoken'
MAX_MEMBERSHIPS_PUBLIC_PROJECTS = None
DEFAULT_CHARSET = 'utf-8'
ATOMIC_REQUESTS = True
THN_CARD_IMAGE_WIDTH = 300
CELERY_DEFAULT_ROUTING_KEY = '********************'
EMAIL_USE_TLS = False
REST_FRAMEWORK = {'DEFAULT_THROTTLE_CLASSES': ('taiga.base.throttling.AnonRateThrottle', 'taiga.base.throttling.UserRateThrottle'), 'DEFAULT_AUTHENTICATION_CLASSES': ('taiga.auth.backends.Token', 'taiga.auth.backends.Session', 'taiga.external_apps.auth_backends.Token'), 'PAGINATE_BY': 30, 'DEFAULT_THROTTLE_RATES': {'import-dump-mode': '1/minute', 'anon': None, 'user': None, 'import-mode': None}, 'MAX_PAGINATE_BY': 1000, 'PAGINATE_BY_PARAM': 'page_size', 'DATETIME_FORMAT': '%Y-%m-%dT%H:%M:%S%z', 'EXCEPTION_HANDLER': 'taiga.base.exceptions.exception_handler', 'FILTER_BACKEND': 'taiga.base.filters.FilterBackend'}
CSRF_COOKIE_AGE = 31449600
MAX_AGE_AUTH_TOKEN = '********************'
PASSWORD_RESET_TIMEOUT_DAYS = '********************'
THN_LOGO_SMALL = 'logo-small'
YEAR_MONTH_FORMAT = 'F Y'
EMAIL_HOST = 'cas02.***home.local'
STATS_ENABLED = False
LANGUAGES_BIDI = ['he', 'ar', 'fa', 'ur'] DATABASES = {'default': {'USER': '', 'CONN_MAX_AGE': 0, 'TEST': {'MIRROR': None, 'COLLATION': None, 'NAME': None, 'CHARSET': None}, 'ENGINE': 'django.db.backends.postgresql', 'ATOMIC_REQUESTS': False, 'TIME_ZONE': None, 'PORT': '', 'OPTIONS': {}, 'PASSWORD': '********************', 'HOST': '', 'NAME': 'taiga', 'AUTOCOMMIT': True}} LOCALE_PATHS = DATABASE_ROUTERS = [] ROOT_URLCONF = 'taiga.urls'
IGNORABLE_404_ENDS =
SESSION_COOKIE_SECURE = False
SILENCED_SYSTEM_CHECKS = []
EMAIL_SUBJECT_PREFIX = '[Django] '
MEDIA_ROOT = '/home/taiga/taiga-back/media'
DEFAULT_EXCEPTION_REPORTER_FILTER = 'django.views.debug.SafeExceptionReporterFilter'
TEMPLATE_CONTEXT_PROCESSORS = ['django.contrib.auth.context_processors.auth', 'django.template.context_processors.debug', 'django.template.context_processors.i18n', 'django.template.context_processors.media', 'django.template.context_processors.static', 'django.template.context_processors.tz', 'django.contrib.messages.context_processors.messages']
AUTH_PASSWORD_VALIDATORS = '********************'
SITE_ID = 'api'
MIDDLEWARE_CLASSES = ['taiga.base.middleware.cors.CoorsMiddleware', 'taiga.events.middleware.SessionIDMiddleware', 'django.middleware.common.CommonMiddleware', 'django.middleware.locale.LocaleMiddleware', 'django.contrib.sessions.middleware.SessionMiddleware', 'django.contrib.auth.middleware.AuthenticationMiddleware', 'django.contrib.messages.middleware.MessageMiddleware']
INSTALLED_APPS = ['django.contrib.auth', 'django.contrib.contenttypes', 'django.contrib.sessions', 'django.contrib.messages', 'django.contrib.admin', 'django.contrib.staticfiles', 'django.contrib.sitemaps', 'taiga.base', 'taiga.base.api', 'taiga.locale', 'taiga.events', 'taiga.front', 'taiga.users', 'taiga.userstorage', 'taiga.external_apps', 'taiga.projects', 'taiga.projects.references', 'taiga.projects.custom_attributes', 'taiga.projects.history', 'taiga.projects.notifications', 'taiga.projects.attachments', 'taiga.projects.likes', 'taiga.projects.votes', 'taiga.projects.milestones', 'taiga.projects.userstories', 'taiga.projects.tasks', 'taiga.projects.issues', 'taiga.projects.wiki', 'taiga.searches', 'taiga.timeline', 'taiga.mdrender', 'taiga.export_import', 'taiga.feedback', 'taiga.stats', 'taiga.hooks.github', 'taiga.hooks.gitlab', 'taiga.hooks.bitbucket', 'taiga.webhooks', 'djmail', 'django_jinja', 'django_jinja.contrib._humanize', 'sr', 'easy_thumbnails', 'raven.contrib.django.raven_compat']
MANAGERS = []
MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'
EMAIL_PORT = 25
ALLOWED_HOSTS = ['*']
MAX_PUBLIC_PROJECTS_PER_USER = None
GITLAB_VALID_ORIGIN_IPS = []
USE_ETAGS = False
APP_EXTRA_EXPOSE_HEADERS = ['taiga-info-total-opened-milestones', 'taiga-info-total-closed-milestones', 'taiga-info-project-memberships', 'taiga-info-project-is-private']

**Comment by superalex** [comment]
It seems the settings in your local.py are not valid, could you please show us your configuration?

**Comment by Shishir20** [comment]
Here is my local.py


from .common import *

MEDIA_URL = "http://triconnode177.triconhome.local:8000/media/"
STATIC_URL = "http://triconnode177.triconhome.local:8000/static/"
ADMIN_MEDIA_PREFIX = "http://triconnode177.triconhome.local:8000/static/admin/"
SITES["front"]["scheme"] = "http"
SITES["front"]["domain"] = "triconnode177.triconhome.local"

SECRET_KEY = "theveryultratopsecretkey"

DEBUG = False
TEMPLATE_DEBUG = False
PUBLIC_REGISTER_ENABLED = True

DEFAULT_FROM_EMAIL = "shishir@***infotech.com"
SERVER_EMAIL = DEFAULT_FROM_EMAIL

EVENTS_PUSH_BACKEND = "taiga.events.backends.rabbitmq.EventsPushBackend"
EVENTS_PUSH_BACKEND_OPTIONS = {"url": "amqp://taiga:PASSWORD@localhost:5672/taiga"}
# Uncomment and populate with proper connection parameters
# for enable email sending. EMAIL_HOST_USER should end by @domain.tld
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_USE_TLS = False
EMAIL_HOST = "cas02.***home.local"
EMAIL_PORT = 25
EMAIL_HOST_USER = "shishir@***infotech.com"
EMAIL_HOST_PASSWORD = "gotham.T20"


# Uncomment and populate with proper connection parameters
# for enable github login/singin.
#GITHUB_API_CLIENT_ID = "yourgithubclientid"
#GITHUB_API_CLIENT_SECRET = "yourgithubclientsecret"

from .celery import *

BROKER_URL = 'amqp://guest:guest@localhost:5672//'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ENABLED = True

**Comment by Shishir20** [comment]
Here is my local.py


from .common import *

MEDIA_URL = "http://xyznode177.xyzhome.local:8000/media/"
STATIC_URL = "http://xyznode177.xyzhome.local:8000/static/"
ADMIN_MEDIA_PREFIX = "http://xyznode177.xyzhome.local:8000/static/admin/"
SITES["front"]["scheme"] = "http"
SITES["front"]["domain"] = "xyznode177.xyzhome.local"

SECRET_KEY = "theveryultratopsecretkey"

DEBUG = False
TEMPLATE_DEBUG = False
PUBLIC_REGISTER_ENABLED = True

DEFAULT_FROM_EMAIL = "shishir@xyzinfotech.com"
SERVER_EMAIL = DEFAULT_FROM_EMAIL

EVENTS_PUSH_BACKEND = "taiga.events.backends.rabbitmq.EventsPushBackend"
EVENTS_PUSH_BACKEND_OPTIONS = {"url": "amqp://taiga:PASSWORD@localhost:5672/taiga"}

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_USE_TLS = False
EMAIL_HOST = "cas02.xyzhome.local"
EMAIL_PORT = 25
EMAIL_HOST_USER = "shishir@xyzinfotech.com"
EMAIL_HOST_PASSWORD = "gotham.T20"

from .celery import *

BROKER_URL = 'amqp://guest:guest@localhost:5672//'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ENABLED = True

**Comment by bameda** [comment]
it seems that your email configuration is wrong... are you sure that your smtp server doesn't use tsl? maybe it use ssl instead?.

Try to remove play with EMAIL_USE_TLS and EMAIL_USE_SSL
```

**Comment by Shishir20** [comment]
Okay. I tried all possible combinations here. No Luck :(

**Comment by bameda** [comment]
Are you sure that in the host cas02.xyzhome.local in the port 25 there is an SMTP server running and you can login with your username and password?
