### ISSUE TITLE
when I add an userstory, it response 500

### ISSUE THREAD

**Issue by bealzh** [taigaio/taiga-back#757]
{"log":"ERROR:2016-06-13 01:21:24,109: Internal Server Error: /api/v1/userstories\n","stream":"stderr","time":"2016-06-13T01:21:24.131270331Z"}
{"log":"Traceback (most recent call last):\n","stream":"stderr","time":"2016-06-13T01:21:24.131324326Z"}
{"log":"  File \"/usr/local/lib/python3.4/site-packages/django/core/handlers/base.py\", line 111, in get_response\n","stream":"stderr","time":"2016-06-13T01:21:24.13134385Z"}
{"log":"    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n","stream":"stderr","time":"2016-06-13T01:21:24.131353301Z"}
{"log":"  File \"/taiga/taiga/base/api/viewsets.py\", line 81, in view\n","stream":"stderr","time":"2016-06-13T01:21:24.13136089Z"}
{"log":"    return self.dispatch(request, *args, **kwargs)\n","stream":"stderr","time":"2016-06-13T01:21:24.13136837Z"}
{"log":"  File \"/usr/local/lib/python3.4/site-packages/django/views/decorators/csrf.py\", line 57, in wrapped_view\n","stream":"stderr","time":"2016-06-13T01:21:24.131375057Z"}
{"log":"    return view_func(*args, **kwargs)\n","stream":"stderr","time":"2016-06-13T01:21:24.131382208Z"}
{"log":"  File \"/taiga/taiga/base/api/views.py\", line 420, in dispatch\n","stream":"stderr","time":"2016-06-13T01:21:24.13138883Z"}
{"log":"    response = self.handle_exception(exc)\n","stream":"stderr","time":"2016-06-13T01:21:24.131398458Z"}
{"log":"  File \"/taiga/taiga/base/api/views.py\", line 417, in dispatch\n","stream":"stderr","time":"2016-06-13T01:21:24.131407146Z"}
{"log":"    response = handler(request, *args, **kwargs)\n","stream":"stderr","time":"2016-06-13T01:21:24.131414451Z"}
{"log":"  File \"/usr/local/lib/python3.4/site-packages/django/db/transaction.py\", line 394, in inner\n","stream":"stderr","time":"2016-06-13T01:21:24.131422471Z"}
{"log":"    return func(*args, **kwargs)\n","stream":"stderr","time":"2016-06-13T01:21:24.131429718Z"}
{"log":"  File \"/taiga/taiga/projects/userstories/api.py\", line 172, in create\n","stream":"stderr","time":"2016-06-13T01:21:24.13143625Z"}
{"log":"    response = super().create(*args, **kwargs)\n","stream":"stderr","time":"2016-06-13T01:21:24.131443098Z"}
{"log":"  File \"/taiga/taiga/base/api/mixins.py\", line 72, in create\n","stream":"stderr","time":"2016-06-13T01:21:24.131449695Z"}
{"log":"    self.object = serializer.save(force_insert=True)\n","stream":"stderr","time":"2016-06-13T01:21:24.1314563Z"}
{"log":"  File \"/taiga/taiga/base/api/serializers.py\", line 1055, in save\n","stream":"stderr","time":"2016-06-13T01:21:24.131463191Z"}
{"log":"    self.object = super().save(**kwargs)\n","stream":"stderr","time":"2016-06-13T01:21:24.131469949Z"}
{"log":"  File \"/taiga/taiga/base/api/serializers.py\", line 614, in save\n","stream":"stderr","time":"2016-06-13T01:21:24.131476525Z"}
{"log":"    self.save_object(self.object, **kwargs)\n","stream":"stderr","time":"2016-06-13T01:21:24.131483258Z"}
{"log":"  File \"/taiga/taiga/base/api/serializers.py\", line 1073, in save_object\n","stream":"stderr","time":"2016-06-13T01:21:24.131489705Z"}
{"log":"    obj.save(**kwargs)\n","stream":"stderr","time":"2016-06-13T01:21:24.131496534Z"}
{"log":"  File \"/taiga/taiga/projects/userstories/models.py\", line 118, in save\n","stream":"stderr","time":"2016-06-13T01:21:24.131502695Z"}
{"log":"    super().save(*args, **kwargs)\n","stream":"stderr","time":"2016-06-13T01:21:24.131509601Z"}
{"log":"  File \"/usr/local/lib/python3.4/site-packages/django/db/models/base.py\", line 589, in save\n","stream":"stderr","time":"2016-06-13T01:21:24.131515947Z"}
{"log":"    force_update=force_update, update_fields=update_fields)\n","stream":"stderr","time":"2016-06-13T01:21:24.13152865Z"}
{"log":"  File \"/usr/local/lib/python3.4/site-packages/django/db/models/base.py\", line 626, in save_base\n","stream":"stderr","time":"2016-06-13T01:21:24.13155745Z"}
{"log":"    update_fields=update_fields, raw=raw, using=using)\n","stream":"stderr","time":"2016-06-13T01:21:24.131568317Z"}
{"log":"  File \"/usr/local/lib/python3.4/site-packages/django/dispatch/dispatcher.py\", line 198, in send\n","stream":"stderr","time":"2016-06-13T01:21:24.131577949Z"}
{"log":"    response = receiver(signal=self, sender=sender, **named)\n","stream":"stderr","time":"2016-06-13T01:21:24.131587171Z"}
{"log":"  File \"/taiga/taiga/projects/references/models.py\", line 92, in attach_sequence\n","stream":"stderr","time":"2016-06-13T01:21:24.131596043Z"}
{"log":"    instance.save(update_fields=['ref'])\n","stream":"stderr","time":"2016-06-13T01:21:24.131603277Z"}
{"log":"  File \"/taiga/taiga/projects/userstories/models.py\", line 118, in save\n","stream":"stderr","time":"2016-06-13T01:21:24.131610197Z"}
{"log":"    super().save(*args, **kwargs)\n","stream":"stderr","time":"2016-06-13T01:21:24.131617155Z"}
{"log":"  File \"/usr/local/lib/python3.4/site-packages/django/db/models/base.py\", line 589, in save\n","stream":"stderr","time":"2016-06-13T01:21:24.131623598Z"}
{"log":"    force_update=force_update, update_fields=update_fields)\n","stream":"stderr","time":"2016-06-13T01:21:24.131630322Z"}
{"log":"  File \"/usr/local/lib/python3.4/site-packages/django/db/models/base.py\", line 626, in save_base\n","stream":"stderr","time":"2016-06-13T01:21:24.131636933Z"}
{"log":"    update_fields=update_fields, raw=raw, using=using)\n","stream":"stderr","time":"2016-06-13T01:21:24.131643685Z"}
{"log":"  File \"/usr/local/lib/python3.4/site-packages/django/dispatch/dispatcher.py\", line 198, in send\n","stream":"stderr","time":"2016-06-13T01:21:24.131650287Z"}
{"log":"    response = receiver(signal=self, sender=sender, **named)\n","stream":"stderr","time":"2016-06-13T01:21:24.131656863Z"}
{"log":"  File \"/taiga/taiga/events/signal_handlers.py\", line 43, in on_save_any_model\n","stream":"stderr","time":"2016-06-13T01:21:24.131663281Z"}
{"log":"    connection.on_commit(emit_event)\n","stream":"stderr","time":"2016-06-13T01:21:24.131670039Z"}
{"log":"  File \"/usr/local/lib/python3.4/site-packages/django/db/__init__.py\", line 40, in __getattr__\n","stream":"stderr","time":"2016-06-13T01:21:24.131676154Z"}
{"log":"    return getattr(connections[DEFAULT_DB_ALIAS], item)\n","stream":"stderr","time":"2016-06-13T01:21:24.131682583Z"}
{"log":"AttributeError: 'DatabaseWrapper' object has no attribute 'on_commit'\n","stream":"stderr","time":"2016-06-13T01:21:24.131689121Z"}

**Comment by superalex** [comment]
Hello @bealzh 

Checking your errors it seems you did the install with a root user, Taiga must be installed with a non root one, did you follow the installation docs?
