### ISSUE TITLE
local installation - unable to edit/delete blocked project as administrator

### ISSUE THREAD

**Issue by pkoretic** [taigaio/taiga-back#758]
Hi all.

I've installed taiga locally (using scripts method).
So I've ended up with some demo data.
As administrator (default user created) I'm unable to delete blocked project?

What can I do to delete it?

Thanks

**Comment by bameda** [comment]
Access to the superadmin pannel and delete it (http://<taiga-back-host>/admin/). 

You can regenerate the db too without the sample data.

```
workon taiga 

dropdb taiga
createdb taiga

#-> Load migrations
python manage.py migrate
#-> Load initial user (admin/123123)
python manage.py loaddata initial_user --traceback
#-> Load initial project_templates (scrum/kanban)
python manage.py loaddata initial_project_templates --traceback
```
