### ISSUE TITLE
we can not edit anything

### ISSUE THREAD

**Issue by alireza-hanifi** [taigaio/taiga-back#759]
we installed taiga in our host successfully with scripts. and only we changed localhost to remote ip.
everything was ok, but after create and editing many user story we were not be able to edit anything.
now in editing permissions, user stories, tasks, . . .  taiga shows this error .

Oops, something happened...
Our Oompa Loompas are sad, your changes were not saved!

**Comment by superalex** [comment]
Hello @alireza-hanifi 

You can check different things:
 - Your logs folder (in the home of the user you are using for Taiga): check if there is any output related to the errors you hare receiving
 - From your browser console: some API calls may be failing, you could check the full body of the server response to check if it has more info.

**Comment by ma5t1n** [comment]
Sounds common to me - have you checked the config-files used by taiga-front (those in conf-dir)?

In my case I found a localhost entries for the api-calls - after changing them everything was fine.

**Comment by alireza-hanifi** [comment]
py problem fixed automatically after running script again and restarting server.
i guess it was for using proxy server on that vps. but i did not know why create and delete were working well but edit did not work. i don't know python ,if not i debugged it.
thanks for attention.

**Comment by superalex** [comment]
You are welcome @alireza-hanifi
