### ISSUE TITLE
Fine-grained workflow and permissions control (enhancement)

### ISSUE THREAD

**Issue by superbiche** [taigaio/taiga-back#762]
Hi !

We've installed an on-premises instance of Taiga to help our team moving from Redmine powered waterfall project management to more agility.

In order to allow our clients to submit issues, we saw that the current permissions management system doesn't allow, for example, to give a user the permission to create an issue and see/edit/delete the issues he created, without being allowed to see/edit/delete the other issues.

Something like this : 
![taiga-permissions](https://cloud.githubusercontent.com/assets/2478146/16119853/b0cb3f46-33dd-11e6-819e-f604c085476c.png)

Let me know if you think this could be a valuable feature. I can begin to implement it.

**Comment by superalex** [comment]
Hello @superbiche 

We had an existing enhancement request for this one (https://tree.taiga.io/project/taiga/issue/2132), I've just copied your comments there. We would have to check with our UX and design people what would be the best option to implement it.

Thank you very much for your offering! ;)
