### ISSUE TITLE
Typo (back/admin) - Memberships

### ISSUE THREAD

**Issue by joeyhub** [taigaio/taiga-back#763]
'Membershipss'

![image](https://cloud.githubusercontent.com/assets/1512978/16152502/206136f0-349a-11e6-822f-c154c06fc068.png)

**Comment by paultag** [comment]
https://github.com/taigaio/taiga-back/blob/master/taiga/projects/models.py#L106 is the offending line

**Comment by bameda** [comment]
Fixed https://github.com/taigaio/taiga-back/commit/e4f96e605343c237373a1d4fa55d44b464138085

Thank you very much Paul 

![](https://media.giphy.com/media/oH9DJbJJr42lO/giphy.gif)
