### ISSUE TITLE
Patch issue for "Comment permission"

### ISSUE THREAD

**Issue by unixfox** [taigaio/taiga-back#765]
The "comment permission" doesn't work for me, it returns:
` "PATCH /api/v1/issues/20 HTTP/1.0" 403 129`

![](https://i.unixfox.eu/50-20-35-2016.png)

I'm on the master branch:
```
user@vps:/home/taiga/taiga-back# git status
On branch master
Your branch is up-to-date with 'origin/master'.
nothing to commit, working directory clean
```

**Comment by bameda** [comment]
master branch is unstable, is normal that contains some errors
