### ISSUE TITLE
Use Taiga with Postgres-XL or Citus

### ISSUE THREAD

**Issue by dimitertodorov** [taigaio/taiga-back#768]
Hi,

So I am looking at expanding our Taiga on-prem deployment.
One of the first things I look at is Redundancy in case of failure. 

Has the backend been tested with either Postgres-XL/pgpool2/Citus solution.

D

**Comment by superalex** [comment]
Hello @dimitertodorov 

We are currently using pgpool in tree.taiga.io so it's fully tested. As far as we know postgres-XL or citus haven't been tested.

Regards!,
