### ISSUE TITLE
[Q] S3 file storage

### ISSUE THREAD

**Issue by zaidqureshi2** [taigaio/taiga-back#77]
I am running my taiga in an ec2 instance using the docker taiga project. I'm trying to configure the storage to use s3 instead of container storage.

I have this right now:
```
DEFAULT_FILE_STORAGE=storages.backends.s3boto3.S3Boto3Storage
AWS_STORAGE_BUCKET_NAME=mybucketname
```

After restarting my containers, I verified they were applied in the container. When I uploaded my profile picture, it didn't upload to my s3.

Let me know what I have to do.

Thanks!

**Comment by zaidqureshi2** [comment]
Any updates?

**Comment by bameda** [comment]
Hi @zaidqureshi2 

We know that django supports S3 as File Storage but we haven't used S3 in any of our installations so far, so we don't have much experience with it. However, we have a future installation in the medium term that may involve using S3 for media and static files. 

When we work on it, we will document and publish the process. 

I'm sorry I can't be more helpful.

**Comment by yamila-moreno** [comment]
Hi there!

Do you know that we have [Taiga Community](https://community.taiga.io/) for questions? Please, check there; maybe another user has already ask something similar. If not, create your own. There are people there willing to help, members of the Taiga team members and other users.

To simplify  the process, we will systematically close all issues that are general support questions and redirect people to Taiga Community.

Taiga Team
