### ISSUE TITLE
Best way of dealing with the taiga secret key

### ISSUE THREAD

**Issue by herbsmn** [taigaio/taiga-back#773]
I saw that @ss-abramchuk used an interesting method here: https://gist.github.com/ss-abramchuk/fd77fe4aa823d92c15e9#installing-taiga-backend

Is this the optimal way to make a taiga secret key?

**Comment by bameda** [comment]
Yes, but maybe I use a big one

```
TAIGA_SECRET_KEY=`< /dev/urandom tr -dc _A-Z-a-z-0-9 | head -c${1:-64};echo;`
```

**Comment by bameda** [comment]
and you can find more info about the SECRET_KEY here: https://docs.djangoproject.com/en/dev/ref/settings/#secret-key
