### ISSUE TITLE
Email notifications

### ISSUE THREAD

**Issue by foxbike** [taigaio/taiga-back#78]
We have completed our installation of Taiga 6 in our production environment but we are unable to get some email notifications to work. For password reset, project assignment, etc., it works but when assigning a task, no email is sent. We have set up the interface to receive all notifications. We have activated CELERY. We tested the call to send_notifications in manage.py. Nothing to do. Do you have a solution?

Thanks.

**Comment by ChriFo** [comment]
Setting the mail variables at the celery container (taiga-async) as well as the following variables fixed it for me.
- EMAIL_BACKEND: `djmail.backends.async.EmailBackend`
- DJMAIL_REAL_BACKEND: `django.core.mail.backends.smtp.EmailBackend`

**Comment by yamila-moreno** [comment]
Hi there!

Do you know that we have [Taiga Community](https://community.taiga.io/) for questions? Please, check there; maybe another user has already ask something similar. If not, create your own. There are people there willing to help, members of the Taiga team members and other users.

To simplify  the process, we will systematically close all issues that are general support questions and redirect people to Taiga Community.

Taiga Team
