### ISSUE TITLE
URL definied in taiga.front.urls not working

### ISSUE THREAD

**Issue by MichaelHierweck** [taigaio/taiga-back#786]
I recently installed taiga backend and frontend and startet to play around. Then I tried to invite a friend but the invitation link was not working. I did some research and found out that all urls defined in taiga/front/urls.py are not working:

```
Page not found (404)
Request Method:	GET
Request URL:	http://example.com/forgot-password
Using the URLconf defined in taiga.urls, Django tried these URL patterns, in this order:
^api/v1/
^api/v1/api-auth/
^admin/
^static\/(?P<path>.*)$
^media\/(?P<path>.*)$
^api/v1/
^api/v1/
The current URL, forgot-password, didn't match any of these.
You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.
```

This also affects URLs such as http://example.com/project/demo/backlog when accessing them directly while navigating (clicking) to the backlog from / (home) works.

**Comment by MichaelHierweck** [comment]
My deployment was buggy. The mapping of unhandled urls to /index.html failed.

**Comment by superalex** [comment]
ok! ;)

**Comment by liangssGift** [comment]
I encountered the same problem，but i could fixed，can you give me more info to fix it？
