### ISSUE TITLE
Taskboard icon on the left bar

### ISSUE THREAD

**Issue by lordloh** [taigaio/taiga-back#795]
I currently reach the taskboard by clicking on "Backlogs" > "Sprint Taskboard". 

It would be continent to have a "Taskboard" icon on the left bar to go to the current taskboard immediately. 

It would also be great to have a drop down menu on the taskboard page to switch to a different sprint taskboard.

**Comment by lordloh** [comment]
@Xaviju : What is the other issue? I would watch / subscribe / upvote it.

Thank you.

**Comment by Xaviju** [comment]
Hi @lordloh 
About the first issue, we already have an open enhancement in Taiga. You can upvote it: https://tree.taiga.io/project/taiga/issue/1813

About the second idea, I need to understand your workflow. A sprint should be a timeboxed group of User Stories with a dev group focused. Why do you need to move between sprints? How many sprints do you do at the same time?

Thanks! (sorry for the late response you were too fast!)

**Comment by lordloh** [comment]
I understand that nothing prevents me from having 2 active sprints at the same time. I am contemplating if it would be any use to have a month or fortnightly sprint and a week long sprint. Just contemplating.

I would not resort to this if I could assign points to tasks and spread it across 2 sprints. But a US cannot be spread across 2 sprints. So I am thinking of having some week achievable tasks and 2 week achievable tasks and run them as 2 concurrent sprints. I am unable to decide if this is workable or utterly crazy.

**Comment by lordloh** [comment]
Moreover, I have seen people at my work place sit and plan the next 4 sprints. This is another reason why I may want to quickly switch between sprints.

PS: Is there a way I can comment on taiga.io issue site? I seem to be able to do so only via github issues.

Thank you :-)

**Comment by Xaviju** [comment]
@lordloh yes, you can have as many sprints as you need, just wanted to understand better the workflow to write down the enhancement: https://tree.taiga.io/project/taiga/issue/4440

Currently we do not have the comments section open in Taiga for non team members. I will ask the team to open it in the future. For open discussions, you can write to our [mailing list](http://groups.google.co.uk/d/forum/taigaio)

Thanks again
