### ISSUE TITLE
Question: Workflow/Triggers

### ISSUE THREAD

**Issue by MichaelHierweck** [taigaio/taiga-back#800]
Is it possible to implement some kind of trigger to handle status changes of stories, tasks or issues?

I would like to implement some automated status changes such as:
- When a story is assigned to a sprint, update the status from new to selected.
- When a task status changes to "in-progess", update the status of the story to "in-progress".
- When all tasks (of a story) are "done", update the status of the story to "done"
[...]

(Currently our users tend to forget updating the story status when working with the sprint taskboard.)

Is there an API that can be used?

**Comment by superalex** [comment]
Hello @MichaelHierweck 

We had an existing enhancement request to include automated actions (https://tree.taiga.io/project/taiga/issue/3281), I've just added your comments there.

Some teams are using taiga webhooks (https://tree.taiga.io/support/integrations/webhooks/) to listen for changes and the Taiga API (https://taigaio.github.io/taiga-doc/dist/api.html) to automate actions.
