### ISSUE TITLE
#problem in circus configuration

### ISSUE THREAD

**Issue by Fatima-Batool** [taigaio/taiga-back#809]
Then you have to reload your circus configuration restart the other services and start taiga-events:

circusctl reloadconfig
circusctl restart taiga
circusctl restart taiga-celery
circusctl start taiga-events
got error in all commands   Timed out.
A time out usually happens in one of those cases:

#1 The Circus daemon could not be reached.
#2 The Circus daemon took too long to perform the operation

For #1, make sure you are hitting the right place
by checking your --endpoint option.

For #2, if you are not expecting a result to
come back, increase your timeout option value
(particularly with waiting switches)
please help me in resolving this error

**Comment by markidm** [comment]
I am having this problem, I can't complete step 3.5 of the [production setup guide](https://taigaio.github.io/taiga-doc/dist/setup-production.html), even after performing step 6.1. Just get the error described by @Fatima-Batool ... any help?
