### ISSUE TITLE
Spelling error (or missed translation) in title text of base email templates

### ISSUE THREAD

**Issue by AndrewS-Vbosch** [taigaio/taiga-back#812]
example: https://github.com/taigaio/taiga-back/blob/54baf7b4dcaac5f432515e3ce9357293860c0fda/taiga/base/templates/emails/base-body-html.jinja#L428

"Supporti" should probably be "Support"

**Comment by bameda** [comment]
Fixed. Thanks for your feedback @AndrewS-Vbosch
