### ISSUE TITLE
People invited to a repo don't get added if they register publicly(not via the invite)

### ISSUE THREAD

**Issue by johnsonc** [taigaio/taiga-back#814]
A person may recieve multiple invites, and may choose to 
1) sign into one (I haven't tested this)
2) Register with "Sign Up" option

For the latter case, the membership tokens are not read even though I think a signal is being raised. 

This is for  the current stable version.

**Comment by superalex** [comment]
Hello @johnsonc 

I'm trying to reproduce this issue but I can't, could you please detail the steps a bit more?

Regards,
