### ISSUE TITLE
[Question] wiki page syntax highlight style 

### ISSUE THREAD

**Issue by changsijay** [taigaio/taiga-back#815]
Hi, When I paste code on wiki page, the code block back ground is grey,
the C include header is also grey as below picture:
https://i.imgur.com/J0f1E8G.png

Is it possible to change the background color or theme?
I tried to hard code the `style` in `~/.virtualenvs/taiga/lib/python3.5/site-packages/markdown/extensions/codehilite.py` 

```
css_class="codehilite", lang=None, style='default',
```
I changed the 'default' to 'xcode', but no effect.
Would it be better to have option to set the code block theme?
Where I can hard code now to make it not grey background?

Thanks

**Comment by changsijay** [comment]
oh, I found it is defined in taiga-front `codehilite.github.css`, ok, I can customize it now. also I prefer there is an option to choose directly from pygments module styles.

**Comment by bameda** [comment]
We are working in a new editor based on https://kaleidosnet.slack.com/messages/random/ for the next release.

**Comment by bameda** [comment]
We are working in a new editor based on https://github.com/yabwe/medium-editor for the next release.
