### ISSUE TITLE
Login API call should not contain auth type

### ISSUE THREAD

**Issue by stevenroose** [taigaio/taiga-back#820]
It is basically explained here: https://github.com/ensky/taiga-contrib-ldap-auth/issues/24

IMO, it should not be required for developers of third party apps to know what authentication is used.

**Comment by bameda** [comment]
There are multiple posible logins simultaneously (normal, github, bitbucket, google auth) and Taiga can use the same password for all of them.

**Comment by bameda** [comment]
The third party apps developers can overwrite the behaviour too. The ldap plugin allow the dual authentication so the API interface support both of them.

**Comment by stevenroose** [comment]
@bameda Currently the Android app TaigaApp fails when using LDAP. What does he need to do to fix this? I advised him to look at the `loginFormType` field in `conf.json` and put the same value in `"type": "<value>"` in the REST login request.

Is this the way to do it?

**Comment by bameda** [comment]
Yes, you have to change this value too.
