### ISSUE TITLE
Cannot find/add other user into project

### ISSUE THREAD

**Issue by changsijay** [taigaio/taiga-back#821]
Hi, I use [taiga-contrib-ldap](https://github.com/ensky/taiga-contrib-ldap-auth) plugin in my company. And I encourage my teammates to use taiga to manage our team jobs.

Now, a user "alvinchiu" logined, I can see his name in django admin `/admin/users/user/`.
and set him as superuser.

Now I want him to join a created project, I tried to add him from django admin `/admin/projects/project/8/change/` membership section `+`. But I cannot see his name in the menu.

Also, I tried to invite by his email from taigo `/project/devops/admin/memberships`, it says "If users are already registered on Taiga, they will be added automatically. Otherwise they will receive an invitation."
But nothing happened.

**Comment by superalex** [comment]
Hello @changsijay 

The admin won't allow you to do it from that area "/admin/projects/project/8/change/" but you could go to "/admin/projects/membership/" and create a new membership for that user in the project.

Inviting by email from /project/devops/admin/memberships should work if the email is the same, could you please attach a screenshot from that section?

Regards,

**Comment by changsijay** [comment]
I successfully added him into the project, below are some screenshots.

1. `http://10.62.41.188/admin/users/user/`
http://imgur.com/TqGkPlO

2. invite alvin from `http://10.62.41.188/project/devops/admin/memberships`
http://imgur.com/HmPrFRG

3. django logs(email message) when I send invite.
http://imgur.com/WgJv2M6

4. `http://10.62.41.188/admin/projects/membership/`
http://imgur.com/bpeZ51d

5. `http://10.62.41.188/admin/projects/membership/add/`
 :bug: the role menu items are duplicated
http://imgur.com/Z3k0PKr

6. After add alvin as "project owner" , go back to `http://10.62.41.188/admin/projects/membership/`
http://imgur.com/90kRXy2

7. Checking the membership in taiga `http://10.62.41.188/project/devops/admin/memberships`
 :bug: the role show "UX" (should be project owner)
http://imgur.com/WLrDaIP

**Comment by changsijay** [comment]
another trivial :bug is that I am not sure about the plural of "membership", I checked dictionary, it says it is an uncountable noun. :octocat: 

http://imgur.com/oErrhgE

**Comment by bameda** [comment]
The mistakes (5, 6) in the role is because you apply a role to alvin from another project. In 5 the role selector show all roles from all projects and you select a Product Owner from other project, so the front can't show the correct one.

**Comment by bameda** [comment]
The typo was fished here: https://github.com/taigaio/taiga-back/commit/e4f96e605343c237373a1d4fa55d44b464138085

**Comment by changsijay** [comment]
Hi @bameda , I am not sure why alvin's role menu items are duplicated
I sorted user as below picture, now alvin is only one role in devops project.
http://imgur.com/6oxKesH

**Comment by bameda** [comment]
the role is not duplicate, you create a member in project X with role from project Y for alvin And there is two roles one in project X and other in project Y with the same name

**Comment by bameda** [comment]
If you want to add members to a project in the superadmin panel please edit a project and add it in this panel, not in the member form because the role selector is not filter correctly and you see all roles instead of related ones with the selected project

**Comment by changsijay** [comment]
got it, thanks a lot :dancers:

**Comment by bameda** [comment]
I've disabled the Add action here (https://github.com/taigaio/taiga-back/commit/4a28721c733f80452c29f8b66bece095b74d5f1a) to prevent mistakes

![image](https://cloud.githubusercontent.com/assets/877218/18343480/da018150-75b3-11e6-93bd-172a116c1348.png)

![image](https://cloud.githubusercontent.com/assets/877218/18343490/e2cc8e24-75b3-11e6-8366-4461fc85e87d.png)

**Comment by bameda** [comment]
You are welcome. Thanks to you for report this bug and for using Taiga

**Comment by bameda** [comment]
No, it's not a good idea to use the superadmin panel. Use the project admin panel to add new members to the project.

**Comment by afrankenstine** [comment]
@bameda Thank you for the reply. The problem I am facing is, even as the super admin I don't have access to view the projects created by other users which I am not a part of from the project admin panel. 

Is there a way to access such projects from project admin panel ?
