### ISSUE TITLE
NoSuchFieldError with TConstruct

### ISSUE THREAD

**Issue by mobehun** [taigaio/taiga-back#822]
With TConstruct 2.5.0 and TAIGA 1.1.3 I get this crash: http://pastebin.com/pikcXu3p
And with TAIGA 1.1.2 I get this: http://pastebin.com/cEjzvAiX
forge: 12.18.1.2077

With TConstruct 2.4.0 and TAIGA 1.1.2 it works fine.

**Comment by superalex** [comment]
Hello @mobehun 

I think you are talking about a different "taiga", I can see in your logs: 	

`UCH	taiga{${version}} [Tinkers Alloying Addon] (taiga-1.10.2-1.1.3.jar) 
`

This is not the project you are looking for ;)
