### ISSUE TITLE
Configure default project text/ properties

### ISSUE THREAD

**Issue by Reagang** [taigaio/taiga-back#833]
Is it possible to change the wording of text eg. Backlog to Tasks ? I would also like to change the default points to be hours. Which file can I edit to do these things.

Thanx for a great tool.

**Comment by bameda** [comment]
Hi Reagang, you can change all text labels in `taiga-front/app/locales/taiga/locale-en.json`

For the backend you can update locales too or change directly in the code.

**Comment by Reagang** [comment]
Thanx alot!
I managed to change the text in taiga-front.
My locale path was slightly different:
**/taiga-front/dist/v-1468840853868/locales/taiga/locale-en.json.**
My taiga-backend locales folder is empty though.

**Comment by bameda** [comment]
Yes, this is because you are using taiga-front-dist. 

In taiga-back, the locales are in `taiga-back/taiga/locale/`

**Comment by Reagang** [comment]
i am trying to rename the default member names eg UX, Front, etc.
I check the following files:
**django.po** - /home/taiga/taiga-back/taiga/locale/en/LC_MESSAGES
**translations.py** - /home/taiga/taiga-back/taiga/projects
but nothing sadly nothing changed. I'm not sure if it is the right files or if there are more files that requires change.

**Comment by bameda** [comment]
Roles are data, so your changes in its names have no effect. In this case you have to change in the current project, or change the defaul projects templates in the database or change and reload the fixtures for new projects.

Remember that you have to regenerate locales (.mo files) before your changes.

**Comment by Reagang** [comment]
Hi bameda,

Thank you for taking the time to answer my questions. 
I left my db settings to  following values in **settings/common.py** :

`DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "taiga",
    }
}`

So i'm trying to view the data in the database using **pgAdmin** but I can't connect to it. 
I'm using the Host ip address, dbname: taiga, user : taiga with no password but pgadmin requires a port number. I tried **5432** but  I keep getting the following error:
`could not connect to server: Connection refused (0x0000274D/10061)
Is the server running on host "**VM IP address**" and accepting
TCP/IP connections on port **5432**?`

I can change the db settings but i'm afraid it will mess up the existing data....

**Comment by bameda** [comment]
Your settings are in `settings/local.py`, `settings/common.py` are generic settings and they could be overwritten by `local.py`. 

You don't need to access to the databasse literally.

- For your curent projects you have to access to Admin > Permissions in your project page and change the name of the roles.
- For new projects you have to update projects templates and there is a lot of modes to do this without accessing directly to the data base.
    - One option is in the superadmin panel at `https://<your-taiga-back-host>/admin/projects/projecttemplate/` you have to edit the two default templates and change the field "Roles".
    - Other options is modify the file `taiga-back/taiga/projects/fixtures/initial_project_templates.json` and edit roles. Then reload the fixture with
```
cd taiga-back
workon taiga
python manage.py loaddata initial_project_templates
```

**Comment by Reagang** [comment]
Perfect! 
Wow this is awesome. Great work!
