### ISSUE TITLE
Epics not available for user-created projects

### ISSUE THREAD

**Issue by jimeney** [taigaio/taiga-back#834]
Running a fresh Taiga install from today, provisioned using Taiga Scripts in Server mode.

Issue: User created projects do not have 'Epics' available in the Admin -> Projects -> Modules to be enabled by the owner.

Furthermore, adding the user 'Admin' to any 'user created' project (owner uses invite functionality and 'admin' user follws the signup link, logging in with their Taiga account), with the intention to enable 'Epics' means that the 'Admin' user effectively removes 'Epics' functionality from all projects.

**Comment by jimeney** [comment]
This appears to be a temporary issue, and may well resolve itself from a combination of either a) passage of time, b) logging out and back in or c) clearing browser cache / forcing a refresh

**Comment by bameda** [comment]
Ok, so I close this bug. Normally you have to refresh your browser after an upgrade.
