### ISSUE TITLE
Combine Taiga with github/bitbucket projects

### ISSUE THREAD

**Issue by Chris2011** [taigaio/taiga-back#84]
What I really want to see is to combine taiga with github and/or bitbucket projects to manage existing projects. So for this you have to use the API's of those systems to integrate those systems into taiga. That would be awesome.

Regards

Chris

**Comment by lukaszsajkowski** [comment]
I agree with sandeshdamkondwa.
It would be great to have this feature. Like in Pivotal Tracker.

**Comment by jmatsushita** [comment]
Hi there, I'm giving a shot at Taiga and like it so far. Really great that you are doing this as an open source project and the UX and design work that went into the software is really impressive! You're setting the bar higher for open source projects. Well done.

A comment on a small improvement that would really make a difference in the documentation (in particular of the Github integration, but also for other integrations - I've tried the slack one). Could you at the beginning of each documentation page, give a short summary of what the integration does (at this stage) and briefly how to use it? Right now I assume it only has this hook to change statuses through commit messages? You need to go to the very bottom of the page and click a link to find out now. Better to have a "What it does" section first and then a "How to configure it" section next, no?

Also on that linked page (https://taiga.io/support/changing-elements-status-via-commit-message/) it says we can find the list of possible status messages in US STATUSES... I guess I "could" grep the code for that, but it could be friendlier :)

**Comment by superalex** [comment]
Thanks for your comments @jmatsushita you are right, our documentation should be more specific about what integration does.

About finding "US STATUSES" it refers to checking them on admin -> custom attributes -> us statuses. You don't need to grep any code to find it (statuses are customizable per project so greping wouldn't work :) )

Regards,

**Comment by Luukyb** [comment]
+1 for @jmatsushita. I didn't see the link to the documentation at first, and I was looking for a hook called "taiga" in bitbucket.

**Comment by tribou** [comment]
Looks like Taiga has a lot of [GitHub integration](https://taiga.io/support/github-integration/) now.  And I noticed you can [change issue status with commit messages](https://taiga.io/support/changing-elements-status-via-commit-message/).  Would it be feasible to also have an option that automatically changes integrated GitHub issues to "Closed" in Taiga when they are closed in GitHub?  (and back to "Open" when they are re-opened?)

Perhaps there would need to be a designation that relates GitHub's "closed" state to Taiga's "closed" slug and GitHub's "open" state to Taiga's "new"?

**Comment by superalex** [comment]
Hello @tribou,

It would be feasible and it's something we would like to add in the future, we are still in what we consider are our first steps with github integration :+1: 

Regards,

**Comment by levivm** [comment]
Is there any way to see github  commit link from taiga ?

**Comment by superalex** [comment]
Hello @levivm 

Actually not, but if could be a good improvement, we will think about it :+1:

**Comment by levivm** [comment]
@superalex  Thx, it would be very nice. In fact, I want to use taiga but without that feature is difficult to review code from a certain task and approve status change.

**Comment by alfcalmar** [comment]
Nice! And if possible make that so we can see bitbucket commit link from taiga too :)

**Comment by SpacyRicochet** [comment]
A question about the Gitlab/Bitbucket/Github integration. Currently the web-hooks allow changes in Gitlab to be reflected in Taiga. Is it also already to reflect changes in Taiga back to Gitlab (or any of the other flavours)?

**Comment by alearcy** [comment]
@SpacyRicochet +1

**Comment by webmaven** [comment]
:+1:

**Comment by yakateam** [comment]
@SpacyRicochet +1

**Comment by rewop** [comment]
+1. great job with Taiga by the way

**Comment by webmaven** [comment]
@superalex, do you have an answer for @SpacyRicochet?

**Comment by superalex** [comment]
It's something we would like to include but we haven't done any progress on it.

**Comment by SpacyRicochet** [comment]
@webmaven Sadly, it's been awhile since I've used Taiga. It didn't catch on in my team as default issue tracking, shouting over monitors and writing whiteboards covered our small four-person team needs well enough. I'll check back if we grow some more, since Taiga is still lovely :)

**Comment by superalex** [comment]
It makes sense @SpacyRicochet!, anyway I hope to see you soon again in Taiga! ;)

**Comment by webmaven** [comment]
@superalex, how does the Taiga team prioritize features?

**Comment by zacbri** [comment]
+1 for 2-way sync with Gitlab. Not much use for issues sync until it is implemented unfortunately.

**Comment by sagendejonge** [comment]
Integration with Bitbucket is great!  However when I push push up a change to Bitbucket I can't see the commit message or link in Taiga.  Is there a way to do this?

**Comment by harrybailey** [comment]
+1 for 2-way sync with Gitlab. I've actually posted a question about it to the Google group before I was pointed here.

https://groups.google.com/forum/#!topic/taigaio/pRyBnoFmDYw

**Comment by Megatronic79** [comment]
+1 for 2-way sync with Gitlab and import of existing projects

**Comment by samundra** [comment]
I am unable to figure out way to see the commit message in taiga that I pushed in bitbucket. I was expecting somekind of commit message that appears in Jira task. I am only able to change the issue status through commit message. 

Thanks for the great tool. :+1:

**Comment by webmaven** [comment]
@superalex, I would still like to know how the Taiga team prioritize features.

**Comment by Chris2011** [comment]
Atm I don't use taiga anymore, but would also like to know what happens to this :)

**Comment by Chris2011** [comment]
Bitbucket projects seems supported now: https://tree.taiga.io/support/integrations/bitbucket-integration/

**Comment by Chris2011** [comment]
And here it is for github: https://tree.taiga.io/support/integrations/github-integration/ and I can see gitlab too. So due to this integrations, I will close this ticket. Thx for the work.
