### ISSUE TITLE
Question: Email overrides

### ISSUE THREAD

**Issue by florisvanwoudenberg** [taigaio/taiga-back#840]
There is a folder taiga-back/email_overrides/templates/emails.
For me it seems that this is the place to adjust the templates so that they match our own identity.
Is this correct?
If not, what is the best practice to send out email in our own identity?

**Comment by bameda** [comment]
Create an external app (a normal django app), like a contrib plugin, call 'taiga-customization' for example that overwrite templates so you don't need to modify taiga-back code.

```
taiga-back/
taiga-back/settings/locale.py <- ADD taiga-customization to INSTALLED_APPS
(...)
taiga-customization/
taiga-customization/setup.py
taiga-customization/email_overriders/
taiga-customization/email_overriders/templates/emails
(...)
```

With this approach you can have two different repositories, one the oficial taiga-back and other one in your company with your changes. So in the future it will be more easy to update the taiga instance because you have not modified the base code.

**Comment by KeizerDev** [comment]
@bameda As I can see we're not the only one with this issue( #700 ), could you maybe help us a bit more. I've started a repo which I can invite you to if you want.
It seems to be a huge opportunity for taiga itself to implement something like this.

**Comment by bameda** [comment]
As I say you only have to copy the structure of some contrib plugin, but only the back content, like https://github.com/taigaio/taiga-contrib-mailchimp-subscription/tree/master/back

And then copy all templates emails and do the modifications you want.

This plugin is a customisation for every company so I think it won't be very reusable.

What are your questions?

**Comment by KeizerDev** [comment]
@bameda how can I only overwrite a default template route  in a plugin, can't find anything like that.

Or do you think you should rewrite the whole mail handler with your new templates in the plugin?

**Comment by bameda** [comment]
You can rewrite only one template or all or some of then. Like I explain in a previous comment (https://github.com/taigaio/taiga-back/issues/840#issuecomment-251622403)

**Comment by KeizerDev** [comment]
@bameda So only with that structure it will be okay? I don't have to write any code in the plugin itself, just that structure?

**Comment by bameda** [comment]
Yes, setup file and the content overwritten templates.

**Comment by KeizerDev** [comment]
@bameda 
I've cloned my repo in my python packages path so it is recognized by taiga and this just work. I only can't get it to work to overwrite the templates.

My setup file looks like this:
```
import versiontools_support
from setuptools import setup, find_packages

setup(
    name = 'taiga-email-overrides',
    version = ":versiontools:email_overriders:",
    description = "The Taiga plugin for custom templates",
    long_description = "",
    keywords = 'taiga, Email, integration',
    author = 'Company',
    author_email = 'info@company.nl',
    url = 'https://github.com/taigaio/taiga-contrib-slack',
    license = '',
    include_package_data = True,
    packages = find_packages(),
    install_requires=[],
    setup_requires = [
        'versiontools >= 1.9',
    ],
    classifiers = [
        "Programming Language :: Python",
        'Development Status :: 4 - Beta',
        'Framework :: Django',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: GNU Affero General Public License v3',
        'Operating System :: OS Independent',
        'Programming Language :: Python',
        'Topic :: Internet :: WWW/HTTP',
    ],
)
```
And my repo has this structure:
```
> tree
.
├── email_overriders
│   ├── __init__.py
│   └── templates
│       └── emails
│           ├── base-body-html.jinja
│           ├── hero-body-html.jinja
│           ├── membership_invitation-body-html.jinja
│           ├── membership_invitation-body-text.jinja
│           ├── membership_invitation-subject.jinja
│           ├── membership_notification-body-html.jinja
│           ├── membership_notification-body-text.jinja
│           ├── membership_notification-subject.jinja
│           ├── transfer_accept-body-html.jinja
│           ├── transfer_accept-body-text.jinja
│           ├── transfer_accept-subject.jinja
│           ├── transfer_reject-body-html.jinja
│           ├── transfer_reject-body-text.jinja
│           ├── transfer_reject-subject.jinja
│           ├── transfer_request-body-html.jinja
│           ├── transfer_request-body-text.jinja
│           ├── transfer_request-subject.jinja
│           ├── transfer_start-body-html.jinja
│           ├── transfer_start-body-text.jinja
│           ├── transfer_start-subject.jinja
│           ├── updates-body-html.jinja
│           └── updates-body-text.jinja
├── MANIFEST.in
├── README.md
├── setup.py
└── versiontools_support.py

3 directories, 27 files
```

And in my `taiga-back/settings/local.py` I've done the following:
```
INSTALLED_APPS += ["taiga-email-overrides"]
```

What am I doing wrong?

**Comment by bameda** [comment]
The error is because the directory is `email_overriders` but in INSTALLED_APPS is `taiga-email-overrides`.

Use 'taiga_email_overrides' to rename the directory and in INSTALLED_APPS. 

(But a good rule to a best naming will be use something like `taiga-contrib-...`.)

Install the package (with `pip install -e .` like in other plugins) instead of copy in your python path.

In setup.py `url = 'https://github.com/taigaio/taiga-contrib-slack',` is wrong too. 


Regards.

**Comment by KeizerDev** [comment]
@bameda It still doesn't work.

This is my working tree.
```
taiga_email_overrides
├── email_overriders
│   ├── __init__.py
│   └── templates
│       └── emails
│           ├── base-body-html.jinja
│           ├── hero-body-html.jinja
│           ├── membership_invitation-body-html.jinja
│           ├── membership_invitation-body-text.jinja
│           ├── membership_invitation-subject.jinja
│           ├── membership_notification-body-html.jinja
│           ├── membership_notification-body-text.jinja
│           ├── membership_notification-subject.jinja
│           ├── transfer_accept-body-html.jinja
│           ├── transfer_accept-body-text.jinja
│           ├── transfer_accept-subject.jinja
│           ├── transfer_reject-body-html.jinja
│           ├── transfer_reject-body-text.jinja
│           ├── transfer_reject-subject.jinja
│           ├── transfer_request-body-html.jinja
│           ├── transfer_request-body-text.jinja
│           ├── transfer_request-subject.jinja
│           ├── transfer_start-body-html.jinja
│           ├── transfer_start-body-text.jinja
│           ├── transfer_start-subject.jinja
│           ├── updates-body-html.jinja
│           └── updates-body-text.jinja
├── MANIFEST.in
├── README.md
├── setup.py
└── versiontools_support.py

```
I've done like you said and improved my setup.py:
```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import versiontools_support
from setuptools import setup, find_packages

setup(
    name = 'taiga_email_overrides',
    version = ":versiontools:email_overriders:",
    description = "The Taiga plugin for custom templates",
    long_description = "",
    keywords = 'taiga, Email, integration',
    author = '-',
    author_email = 'info@-.nl',
    url = 'https://github.com/studio-fonkel/taiga-email-overrides',
    license = '',
    include_package_data = True,
    packages = find_packages(),
    install_requires=[],
    setup_requires = [
        'versiontools >= 1.9',
    ],
    classifiers = [
        'Programming Language :: Python',
    ],
)

```
But it's still not working. What am I doing wrong?

**Comment by KeizerDev** [comment]
@bameda I've made sure the `INSTALLED_APPS` was also right, but still no luck..

**Comment by bameda** [comment]
You are still using `email_overriders` instead of `taiga_email_overwrites`

```
taiga_email_overrides
├── email_overriders
│   ├── __init__.py
│   └── templates
│       └── emails
(...)
```

With my recomendations the app name should be `taiga-contrib-email-overrides` so the module and django app should be `taiga_contrib_email_overrides`

So, in setup.py use

```
name = "taiga-contrib-email-overrides"
(...)
```

Your dir tree must be

```
taiga-contrib-email-overrides
├── setup.py
├── taiga_contrib_email_overrides
│   ├── __init__.py
│   └── templates
│       └── emails
(...)
```

And in `taiga-back/settings/local.py`
```
INSTALLED_APPS += ["taiga_contrib_email_overrides"]
```

**Comment by bameda** [comment]
Where is your code? Can I check your repository?

**Comment by KeizerDev** [comment]
@bameda it's here https://github.com/KeizerDev/taiga-contrib-email-overrides, i've made you collaborator

**Comment by bameda** [comment]
ok, I was wrong the overrider app must be first because django use the first appearance of the template file instead of the last one.

So change in `settings/local.py'

```
INSTALLED_APPS += ["taiga_contrib_email_overrides"]
```
by

```
INSTALLED_APPS = ["taiga_contrib_email_overrides"] + INSTALLED_APPS
```

**Comment by KeizerDev** [comment]
@bameda Thanks! That was it :+1: 

Thanks for your help

**Comment by bameda** [comment]
You are welcome :smile: , and sorry for my mistake.

If you want to play with emails there is a useful command to test the results

```
cd taiga-back
workon taiga
./manage.py test_emails <email_address>
```

This command send example of all the mails in taiga to your `<email_address>`.

The code of this command is in `taiga-back/taiga/base/management/commands/test_emails.py` 
https://github.com/taigaio/taiga-back/blob/master/taiga/base/management/commands/test_emails.py.
