### ISSUE TITLE
[Q] What is the best way to get helpful logs to debug configuration?

### ISSUE THREAD

**Issue by kota65535** [taigaio/taiga-back#85]
I've started to install taiga with [taiga-docker](https://github.com/kaleidos-ventures/taiga-docker/). 
When I have some configuration mistake, taiga-back often returns 500, but the container does not show any informational log.
For example, If I try password recovery when the email settings are incomplete, I got only logs like below:

```
Mar 15 04:17:42 ip-172-20-4-178 docker-compose[13858]: taiga-gateway_1          | 172.20.0.76 - - [14/Mar/2022:19:17:42 +0000] "POST /api/v1/users/password_recovery HTTP/1.1" 500 141 "http://taiga-01.sys.ai-partners.jp:9000/forgot-password" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.51 Safari/537.36" "-"
```

Cloud you tell me what is the best way to get more helpful logs for debugging configurations?

**Comment by yamila-moreno** [comment]
Hi there!

Do you know that we have [Taiga Community](https://community.taiga.io/) for questions? Please, check there; maybe another user has already ask something similar. If not, create your own. There are people there willing to help, members of the Taiga team members and other users.

To simplify  the process, we will systematically close all issues that are general support questions and redirect people to Taiga Community.

Taiga Team
