### ISSUE TITLE
how to use avatar https url?

### ISSUE THREAD

**Issue by yungang** [taigaio/taiga-back#858]
In old version, there is a const base url:

GRAVATAR_BASE_URL = "//www.gravatar.com/avatar/{}?{}"

so, I can change this to use https, but in newest master, this string has been deleted, because of network, I only can use https, what should I do or set ?

**Comment by superalex** [comment]
Hello @yungang 

All the gravatar generated urls are now related to taiga-front (that setting won't do anything now) and all these urls are generated with https. Could you show an example of  a bad generated url?

**Comment by yungang** [comment]
thanks for your response。
I use taiga-front-pre.
In [user setting] page, when I set [Use default Image], it report(In chrome dev tool):
GET http://i0.wp.com/192.168.1.138/v-1476536352617/images/user-avatars/user-avatar-03.png 404 (Not Found)

But I dont know how to process [http://i0.wp.com/] ...
local host address is 192.168.1.138

**Comment by superalex** [comment]
As you are not exposing your instance to the outside that url will never work. You can disable gravatar setting "gravatar" to false in your conf.json file

**Comment by htotoo** [comment]
Should have a setting that sets the gravatar to one of the fallback images (mm, identicon, monsterid, ...)
