### ISSUE TITLE
Markdown renderer removes content in curly brackets ({{ ... }})

### ISSUE THREAD

**Issue by frederik-elwert** [taigaio/taiga-back#861]
When I want to use django template syntax in comments, parts in curly brackets (i.e., django variable syntax) are removed from the output:

```
Use `{{ request.scheme }}://{{ request.get_host }}` in templates.
```

renders as:

Use `://` in templates.

Django templatetag syntax (`{% %}`) is fine, just variable syntax is broken.

This happens on taiga.io, current Firefox.

**Comment by bameda** [comment]
We are working in a new wysiwyg editor similar to the medium editor. But right now you can use \`\`\` instead '

```
    Use 
    ```
    {{ request.scheme }}://{{ request.get_host }}
    ```
    in templates.
```
