### ISSUE TITLE
Modify settings/local.py.sample to connect to db successfully

### ISSUE THREAD

**Issue by RSchlenker** [taigaio/taiga-back#866]
Hi Guys,
I recently tried to install taiga using the development instructions provided in the documentation.
I had the same issue as is explained and solved in that particular case in https://groups.google.com/forum/#!topic/taigaio/f6qpgLf8Cjk 
The suggestions didn't worked for me, I had to modify the HOST configuration in the local.py file, to let the HOST be localhost. This should be adapted to the sample file if I don't oversee any mistakes.
The setup worked for me so far.

Kind regards,
R. Schlenker

Thanks for reporting!

**Comment by superalex** [comment]
Hello!,

Were you doing the installation on a ubuntu 16.04?, (all the installation instructions are assuming that OS).
