### ISSUE TITLE
Taiga attempting to Send Emails to example@example.com

### ISSUE THREAD

**Issue by ndianabasi** [taigaio/taiga-back#869]
I noticed that Taiga is attempting to send emails to example@example.com which are bouncing.

The email subjects are like these:
```
[Django] ERROR (EXTERNAL IP): Internal Server Error: /api/v1/memberships/49
[Django] ERROR (EXTERNAL IP): Internal Server Error: /api/v1/userstories/66
[Django] ERROR (EXTERNAL IP): Internal Server Error: /api/v1/projects/1
```

Taiga instance is self-hosted.

Taiga version is 2.1.0.

What can I do rectify this issue so that Django can deliver this error notifications to project SysAdmin email.

Thank you.

**Comment by bameda** [comment]
in `taiga-back/settings/local.py` add something like this

```python
ADMINS = (
    ("Admin1", "example1@example.com"),
    ("Admin2", "example2@example.com"),
    ("Admin3", "example3@example.com"),
)
```

and restart the server.
