### ISSUE TITLE
inconsistent behavior of issues and tasks apis

### ISSUE THREAD

**Issue by mjrk** [taigaio/taiga-back#873]
If I want to query issues or user stories assigned of any of a list of users, I can do

    curl localhost:8000/api/v1/issues?assigned_to=11,10
    curl localhost:8000/api/v1/userstories?assigned_to=11,10

if I do the same for tasks

    curl localhost:8000/api/v1/userstories?assigned_to=11,10

I get

    {"_error_message": "Error in filter params types.", "_error_type": taiga.base.exceptions.BadRequest"}

The expected behavior would be to be consistent with the other APIs. It happens on the current master.

I'd offer to fix it (+test) if you point me in the right direction. Some digging did not make the difference to the other routes obvious to me.

**Comment by bameda** [comment]
Ummmm it seems a bug because filters in taskboard panel don't work properly. We'll work on it soon to resolve the problem.

Thanks for report this.

**Comment by superalex** [comment]
Thanks for reporting @mjrk it should be fixed now.

Regards,

**Comment by mjrk** [comment]
Cool, thanks for you great work
