### ISSUE TITLE
conn = _connect(dsn, connection_factory=connection_factory, async=async) django.db.utils.OperationalError: FATAL: role "mathiasburton" does not exist

### ISSUE THREAD

**Issue by mathiasburton** [taigaio/taiga-back#882]
**Before adding an issue**
Please ensure that your issue is not already reported in our [issues list](https://tree.taiga.io/project/taiga/issues?order_by=-created_date).
If this issue was already reported, remember that you can upvote it to raise its importance.
I found similar issues, but not mine. 

**Do you want to request a *feature* or report a *bug*?**
report a bug

**What is the current behavior?**
conn = _connect(dsn, connection_factory=connection_factory, async=async) django.db.utils.OperationalError: FATAL: role "mathiasburton" does not exist

**If the current behavior is a bug, please provide the steps to reproduce.**
I am trying to set up Taiga on an Azure ubuntu image. Most of the process has gone smoothly until I tried to populate the initial data. I’m following from http://taigaio.github.io/taiga-doc/dist/setup-production.html

I tried to run
python
 manage.py migrate —noinput

That gave me the error: 
conn = _connect(dsn, connection_factory=connection_factory, async=async) django.db.utils.OperationalError: FATAL: role "mathiasburton" does not exist

I tried to follow advice from:
http://stackoverflow.com/questions/12316819/django-database-connection-error 

and input 
psql -u postgres createuser -P mathiasburton

I got back 
/usr/lib/postgresql/9.5/bin/psql: invalid option -- ‘u'

**What is the expected behavior?**
I was expecting to complete the initial data and have a new user admin with password 123123.

**Is it happening in taiga.io or in your own instance?**
my own instance on installation

**What browser/version are you using?**
I'm on an ubuntu image on Microsoft Azure on a mac, working in Chrome.

**Are there any console errors *(Ctrl + F12)* in red?**
no 

Thanks for reporting!

**Comment by superalex** [comment]
https://tree.taiga.io/project/taiga/issue/3640 answer solved the problem.
