### ISSUE TITLE
How to add a global role?

### ISSUE THREAD

**Issue by karlolopez** [taigaio/taiga-back#884]
Hi, I have an instance of taiga and I would like to know how to achive the following implementation, I want to create a global role, its kind of different to superuser, an example can help me to explain better:

The main difference between this roles is in project creation:

1.- Main (This one can create projects)
2.- Second (This one cant create projects, but it can be assigned to projects, even as project admin)

Thanks :)

**Comment by superalex** [comment]
Hello @karlolopez 

Taiga roles are associated per project but don't include the "create project" permissión. A user can create project if it fits on theirs MAX_PRIVATE_PROJECTS_PER_USER and MAX_PUBLIC_PROJECTS_PER_USER.

You could set those values in your local.py file to 0 (so no new users can create projects by default) and then update those values for users who you want to have privileges to create new projects.
