### ISSUE TITLE
CHANGE_NOTIFICATIONS_MIN_INTERVAL usage and change notification email noise

### ISSUE THREAD

**Issue by clmanalo** [taigaio/taiga-back#891]
On our self hosted taiga updated to v3.0, we tried following the commands indicated found in this git issue (#731) to reduce the amount of emails being received per change. I set CHANGE_NOTIFICATIONS_MIN_INTERVAL to 3000 seconds and, for the mean time, I manually triggered ```python manage.py send_notifications``` after around 6 minutes. 

I noticed that the notifications sent out aren't compiled in one email as mentioned in #731. The notifications of each change were sent out. So if I did three changes, there were three emails instead of just one. Is this really the behavior of this?

**Comment by superalex** [comment]
It depends on when you did those changes, if done in the CHANGE_NOTIFICATIONS_MIN_INTERVAL range if time they should be included in the same email (it tries to mix consecutive changes, not all the changes). The frequency you execute the command won't affect directly the number of emails sent.

Regards,

**Comment by clmanalo** [comment]
hi @superalex . Consecutive changes on the same field would be in the same email? If not, the emails would be separate? I did all the changes within the interval specifed before triggering the command. 

thanks

**Comment by superalex** [comment]
Yes, consecutive changes on the same item in the interval specified should be in the same email.

**Comment by clmanalo** [comment]
hi @superalex. i was doing some testing. i set the change interval to three minutes (180) seconds and changed a custom field three times within a three minute period. The values are

10,000,000,000.00 -> starting value
50,000.00
100,000.00
70,000.00 -> ending value

I only got an email for the final change from 100,000.00 to 70,000.00. is this correct? thanks

**Comment by superalex** [comment]
No, it shouldn't, are you sure you saved the changes on each update?

I've done a test with a custom field called "velit" and after three consecutive changes my email looks like:

![image](https://cloud.githubusercontent.com/assets/1579633/20746348/b111f374-b6e5-11e6-897b-cb51c6bef816.png)

**Comment by clmanalo** [comment]
hi @superalex . yes i was saving it on each update. i will review the code again. there may have been a customization which affected this. but at least i have a baseline to go on. i'll send another message again if i find something. thanks again.

**Comment by superalex** [comment]
Ok! ;)

**Comment by clmanalo** [comment]
hi @superalex after a bit of review, i found that the there was custom code done before which limited the number of changes sent to only the last change done. i remove that custom code and returned the one shipped with taiga and it worked :) thanks
