### ISSUE TITLE
Failure to send email will cause error

### ISSUE THREAD

**Issue by wxchenxueqi** [taigaio/taiga-back#892]
my mail account server didn't accept the taiga mail , so the api server often error.
how to edit the local.py or the source to make that i can run the api server without 'send mail error'?
thanks

**Comment by superalex** [comment]
Hello @wxchenxueqi 

If Taiga is working in synchronous mode and the email server fails the action trying to send the email will also fail (save, delete...)

You can make Taiga notifications work in asynchronous mode if you set "CHANGE_NOTIFICATIONS_MIN_INTERVAL" to a value different than 0, this setting assumes you are manually calling the send_notifications command "python manage.py send_notifications" (the easiest way should be doing it from a cron job)

Regards!,
