### ISSUE TITLE
no notifications are sent

### ISSUE THREAD

**Issue by rufinus** [taigaio/taiga-back#894]
In my local Installation no notifications are sent. 
The mail setup itself is working, i get for example the password recovery mail.
But on mentions in comments like `@username` no mail is sent.

It was confirmed the username has notifcations enabled for this project. 

What can i do to further debug this?

**Comment by superalex** [comment]
Hello @rufinus what kind of installation did you follow development or production?.

**Comment by rufinus** [comment]
@superalex production.

**Comment by superalex** [comment]
Did you customize your email settings?, if you are using a local email server you could probably check your /var/log/mail.log file to see if the emails are sent.

Regards,

**Comment by rufinus** [comment]
i use my mail server. i dont see any mails sent in the logs. but password recovery itself is working.

here is the complete local.py:
```
from .common import *

MEDIA_URL = "https://taiga.myhost.at/media/"
STATIC_URL = "https://taiga.myhost.at/static/"
ADMIN_MEDIA_PREFIX = "https://taiga.myhost.at/static/admin/"
SITES["front"]["scheme"] = "https"
SITES["front"]["domain"] = "taiga.myhost.at"

SECRET_KEY = "xxxxxx"

DEBUG = False
TEMPLATE_DEBUG = False
PUBLIC_REGISTER_ENABLED = False

DEFAULT_FROM_EMAIL = "hostmaster@myhost.at"
SERVER_EMAIL = DEFAULT_FROM_EMAIL

EVENTS_PUSH_BACKEND = "taiga.events.backends.rabbitmq.EventsPushBackend"
EVENTS_PUSH_BACKEND_OPTIONS = {"url": "amqp://taiga:xxxxxx@localhost:5672/taiga"}

# Uncomment and populate with proper connection parameters
# for enable email sending. EMAIL_HOST_USER should end by @domain.tld
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_USE_TLS = False
EMAIL_HOST = "mail.myhost.at"
#EMAIL_HOST_USER = "hostmaster@myhost.at"
#EMAIL_HOST_PASSWORD = ""
EMAIL_PORT = 25

# Uncomment and populate with proper connection parameters
# for enable github login/singin.
#GITHUB_API_CLIENT_ID = "yourgithubclientid"
#GITHUB_API_CLIENT_SECRET = "yourgithubclientsecret"


DEFAULT_FROM_EMAIL = "hostmaster@myhost.at"
CHANGE_NOTIFICATIONS_MIN_INTERVAL = 300
FEEDBACK_ENABLED = True
FEEDBACK_EMAIL = "hostmaster@myhost.at"
STATS_ENABLED = True

INSTALLED_APPS += ["taiga_contrib_slack"]

from .celery import *
BROKER_URL = 'amqp://taiga:xxxxx@localhost:5672/taiga'
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ENABLED = True

```

**Comment by bameda** [comment]
If you set CHANGE_NOTIFICATIONS_MIN_INTERVAL to a vaulue grater than 0 (second), notifications works in async mode and all changes related to a single epic/user story/task/issue in the last N seconds will be compiled into one email, so you have to execute the command `workon taiga && python manage.py send_notifications` periodically to sent emails (maybe with a cron task).

**Comment by rufinus** [comment]
@bameda thank you. i thought it was something simple :)

**Comment by bameda** [comment]
You are welcome. We should add some documentation about this.

**Comment by virse** [comment]
Hey there,

I reopen this issue cause I'm running in to the same issue, but the recommended solution doesn't work. I also receive the password revovery mails or the invitation mails for a new user. So the mail config is fine and working. But I don't receive for example the team mails in a project or any other notifications (due date).

I see no errors in my mail-log.

I've changed my `CHANGE_NOTIFICATIONS_MIN_INTERVAL` to 120 sec and I use a cron task (as recommended) to call the `send_notifications`.

I am running my own instance in production mode, newest taiga-version.

Here is my

**local.py**

```
from .common import *

MEDIA_URL = "https://taiga.xxx.de/media/"
STATIC_URL = "https://taiga.xxx.de/static/"
SITES["front"]["scheme"] = "https"
SITES["front"]["domain"] = "taiga.xxx.de"

SECRET_KEY = "xyz"

DEBUG = False
PUBLIC_REGISTER_ENABLED = False

ADMINS = (
    ("admin", "admin@xxx.de"),
)

ALLOWED_HOSTS = ['taiga.xxx.de']

DEFAULT_FROM_EMAIL = "taiga@xxx.de"
SERVER_EMAIL = DEFAULT_FROM_EMAIL

EVENTS_PUSH_BACKEND = "taiga.events.backends.rabbitmq.EventsPushBackend"
EVENTS_PUSH_BACKEND_OPTIONS = {"url": "amqp://taiga:PASSWORD_FOR_EVENTS@localhost:5672/taiga"}

CELERY_ENABLED = True

DEFAULT_FROM_EMAIL = "taiga@xxx.de"
CHANGE_NOTIFICATIONS_MIN_INTERVAL = 120 #seconds

# EMAIL SETTINGS EXAMPLE
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False # You cannot use both (TLS and SSL) at the same time!
EMAIL_HOST = 'mail.xxx.de'
EMAIL_PORT = 587
EMAIL_HOST_USER = 'admin@xxx.de'
EMAIL_HOST_PASSWORD = 'xyz'
```

And the `cron task`:

`cd /home/taiga/taiga-back && /home/taiga/.virtualenvs/taiga/bin/python manage.py send_notifications`

When I call the above cron command I receive this error:

```
cd /home/taiga/taiga-back && /home/taiga/.virtualenvs/taiga/bin/python manage.py send_notifications ..
Trying import local.py settings...
/home/taiga/taiga-back/taiga/base/utils/iterators.py:56: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'taiga.projects.notifications.models.HistoryChangeNotification'> QuerySet.
  paginator = Paginator(queryset, itersize)
```

Thx for any help and hints on that.

best regards, virse

**Comment by Apurv-P** [comment]
Hello 

After upgrade taiga from 5.0 to 6, I am unable send the email notifications, everything others are working perfectly

my config.py file like this

`import os

from .common import *   # noqa, pylint: disable=unused-wildcard-import

#########################################
## GENERIC
#########################################

DEBUG = False

#ADMINS = (
#    ("Admin", "myemail@gmail.com"),
#)

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'taiga',
        'USER': 'taiga',
        'PASSWORD': 'taiga',
        'HOST': '127.0.0.1',
        'PORT': '27017',
    }
}

SECRET_KEY = "theveryultratopsecretkey"
TAIGA_URL = "https://xyz.com"
SITES = {
    "api": {"domain": "xyz.com", "scheme": "https", "name": "api"},
    "front": {"domain": "xyz.com", "scheme": "https", "name": "front"}
}

# Setting DEFAULT_PROJECT_SLUG_PREFIX to false
# removes the username from project slug
DEFAULT_PROJECT_SLUG_PREFIX = False

#########################################
## MEDIA AND STATIC
#########################################

# MEDIA_ROOT = '/home/taiga/media'
MEDIA_URL = f"{ TAIGA_URL }/media/"
DEFAULT_FILE_STORAGE = "taiga_contrib_protected.storage.ProtectedFileSystemStorage"
THUMBNAIL_DEFAULT_STORAGE = DEFAULT_FILE_STORAGE

# STATIC_ROOT = '/home/taiga/static'
STATIC_URL = f"{ TAIGA_URL }/static/"

#########################################
## EMAIL
#########################################
# https://docs.djangoproject.com/en/3.1/topics/email/
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
CHANGE_NOTIFICATIONS_MIN_INTERVAL = 120  # seconds
DEFAULT_FROM_EMAIL = 'myemail@gmail.com'
#EMAIL_USE_TLS = True
EMAIL_USE_SSL = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465
EMAIL_HOST_USER = 'myemail@gmail.com'
EMAIL_HOST_PASSWORD = 'Password'

#########################################
## EVENTS
#########################################
EVENTS_PUSH_BACKEND = "taiga.events.backends.rabbitmq.EventsPushBackend"
EVENTS_PUSH_BACKEND_OPTIONS = {
    "url": "amqp://taiga:PASSWORD_FOR_EVENTS@localhost:5672/taiga"
}


#########################################
## TAIGA ASYNC
#########################################
CELERY_ENABLED = os.getenv('CELERY_ENABLED', 'True') == 'True'

from kombu import Queue  # noqa

CELERY_BROKER_URL = "amqp://taiga:PASSWORD_FOR_EVENTS@localhost:5672/taiga"
#CELERY_RESULT_BACKEND = None # for a general installation, we don't need to store the results
CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
CELERY_ACCEPT_CONTENT = ['pickle', ]  # Values are 'pickle', 'json', 'msgpack' and 'yaml'
CELERY_TASK_SERIALIZER = "pickle"
CELERY_RESULT_SERIALIZER = "pickle"
CELERY_TIMEZONE = 'Europe/Madrid'
CELERY_TASK_DEFAULT_QUEUE = 'tasks'
CELERY_QUEUES = (
    Queue('tasks', routing_key='task.#'),
    Queue('transient', routing_key='transient.#', delivery_mode=1)
)
CELERY_TASK_DEFAULT_EXCHANGE = 'tasks'
CELERY_TASK_DEFAULT_EXCHANGE_TYPE = 'topic'
CELERY_TASK_DEFAULT_ROUTING_KEY = 'task.default'


#########################################
## CONTRIBS
#########################################
# INSTALLED_APPS += [
#     "taiga_contrib_slack",
#     "taiga_contrib_github_auth",
#     "taiga_contrib_gitlab_auth"
# ]
#
# GITHUB_API_CLIENT_ID = "changeme"
# GITHUB_API_CLIENT_SECRET = "changeme"
#
# GITLAB_API_CLIENT_ID = "changeme"
# GITLAB_API_CLIENT_SECRET = "changeme"
# GITLAB_URL = "changeme"


#########################################
## TELEMETRY
#########################################

ENABLE_TELEMETRY = True

#########################################
##  REGISTRATION
#########################################

PUBLIC_REGISTER_ENABLED = False

#########################################
## THROTTLING
#########################################

#REST_FRAMEWORK["DEFAULT_THROTTLE_RATES"] = {
#    "anon-write": "20/min",
#    "user-write": None,
#    "anon-read": None,
#    "user-read": None,
#    "import-mode": None,
#    "import-dump-mode": "1/minute",
#    "create-memberships": None,
#    "login-fail": None,
#    "register-success": None,
#    "user-detail": None,
#    "user-update": None,
#}

# This list should contain:
#  - Taiga users IDs
#  - Valid clients IP addresses (X-Forwarded-For header)
#REST_FRAMEWORK["DEFAULT_THROTTLE_WHITELIST"] = []

# LIMIT ALLOWED DOMAINS FOR REGISTER AND INVITE
# None or [] values in USER_EMAIL_ALLOWED_DOMAINS means allow any domain
#USER_EMAIL_ALLOWED_DOMAINS = None

# PUCLIC OR PRIVATE NUMBER OF PROJECT PER USER
#MAX_PRIVATE_PROJECTS_PER_USER = None # None == no limit
#MAX_PUBLIC_PROJECTS_PER_USER = None # None == no limit
#MAX_MEMBERSHIPS_PRIVATE_PROJECTS = None # None == no limit
#MAX_MEMBERSHIPS_PUBLIC_PROJECTS = None # None == no limit


#########################################
## SITEMAP
#########################################

# If is True /front/sitemap.xml show a valid sitemap of taiga-front client
#FRONT_SITEMAP_ENABLED = False
#FRONT_SITEMAP_CACHE_TIMEOUT = 24*60*60  # In second


#########################################
## FEEDBACK
#########################################

# Note: See config in taiga-front too
#FEEDBACK_ENABLED = True
#FEEDBACK_EMAIL = "support@taiga.io"


#########################################
## STATS
#########################################

#STATS_ENABLED = False
#STATS_CACHE_TIMEOUT = 60*60  # In second


#########################################
## IMPORTERS
#########################################

# Configuration for the GitHub importer
# Remember to enable it in the front client too.
#IMPORTERS["github"] = {
#    "active": True,
#    "client_id": "XXXXXX_get_a_valid_client_id_from_github_XXXXXX",
#    "client_secret": "XXXXXX_get_a_valid_client_secret_from_github_XXXXXX"
#}

# Configuration for the Trello importer
# Remember to enable it in the front client too.
#IMPORTERS["trello"] = {
#    "active": True, # Enable or disable the importer
#    "api_key": "XXXXXX_get_a_valid_api_key_from_trello_XXXXXX",
#    "secret_key": "XXXXXX_get_a_valid_secret_key_from_trello_XXXXXX"
#}

# Configuration for the Jira importer
# Remember to enable it in the front client too.
#IMPORTERS["jira"] = {
#    "active": True, # Enable or disable the importer
#    "consumer_key": "XXXXXX_get_a_valid_consumer_key_from_jira_XXXXXX",
#    "cert": "XXXXXX_get_a_valid_cert_from_jira_XXXXXX",
#    "pub_cert": "XXXXXX_get_a_valid_pub_cert_from_jira_XXXXXX"
#}
`

cronjob already set
*/2 * * * * cd /home/taiga/taiga-back && /home/taiga/.virtualenvs/taiga/bin/python manage.py send_notifications

need Help

Thank you,
Apurv

**Comment by Apurv-P** [comment]
Resolved it!👍 

just changed EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' instead of EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend" in taiga-back settings/common.py

Thanks
Apurv P.

**Comment by bameda** [comment]
Hi @Apurv-P 

making changes to `common.py` is a very bad idea because you are changing the source code.

The problem is because your crontrab is not using  your `config.py` file

The crontab comand should be something like:

```
cd /home/taiga/taiga-back && DJANGO_SETTINGS_MODULE=settings.config /home/taiga/.virtualenvs/taiga/bin/python manage.py send_notifications
```
It's important to use `config.py` to load all the settings of your environment and not the default values. 

I hope this can help
