### ISSUE TITLE
Change notification recipients

### ISSUE THREAD

**Issue by jerickbixly** [taigaio/taiga-back#895]
Hi

Just to confirm, If changes were done to an epic or any user story, issue, or task would the project member who did the change and the other watchers receive an email about the change or only the other watchers would receive and email and the person who did the change will not receive any.

thanks

**Comment by bameda** [comment]
The person who did the change will not receive any notification. It has no sense, you have made the change so you know about it.

**Comment by jerickbixly** [comment]
thanks @bameda
