### ISSUE TITLE
userstories_rolepoints.points_id set to NULL, breaks API

### ISSUE THREAD

**Issue by pdeffendol** [taigaio/taiga-back#896]
We're running a local install, at version 3.0.0.  

Some of the users reported a project that stopped responding to viewing of user stories, expanding of stories in epics, etc.  After some digging, we found that one of the records in the userstories_rolepoints table for the project had a NULL in the points_id column.  After updating the record with a valid value, everything worked. 

I unfortunately don't know how the data got corrupted, but I'm recording this here as an Issue in case anyone else sees it.  Following is the exception and trace from the API call:

```
DataError at /api/v1/userstories
invalid input syntax for type json
DETAIL:  Expected JSON value, but found "}".
CONTEXT:  JSON data, line 1: {"79":}
Request Method:	GET
Request URL:	http://taiga.****.com/api/v1/userstories?epic=2&include_tasks=true&order_by=epic_order
Django Version:	1.9.2
Exception Type:	DataError
Exception Value:	
invalid input syntax for type json
DETAIL:  Expected JSON value, but found "}".
CONTEXT:  JSON data, line 1: {"79":}
Exception Location:	/opt/taiga/.virtualenv/lib/python3.4/site-packages/django/db/backends/utils.py in execute, line 64
Python Executable:	/opt/taiga/.virtualenv/bin/python3.4
Python Version:	3.4.5
Python Path:	
['/opt/taiga/back',
 '/opt/taiga/back',
 '/opt/taiga/.virtualenv/bin',
 '/opt/taiga/.virtualenv/lib/python3.4/site-packages',
 '/usr/lib64/python34.zip',
 '/usr/lib64/python3.4',
 '/usr/lib64/python3.4/plat-linux',
 '/usr/lib64/python3.4/lib-dynload',
 '/opt/taiga/back']
Server time:	Fri, 9 Dec 2016 22:10:20 +0000
```

![data](https://cloud.githubusercontent.com/assets/8208/21066546/5403da2c-be23-11e6-8183-f9adbb3af479.png)

**Comment by superalex** [comment]
Thank you very much for reporting @pdeffendol 

We have been trying to reproduce the issue but we can't, we have also checked our instance at tree.taiga.io and we can't find any row with those problems:

```
taiga=> SELECT COUNT(*) from userstories_rolepoints where role_id=NULL;
 count 
-------
     0
(1 row)

taiga=> SELECT COUNT(id) from userstories_rolepoints;
  count  
---------
 3172807
(1 row)

```
