### ISSUE TITLE
Question: Email notification receipt on watched public project

### ISSUE THREAD

**Issue by jerickbixly** [taigaio/taiga-back#897]
Hi

i was doing some testing on my machine of taiga and i noticed that i could watch a user story for a public project and receive an email from this if there are changes but that project won't be in my notifications -> email page. Is my assumption correct that the email page only lists projects you're a member of and does not include projects where you have watched user stories but you're not a member of those projects? 

thanks

**Comment by superalex** [comment]
@jerickbixly you are right, you can check your watched elements accesing to https://tree.taiga.io/profile and clicking on the watched section

Regards,

**Comment by jerickbixly** [comment]
thanks @superalex

**Comment by superalex** [comment]
You are welcome ;)
