### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by Mochaka** [taigaio/taiga-back#898]
I'm getting timout issues on Taiga, i've been watching the logs and such but don't see anything useful.

[2016-12-12 03:25:39 +0000] [1552] [CRITICAL] WORKER TIMEOUT (pid:1739)
[2016-12-12 03:25:39 +0000] [2250] [INFO] Booting worker with pid: 2250
2016/12/12 03:25:39 [error] 1409#1409: *1 upstream prematurely closed connection while reading response header from upstream, client: xxxxxx, server: xxxxxxx, request: "PATCH /api/v1/issues/125 HTTP/2.0", upstream: "http://127.0.0.1:8001/api/v1/issues/125", host: "xxxxxx", referrer: "https://xxxxxx/project/dan-bbn/issue/7"

Anyone have any ideas on how to debug this issue?

**Comment by superalex** [comment]
Hello @Mochaka, those are the nginx logs, it seems there are some errors on taiga-back.

Taiga back is daemonized with circus and you could check your those logs under the logs folder of your taiga user.

Regards,

**Comment by Mochaka** [comment]
Hey @superalex 

I've checked there, and those are the only things showing, the worker timeout and the nginx log.

I've been trying to figure it out for a while, but to no avail.

**Comment by Mochaka** [comment]
Hey @superalex 

I figured out it was the emailing via SMTP.

After playing around with config for hours, i figured out you can use djmail. 

For anyone else struggling with this issue:

EMAIL_BACKEND = "djmail.backends.async.EmailBackend"
DJMAIL_REAL_BACKEND="django.core.mail.backends.smtp.EmailBackend"

**Comment by superalex** [comment]
Thanks @Mochaka  :+1:

**Comment by vituocgia** [comment]
Hello there
I'm facing this issue now
I was config as Mochaka's comment, but the email was not sent... Just solve the issue about 504 error response...
