### ISSUE TITLE
Remove alt logo from emails

### ISSUE THREAD

**Issue by m-messiah** [taigaio/taiga-back#899]
Today, we have alt text for Taiga logo in notification emails (here: [updates-body-html.jinja#L398](https://github.com/taigaio/taiga-back/blob/master/taiga/base/templates/emails/updates-body-html.jinja#L398), so when email received - we have useless text in email preview:

![screen shot 2016-12-13 at 11 56 26](https://cloud.githubusercontent.com/assets/2103030/21133738/78e34278-c12b-11e6-944e-8ac28deb099f.png)

Expected: no "Taiga logo" text - more info about event.

**Comment by bameda** [comment]
Done. https://github.com/taigaio/taiga-back/commit/271385c789ed81906099068af25ecc01167b65fa

Thanks for report it
