### ISSUE TITLE
[FR] assist in the development of the Taiga node on the awesome open source project https://n8n.io/

### ISSUE THREAD

**Issue by wgicio** [taigaio/taiga-back#90]
Please describe the problem / need you are trying to solve.

I use the open source project [n8n](https://n8n.io/) - think zapier but way cooler.
A taiga node / intergration already exists however it is limiited

I've started a list feature requests for the node here:
https://community.n8n.io/t/taiga-node-feature-requests/11911/3

It would be great if you could contribute to this project with your coding skills and get the node completed or sign up and vote for the features

Love Taiga and thanks for all the hard work!

**Comment by daniel-herrero** [comment]
Hi @wgicio,

Thank you for reporting about this FR. As we already have a similar one regarding [n8n.io](https://tree.taiga.io/project/taiga/issue/2543), we'll close this issue (to avoids duplicated) but it'll be linked from the original.

Best regards!
