### ISSUE TITLE
No provisionning possible with Django 1.9

### ISSUE THREAD

**Issue by fuegowolf** [taigaio/taiga-back#904]
Hi !

I wanted to have a self hosted version of taiga with Docker, so I used a repo, but the mess was so important that I decided to do it myself. However, when I pulled the `stable` branch of this repository and ran `pip install -r requirements.txt`, the `regenerate.sh` file was not usable to provision.

In fact, when I'm running just after the pip install that file, I got : 

`AttributeError: module 'django.db.models' has no attribute 'get_model'`

I got errors about dropdb too, but I think it is okay. Google said to me that error is due to **Django 1.9**, and when I rollback to another commit, before this change, eveything is working even if I need to upgrade bleach.

Why do I have this error ? I think that nobody noticed that since that upgrade from Django 1.8 to 1.9 is weird. Thank you in advance :)

**Comment by jespino** [comment]
Hi, sorry the delay in the response.

I think this may be related to the usage of some taiga plugin in back that ins't correctly upgrade.

If you have everything up to date in Taiga, this error mustn't happen.

**Comment by fuegowolf** [comment]
Thx anyway ! All is doing good now :)

**Comment by optimum-web** [comment]
I have the same issue in stable branch 
`Traceback (most recent call last):
  File "manage.py", line 29, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/usr/local/lib/python3.6/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/app/taiga/feedback/apps.py", line 31, in ready
    from taiga.urls import urlpatterns
  File "/app/taiga/urls.py", line 23, in <module>
    from .routers import router
  File "/app/taiga/routers.py", line 275, in <module>
    from taiga.export_import.api import ProjectImporterViewSet, ProjectExporterViewSet
  File "/app/taiga/export_import/api.py", line 47, in <module>
    from . import validators
  File "/app/taiga/export_import/validators/__init__.py", line 1, in <module>
    from .validators import PointsExportValidator
  File "/app/taiga/export_import/validators/validators.py", line 281, in <module>
    class EpicExportValidator(WatcheableObjectModelValidatorMixin):
  File "/app/taiga/export_import/validators/validators.py", line 286, in EpicExportValidator
    user_stories = EpicRelatedUserStoryExportValidator(many=True, required=False)
  File "/app/taiga/base/api/serializers.py", line 247, in __init__
    self.fields = self.get_fields()
  File "/app/taiga/base/api/serializers.py", line 283, in get_fields
    default_fields = self.get_default_fields()
  File "/app/taiga/base/api/serializers.py", line 776, in get_default_fields
    related_model = _resolve_model(model_field.rel.to)
  File "/app/taiga/base/api/serializers.py", line 101, in _resolve_model
    return models.get_model(app_name, model_name)
AttributeError: module 'django.db.models' has no attribute 'get_model'`

any ideas ?

**Comment by bameda** [comment]
What version of taiga are you using, and what version of Django?? it seems they are incompatible. 

```
cd taiga-back
git describe --tag
```

```
workon taiga
pip show django | grep version
```

**Comment by optimum-web** [comment]
Hi, thanks for quick feedback , 

root@ac64abdcccdb:/app# git describe --tag
3.1.0-34-g61c0653
root@ac64abdcccdb:/app# pip show django
Name: Django
Version: 1.10.6
Installed from requirements https://github.com/taigaio/taiga-back/blob/stable/requirements.txt

**Comment by optimum-web** [comment]
Here is the list of installed apps


INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.admin",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",

    "taiga.base",
    "taiga.base.api",
    "taiga.locale",
    "taiga.events",
    "taiga.front",
    "taiga.users",
    "taiga.userstorage",
    "taiga.external_apps",
    "taiga.projects",
    "taiga.projects.references",
    "taiga.projects.custom_attributes",
    "taiga.projects.history",
    "taiga.projects.notifications",
    "taiga.projects.attachments",
    "taiga.projects.likes",
    "taiga.projects.votes",
    "taiga.projects.milestones",
    "taiga.projects.userstories",
    "taiga.projects.tasks",
    "taiga.projects.issues",
    "taiga.projects.wiki",
    "taiga.searches",
    "taiga.timeline",
    "taiga.mdrender",
    #"taiga.export_import",
   # "taiga.feedback",
    "taiga.stats",
    "taiga.hooks.github",
    "taiga.hooks.gitlab",
    "taiga.hooks.bitbucket",
    "taiga.webhooks",

    "djmail",
    "django_jinja",
    "django_jinja.contrib._humanize",
    "sr",
    "easy_thumbnails",
    "raven.contrib.django.raven_compat",
]
and middleware
MIDDLEWARE_CLASSES = [
    "taiga.base.middleware.cors.CoorsMiddleware",
    "taiga.events.middleware.SessionIDMiddleware",

    # Common middlewares
    "django.middleware.common.CommonMiddleware",
    "django.middleware.locale.LocaleMiddleware",

    # Only needed by django admin
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
]

**Comment by bameda** [comment]
Is strange, stable branch is running in taiga.io and dosen't have this error. However this line https://github.com/taigaio/taiga-back/blob/61c06538986bf236ba6d0b6bb3ca19a64ad329bb/taiga/base/api/serializers.py#L101 showld be fixed because we use a deprecate method.

**Comment by optimum-web** [comment]
However I can not find get_model in https://github.com/django/django/tree/1.10.6/django/db/models
Instead, they use apps.get_model as I can see.

**Comment by optimum-web** [comment]
I updated taiga-back/taiga/base/api/serializers.py with importing apps

```
+from django.apps import apps
 from django.forms import widgets
 from django.utils import six
 from django.utils.translation import ugettext as _
@@ -98,7 +99,7 @@ def _resolve_model(obj):
     """
     if type(obj) == str and len(obj.split(".")) == 2:
         app_name, model_name = obj.split(".")
-        return models.get_model(app_name, model_name)
+        return apps.get_model(app_name, model_name)
```

"no attribute 'get_model" error is gone but now I have another one 
```
" File "/usr/local/lib/python3.6/site-packages/django/apps/registry.py", line 155, in get_app_config
    raise LookupError(message)
LookupError: No installed app with label 'epic"
```

which put me to think the problem is still in the requirements.txt (stable branch).

**Comment by optimum-web** [comment]
Ok I finally did it. 
Patch above and added two lines into settings/local.py

```
IMPORTERS = {}
and
INSTALLED_APPS = [
..
 "taiga.projects.epics",
..
]

```
and it works !

**Comment by bameda** [comment]
its better extends INSTALLED_APPS than overwrite
