### ISSUE TITLE
Taiga slowness whn US statuses updating

### ISSUE THREAD

**Issue by vitak** [taigaio/taiga-back#905]
Hi.
I have taiga installed on my own VPS (Ubuntu/nygix).

On server are 4GB ram and two-core 2.4 Ghx processor. Taiga is only appliaction on this server.

When changing US status taiga took 2 min time for this. I think it cant be normal.

There is some logs about request:

```
Request URL:http://taiga.bglab.info/api/v1/userstories/143?include_attachments=true&include_tasks=true
Request Method:PATCH
Status Code:200 OK
Remote Address:52.178.223.243:80
Response Headers
view source
Access-Control-Allow-Credentials:true
Access-Control-Allow-Headers:content-type,x-requested-with,authorization,accept-encoding,x-disable-pagination,x-lazy-pagination,x-host,x-session-id,set-orders
Access-Control-Allow-Methods:POST,GET,OPTIONS,PUT,DELETE,PATCH,HEAD
Access-Control-Allow-Origin:*
Access-Control-Expose-Headers:x-pagination-count,x-paginated,x-paginated-by,x-pagination-current,x-pagination-next,x-pagination-prev,x-site-host,x-site-register,taiga-info-total-opened-milestones,taiga-info-total-closed-milestones,taiga-info-project-memberships,taiga-info-project-is-private,taiga-info-order-updated
Access-Control-Max-Age:3600
Allow:GET, PUT, PATCH, DELETE, HEAD, OPTIONS
Connection:keep-alive
Content-Language:en
Content-Type:application/json
Date:Wed, 28 Dec 2016 13:21:11 GMT
Server:nginx/1.4.6 (Ubuntu)
Taiga-Info-Order-Updated:{"135": 2, "136": 4, "137": 3, "138": 1, "139": 10007, "140": 2, "141": 6, "143": 0, "149": 11, "150": 10, "151": 13, "156": 10005, "157": 10007, "158": 10007, "178": 1478604183840, "180": 1478607021157, "181": 1479673243224, "190": 1479744836484}
Transfer-Encoding:chunked
Vary:Accept-Language
Request Headers
view source
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en
Authorization:Bearer eyJ1c2VyX2F1dGhlbnRpY2F0aW9uX2lkIjoxNX0:1bWg6p:2vNE5krpByizQulCGkWEr2qWJA8
Connection:keep-alive
Content-Length:42
Content-Type:application/json
Host:taiga.bglab.info
Origin:http://taiga.bglab.info
Referer:http://taiga.bglab.info/project/vitezslavmergl-gammonspacenet/kanban
set-orders:{}
User-Agent:Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36
X-Session-Id:0e6f5f4a02977bdd152b0939181a19f0108dab94
Query String Parameters
view source
view URL encoded
include_attachments:true
include_tasks:true
Request Payload
view source
{version: 3, status: 83, kanban_order: 0}
kanban_order:0
status:83
version:3
```

And timeline:
![image](https://cloud.githubusercontent.com/assets/6680486/21522982/6be3ea4c-cd0a-11e6-8d7c-0ae6812568b2.png)

Any ideas for make Taiga faster? 2 minutes for status change is realy too much.

**Comment by superalex** [comment]
By default taiga will be working in synchronous mode if updating an US implies email notifications that 2 seconds will include that time. Did you enable asynchronous tasks for your isntance? https://taigaio.github.io/taiga-doc/dist/setup-production.html#_async_tasks_optional

**Comment by vitak** [comment]
Hi,
By tutorial which u sent i change my taiga to async.
After this all chenges in US end with 400 Error.

In taiga.apache.error.log is:
`[Tue Jan 03 13:31:12.038883 2017] [proxy_http:error] [pid 19621] (70007)The timeout specified has expired: [client 84.42.187.10:62315] AH01095: prefetch request body failed to 127.0.0.1:8001 (127.0.0.1) from 84.42.187.10 ()
`

No errors in celery log.

In gunicorn log is:
`[2017-01-03 13:27:12 +0100] [21038] [CRITICAL] WORKER TIMEOUT (pid:21048)`


Task is still proccessed some about 2 min, but this time ends with error.

**Comment by superalex** [comment]
It seems your taiga-back can't boot properly (probably some misconfiguration related to the asynch tasks). You could try launching taiga-back with "python manage.py runserver" to see if there are any errors.

**Comment by vitak** [comment]
"python manage.py runserver" not show any error, but i delete all local content except database and try install everything from start and taiga now woking (i hope). Thank you

**Comment by superalex** [comment]
You are welcome @vitak
