### ISSUE TITLE
gogs integration - pull request merging is repeating all issue actions

### ISSUE THREAD

**Issue by nequez** [taigaio/taiga-back#912]
Merging pull request on gogs interface triggers repeating all commit message actions.  

**To reproduce:**
* create branch
* make some commits with TG-xx #done and TG-xx #new, watch tasks are updated in Taiga
* create pull request in gogs containing previous commits
* merge pull request
* watch taiga to see that pull request merge is repeating all task actions

**Expected behavior**
Merging pull request should not repeat all commit actions. If pull request title containts TG-xx #status it should trigger action on merge.

**Comment by superalex** [comment]
Thanks for reporting @nequez I think this is a duplicated one from https://tree.taiga.io/project/taiga/issue/4025 so I've copied your comments there.
