### ISSUE TITLE
I cannot add a user to a project because the username is missing.

### ISSUE THREAD

**Issue by ravloony** [taigaio/taiga-back#913]
**Do you want to request a *feature* or report a *bug*?**

Report a bug

**What is the current behavior?**

I cannot add a user to a project.

**If the current behavior is a bug, please provide the steps to reproduce.**

go to <url>/projects/<your_project>/admin/memberships
Click on "New Member"
In the popup, add an email and a message and click "Create".

**What is the expected behavior?**

**Is it happening in taiga.io or in your own instance?**

My own instance.

**What browser/version are you using?**

Chrome 55.0.2883.87 on NixOS

**Are there any console errors *(Ctrl + F12)* in red?**

`POST http://taiga-test.yelsterdigital.com/api/v1/memberships/bulk_create 400 (Bad Request)`

The network request gives me:

`{"bulk_memberships": [{"username": ["This field is required."]}]}`

POST payload was:
`{"project_id":1, "bulk_memberships": [{"email":"email@example.com","role_id":1}], "invitation_extra_text":"eoaueoaua"}`

**Comment by bameda** [comment]
are you using stable branch or master branch in the two repositories?

**Comment by ravloony** [comment]
I'll check

**Comment by bameda** [comment]
it seems that you are using master branch in taiga-back instead of stable.

**Comment by ravloony** [comment]
I'll switch. Front is using taiga-front-dist on master. Should that change?

**Comment by ravloony** [comment]
Ok now the error is just `{"error": "Server application error"}`

**Comment by ravloony** [comment]
My fault for the last error. Badly configured email host. I am closing this issue.

Thank you for the help, @bameda !!

**Comment by bameda** [comment]
Great :-) you are welcome.
