### ISSUE TITLE
Images arn't being showen when front uses a different port

### ISSUE THREAD

**Issue by alonikomax** [taigaio/taiga-back#914]
**Do you want to request a *feature* or report a *bug*?**
bug

**What is the current behavior?**
images arn't being shown

**If the current behavior is a bug, please provide the steps to reproduce.**
create front on a different port like 8888

**What is the expected behavior?**
images are being showen

**Is it happening in taiga.io or in your own instance?**
my own

**What browser/version are you using?**
firefox, chrome

**Are there any console errors *(Ctrl + F12)* in red?**
nope

**I have been able to temp fix this**

I've seen that [def get_photo_url(photo)](https://github.com/taigaio/taiga-back/blob/e91496b3c6ed661d75b0fadd2ca61091bbc7baff/taiga/users/services.py#L73):

is using [get_absolute_url(url)](https://github.com/taigaio/taiga-back/blob/e91496b3c6ed661d75b0fadd2ca61091bbc7baff/taiga/users/services.py#L73)
after getting the url using:
**url = get_thumbnailer(photo)[settings.THN_AVATAR_SMALL].url**
this returns a url with the correct domain and scheme but without the port. something like:
https://mydomain.com/abcd
instead of
https://mydomain.com:8888/abcd

This causes the return of this address instead of building one using **build_url(path, scheme=site.scheme, domain=site.domain)** which will give the port as it's using the users settings.

I have been able to fix this by adding:

    if ":8888" not in path:
        path = path.replace(".com",".com:8888",1)

inside the if is_absolute_url(path):

**Comment by bameda** [comment]
@alonikomax I think the solution is more simple. 

- Undo your changes to the code.
- Change or add in `taiga-back/settings/local.py` the attribute `MEDIA_URL` to the correct url. For example `MEDIA_URL = "http://my-taiga-host.com:8888/media/"` 
- Restart the service of taiga-back.
