### ISSUE TITLE
[BUG] Can not invite new members to project - API error 500

### ISSUE THREAD

**Issue by vojtechmares** [taigaio/taiga-back#92]
**Describe the bug**
Users are not being invited to the project. First I thought it was an SMTP issue (using my own mail server - https://poste.io), but I found out that the API is giving me error 500 for the endpoint `/api/v1/memberships/bulk_create`

I have a Caddy web server running on port 80 and 443 to handle HTTPS, all traffic is going to the nginx with provided configuration, no changes.

**How can we reproduce the behavior**
Run self-hosted Taiga via docker compose, create scrum project and add member. Using the `stable` branch.

**Workarounds**
None

**Screenshots**
None

**Taiga environment**
Self-hosted, `stable` branch

**Desktop (please complete the following information):**
 - **OS:** macOS
 - **Browser:** Chrome
 - **Version:** 99.0.4818.0 (Official Build) dev (arm64) 

**Additional context**

**Comment by ChriFo** [comment]
I had the same error. 

Then with `Debug=True` I get: `ValueError: EMAIL_USE_TLS/EMAIL_USE_SSL are mutually exclusive, so only set one of those settings to True.`

Documentation is here: https://docs.djangoproject.com/en/2.2/ref/settings/#std:setting-EMAIL_USE_TLS

**Comment by vojtechmares** [comment]
Fixed by updating config to use one of SMTP TLS settings 🤦‍♂️
