### ISSUE TITLE
different payload coming from POST service webhook for Bitbucket Server 

### ISSUE THREAD

**Issue by alirezamansoori** [taigaio/taiga-back#924]
quick question.. the bitbucket integration piece for push PushEventHook looks for a json file in this format.. 
```
payload = {        
        "push": {
            "changes": [
                {
                    "commits": [
                        { "message": "test message   test   TG-%s    #%s   ok   bye!" % (epic.ref, new_status.slug) }
                    ]
                }
            ]
        }
```
My bitbucket installation is sending out a json file in this format..
```
payload = {
        "changesets": {            
            "values": [
                {
                    "toCommit": 
                        { "message": "test message   test   TG-%s    #%s   ok   bye!" % (epic.ref, new_status.slug) }
                    
                }
            ]
        }
```

here's a full example of the payload: https://confluence.atlassian.com/bitbucketserver/post-service-webhook-for-bitbucket-server-776640367.html

Probably a dumb question, but to get this work for myself is this as straightforward as changing the PushEventHook to look for the values it needs under different nodes?

**Comment by alirezamansoori** [comment]
I'm going to close this as it wasn't really a good question... They seem to be completely different, from headers to the content of the payloads. I got it to work by modifying the bitbucket classes. 
anyways, thanks for the great work so far on this project.

**Comment by superalex** [comment]
Thanks @alirezamansoori
