### ISSUE TITLE
Troubleshooting newly setup Taiga on own server

### ISSUE THREAD

**Issue by dqlopez** [taigaio/taiga-back#928]
Just finished setting up Taiga by following the setup docs [here](https://taigaio.github.io/taiga-doc/dist/setup-production.html). Upon accessing the configured site (http://taiga.mysite.com/discover), all I see is a nice page with **"Something happened and our Oompa Loompas are working on it."**.

I tried digging up the ~logs and found several files:

```
(taiga) taiga@ubuntu:~/logs$ ll
total 56
drwxrwxr-x 2 taiga taiga  4096 Jan 30 15:24 ./
drwxr-xr-x 9 taiga taiga  4096 Jan 30 15:28 ../
-rw-r--r-- 1 root  root    420 Jan 30 15:21 celery.stderr.log
-rw-r--r-- 1 root  root   1180 Jan 30 15:21 celery.stdout.log
-rw-r--r-- 1 root  root   2461 Jan 30 15:21 gunicorn.stderr.log
-rw-r--r-- 1 root  root      0 Jan 30 15:11 gunicorn.stdout.log
-rw-r--r-- 1 root  root  34647 Jan 30 15:37 nginx.access.log
-rw-r--r-- 1 root  root      0 Jan 30 15:24 nginx.error.log
-rw-r--r-- 1 root  root      0 Jan 30 15:12 taigaevents.stderr.log
-rw-r--r-- 1 root  root      0 Jan 30 15:12 taigaevents.stdout.log
```
Checked on the non 0 log and doesn't seem to found any error reference on where I should start. Any thoughts on how to start troubleshooting this?

**Comment by bameda** [comment]
What is the api url? What do you have in conf.json?

**Comment by dqlopez** [comment]
@bameda 
**conf.json**
```
taiga@ubuntu:~/taiga-front-dist/dist$ more conf.json 
{
    "api": "http://taiga.mysite.com:8000/api/v1/",
    "eventsUrl": "ws://taiga.mysite.com/events",
    "eventsMaxMissedHeartbeats": 5,
    "eventsHeartbeatIntervalTime": 60000,
    "eventsReconnectTryInterval": 10000,
    "debug": true,
    "debugInfo": false,
    "defaultLanguage": "en",
    "themes": ["taiga"],
    "defaultTheme": "taiga",
    "publicRegisterEnabled": true,
    "feedbackEnabled": true,
    "privacyPolicyUrl": null,
    "termsOfServiceUrl": null,
    "maxUploadFileSize": null,
    "contribPlugins": [],
    "tribeHost": null,
    "gravatar": true
}
```

**Comment by bameda** [comment]
Is http://taiga.mysite.com:8000/api/v1/ working? Can you visit this url?

**Comment by dqlopez** [comment]
No it isn't, getting a refuse to connect error. Perhaps a firewall issue but I haven't installed one since I setup a fresh Ubuntu instance.

**Comment by bameda** [comment]
I don't know what are your nginx setings but maybe the url should be http://taiga.mysite.com/api/v1/ if you are using a proxypass

**Comment by dqlopez** [comment]
Just followed what was on doc:
_sites-available/taiga_

```
server {
    listen 80 default_server;
    server_name _;

    large_client_header_buffers 4 32k;
    client_max_body_size 50M;
    charset utf-8;

    access_log /home/taiga/logs/nginx.access.log;
    error_log /home/taiga/logs/nginx.error.log;

    # Frontend
    location / {
        root /home/taiga/taiga-front-dist/dist/;
        try_files $uri $uri/ /index.html;
    }

    # Backend
    location /api {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://127.0.0.1:8001/api;
        proxy_redirect off;
    }

    # Django admin access (/admin/)
    location /admin {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://127.0.0.1:8001$request_uri;
        proxy_redirect off;
    }

    # Static files
    location /static {
        alias /home/taiga/taiga-back/static;
    }

    # Media files
    location /media {
        alias /home/taiga/taiga-back/media;
    }

    # Events
    location /events {
       proxy_pass http://127.0.0.1:8888/events;
       proxy_http_version 1.1;
       proxy_set_header Upgrade $http_upgrade;
       proxy_set_header Connection "upgrade";
       proxy_connect_timeout 7d;
       proxy_send_timeout 7d;
       proxy_read_timeout 7d;
    }
}
```

**Comment by bameda** [comment]
Change in conf.json

```
    "api": "http://taiga.mysite.com:8000/api/v1/",
```
to
```
    "api": "http://taiga.mysite.com/api/v1/",
```

**Comment by dqlopez** [comment]
There it works now. I wonder I already change as you suggested, what I did is restart nginx. Then it works. By the way, how can I access the admin? Say for example to disable the Sign Up link, is it possible?

**Comment by bameda** [comment]
In local.py you can remove these lines because they are deprecated

ADMIN_MEDIA_PREFIX
TEMPLATE_DEBUG

**Comment by bameda** [comment]
To disable sign up link you have to change in `local.py` 

```
PUBLIC_REGISTER_ENABLED = True
```
to 
```
PUBLIC_REGISTER_ENABLED = False
```
and in `conf.json`
```
    "publicRegisterEnabled": true,
```
to
```
    "publicRegisterEnabled": false,
```

**Comment by dqlopez** [comment]
@bameda Thanks man. I wonder where in docs can I find those options?

**Comment by bameda** [comment]
To access to the admin panel go to http://taiga.mysite.com/admin/ but the admin panel is a simple CRUD over the data model.

**Comment by dqlopez** [comment]
> To access to the admin panel go to http://taiga.mysite.com/admin/ but the admin panel is a simple CRUD over the data model.

Unfortunately, this resolves to 404 when I access this.

**Comment by bameda** [comment]
We should add more FAQs to the documentation https://github.com/taigaio/taiga-doc/blob/master/setup-faqs.adoc

**Comment by dqlopez** [comment]
Seems that the images I upload are pixelated. Is there any settings that limits this?

**Comment by bameda** [comment]
pixelated?? maybe you upload an small image

**Comment by bameda** [comment]
Is strange, the admin panel according to you nginx settings should be  http://taiga.mysite.com/admin/ (be careful and don't remove the last / )

**Comment by dqlopez** [comment]
Sorry for the late reply @bameda, yes you are for having that "/", explicitly :dancer:

**Comment by bameda** [comment]
Great!!
