### ISSUE TITLE
Taiga API response wrong data

### ISSUE THREAD

**Issue by wadinj** [taigaio/taiga-back#929]
Hello,

I try to use Taiga API to get some informations on my user story. To do that, first I call the WS login normal : https://api.taiga.io/api/v1/auth. The response seems to be good. I get my authent token and I pass it on https://api.taiga.io/api/v1/userstories?project=1 with Header : 
Authorization : Bearer "TOKEN_RETRIEVE_FROM_WS"
The WebService response with wrong data that doesn't match with mine : 
`[{"backlog_order": 0, "owner": 9, "sprint_order": 1, "total_voters": 0, "status": 2, "points": {"43": 1, "45": 2, "46": 1, "44": 1}, "assigned_to_extra_info": null, "total_points": 0.0, "ref": 1, "comment": "", "milestone": 1, "client_requirement": false, "project_extra_info": {"name": "Taiga", "slug": "taiga", "logo_small_url": "https://media.taiga.io/project/7/2/5/3/5be1bdff48f7470b36ad1357fc512b36f1235ed5d3f677f182bb220d5a15/logo-color.png.80x80_q85_crop.png", "id": 1}, "attachments": [], "project": 1, "milestone_slug": "sprint-0", "epics": null, "subject": "Arreglar las gr\u00e1ficas", "is_watcher": false, "tags": [["front", "#1b78eb"], ["graphs", null]], "version": 5, "created_date": "2013-10-30T08:22:32.262Z", "is_blocked": false, "tasks": [], "external_reference": null, "id": 26, "is_closed": true, "assigned_to": null, "tribe_gig": null, "finish_date": "2013-11-05T15:15:55.011Z", "status_extra_info": {"name": "Released", "color": "#3465a4", "is_closed": true}, "is_voter": false, "team_requirement": false, "total_watchers": 0, "generated_from_issue": null, "owner_extra_info": {"gravatar_id": "ca3f184c1e11414128d75b06509535bf", "is_active": true, "photo": "https://media.taiga.io/user/5/6/8/f/db894b825b1f4b9fdca753d8d1d9e2b2739ce2dff7ce8da0f9ff9051b152/keibbsfn_400x400.png.80x80_q85_crop.png", "id": 9, "full_name_display": "David Barrag\u00e1n", "username": "bameda", "big_photo": "https://media.taiga.io/user/5/6/8/f/db894b825b1f4b9fdca753d8d1d9e2b2739ce2dff7ce8da0f9ff9051b152/keibbsfn_400x400.png.300x300_q85_crop.png"}, "blocked_note": "", "modified_date": "2014-08-22T08:01:37.249Z", "kanban_order": 102, "origin_issue": null, "milestone_name": "Sprint 0", "epic_order": null, "watchers": []}, {"backlog_order": 0, "owner": 9, "sprint_order": 1, "total_voters": 0, "status": 2, "points": {"43": 2, "45": 4, "46": 1, "44": 1}, "assigned_to_extra_info": null, "total_points": 1.0, "ref": 3, "comment": "", "milestone": 29, "client_requirement": false, "project_extra_info": {"name": "Taiga", "slug": "taiga", "logo_small_url": "https://media.taiga.io/project/7/2/5/3/5be1bdff48f7470b36ad1357fc512b36f1235ed5d3f677f182bb220d5a15/logo-color.png.80x80_q85_crop.png", "id": 1}, "attachments": [], "project": 1, "milestone_slug": "sprint-3-1", "epics": null, "subject": "Poder definir estados, tipos, severidades, prioridades y puntos de un proyecto desde la pantalla de administraci\u00f3n", "is_watcher": false, "tags": [], "version": 3, "created_date": "2013-12-10T10:15:02.361Z", "is_blocked": false, "tasks": [], "external_reference": null, "id": 177, "is_closed": true, "assigned_to": null, "tribe_gig": null, "finish_date": "2013-12-14T14:28:36.159Z", "status_extra_info": {"name": "Released", "color": "#3465a4", "is_closed": true}, "is_voter": false, "team_requirement": false, "total_watchers": 0, "generated_from_issue": null, "owner_extra_info": {"gravatar_id": "ca3f184c1e11414128d75b06509535bf", "is_active": true, "photo": "https://media.taiga.io/user/5/6/8/f/db894b825b1f4b9fdca753d8d1d9e2b2739ce2dff7ce8da0f9ff9051b152/keibbsfn_400x400.png.80x80_q85_crop.png", "id": 9, "full_name_display": "David Barrag\u00e1n", "username": "bameda", "big_photo": "https://media.taiga.io/user/5/6/8/f/db894b825b1f4b9fdca753d8d1d9e2b2739ce2dff7ce8da0f9ff9051b152/keibbsfn_400x400.png.300x300_q85_crop.png"}, "blocked_note": "", "modified_date": "2014-08-22T08:02:46.764Z", "kanban_order": 109, "origin_issue": null, "milestone_name": "Sprint 2", "epic_order": null, "watchers": []} 
`
etc....

What I did wrong ? What is this response ?

Thank you,
Jonathan

**Comment by bameda** [comment]
You are using `?project=1` and this project is Taiga (https://tree.taiga.io/project/taiga/), not your project. What is your project id?

**Comment by wadinj** [comment]
Thank you for this quickly feedback.
How can I retrieve the id of my project ?

Thanks a lot,
Best regards,
Jonathan

**Comment by bameda** [comment]
You can use the slug of your project, if your project slug is 'wadinj_myproject' you can do a call to

`https://api.taiga.io/api/v1/projects/by_slug?slug=wadinj_myproject`

Or you can get a list of your projects  (knowing your user id) 

`https://api.taiga.io/api/v1/projects?member=<user id>&order_by=user_order`

**Comment by wadinj** [comment]
Works perfectly,

Thanks,
Jonathan

**Comment by bameda** [comment]
Great, you are welcome. :smiley_cat:

**Comment by DarioCubero** [comment]
Really useful, it works.
Much thanks @bameda.
