### ISSUE TITLE
Taiga-gitlab integration gives 405 error

### ISSUE THREAD

**Issue by omkartelee08** [taigaio/taiga-back#930]
Hi,

I have local taiga installation.
the Gitlab intehration, when I add a webhook, it failes  gives 405 errror in nginx.error.log as follow

"GET /api/v1/gitlab-hook?project=12&key=7efb179dbe2f4a74881e8dfec64aa238 HTTP/1.1" 405 115"

my local.py is

from .common import *

MEDIA_ROOT = '/home/taiga/taiga-data/media'
STATIC_ROOT = '/home/taiga/taiga-data/static'

MEDIA_URL = "http://10.43.11.193/media/"
STATIC_URL = "http://10.43.11.193/static/"

ADMINS = (
    ("Admin", "admin@xxx.com"),
)

 #This should change if you want generate urls in emails
#for external dns.
SITES["front"]["domain"] = "10.43.11.193"

 my database resides on some other machine [setting excluded].

also, the Payload URL generated contains "localhost"

**Comment by snsn** [comment]
gitlab is currently offline due to some issues. It seems to have affected, I think.

**Comment by omkartelee08** [comment]
@snsn I have my internal gitlab server

**Comment by snsn** [comment]
oh, I misunderstood.

**Comment by jespino** [comment]
/api/v1/gitlab-hook endpoint only accept POST requests, that GET call is made by Gitlab?

About the payload url with "locahost", can you check your taiga-front conf.json?

**Comment by omkartelee08** [comment]
Hi, I resolved the 405 error.
about "localhost"
my conf.json
{
    "api": "/api/v1/",
    "eventsUrl": null,
    "debug": "true",
    "publicRegisterEnabled": true,
    "feedbackEnabled": false,
    "privacyPolicyUrl": null,
    "termsOfServiceUrl": null,
    "maxUploadFileSize": null,
    "gitHubClientId": null,
    "contribPlugins": [],
    "gravatar" : false
}

what variable i need to change ?

**Comment by jespino** [comment]
Sorry, my fault, isn't a problem in the taiga-front config, is a problem in the taiga back config, you only need to add SITES["api"]["domain"] = "10.43.11.193" to your settings/local.py

**Comment by omkartelee08** [comment]
**It works**  :)
Thanks a lot @jespino

**Comment by jespino** [comment]
You are welcome 😃
