### ISSUE TITLE
GitLab Integration - Questions / Issues

### ISSUE THREAD

**Issue by sftd** [taigaio/taiga-back#931]
Taiga: own instace, version 3.0.0
GitLab: Community Edition 8.16.3

I've set up GitLab integration with 3 types of events: Push Events, Issues Events, Note Events. As I understand those are the ones supported by Taiga.

My main question is should issue status in Taiga be updated after updating status in GitLab? It doesn't in my setup which demands that I close both manually which is kind of uncomfortable (it can be done with commit message, but still need to know 2 different issue ids which is also quite uncomfortable).

Maybe what's worth mentioning is that I get following error when testing Taiga integration from GitLab:

> Hook executed successfully but returned HTTP 400 {"_error_type"=>"taiga.base.exceptions.BadRequest", "_error_message"=>"The status doesn't exist"}

Thank you for help in advance.

**Comment by bameda** [comment]
Please @sftd, read the suport page: https://tree.taiga.io/support/integrations/gitlab-integration/

**Comment by sftd** [comment]
That's basically where I came from :). I was just confused that updating Taiga status when updating GitLab status is neither in "what can we do" nor in "what can't we do" as it seems to be quite important feature.

But as I understand I should assume if it isn't explicitly listed in "what can we do" it's not supported?

I just thought it might not work due to GitLab integration changes as Taigas GitLab integration help page refers to older GitLab version.

Thanks for help.

**Comment by bameda** [comment]
The only method to change status is with the commit message, Taiga dosn't know what is the realation between Github statuses and Taiga statuses.
