### ISSUE TITLE
Useless taiga

### ISSUE THREAD

**Issue by vitak** [taigaio/taiga-back#932]
After months spending with configure taiga on my own server i give it up a think about move my project to taiga.io even if i must pay it.

I want to login in to tree.taiga.io, but its not working at all. https://api.taiga.io/api/v1/auth simply return "Status Code:504 Gateway Time-out" even if i login with creditials or github acc.

So i like to leave taiga and my question is. Is there some way to convert data from taiga to another similar system?
Thank you for response and hope sometime in future will be taiga useable.

**Comment by superalex** [comment]
Hello @vitak 

Two days ago we had a problem with our hardware infrastructure, the main database server was running out of RAM, we planned an intervention as soon as possible and fixed the problem. I'm sorry you experienced those problems just at the time you were considering moving to it, I hope you can reconsider using Taiga in the future.

About extracting the taiga data, you have two options:
 - The export feature generates a json file containing the entire project, you could parse that json file and use that info in any other system
 - You could use taiga API directly to extract all the info related to your projects: https://taigaio.github.io/taiga-doc/dist/api.html

**Comment by bameda** [comment]
- And you can export the data (without attachment files) as csv format too.

https://tree.taiga.io/support/admin/csv-reports/
https://tree.taiga.io/support/admin/import-export-projects/
