### ISSUE TITLE
Is members supposed to return only user IDs?

### ISSUE THREAD

**Issue by bluefalcon26** [taigaio/taiga-back#934]
**Do you want to request a *feature* or report a *bug*?**
Bug
**What is the current behavior?**
1. Navigate to url doman:8000/api/v1/projects?member=#&order_by=memberships__user_order
    where # is the current member number
2. The API returns only the id for the "**_members_**" field
3. I believe the front end is expecting more data, given that PageMixin->fillUsersAndRoles(users,roles) tries to call .is_active on the data.
**What is the expected behavior?**
The API returns data including the "is_active" field.
**Is it happening in taiga.io or in your own instance?**
Private instance
**What browser/version are you using?**
chrome, debian
**Are there any console errors *(Ctrl + F12)* in red?**
No

![image](https://cloud.githubusercontent.com/assets/5347387/22761228/7c92ab04-ee1f-11e6-9290-6e9a12a95c0a.png)
![image](https://cloud.githubusercontent.com/assets/5347387/22761268/a23aec2c-ee1f-11e6-857c-d2cf7bda0310.png)

**Comment by bameda** [comment]
This call return all the projects where the user with id # is a member, order by the custom user order. 

I don't understand why you need the attribute is_active from the user entity, not project.

**Comment by bameda** [comment]
If you need the member list of some project you should to request the project detail, no a project list.

For example 
`https://api.taiga.io/api/v1/projects/by_slug?slug=taiga`
or
`https://api.taiga.io/api/v1/projects/1 `
