### ISSUE TITLE
Can i disable Sign up process ?

### ISSUE THREAD

**Issue by omkartelee08** [taigaio/taiga-back#938]
Hi,

I have a Internal Taiga installation.

Is there any way, I can disable 'Sign up' button, only invited people should be able to sign up to Taiga.

**Comment by superalex** [comment]
Yes, you have to edit settings/local.py in taiga-back and change this:

```
(...)
PUBLIC_REGISTER_ENABLED` = False
(...)

```

And in taiga-front you have to disable public registration too, edit your conf.json file and set:
```
(...)
publicRegisterEnabled": false,
(...)
```

**Comment by commssource** [comment]
Many thanks, great help 👍
