### ISSUE TITLE
Taiga not generating https url for image

### ISSUE THREAD

**Issue by omkartelee08** [taigaio/taiga-back#940]
I have local taiga setup.

I have enabled https over it.
I am not able to see media.
Because media URL generated is in HTTP.
The URL for any image is http://xxx.xx.com

I also need to add a proxy over it, so, Is there any way by which I can generate, dynamic media url.

**Comment by bameda** [comment]
What value do you have in MEDIA_URL in local.py?

**Comment by omkartelee08** [comment]
MEDIA_URL =  "/media"

**Comment by bameda** [comment]
MEDIA_URL should be a valid url. 
Put a complete url and try it again. 

You should to have https urls in SITES['front'] and SITES['back'] and configure the proxy pass in nginx to allow https
