### ISSUE TITLE
404 on /change-email/

### ISSUE THREAD

**Issue by tchncs** [taigaio/taiga-back#941]
Ohai there, i am not quite sure if this is a misconfiguration or an actual issue.
Also i hope this is the correct repo for this.

I just set up taiga so far, the rabbitmqserver is not yet ready but the rest of the setup should be complete so far.
Unfortunaly i am unable to change my email since the link does not work:

`[16/Feb/2017:17:42:44 +0100] "GET /change-email/aa3ff134-...-00163cc81a13 HTTP/2.0" 404 38`

**Comment by superalex** [comment]
Hello!,

Are you sure that change email token wasn't used before?

**Comment by tchncs** [comment]
I am sorry, it was a bad caddy (webserver) file. :S

**Comment by aallouche** [comment]
@tchncs Hi!
Could you explain what you fixed in your caddyfile as I got a similar issue?
Taiga works well but I get 404 on some direct url like /change-email or /invitation

Woudl be very helpful for other Caddy lovers ;)

**Comment by tchncs** [comment]
Oh hi, this is my current caddy config - /admin is not working (anymore for some odd reason) but anything else is:

```
tree.domain.de {
        tls very@ma.il {
                key_type rsa4096
        }
        gzip
        rewrite {
                if {path} not_match ^/api
                to {path} {path}/ /index.html
        }
        root /home/user/taiga-front-dist/dist
        proxy /api localhost:8001 {
                header_upstream Host {host}
                header_upstream X-Real-IP {remote}
                header_upstream X-Scheme {scheme}
                header_upstream X-Forwarded-Proto {scheme}      
                transparent
        }
        proxy /admin localhost:8001 {
                header_upstream Host {host}
                header_upstream X-Real-IP {remote}
                header_upstream X-Scheme {scheme}
                header_upstream X-Forwarded-Proto {scheme}              
                transparent
        }
        log /var/log/caddy/tree_access.log
        errors /var/log/caddy/tree_error.log
}
tree.domain.de/events {
        proxy / localhost:8878 {
                websocket
        }
}

tree.domain.de/static {
        root /home/user/taiga-back/static/
}

tree.domain.de/media {
        root /home/user/taiga-back/media/
}
```

I am not sure but i guess there was something i wanted to clean up somewhen - however - this results in a working taiga so far^^
If you find out how to bring django to work, i would be happy if you share it^^

**Comment by aallouche** [comment]
@tchncs 
I was missing the rewrite directive! Everything is up and running, thank you so much!

``` go
    rewrite {
        if {path} not_match ^/api
        if {path} not_match ^/admin
        if {path} not_match ^/events
        to /{path} /{path}/ /index.html
    }
```
Note : I need a leading / in the 'to' directive as I use caddy 0.10.1

You can then access the django admin at /admin/ (with trailing /)

**Comment by tchncs** [comment]
Wooo thanks! \o/

**Comment by tchncs** [comment]
@aallouche is it still working for you, appears to be broken again for me. :(
