### ISSUE TITLE
Cannot update tags on User Story through API

### ISSUE THREAD

**Issue by hlarsen** [taigaio/taiga-back#945]
i'm trying to use the API to send a PATCH request to add tags to a user story, however i'm getting a permission denied error. we're using a self-hosted instance running on the stable branch, commit 9bdf1e0 i believe.

notes:
- the account i'm using with the API is the creator of the user story i'm trying to edit
- the account's role has full permissions for everything
- base url: https://$taigaInstance.com/api/v1/userstories/$storyId
- payload: {"tags": [ "tech needs" ], "version": 1}

logging in and other operations through the API work such as creating user stories and sending users invitations to projects, so i'm not sure if this is a bug or i'm not correctly using the API for this operation.

what's happening: receive the following error - {"_error_message": "You do not have permission to perform this action.", "_error_type": "taiga.base.exceptions.PermissionDenied"}

what i expect to happen:  success

**Comment by jespino** [comment]
Hi @hlarsen,

Can you confirm that you are using the User Story ID, and not the User Story reference? The user story ID is what the API use mainly, the User Story reference, is what is showed in URLs and in the user interface.

**Comment by hlarsen** [comment]
pretty sure i was using the story references; thanks for the tip!
