### ISSUE TITLE
How to downgrade database ?

### ISSUE THREAD

**Issue by p418** [taigaio/taiga-back#950]
**Do you want to request a *feature* or report a *bug*?**

Report a *bug*.

**What is the current behavior?**

I was mistakenly using master branch in taiga-backend (as one reported in #913).
So, I switched to stable branch.

After some days, I discovered that I can't create new project anymore.

I unsuccessfully tried to  downgrade database using django command:

```sh
./manage.py migrate projects zero
Trying import local.py settings...
Operations to perform:
  Unapply all migrations: projects
Running migrations:
  Rendering model states... DONE
  Unapplying userstories.0014_auto_20160928_0540...Raven is not configured (logging is disabled). Please see the documentation for more information.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
psycopg2.DataError: integer out of range

```

So, how can I downgrade database without loosing users datas?

**If the current behavior is a bug, please provide the steps to reproduce.**

1. From personal dashboard, Projects > Create Project.
2. Fill in needed Informations
3. Validate

-> Nothing Happens

**What is the expected behavior?**

New Project form should close and bring you to your new project .

**Is it happening in taiga.io or in your own instance?**
My Own.

**What browser/version are you using?**

Chromium Version 58.0.3028.0 / Windows 7

**Are there any console errors *(Ctrl + F12)* in red?**

_Console error:_
> POST http://my-taiga-instance/api/v1/projects 500 (Internal Server Error)

_Request Payload:_
```js
{"is_private":false,"creation_template":1,"name":"test","description":"test"}
```
_Server log:_
> [...]
>   File "/usr/local/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
>     raise value.with_traceback(tb)
>   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
>     return self.cursor.execute(sql, params)
> django.db.utils.IntegrityError: null value in column "is_contact_activated" violates not-null constraint

**Comment by superalex** [comment]
Hello we have updated the stable branch to the last release. You could move to the stable branches again and follow the upgrade instructions: https://taigaio.github.io/taiga-doc/dist/upgrades.html
