### ISSUE TITLE
error with /home/Taiga/taiga-back/taiga/mdrender/service.py

### ISSUE THREAD

**Issue by Exellent1988** [taigaio/taiga-back#954]
in line 25 
/home/Taiga/taiga-back/taiga/mdrender/service.py
 the import statement should be``from html5lib.serializer import HTMLSerializer
``

**Comment by superalex** [comment]
Hello @Exellent1988 

What's exactly the problem?, are you receiving any error?, I've checked that import in both python 3.4 and 3.6 and it works...

**Comment by Exellent1988** [comment]
i tryed it with python 3.5 ( my shame it was on an ubuntu 14.04 server) which mightbe the prob

**Comment by superalex** [comment]
Thanks @Exellent1988 , that's probably the problem ;)
