### ISSUE TITLE
3.1.0 Install : CommandError: No fixture named 'initial_role' found.

### ISSUE THREAD

**Issue by Jerome-mi** [taigaio/taiga-back#958]
Hi all,
on a brand new ubuntu 16.04 server, following the tutorial, I've this issue when launching the
`python manage.py loaddata initial_role` command : 

```
...
Installed 1 object(s) from 1 fixture(s)
(taiga) taiga@xxxx:~/taiga-back$ python manage.py loaddata initial_project_templates
Trying import local.py settings...
Trying import development.py settings...
Installed 2 object(s) from 1 fixture(s)
(taiga) taiga@xxxx:~/taiga-back$ python manage.py loaddata initial_role
Trying import local.py settings...
Trying import development.py settings...
CommandError: No fixture named 'initial_role' found.


```

How can I pass through ? What is the incidence ?
Thx !

**Comment by bameda** [comment]
Hi @Jerome-mi,  what setup gidue are you follow?

**Comment by bameda** [comment]
I found it, is a mistake, ignore this command.

**Comment by Jerome-mi** [comment]
thanks !

**Comment by medchedli** [comment]
Having the same problem when trying to setup taiga on Ubuntu 16.04 server using TAIGA-SCRIPTS
![capture du 2017-10-16 17-42-12](https://user-images.githubusercontent.com/3912825/31624151-9df2d91a-b299-11e7-8fe0-f0740ed55c02.png) 

`Installed 1 object(s) from 1 fixture(s)
Trying import local.py settings...
Installed 2 object(s) from 1 fixture(s)
Trying import local.py settings...
CommandError: No fixture named 'initial_role' found.
Trying import local.py settings...`

the script freeze at this point

**Comment by cjohnsonuk** [comment]
+1, getting the same Ubuntu 16.10, installing from scripts using these instructions http://taigaio.github.io/taiga-doc/dist/setup-alternatives.html
