### ISSUE TITLE
3.1.0 Fresh Install Taiga-events : connection refused

### ISSUE THREAD

**Issue by Jerome-mi** [taigaio/taiga-back#959]
Hi all !
on a fresh taiga install on ubuntu 16.04, following official tutorial :
I have this in my nginx.error.log : 

> 2017/03/18 09:37:13 [error] 1335#1335: *144 connect() failed (111: Connection refused) while connecting to upstream, client: xxxx, server: xxxx, request: "GET /events HTTP/1.1", upstream: "http://127.0.0.1:8888/events", host: "xxxx"

and that in my taigaevents.stderr.log :

> TypeError: this is not a typed array.
>     at Function.from (native)
>     at Object.<anonymous> (/mnt/vdb/www/taiga/taiga-events/node_modules/ws/lib/PerMessageDeflate.js:10:24)
>     at Module._compile (module.js:410:26)
>     at Object.Module._extensions..js (module.js:417:10)
>     at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
>     at Function.Module._load (module.js:301:12)
>     at Module.require (module.js:354:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (/mnt/vdb/www/taiga/taiga-events/node_modules/ws/lib/WebSocket.js:16:27)
>     at Module._compile (module.js:410:26)
>     at Object.Module._extensions..js (module.js:417:10)
>     at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
>     at Function.Module._load (module.js:301:12)
>     at Module.require (module.js:354:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (/mnt/vdb/www/taiga/taiga-events/node_modules/ws/index.js:9:19)
>     at Module._compile (module.js:410:26)
>     at Object.Module._extensions..js (module.js:417:10)
>     at Module.load (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
>     at Function.Module._load (module.js:301:12)
>     at Module.require (module.js:354:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (/mnt/vdb/www/taiga/taiga-events/index.coffee:4:19)
>     at Object.<anonymous> (/mnt/vdb/www/taiga/taiga-events/index.coffee:1:1)
>     at Module._compile (module.js:410:26)
>     at Object.exports.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:173:23)
>     at compileScript (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:224:29)
>     at compilePath (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:174:14)
>     at Object.exports.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:98:20)
>     at Object.<anonymous> (/usr/local/lib/node_modules/coffee-script/bin/coffee:7:41)
>     at Module._compile (module.js:410:26)
>     at Object.Module._extensions..js (module.js:417:10)
>     at Module.load (module.js:344:32)
>     at Function.Module._load (module.js:301:12)
>     at Function.Module.runMain (module.js:442:10)
>     at startup (node.js:136:18)
>     at node.js:966:3
> 
Everything seems to be correct in the configuration, no issue on install.
Please help !

**Comment by jespino** [comment]
Looks like is there any problem in your installation of "ws" node module. Which version of node are you using?

Can you try to remove the node_modules directory in taiga-events and run npm install again, and try to restart taiga events?

**Comment by Jerome-mi** [comment]
Thanks for help jesus !

> npm show ws version

gave me : 2.2.2

I removed ws directory from nodes_modules and then ran nom install again :
> TaigaIO-Events@0.0.1 /mnt/vdb/www/taiga/taiga-events
> └── ws@2.2.2 
> npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
> npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.1.1

> uname -a :
> Linux ov-dbae09 4.4.0-66-generic #87-Ubuntu SMP Fri Mar 3 15:29:05 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

and finally
> circusctl restart taiga-events... 

but I've still the same errors in logs and when I move a card on a client the others are not notified...
I also tried a systemctl restart for circus and nginx
I also tried the same removing the whole node_modules directory

**Comment by jespino** [comment]
Can you run it manually using node_modules/coffee-script/bin/coffee index.coffee? you get the same errors?

**Comment by theriverman** [comment]
Hi,

I don't see it mentioned, could you please issue the following commands please:
node -v
nodejs -v

and post your results!

/riverman

**Comment by Jerome-mi** [comment]
@Jesus

> taiga@ov-dbae09:~/taiga-events$ node_modules/coffee-script/bin/coffee index.coffee
> TypeError: this is not a typed array.
>     at Function.from (native)
>     at Object.<anonymous> (/mnt/vdb/www/taiga/taiga-events/node_modules/ws/lib/PerMessageDeflate.js:10:24)
>     at Module._compile (module.js:410:26)
>     at Object.Module._extensions..js (module.js:417:10)
>     at Module.load (/mnt/vdb/www/taiga/taiga-events/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
>     at Function.Module._load (module.js:301:12)
>     at Module.require (module.js:354:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (/mnt/vdb/www/taiga/taiga-events/node_modules/ws/lib/WebSocket.js:16:27)
>     at Module._compile (module.js:410:26)
>     at Object.Module._extensions..js (module.js:417:10)
>     at Module.load (/mnt/vdb/www/taiga/taiga-events/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
>     at Function.Module._load (module.js:301:12)
>     at Module.require (module.js:354:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (/mnt/vdb/www/taiga/taiga-events/node_modules/ws/index.js:9:19)
>     at Module._compile (module.js:410:26)
>     at Object.Module._extensions..js (module.js:417:10)
>     at Module.load (/mnt/vdb/www/taiga/taiga-events/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
>     at Function.Module._load (module.js:301:12)
>     at Module.require (module.js:354:17)
>     at require (internal/module.js:12:17)
>     at Object.<anonymous> (/mnt/vdb/www/taiga/taiga-events/index.coffee:4:19)
>     at Object.<anonymous> (/mnt/vdb/www/taiga/taiga-events/index.coffee:1:1)
>     at Module._compile (module.js:410:26)
>     at Object.exports.run (/mnt/vdb/www/taiga/taiga-events/node_modules/coffee-script/lib/coffee-script/coffee-script.js:173:23)
>     at compileScript (/mnt/vdb/www/taiga/taiga-events/node_modules/coffee-script/lib/coffee-script/command.js:224:29)
>     at compilePath (/mnt/vdb/www/taiga/taiga-events/node_modules/coffee-script/lib/coffee-script/command.js:174:14)
>     at Object.exports.run (/mnt/vdb/www/taiga/taiga-events/node_modules/coffee-script/lib/coffee-script/command.js:98:20)
>     at Object.<anonymous> (/mnt/vdb/www/taiga/taiga-events/node_modules/coffee-script/bin/coffee:7:41)
>     at Module._compile (module.js:410:26)
>     at Object.Module._extensions..js (module.js:417:10)
>     at Module.load (module.js:344:32)
>     at Function.Module._load (module.js:301:12)
>     at Function.Module.runMain (module.js:442:10)
>     at startup (node.js:136:18)
>     at node.js:966:3
> 
@theriverman 
as I'm running on a frech ubuntu 16.04 :

**Comment by jespino** [comment]
Ok, this is the problem, we use node >= 6, so you have to install a newer version of node.

We normally use nvm (https://github.com/creationix/nvm).

So install nvm, install a newer version of node, for example the last one, with (nvm install 7.7.4), enable it with nvm use 7.7.4, delete your current node_modules, and run npm install again.

This must solve the problem :)

**Comment by theriverman** [comment]
@jespino I had the same (or maybe just similar) issue before.

I suggest updating [Taiga: Setup production environment > Install all the javascript dependencies needed](http://taigaio.github.io/taiga-doc/dist/setup-production.html) documentation, because `sudo apt-get install -y nodejs nodejs-legacy npm` installs an old node/nodejs version on Ubuntu[16.04]. 

I suggest replacing the command with a [link to NodeJS official site > Installing Node.js via package manager](https://nodejs.org/en/download/package-manager/#installing-node-js-via-package-manager). 

/riverman

**Comment by Jerome-mi** [comment]
OK,
I've installed the version 7 using nodesource repository and everything seems to be correct. No more errors and clients are notified when card are moving... almost every time !
 Thanks Jesus and Kristof !
I'll always trust in Jesus even if sometimes he may need some help...

**Comment by jespino** [comment]
jajajaja, thanks @theriverman, and yes, I will change the documentation with your proposal.

**Comment by biddaputzese** [comment]
Hello,

I have the same issue on a fresh install.
Following the tips showed here, I've installed nodejs v.7.10.1 and errors are still issued.

Should I open a new issue or could you reopen this one ?

Thank you ;-)
