### ISSUE TITLE
Restoring Taiga Backup from postgres dump and /media

### ISSUE THREAD

**Issue by paulkernstock** [taigaio/taiga-back#961]
I'm trying out restoring the backup of my Taiga-Server and I am having some problems with restoring the database.
I set up a fresh Ubuntu-Server and to troubleshoot this I set up a new and basic Taiga-installation, reffering to [the official how-to](https://taigaio.github.io/taiga-doc/dist/setup-production.html), which I set up with the example projects data that are provided. Working just fine.

Now referring to #100, I created a database-dump. The dump-command was:

    sudo -u postgres pg_dump --format=custom --dbname=taiga --file=~/Backup/taiga-postgres.dump

Then on the frontend in my browser and as "admin" I manually deleted some random of these example projects. Then I tried to restore the previously created database-dump:

    sudo -u postgres pg_restore -d taiga ~/Backup/taiga-postgres.dump

This having done, the projects still seems to be deleted, at least I can't see them in my browser. Also 'pg_restore' threw 583 of errors, most of which were '... already exists'-ones. You can find the log [here](https://gist.github.com/paulkernstock/fb53544f4c67eb81576bb69ec2b9ece4).

Even trying to re-setup everything by repeating the installation commands

    python manage.py migrate --noinput
    python manage.py loaddata initial_user
    python manage.py loaddata initial_project_templates
    python manage.py compilemessages
    python manage.py collectstatic --noinput
    python manage.py sample_data

has no effect.

I also tried reloading all servers:

    sudo /etc/init.d/postgresql reload
    python ~/taiga-back/manage.py runserver
    sudo service circusd restart
    sudo service nginx restart

All without effect, the projects remain deleted.

Strange thing is: Requesting a list of projects, using

    curl -X GET \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer ${AUTH_TOKEN}" \
    http://localhost:8000/api/v1/projects

lists me all deleted projects (see [here](https://gist.github.com/paulkernstock/c7b4634d376b1ee32bc152e1a1c65dde)).

Thanks for any suggestions!

**Comment by jespino** [comment]
Hi Paul,

I have two proposals here.

First one, try it in an incognito browser session, if this list correctly
your projects, try to remove all your local storage data.

Second one, try to create a new fresh and clean database (for example
taiga2) and load the dump there, and change your taiga-back settings to use
this second database (I'm not sure if restoring the backup over the
existing database is generating any problem).

Regards.

**Comment by paulkernstock** [comment]
Second did the trick! Thanks!

More precisely I deleted the old database via

    sudo -u postgres dropdb taiga

and recreated a new one. The `pg_restore` ran without errors.

At first Taiga ran with some issues (e.g. no avatar pictures) but after I reintroduced the complete configuration, everything seems to be fine. I'll have that tested.
