### ISSUE TITLE
Taiga front end crashes after sorting SCRUM backlog

### ISSUE THREAD

**Issue by magalhas** [taigaio/taiga-back#967]
Since Taiga 3.0, the UI crashes when sorting an user story in the SCRUM backlog. I've searched for this issue and did not find anything referencing this which is very odd. What happens is that the sorting occurs (if I check the list again) but I'm redirected to the "something happened, take me home" screen.

I've recently updated to Taiga 3.1 but the problem persists. Maybe I should have created this in on the front end project but I believe this happens because there's a 502 in the back end (though no error is logged).

**Comment by jespino** [comment]
Hi @magalhas 

To understand what is going on we need the error. This 502 means that the nginx can't get a response from taiga for more than the timeout defined in nginx configuration. This may means that the taiga server isn't responding on time for this requests.

You can try to configure you taiga server to serve directly without nginx in the middle (this is not the good way to have it configured) and see what happends.

**Comment by magalhas** [comment]
Thank you @jespino . After investigating a little bit further I found out that the problem was due to the nginx configuration. The response header size was exceeding the allowed for the proxy response buffer, increasing the buffer size fixed the issue.

**Comment by jespino** [comment]
Great! :)
