### ISSUE TITLE
[Q] Am I building the docker image of this repository incorrectly?

### ISSUE THREAD

**Issue by Mr-Draco** [taigaio/taiga-back#97]
I cloned this repository and built the Docker image from the root of the repository with `docker build --tag yuppers/taiga-back -f docker/Dockerfile `.

While in the container created with the image `yuppers/taiga-back`, output from running `/taiga-back/docker/async_entrypoint.sh`
```
Give permission to taiga:taiga
Starting Celery...
Traceback (most recent call last):
  File "/opt/venv/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/opt/venv/lib/python3.7/site-packages/celery/__main__.py", line 14, in main
    from celery.bin.celery import main as _main
  File "/opt/venv/lib/python3.7/site-packages/celery/bin/celery.py", line 11, in <module>
    from pkg_resources import iter_entry_points
  File "/opt/venv/lib/python3.7/site-packages/pkg_resources/__init__.py", line 32, in <module>
    import plistlib
  File "/usr/local/lib/python3.7/plistlib.py", line 65, in <module>
    from xml.parsers.expat import ParserCreate
  File "/usr/local/lib/python3.7/xml/parsers/expat.py", line 4, in <module>
    from pyexpat import *
ImportError: libexpat.so.1: cannot open shared object file: No such file or directory
```

I compared the Dockerfile from the repository used to build the image yuppers/taiga-back with the [image layers of taigaio/taiga-back:latest published 4 months ago to the docker hub](https://hub.docker.com/layers/taiga-back/taigaio/taiga-back/latest/images/sha256-0eef29a7b07ff9cffc3966b379a6073d2700531aed76a5cf20e7dbf79aa05d5f?context=explore) and there were no significant differences.

Given that I didn't make a mistake while building, would it make sense to add `apt install libexpat1-dev`? I did `apt install libexpat1-dev` and it seems to fix the error.

I want to note that the command `/taiga-back/docker/async_entrypoint.sh` does work in containers from the image `taigaio/taiga-back:latest`

Somewhat unrelated, but something I also want to note that [this page](https://docs.python.org/3/library/pyexpat.html) suggests that "pyexpat module is not secure against maliciously constructed data."

**Comment by yamila-moreno** [comment]
Hi there!

Do you know that we have [Taiga Community](https://community.taiga.io/) for questions? Please, check there; maybe another user has already ask something similar. If not, create your own. There are people there willing to help, members of the Taiga team members and other users.

To simplify  the process, we will systematically close all issues that are general support questions and redirect people to Taiga Community.

Taiga Team
