### ISSUE TITLE
[query] Feasibility of offline operations

### ISSUE THREAD

**Issue by kwill** [taigaio/taiga-back#970]
I am a developer using Taiga. When modifying shared data, I prefer to download and modify text files offline then merge them back into the shared public version, so that I can work asynchronously and merge updates as they are ready.

Does existing Taiga architecture lend itself to an download-edit-merge workflow? For example:
* does the wiki lend itself to a Git-based text-file backend?
* does the API include signals suitable for a download-modify-upload workflow that somehow catches intermediate edits?
* would it be feasible to run a local Taiga instance, and sync the database with a remote instance?

Or is Taiga focussed solely on remote server installation + browser interface? (Which would be fair enough.)

**Comment by superalex** [comment]
Hello @kwill 

The wiki doesn't lend lend to a Git-based text-file backend. About the intermediate edits, your project can have configured webhooks (https://taigaio.github.io/taiga-doc/dist/webhooks.html) so your external applications can be notified about any change on Taiga.

If you are running your own taiga intance syncing databases can be done using a master/slave database schema.

Regards,

**Comment by kwill** [comment]
Thanks!

**Comment by mahalingams** [comment]
it's download offline?
