### ISSUE TITLE
Invitation email doesn't use https link after enable https

### ISSUE THREAD

**Issue by LeGiangAnh** [taigaio/taiga-back#978]
**Do you want to request a *feature* or report a *bug*?**
Bug

**What is the current behavior?**
The invitation email doesn't use SSL (https). The rest links work correctly with https.

**If the current behavior is a bug, please provide the steps to reproduce.**
Enable https follow the guidelines. Then add a new member via Admin frontend.

**What is the expected behavior?**
The registration link should use https.

**Is it happening in taiga.io or in your own instance?**

**What browser/version are you using?**
Chrome
**Are there any console errors *(Ctrl + F12)* in red?**
No

**Comment by superalex** [comment]
Hello @LeGiangAnh ,

It sounds like your taiga-back isn't correctly configured, you should check your  SITES["front"]["scheme"] setting in your local.py file
