### ISSUE TITLE
Assign US points in tasks

### ISSUE THREAD

**Issue by sydcanem** [taigaio/taiga-back#98]
Our agile team uses a different (paid) app but this seems to be a very good alternative. Thanks for making this.

One thing I'm missing in the previous app is the ability to log how much hours we're done by the devs for that specific task. If we could assign/set ratio of story point -> hour that would be awesome.

**Comment by mackaltman** [comment]
@danschick and @superalex, there seems to be a misunderstanding between your view of what Agile Scrum means. The Scrum approach is to get away from "time". The Kanban approach is more correlated to "time". Scrum is used by developers working on software, generally, to promote competition of point accumulation. Points are assigned on varying degrees (i.e. difficulty, time consuming, etc.). While something may take a lot of time, it doesn't mean it's difficult. Additionally, something of a higher tier of knowledge (i.e. legal review requirements) won't necessarily take a lot of time but deserves more points. In the end, the goal is to achieve the most points for each Sprint.

For a "straightforward", or "hours", based approach, you would look more at the Kanban approach. Kanban is best used for user administration, PC repair, network administration, etc. It takes X amount of time for (1) a user to be created, (2) a PC to be repaired and (3) an IP address to be white listed. These are where you were utilize Kanban.

**Comment by AndrewDryga** [comment]
Hi guys, any update on ETA for custom fields? :)

**Comment by Xaviju** [comment]
@AndrewDryga custom fields are in the next release for sure, we are about 2 weeks away.

**Comment by hariniramaprasad** [comment]
Hi, I was wondering if there is an update on when custom fields will be available.

**Comment by eaposner** [comment]
Hi. Yes, should be live in next week's release. We've scheduled it for Tuesday.

**Comment by hariniramaprasad** [comment]
That's great! Look forward to using this feature. :)

**Comment by adelatorrefoss** [comment]
@luisrudge , @AndrewDryga and @hariniramaprasad ... the Taiga version with custom fields are available in http://taiga.io  :-)

**Comment by lordloh** [comment]
The custom fields are not useful for filtering or  sorting :-(.
If I do try to assign US points in tasks (as custom field) there is no semantic meaning for it in the sprint. Any suggested ways to get around this?

**Comment by Xaviju** [comment]
Custom fields work as a extra information on the US, task or issue detail, and are not available for filtering. Tasks can not be estimated in points in Taiga nor filtered by custom fields.
There is an open issue in Taiga about this: You can upovote it: https://tree.taiga.io/project/taiga/issue/3734
