### ISSUE TITLE
[QUESTION] what are github, gogs, gitlab etc users for?

### ISSUE THREAD

**Issue by Kyslik** [taigaio/taiga-back#988]
As title says.

Follow up can I delete those users? What is ["system account"](https://github.com/taigaio/taiga-back/blob/4a28721c733f80452c29f8b66bece095b74d5f1a/taiga/hooks/github/migrations/0001_initial.py#L17-L22) for? (`is_system` flag). 

<img width="1113" alt="screen shot 2017-04-22 at 3 31 38 pm" src="https://cloud.githubusercontent.com/assets/2067589/25304918/829732be-2771-11e7-8e91-6e140497bc95.png">

**Comment by superalex** [comment]
Hello @Kyslik if you want that github, gitlab and bitbucket integrations keep working you shouldn't remove those users:
- https://tree.taiga.io/support/integrations/github-integration/
- https://tree.taiga.io/support/integrations/gitlab-integration/
- https://tree.taiga.io/support/integrations/bitbucket-integration/

Regards!,
