### ISSUE TITLE
Taiga can't work behind a general reverse proxy (managing for instance SSL-termination) because of hardcoded url in JS

### ISSUE THREAD

**Issue by Annakan** [taigaio/taiga-back#989]
The settings of the backed hardcode the full url and the protocol and the hostname of taiga in several places.

Is there a good reason to do this  ?
Because it seems to make impossible to use taiga in a setting where it is accessed through a a proxy that is going SSL termination, as in many enterprise situations.
Chrome is even blocking most calls with the explicit message

> Mixed Content: The page at 'https://xxxx/discover' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://xxxx/api/v1/stats/discover'. This request has been blocked; the content must be served over HTTPS.

I know we shall not trust what the user browser send but could we not trust the web server to set proper headers from what he actually extracted from the request and use that to build the url ?

I don't see any ways around this .

**Comment by superalex** [comment]
Hello @Annakan could you please detail where are those url's hardcoded?. There shouldn't be any of them, all the url's should be configurable.

https://tree.taiga.io is configured with a general reverse proxy.

**Comment by Annakan** [comment]
Sorry I realize that this was wronly tittled
The hardcoded URLs and Scheme are in the settings (but still "hardcoded").

In local.py
````python
MEDIA_URL = "http://taiga.appforge.xxxx/media/"
STATIC_URL = "http://taiga.appforge.xxxx/static/"
ADMIN_MEDIA_PREFIX = "http://taiga.appforge.xxxx/static/admin/"
SITES["front"]["scheme"] = "http"
SITES["front"]["domain"] = "taiga.appforge.xxxx"
````
The problem is when you have a reverse proxy doing SSL termination, for instance because you want to grant outside organization access through an HTTPS portal.
It becomes even more of a problem when the outside url is different front the inside one.

I might be wrong but it seems to me that as in a "non javascript heavy" website, one should never assume  the scheme and hostname it is called from.

Would it not be possible to get those from special headers set by the nginx for instance so that you build the JS callback url "properly" and right  ?

Or do you have another advice in such cases ?

**Comment by superalex** [comment]
We can't just assume the scheme and hostname. Some parts of the code require to know it, for example when email notifications are sent.

In this case I think you should enable just one url with or without https for both environments (inside and outside organization).
