### ISSUE TITLE
Automatically move stories to next sprint

### ISSUE THREAD

**Issue by alex-hutton** [taigaio/taiga-back#991]
Hi, thanks for the great software.

This is a feature request.

When the timeframe of a sprint ends, I would like the option to have unclosed stories moved automatically to the next chronological sprint.

If this feature is desired I will try and submit a PR for it.

**Comment by superalex** [comment]
Thank you very much @alex-hutton I think this one is duplicated here: https://tree.taiga.io/project/taiga/issue/2371

If you are interested in proposing such a major change you can follow this guide with the steps required to include a PR in taiga: https://tree.taiga.io/support/frequently-asked-questions/how-can-i-contribute-to-taiga/#propose-some-feature-or-enhancement

Regards,
