### ISSUE TITLE
Use LDAP authentification (not working)

### ISSUE THREAD

**Issue by NicolasLMD** [taigaio/taiga-back#999]
Hi,

The LDAP auth doesn't work on my production env. When I try to log in, I got this message "Oops, something happened...Our Oompa Loompas are sad, your changes were not saved!"

I'm not enough familiar with LDAP to be able to set up it alone. I made some tests with ldapsearch on my ubuntu server (the LDAP server is on a Windows server machine, and I want to make requests on the Active Directory rep). The tests showed that I successfully manage to connect and bind but not search. Can you help me ?
My AD server (on windows server) contains a list of users and a list of users groups under a server name ("ul.myserver.com"). Users can be on different groups but one indicates users allowed to connect on Taiga (group name = "TaigaConnect")

I want to connect with the same login/password than on windows machine (not with my email or full name)

I set up local.py like this :

LDAP_SEARCH_BASE = 'CN=TaigaConnect,CN-Users,DC=ul,DC=myserver,DC=com'
LDAP_SEARCH_PROPERTY = 'sAMAccountName'
LDAP_SEARCH_SUFFIX = None # '@example.com'
LDAP_EMAIL_PROPERTY = 'mail'
LDAP_FULL_NAME_PROPERTY = 'DisplayName'

I also tested property 'uid'

Can you tell me how to correct it ?

Thank you

**Comment by superalex** [comment]
Hello @NicolasLMD 

Sorry but the ldap plugin is maintained by another development team: https://github.com/ensky/taiga-contrib-ldap-auth
